void MakePlotsPath(const char* data_path, const char* mc_path){

	printf("data = %s, mc = %s\n",data_path,mc_path);

	gROOT->SetStyle("Plain");
	gStyle->SetPalette(1);
	gStyle->SetOptStat(0);
	gStyle->SetPalette(1);
	gStyle->SetCanvasColor(0);
	gStyle->SetFrameFillColor(0);
	gStyle->SetOptTitle(0);
	
	TString mc_fileName(Form("%s/histograms.root",mc_path));
	TString data_fileName(Form("%s/histograms.root",data_path));
	TFile* mc_file = new TFile(mc_fileName.Data());
	TFile* data_file = new TFile(data_fileName.Data());

	TString mc_fileNameEvStat(Form("%s/event_stat.root",mc_path));
	TString data_fileNameEvStat(Form("%s/event_stat.root",data_path));
	TFile* mc_fileEvSt = new TFile(mc_fileNameEvStat.Data());
	TFile* data_fileEvSt = new TFile(data_fileNameEvStat.Data());
	TDirectoryFile* mc_dir = (TDirectoryFile*)mc_fileEvSt->Get("trigger_histograms_");

	// WARNING!!!! check the trigger classes for your run!!!!
	TDirectoryFile* data_dirCINT1B = (TDirectoryFile*)data_fileEvSt->Get("trigger_histograms_+CINT1B-ABCE-NOPF-ALL");
	TDirectoryFile* data_dirCINT1A = (TDirectoryFile*)data_fileEvSt->Get("trigger_histograms_+CINT1A-ABCE-NOPF-ALL");
	TDirectoryFile* data_dirCINT1C = (TDirectoryFile*)data_fileEvSt->Get("trigger_histograms_+CINT1C-ABCE-NOPF-ALL");
	TDirectoryFile* data_dirCINT1E = (TDirectoryFile*)data_fileEvSt->Get("trigger_histograms_+CINT1-E-NOPF-ALL");

	// mc
	TH2D* mc_etaPhi = (TH2D*)mc_file->Get("fEtaPhi");
	TH1D* mc_eta = (TH1D*)mc_etaPhi->ProjectionX();
	TH1D* mc_phi = (TH1D*)mc_etaPhi->ProjectionY();
	TH1D* mc_phiEta1 = (TH1D*)mc_etaPhi->ProjectionY("mc_phiEta1",mc_eta->FindBin(-1.4),mc_eta->FindBin(1.4)-1);
	TH1D* mc_phiEtaNeg = (TH1D*)mc_etaPhi->ProjectionY("mc_phiEtaNeg",mc_eta->FindBin(-1.4),mc_eta->FindBin(0)-1);
	TH1D* mc_phiEtaPos = (TH1D*)mc_etaPhi->ProjectionY("mc_phiEtaPos",mc_eta->FindBin(0),mc_eta->FindBin(1.4)-1);
	TH1D* mc_deltaPhi = (TH1D*)mc_file->Get("fDeltaPhi");
	TH1D* mc_deltaTheta = (TH1D*)mc_file->Get("fDeltaTheta");
	TH1D* mc_vtxX = (TH1D*)mc_file->Get("fVtxX");
	TH1D* mc_vtxY = (TH1D*)mc_file->Get("fVtxY");
	TH1D* mc_vtxZ = (TH1D*)mc_file->Get("fVtxZ");
	TH3D* mc_vtxContributors = (TH3D*)mc_file->Get("fVtxContributors");
	TH1D* mc_vtxXContributors = (TH1D*)mc_vtxContributors->ProjectionX();
	TH1D* mc_vtxYContributors = (TH1D*)mc_vtxContributors->ProjectionY();
	TH1D* mc_vtxZContributors = (TH1D*)mc_vtxContributors->ProjectionZ();
	TH1F* mc_HistFiredBitsSPD = (TH1F*)mc_dir->Get("fHistFiredBitsSPD");
	mc_etaPhi->SetName("mc_etaPhi");
	mc_eta->SetName("mc_eta");
	mc_phi->SetName("mc_phi");
	mc_deltaPhi->SetName("mc_deltaPhi");
	mc_deltaTheta->SetName("mc_deltaTheta");
	mc_vtxX->SetName("mc_vtxX");
	mc_vtxY->SetName("mc_vtxY");
	mc_vtxZ->SetName("mc_vtxZ");
	mc_vtxXContributors->SetName("mc_vtxXContributors");
	mc_vtxYContributors->SetName("mc_vtxYContributors");
	mc_vtxZContributors->SetName("mc_vtxZContributors");

	// data
	TH2D* data_etaPhi = (TH2D*)data_file->Get("fEtaPhi");
	TH1D* data_eta = (TH1D*)data_etaPhi->ProjectionX();
	TH1D* data_phi = (TH1D*)data_etaPhi->ProjectionY();
	TH1D* data_phiEta1 = (TH1D*)data_etaPhi->ProjectionY("data_phiEta1",data_eta->FindBin(-1.4),data_eta->FindBin(1.4)-1);
	TH1D* data_phiEtaNeg = (TH1D*)data_etaPhi->ProjectionY("data_phiEtaNeg",data_eta->FindBin(-1.4),data_eta->FindBin(0)-1);
	TH1D* data_phiEtaPos = (TH1D*)data_etaPhi->ProjectionY("data_phiEtaPos",data_eta->FindBin(0),data_eta->FindBin(1.4)-1);
	TH1D* data_deltaPhi = (TH1D*)data_file->Get("fDeltaPhi");
	TH1D* data_deltaTheta = (TH1D*)data_file->Get("fDeltaTheta");
	TH1D* data_vtxX = (TH1D*)data_file->Get("fVtxX");
	TH1D* data_vtxY = (TH1D*)data_file->Get("fVtxY");
	TH1D* data_vtxZ = (TH1D*)data_file->Get("fVtxZ");
	TH3D* data_vtxContributors = (TH3D*)data_file->Get("fVtxContributors");
	TH1D* data_vtxXContributors = (TH1D*)data_vtxContributors->ProjectionX();
	TH1D* data_vtxYContributors = (TH1D*)data_vtxContributors->ProjectionY();
	TH1D* data_vtxZContributors = (TH1D*)data_vtxContributors->ProjectionZ();
	TH1F* data_HistFiredBitsSPDCINT1B = (TH1F*)data_dirCINT1B->Get("fHistFiredBitsSPD");
	TH1F* data_HistFiredBitsSPDCINT1A = (TH1F*)data_dirCINT1A->Get("fHistFiredBitsSPD");
	TH1F* data_HistFiredBitsSPDCINT1C = (TH1F*)data_dirCINT1C->Get("fHistFiredBitsSPD");
	TH1F* data_HistFiredBitsSPDCINT1E = (TH1F*)data_dirCINT1E->Get("fHistFiredBitsSPD");
	data_etaPhi->SetName("data_etaPhi");
	data_eta->SetName("data_eta");
	data_phi->SetName("data_phi");
	data_deltaPhi->SetName("data_deltaPhi");
	data_deltaTheta->SetName("data_deltaTheta");
	data_vtxX->SetName("data_vtxX");
	data_vtxY->SetName("data_vtxY");
	data_vtxZ->SetName("data_vtxZ");
	data_vtxXContributors->SetName("data_vtxXContributors");
	data_vtxYContributors->SetName("data_vtxYContributors");
	data_vtxZContributors->SetName("data_vtxZContributors");
	mc_HistFiredBitsSPD->SetName("mc_HistFiredBitsSPD");
	data_HistFiredBitsSPDCINT1B->SetName("data_HistFiredBitsSPDCINT1B");
	data_HistFiredBitsSPDCINT1A->SetName("data_HistFiredBitsSPDCINT1A");
	data_HistFiredBitsSPDCINT1C->SetName("data_HistFiredBitsSPDCINT1C");
	data_HistFiredBitsSPDCINT1E->SetName("data_HistFiredBitsSPDCINT1E");

	// ratios
	TH1D* ratio_phi = new TH1D("ratio_phi","#phi; #phi [rad]; Ratio", 18*5,0,2*TMath::Pi());
	TH1D* ratio_phiEta1 = new TH1D("ratio_phiEta1","#phi; #phi (|#eta|<1.4) [rad]; Ratio", 18*5,0,2*TMath::Pi() );
	TH1D* ratio_phiEtaNeg = new TH1D("ratio_phiEtaNeg","#phi; #phi (#eta<0) [rad]; Ratio", 18*5,0,2*TMath::Pi() );
	TH1D* ratio_phiEtaPos = new TH1D("ratio_phiEtaPos","#phi; #phi (#eta>0) [rad]; Ratio", 18*5,0,2*TMath::Pi() );
	TH1D* ratio_deltaPhi = new TH1D("ratio_deltaPhi","#Delta#phi; #Delta #phi;Ratio", 500, -1, 1);
	TH1D* ratio_deltaTheta = new TH1D("ratio_deltaTheta","#Delta#theta; #Delta #theta;Ratio", 500, -0.2, 0.2);
	TH1D* ratio_vtxX = new TH1D("ratio_vtxX", "x SPD primary vertex; x [cm]; Ratio",100,-1,1);
	TH1D* ratio_vtxY = new TH1D("ratio_vtxY", "y SPD primary vertex; y [cm]; Ratio",100,-1,1);
	TH1D* ratio_vtxZ = new TH1D("ratio_vtxZ", "z SPD primary vertex; z [cm]; Ratio",100,-30,30);
	TH1D* ratio_vtxXContributors = new TH1D("ratio_vtxXContributors", "x SPD primary vertex; x_{SPDvtx (N. Contributors > 0)} [cm]; Ratio",100,-1,1);
	TH1D* ratio_vtxYContributors = new TH1D("ratio_vtxYContributors", "y SPD primary vertex; y_{SPDvtx (N. Contributors > 0)} [cm]; Ratio",100,-1,1);
	TH1D* ratio_vtxZContributors = new TH1D("ratio_vtxZContributors", "z SPD primary vertex; z_{SPDvtx (N. Contributors > 0)} [cm]; Ratio",100,-30,30);
	TH1D* ratio_HistFiredBitsSPD = new TH1D("ratio_HistFiredBitsSPD", "SPD GFO; chip number; Ratio",1200,-0.5,1199.5);

	TCanvas* cEta = new TCanvas("cEta", "#eta", 50,50, 550, 550);
	TCanvas* cPhi = new TCanvas("cPhi", "#phi", 50,50,550, 550);
	TCanvas* cPhiEta1 = new TCanvas("cPhiEta1", "#phi, |#eta| < 1.4", 50,50,550, 550);
	TCanvas* cPhiEtaNeg = new TCanvas("cPhiEtaNeg", "#phi, #eta < 0", 50,50,550, 550);
	TCanvas* cPhiEtaPos = new TCanvas("cPhiEtaPos", "#phi, #eta > 0", 50,50,550, 550);
	TCanvas* cDeltaPhi = new TCanvas("cDeltaPhi", "#Delta#phi", 50,50, 550, 550);
	TCanvas* cDeltaTheta = new TCanvas("cDeltaTheta", "#Delta#theta", 50,50, 550, 550);
	TCanvas* cvtxX = new TCanvas("cvtxX", "vtxX", 50,50,550, 550);
	TCanvas* cvtxY = new TCanvas("cvtxY", "vtxY", 50,50,550, 550);
	TCanvas* cvtxZ = new TCanvas("cvtxZ", "vtxZ", 50,50,550, 550);
	TCanvas* cvtxXContributors = new TCanvas("cvtxXContributors", "vtxXContributors", 50,50,550, 550);
	TCanvas* cvtxYContributors = new TCanvas("cvtxYContributors", "vtxYContributors", 50,50,550, 550);
	TCanvas* cvtxZContributors = new TCanvas("cvtxZContributors", "vtxZContributors", 50,50,550, 550);
	TCanvas* cSPDGFO = new TCanvas("cSPDGFO", "SPD GFO", 50,50,950, 550);
	TCanvas* cratioPhi = new TCanvas("cratioPhi", "#phi", 50,50,550, 550);
	TCanvas* cratioPhiEta1 = new TCanvas("cratioPhiEta1", "#phi, |#eta| < 1.4", 50,50,550, 550);
	TCanvas* cratioPhiEtaNeg = new TCanvas("cratioPhiNeg", "#phi, #eta < 0", 50,50,550, 550);
	TCanvas* cratioPhiEtaPos = new TCanvas("cratioPhiPos", "#phi, #eta > 0", 50,50,550, 550);
	TCanvas* cratioDeltaPhi = new TCanvas("cratioDeltaPhi", "#Delta#phi", 50,50, 550, 550);
	TCanvas* cratioDeltaTheta = new TCanvas("cratioDeltaTheta", "#Delta#theta", 50,50, 550, 550);
	TCanvas* cratiovtxX = new TCanvas("cratiovtxX", "vtxX", 50,50,550, 550);
	TCanvas* cratiovtxY = new TCanvas("cratiovtxY", "vtxY", 50,50,550, 550);
	TCanvas* cratiovtxZ = new TCanvas("cratiovtxZ", "vtxZ", 50,50,550, 550);
	TCanvas* cratiovtxXContributors = new TCanvas("cratiovtxXContributors", "vtxXContributors", 50,50,550, 550);
	TCanvas* cratiovtxYContributors = new TCanvas("cratiovtxYContributors", "vtxYContributors", 50,50,550, 550);
	TCanvas* cratiovtxZContributors = new TCanvas("cratiovtxZContributors", "vtxZContributors", 50,50,550, 550);
	TCanvas* cratioSPDGFO = new TCanvas("cratioSPDGFO", "SPD GFO", 50,50,950, 550);

	cEta->SetLeftMargin(0.15);
	cEta->SetRightMargin(0.05);
	cPhi->SetLeftMargin(0.15);
	cPhi->SetRightMargin(0.05);
	cPhiEta1->SetLeftMargin(0.15);
	cPhiEta1->SetRightMargin(0.05);
	cPhiEtaNeg->SetLeftMargin(0.15);
	cPhiEtaNeg->SetRightMargin(0.05);
	cPhiEtaPos->SetLeftMargin(0.15);
	cPhiEtaPos->SetRightMargin(0.05);
	cDeltaPhi->SetLeftMargin(0.15);
	cDeltaPhi->SetRightMargin(0.05);
	cDeltaTheta->SetLeftMargin(0.15);
	cDeltaTheta->SetRightMargin(0.05);
	cvtxX->SetLeftMargin(0.15);
	cvtxX->SetRightMargin(0.05);
	cvtxY->SetLeftMargin(0.15);
	cvtxY->SetRightMargin(0.05);
	cvtxZ->SetLeftMargin(0.15);
	cvtxZ->SetRightMargin(0.05);
	cvtxXContributors->SetLeftMargin(0.15);
	cvtxXContributors->SetRightMargin(0.05);
	cvtxYContributors->SetLeftMargin(0.15);
	cvtxYContributors->SetRightMargin(0.05);
	cvtxZContributors->SetLeftMargin(0.15);
	cvtxZContributors->SetRightMargin(0.05);
	cSPDGFO->SetLeftMargin(0.15);
	cSPDGFO->SetRightMargin(0.05);

	cratioPhi->SetLeftMargin(0.15);
	cratioPhi->SetRightMargin(0.05);
	cratioPhiEta1->SetLeftMargin(0.15);
	cratioPhiEta1->SetRightMargin(0.05);
	cratioPhiEtaNeg->SetLeftMargin(0.15);
	cratioPhiEtaNeg->SetRightMargin(0.05);
	cratioPhiEtaPos->SetLeftMargin(0.15);
	cratioPhiEtaPos->SetRightMargin(0.05);
	cratioDeltaPhi->SetLeftMargin(0.15);
	cratioDeltaPhi->SetRightMargin(0.05);
	cratioDeltaTheta->SetLeftMargin(0.15);
	cratioDeltaTheta->SetRightMargin(0.05);
	cratiovtxX->SetLeftMargin(0.15);
	cratiovtxX->SetRightMargin(0.05);
	cratiovtxY->SetLeftMargin(0.15);
	cratiovtxY->SetRightMargin(0.05);
	cratiovtxZ->SetLeftMargin(0.15);
	cratiovtxZ->SetRightMargin(0.05);
	cratiovtxXContributors->SetLeftMargin(0.15);
	cratiovtxXContributors->SetRightMargin(0.05);
	cratiovtxYContributors->SetLeftMargin(0.15);
	cratiovtxYContributors->SetRightMargin(0.05);
	cratiovtxZContributors->SetLeftMargin(0.15);
	cratiovtxZContributors->SetRightMargin(0.05);
	cratioSPDGFO->SetLeftMargin(0.15);
	cratioSPDGFO->SetRightMargin(0.05);

	cDeltaPhi->SetLogy();
	cDeltaTheta->SetLogy();
	cvtxX->SetLogy();
	cvtxY->SetLogy();
	cvtxZ->SetLogy();
	cvtxXContributors->SetLogy();
	cvtxYContributors->SetLogy();
	cvtxZContributors->SetLogy();

	mc_eta->SetLineColor(2);
	mc_eta->SetLineWidth(2);
	mc_eta->GetYaxis()->SetTitleOffset(1.6);
	mc_eta->GetYaxis()->SetTitle("Entries");
	mc_eta->Scale(data_eta->Integral()/mc_eta->Integral());
	data_eta->SetLineColor(4);
	data_eta->SetLineWidth(2);
	data_eta->SetLineStyle(2);
	mc_eta->SetMaximum(TMath::Max(mc_eta->GetMaximum(),data_eta->GetMaximum())*1.2);
	cEta->cd();
	mc_eta->Draw("hist");
	data_eta->Draw("hist same");

	mc_phi->SetLineColor(2);
	mc_phi->SetLineWidth(2);
	mc_phi->Scale(data_phi->Integral()/mc_phi->Integral());
	mc_phi->GetYaxis()->SetTitleOffset(1.9);
	mc_phi->GetYaxis()->SetTitle("Entries");
	data_phi->SetLineColor(4);
	data_phi->SetLineWidth(2);
	data_phi->SetLineStyle(2);
	mc_phi->SetMaximum(TMath::Max(mc_phi->GetMaximum(),data_phi->GetMaximum())*1.2);
	cPhi->cd();
	mc_phi->Draw("hist err");
	data_phi->Draw("hist err same");

	TLegend* leg = new TLegend(0.6,0.88,0.9,0.75);
	leg->SetFillColor(0);
	leg->AddEntry(mc_phi,Form("%s",mc_path),"L");
	leg->AddEntry(data_phi,Form("%s",data_path),"L");
	leg->Draw("same");

	mc_phiEta1->SetLineColor(2);
	mc_phiEta1->SetLineWidth(2);
	mc_phiEta1->Scale(data_phiEta1->Integral()/mc_phiEta1->Integral());
	mc_phiEta1->GetYaxis()->SetTitleOffset(1.9);
	mc_phiEta1->GetYaxis()->SetTitle("Entries");
	mc_phiEta1->GetXaxis()->SetTitle("#phi (|#eta|<1.4) [rad]");
	data_phiEta1->SetLineColor(4);
	data_phiEta1->SetLineWidth(2);
	data_phiEta1->SetLineStyle(2);
	mc_phiEta1->SetMaximum(TMath::Max(mc_phiEta1->GetMaximum(),data_phiEta1->GetMaximum())*1.2);
	cPhiEta1->cd();
	mc_phiEta1->Draw("hist err");
	data_phiEta1->Draw("hist err same");

	mc_phiEtaNeg->SetLineColor(2);
	mc_phiEtaNeg->SetLineWidth(2);
	mc_phiEtaNeg->Scale(data_phiEtaNeg->Integral()/mc_phiEtaNeg->Integral());
	mc_phiEtaNeg->GetYaxis()->SetTitleOffset(1.9);
	mc_phiEtaNeg->GetYaxis()->SetTitle("Entries");
	mc_phiEtaNeg->GetXaxis()->SetTitle("#phi (-1.4<#eta<0) [rad]");
	data_phiEtaNeg->SetLineColor(4);
	data_phiEtaNeg->SetLineWidth(2);
	data_phiEtaNeg->SetLineStyle(2);
	mc_phiEtaNeg->SetMaximum(TMath::Max(mc_phiEtaNeg->GetMaximum(),data_phiEtaNeg->GetMaximum())*1.2);
	cPhiEtaNeg->cd();
	mc_phiEtaNeg->Draw("hist err");
	data_phiEtaNeg->Draw("hist err same");

	mc_phiEtaPos->SetLineColor(2);
	mc_phiEtaPos->SetLineWidth(2);
	mc_phiEtaPos->Scale(data_phiEtaPos->Integral()/mc_phiEtaPos->Integral());
	mc_phiEtaPos->GetYaxis()->SetTitleOffset(1.9);
	mc_phiEtaPos->GetYaxis()->SetTitle("Entries");
	mc_phiEtaPos->GetXaxis()->SetTitle("#phi (0<#eta<1.4) [rad]");
	data_phiEtaPos->SetLineColor(4);
	data_phiEtaPos->SetLineWidth(2);
	data_phiEtaPos->SetLineStyle(2);
	mc_phiEtaPos->SetMaximum(TMath::Max(mc_phiEtaPos->GetMaximum(),data_phiEtaPos->GetMaximum())*1.2);
	cPhiEtaPos->cd();
	mc_phiEtaPos->Draw("hist err");
	data_phiEtaPos->Draw("hist err same");

	mc_deltaPhi->SetLineColor(2);
	mc_deltaPhi->SetLineWidth(2);
	mc_deltaPhi->GetYaxis()->SetTitleOffset(1.8);
	mc_deltaPhi->Scale(data_deltaPhi->Integral()/mc_deltaPhi->Integral());
	mc_deltaPhi->GetXaxis()->SetRangeUser(-0.15,0.15);
	data_deltaPhi->SetLineColor(4);
	data_deltaPhi->SetLineWidth(2);
	data_deltaPhi->SetLineStyle(2);
	mc_deltaPhi->SetMaximum(TMath::Max(mc_deltaPhi->GetMaximum(),data_deltaPhi->GetMaximum())*1.2);
	cDeltaPhi->cd();
	mc_deltaPhi->Draw("hist err");
	data_deltaPhi->Draw("hist err same");

	mc_deltaTheta->SetLineColor(2);
	mc_deltaTheta->SetLineWidth(2);
	mc_deltaTheta->GetYaxis()->SetTitleOffset(1.8);
       	mc_deltaTheta->Scale(data_deltaTheta->Integral()/mc_deltaTheta->Integral());
	mc_deltaTheta->GetXaxis()->SetRangeUser(-0.05,0.05);
	data_deltaTheta->SetLineColor(4);
	data_deltaTheta->SetLineWidth(2);
	data_deltaTheta->SetLineStyle(2);
	mc_deltaTheta->SetMaximum(TMath::Max(mc_deltaTheta->GetMaximum(),data_deltaTheta->GetMaximum())*1.2);
	cDeltaTheta->cd();
	mc_deltaTheta->Draw("hist err");
	data_deltaTheta->Draw("hist err same");

	mc_vtxX->SetLineColor(2);
	mc_vtxX->SetLineWidth(2);
	mc_vtxX->GetYaxis()->SetTitleOffset(1.6);
	mc_vtxX->GetYaxis()->SetTitle("Entries");
	mc_vtxX->GetXaxis()->SetTitle("x_{SPDvtx} [cm]");
       	mc_vtxX->Scale(data_vtxX->Integral()/mc_vtxX->Integral());
	data_vtxX->SetLineColor(4);
	data_vtxX->SetLineWidth(2);
	data_vtxX->SetLineStyle(2);
	mc_vtxX->SetMaximum(TMath::Max(mc_vtxX->GetMaximum(),data_vtxX->GetMaximum())*1.2);
	cvtxX->cd();
	mc_vtxX->Draw("hist err");
	data_vtxX->Draw("hist err same");

	mc_vtxY->SetLineColor(2);
	mc_vtxY->SetLineWidth(2);
	mc_vtxY->GetYaxis()->SetTitleOffset(1.6);
	mc_vtxY->GetYaxis()->SetTitle("Entries");
	mc_vtxY->GetXaxis()->SetTitle("y_{SPDvtx} [cm]");
	mc_vtxY->Scale(data_vtxY->Integral()/mc_vtxY->Integral());
	data_vtxY->SetLineColor(4);
	data_vtxY->SetLineWidth(2);
	data_vtxY->SetLineStyle(2);
	mc_vtxY->SetMaximum(TMath::Max(mc_vtxY->GetMaximum(),data_vtxY->GetMaximum())*1.2);
	cvtxY->cd();
	mc_vtxY->Draw("hist err");
	data_vtxY->Draw("hist err same");

	mc_vtxZ->SetLineColor(2);
	mc_vtxZ->SetLineWidth(2);
	mc_vtxZ->GetYaxis()->SetTitleOffset(1.6);
	mc_vtxZ->GetYaxis()->SetTitle("Entries");
	mc_vtxZ->GetXaxis()->SetTitle("z_{SPDvtx} [cm]");
       	mc_vtxZ->Scale(data_vtxZ->Integral()/mc_vtxZ->Integral());
	data_vtxZ->SetLineColor(4);
	data_vtxZ->SetLineWidth(2);
	data_vtxZ->SetLineStyle(2);
	mc_vtxZ->SetMaximum(TMath::Max(mc_vtxZ->GetMaximum(),data_vtxZ->GetMaximum())*1.2);
	cvtxZ->cd();
	mc_vtxZ->Draw("hist err");
	data_vtxZ->Draw("hist err same");

	mc_vtxXContributors->SetLineColor(2);
	mc_vtxXContributors->SetLineWidth(2);
	mc_vtxXContributors->GetYaxis()->SetTitleOffset(1.6);
	mc_vtxXContributors->GetYaxis()->SetTitle("Entries");
	mc_vtxXContributors->GetXaxis()->SetTitle("x_{SPDvtx (N. Contributors > 0)} [cm]");
       	mc_vtxXContributors->Scale(data_vtxXContributors->Integral()/mc_vtxXContributors->Integral());
	data_vtxXContributors->SetLineColor(4);
	data_vtxXContributors->SetLineWidth(2);
	data_vtxXContributors->SetLineStyle(2);
	mc_vtxXContributors->SetMaximum(TMath::Max(mc_vtxXContributors->GetMaximum(),data_vtxXContributors->GetMaximum())*1.2);
	cvtxXContributors->cd();
	mc_vtxXContributors->Draw("hist err");
	data_vtxXContributors->Draw("hist err same");

	mc_vtxYContributors->SetLineColor(2);
	mc_vtxYContributors->SetLineWidth(2);
	mc_vtxYContributors->GetYaxis()->SetTitleOffset(1.6);
	mc_vtxYContributors->GetYaxis()->SetTitle("Entries");
	mc_vtxYContributors->GetXaxis()->SetTitle("y_{SPDvtx (N. Contributors > 0)} [cm]");
	mc_vtxYContributors->Scale(data_vtxYContributors->Integral()/mc_vtxYContributors->Integral());
	data_vtxYContributors->SetLineColor(4);
	data_vtxYContributors->SetLineWidth(2);
	data_vtxYContributors->SetLineStyle(2);
	mc_vtxYContributors->SetMaximum(TMath::Max(mc_vtxYContributors->GetMaximum(),data_vtxYContributors->GetMaximum())*1.2);
	cvtxYContributors->cd();
	mc_vtxYContributors->Draw("hist err");
	data_vtxYContributors->Draw("hist err same");

	mc_vtxZContributors->SetLineColor(2);
	mc_vtxZContributors->SetLineWidth(2);
	mc_vtxZContributors->GetYaxis()->SetTitleOffset(1.6);
	mc_vtxZContributors->GetYaxis()->SetTitle("Entries");
	mc_vtxZContributors->GetXaxis()->SetTitle("z_{SPDvtx (N. Contributors > 0)} [cm]");
       	mc_vtxZContributors->Scale(data_vtxZContributors->Integral()/mc_vtxZContributors->Integral());
	data_vtxZContributors->SetLineColor(4);
	data_vtxZContributors->SetLineWidth(2);
	data_vtxZContributors->SetLineStyle(2);
	mc_vtxZContributors->SetMaximum(TMath::Max(mc_vtxZContributors->GetMaximum(),data_vtxZContributors->GetMaximum())*1.2);
	cvtxZContributors->cd();
	mc_vtxZContributors->Draw("hist err");
	data_vtxZContributors->Draw("hist err same");

	mc_HistFiredBitsSPD->SetLineColor(2);
	mc_HistFiredBitsSPD->SetLineWidth(2);
	mc_HistFiredBitsSPD->GetYaxis()->SetTitleOffset(1.2);
	mc_HistFiredBitsSPD->GetYaxis()->SetTitle("Entries");
       	mc_HistFiredBitsSPD->Scale(data_HistFiredBitsSPDCINT1B->Integral()/mc_HistFiredBitsSPD->Integral());
	data_HistFiredBitsSPDCINT1B->SetLineColor(4);
	data_HistFiredBitsSPDCINT1B->SetLineWidth(2);
	data_HistFiredBitsSPDCINT1B->SetLineStyle(2);
	mc_HistFiredBitsSPD->SetMaximum(TMath::Max(mc_HistFiredBitsSPD->GetMaximum(),data_HistFiredBitsSPDCINT1B->GetMaximum())*1.2);
	cSPDGFO->cd();
	mc_HistFiredBitsSPD->Draw("hist err");
	data_HistFiredBitsSPDCINT1B->Draw("hist err same");

	ratio_phi->SetLineWidth(2);
	ratio_phi->Divide(mc_phi,data_phi);
	ratio_phi->GetYaxis()->SetRangeUser(0.5,1.5);
	ratio_phi->GetYaxis()->SetTitleOffset(1.9);
	ratio_phi->GetYaxis()->SetTitle("Ratio");
	cratioPhi->cd();
	ratio_phi->Draw("hist");

	TPaveText* text = new TPaveText(0.2,1,0.8,0.9,"NDC");
	text->SetFillColor(0);
	text->AddText(Form("%s/%s",mc_path,data_path));
	text->Draw("same");

       	ratio_phiEta1->SetLineWidth(2);
	ratio_phiEta1->Divide(mc_phiEta1,data_phiEta1);
	ratio_phiEta1->GetYaxis()->SetRangeUser(0.5,1.5);
	ratio_phiEta1->GetYaxis()->SetTitleOffset(1.9);
	ratio_phiEta1->GetYaxis()->SetTitle("Ratio");
	cratioPhiEta1->cd();
	ratio_phiEta1->Draw("hist");

       	ratio_phiEtaNeg->SetLineWidth(2);
	ratio_phiEtaNeg->Divide(mc_phiEtaNeg,data_phiEtaNeg);
	ratio_phiEtaNeg->GetYaxis()->SetRangeUser(0.5,1.5);
	ratio_phiEtaNeg->GetYaxis()->SetTitleOffset(1.9);
	ratio_phiEtaNeg->GetYaxis()->SetTitle("Ratio");
	cratioPhiEtaNeg->cd();
	ratio_phiEtaNeg->Draw("hist");

       	ratio_phiEtaPos->SetLineWidth(2);
	ratio_phiEtaPos->Divide(mc_phiEtaPos,data_phiEtaPos);
	ratio_phiEtaPos->GetYaxis()->SetRangeUser(0.5,1.5);
	ratio_phiEtaPos->GetYaxis()->SetTitleOffset(1.9);
	ratio_phiEtaPos->GetYaxis()->SetTitle("Ratio");
	cratioPhiEtaPos->cd();
	ratio_phiEtaPos->Draw("hist");

	ratio_deltaPhi->SetLineWidth(2);
	ratio_deltaPhi->Divide(mc_deltaPhi,data_deltaPhi);
	ratio_deltaPhi->GetYaxis()->SetRangeUser(0.5,1.5);
	ratio_deltaPhi->GetXaxis()->SetRangeUser(-0.15,0.15);
	ratio_deltaPhi->GetYaxis()->SetTitleOffset(1.9);
	ratio_deltaPhi->GetYaxis()->SetTitle("Ratio");
	cratioDeltaPhi->cd();
	ratio_deltaPhi->Draw("hist");

	ratio_deltaTheta->SetLineWidth(2);
	ratio_deltaTheta->Divide(mc_deltaTheta,data_deltaTheta);
	ratio_deltaTheta->GetXaxis()->SetRangeUser(-0.05,0.05);
	ratio_deltaTheta->GetYaxis()->SetRangeUser(0.5,1.5);
	ratio_deltaTheta->GetYaxis()->SetTitleOffset(1.9);
	ratio_deltaTheta->GetYaxis()->SetTitle("Ratio");
	cratioDeltaTheta->cd();
	ratio_deltaTheta->Draw("hist");

	ratio_vtxX->SetLineWidth(2);
	ratio_vtxX->Divide(mc_vtxX,data_vtxX);
	ratio_vtxX->GetYaxis()->SetRangeUser(0.5,1.5);
	ratio_vtxX->GetYaxis()->SetTitleOffset(1.9);
	ratio_vtxX->GetYaxis()->SetTitle("Ratio");
	cratiovtxX->cd();
	ratio_vtxX->Draw("hist");

	ratio_vtxY->SetLineWidth(2);
	ratio_vtxY->Divide(mc_vtxY,data_vtxY);
	ratio_vtxY->GetYaxis()->SetRangeUser(0.5,1.5);
	ratio_vtxY->GetYaxis()->SetTitleOffset(1.9);
	ratio_vtxY->GetYaxis()->SetTitle("Ratio");
	cratiovtxY->cd();
	ratio_vtxY->Draw("hist");

	ratio_vtxZ->SetLineWidth(2);
	ratio_vtxZ->Divide(mc_vtxZ,data_vtxZ);
	ratio_vtxZ->GetYaxis()->SetRangeUser(0.5,1.5);
	ratio_vtxZ->GetYaxis()->SetTitleOffset(1.9);
	ratio_vtxZ->GetYaxis()->SetTitle("Ratio");
	cratiovtxZ->cd();
	ratio_vtxZ->Draw("hist");

	ratio_vtxXContributors->SetLineWidth(2);
	ratio_vtxXContributors->Divide(mc_vtxXContributors,data_vtxXContributors);
	ratio_vtxXContributors->GetYaxis()->SetRangeUser(0.5,1.5);
	ratio_vtxXContributors->GetYaxis()->SetTitleOffset(1.9);
	ratio_vtxXContributors->GetYaxis()->SetTitle("Ratio");
	cratiovtxXContributors->cd();
	ratio_vtxXContributors->Draw("hist");

	ratio_vtxYContributors->SetLineWidth(2);
	ratio_vtxYContributors->Divide(mc_vtxYContributors,data_vtxYContributors);
	ratio_vtxYContributors->GetYaxis()->SetRangeUser(0.5,1.5);
	ratio_vtxYContributors->GetYaxis()->SetTitleOffset(1.9);
	ratio_vtxYContributors->GetYaxis()->SetTitle("Ratio");
	cratiovtxYContributors->cd();
	ratio_vtxYContributors->Draw("hist");

	ratio_vtxZContributors->SetLineWidth(2);
	ratio_vtxZContributors->Divide(mc_vtxZContributors,data_vtxZContributors);
	ratio_vtxZContributors->GetYaxis()->SetRangeUser(0.5,1.5);
	ratio_vtxZContributors->GetYaxis()->SetTitleOffset(1.9);
	ratio_vtxZContributors->GetYaxis()->SetTitle("Ratio");
	cratiovtxZContributors->cd();
	ratio_vtxZContributors->Draw("hist");

	ratio_HistFiredBitsSPD->SetLineWidth(2);
	ratio_HistFiredBitsSPD->Divide(mc_HistFiredBitsSPD,data_HistFiredBitsSPDCINT1B);
	ratio_HistFiredBitsSPD->GetYaxis()->SetRangeUser(0.5,1.5);
	ratio_HistFiredBitsSPD->GetYaxis()->SetTitleOffset(1.9);
	ratio_HistFiredBitsSPD->GetYaxis()->SetTitle("Ratio");
	cratioSPDGFO->cd();
	ratio_HistFiredBitsSPD->Draw("hist");

	cEta->cd();
	cEta->Print(Form("Plots/Plots_%s/eta.gif",mc_path));
	cEta->Print(Form("Plots/Plots_%s/eta.eps",mc_path));
	cPhi->cd();
	cPhi->Print(Form("Plots/Plots_%s/phi.gif",mc_path));
	cPhi->Print(Form("Plots/Plots_%s/phi.eps",mc_path));
	cPhiEta1->cd();
	cPhiEta1->Print(Form("Plots/Plots_%s/phiEta1.gif",mc_path));
	cPhiEta1->Print(Form("Plots/Plots_%s/phiEta1.eps",mc_path));
	cPhiEtaNeg->cd();
	cPhiEtaNeg->Print(Form("Plots/Plots_%s/phiEtaNeg.gif",mc_path));
	cPhiEtaNeg->Print(Form("Plots/Plots_%s/phiEtaNeg.eps",mc_path));
	cPhiEtaPos->cd();
	cPhiEtaPos->Print(Form("Plots/Plots_%s/phiEtaPos.gif",mc_path));
	cPhiEtaPos->Print(Form("Plots/Plots_%s/phiEtaPos.eps",mc_path));
	cDeltaPhi->cd();
	cDeltaPhi->Print(Form("Plots/Plots_%s/deltaPhi.gif",mc_path));
	cDeltaPhi->Print(Form("Plots/Plots_%s/deltaPhi.eps",mc_path));
	cDeltaTheta->cd();
	cDeltaTheta->Print(Form("Plots/Plots_%s/deltaTheta.gif",mc_path));
	cDeltaTheta->Print(Form("Plots/Plots_%s/deltaTheta.eps",mc_path));
	cvtxX->cd();
	cvtxX->Print(Form("Plots/Plots_%s/vtxX.gif",mc_path));
	cvtxX->Print(Form("Plots/Plots_%s/vtxX.eps",mc_path));
	cvtxY->cd();
	cvtxY->Print(Form("Plots/Plots_%s/vtxY.gif",mc_path));
	cvtxY->Print(Form("Plots/Plots_%s/vtxY.eps",mc_path));
	cvtxZ->cd();
	cvtxZ->Print(Form("Plots/Plots_%s/vtxZ.gif",mc_path));
	cvtxZ->Print(Form("Plots/Plots_%s/vtxZ.eps",mc_path));
	cvtxXContributors->cd();
	cvtxXContributors->Print(Form("Plots/Plots_%s/vtxXContributors.gif",mc_path));
	cvtxXContributors->Print(Form("Plots/Plots_%s/vtxXContributors.eps",mc_path));
	cvtxYContributors->cd();
	cvtxYContributors->Print(Form("Plots/Plots_%s/vtxYContributors.gif",mc_path));
	cvtxYContributors->Print(Form("Plots/Plots_%s/vtxYContributors.eps",mc_path));
	cvtxZContributors->cd();
	cvtxZContributors->Print(Form("Plots/Plots_%s/vtxZContributors.gif",mc_path));
	cvtxZContributors->Print(Form("Plots/Plots_%s/vtxZContributors.eps",mc_path));
	cSPDGFO->cd();
	cSPDGFO->Print(Form("Plots/Plots_%s/SPDGFO.gif",mc_path));
	cSPDGFO->Print(Form("Plots/Plots_%s/SPDGFO.eps",mc_path));

	cratioPhi->cd();
	cratioPhi->Print(Form("Plots/Plots_%s/ratiophi.gif",mc_path));
	cratioPhi->Print(Form("Plots/Plots_%s/ratiophi.eps",mc_path));
	cratioPhiEta1->cd();
	cratioPhiEta1->Print(Form("Plots/Plots_%s/ratiophiEta1.gif",mc_path));
	cratioPhiEta1->Print(Form("Plots/Plots_%s/ratiophiEta1.eps",mc_path));
	cratioPhiEtaNeg->cd();
	cratioPhiEtaNeg->Print(Form("Plots/Plots_%s/ratiophiEtaNeg.gif",mc_path));
	cratioPhiEtaNeg->Print(Form("Plots/Plots_%s/ratiophiEtaNeg.eps",mc_path));
	cratioPhiEtaPos->cd();
	cratioPhiEtaPos->Print(Form("Plots/Plots_%s/ratiophiEtaPos.gif",mc_path));
	cratioPhiEtaPos->Print(Form("Plots/Plots_%s/ratiophiEtaPos.eps",mc_path));
	cratioDeltaPhi->cd();
	cratioDeltaPhi->Print(Form("Plots/Plots_%s/ratiodeltaPhi.gif",mc_path));
	cratioDeltaPhi->Print(Form("Plots/Plots_%s/ratiodeltaPhi.eps",mc_path));
	cratioDeltaTheta->cd();
	cratioDeltaTheta->Print(Form("Plots/Plots_%s/ratiodeltaTheta.gif",mc_path));
	cratioDeltaTheta->Print(Form("Plots/Plots_%s/ratiodeltaTheta.eps",mc_path));
	cratiovtxX->cd();
	cratiovtxX->Print(Form("Plots/Plots_%s/ratiovtxX.gif",mc_path));
	cratiovtxX->Print(Form("Plots/Plots_%s/ratiovtxX.eps",mc_path));
	cratiovtxY->cd();
	cratiovtxY->Print(Form("Plots/Plots_%s/ratiovtxY.gif",mc_path));
	cratiovtxY->Print(Form("Plots/Plots_%s/ratiovtxY.eps",mc_path));
	cratiovtxZ->cd();
	cratiovtxZ->Print(Form("Plots/Plots_%s/ratiovtxZ.gif",mc_path));
	cratiovtxZ->Print(Form("Plots/Plots_%s/ratiovtxZ.eps",mc_path));
	cratiovtxXContributors->cd();
	cratiovtxXContributors->Print(Form("Plots/Plots_%s/ratiovtxXContributors.gif",mc_path));
	cratiovtxXContributors->Print(Form("Plots/Plots_%s/ratiovtxXContributors.eps",mc_path));
	cratiovtxYContributors->cd();
	cratiovtxYContributors->Print(Form("Plots/Plots_%s/ratiovtxYContributors.gif",mc_path));
	cratiovtxYContributors->Print(Form("Plots/Plots_%s/ratiovtxYContributors.eps",mc_path));
	cratiovtxZContributors->cd();
	cratiovtxZContributors->Print(Form("Plots/Plots_%s/ratiovtxZContributors.gif",mc_path));
	cratiovtxZContributors->Print(Form("Plots/Plots_%s/ratiovtxZContributors.eps",mc_path));
	cratioSPDGFO->cd();
	cratioSPDGFO->Print(Form("Plots/Plots_%s/ratioSPDGFO.gif",mc_path));
	cratioSPDGFO->Print(Form("Plots/Plots_%s/ratioSPDGFO.eps",mc_path));

	TFile* plotsfile = new TFile(Form("Plots/Plots_%s/plots.root",mc_path),"RECREATE");
	mc_eta->Write();
	mc_phi->Write();
	mc_phiEta1->Write();
	mc_phiEtaNeg->Write();
	mc_phiEtaPos->Write();
	mc_deltaPhi->Write();
	mc_deltaTheta->Write();
	mc_vtxX->Write();
	mc_vtxY->Write();
	mc_vtxZ->Write();
	mc_vtxXContributors->Write();
	mc_vtxYContributors->Write();
	mc_vtxZContributors->Write();
	mc_HistFiredBitsSPD->Write();
	data_eta->Write();
	data_phi->Write();
	data_phiEta1->Write();
	data_phiEtaNeg->Write();
	data_phiEtaPos->Write();
	data_deltaPhi->Write();
	data_deltaTheta->Write();
	data_vtxX->Write();
	data_vtxY->Write();
	data_vtxZ->Write();
	data_vtxXContributors->Write();
	data_vtxYContributors->Write();
	data_vtxZContributors->Write();
	data_HistFiredBitsSPDCINT1B->Write();
	data_HistFiredBitsSPDCINT1A->Write();
	data_HistFiredBitsSPDCINT1C->Write();
	data_HistFiredBitsSPDCINT1E->Write();
	ratio_phi->Write();
	ratio_phiEta1->Write();
	ratio_phiEtaNeg->Write();
	ratio_phiEtaPos->Write();
	ratio_deltaPhi->Write();
	ratio_deltaTheta->Write();
	ratio_vtxX->Write();
	ratio_vtxY->Write();
	ratio_vtxZ->Write();
	ratio_vtxXContributors->Write();
	ratio_vtxYContributors->Write();
	ratio_vtxZContributors->Write();
	ratio_HistFiredBitsSPD->Write();
	plotsfile->Close();
}



