#!/bin/bash

#1: space charge file
#2: output dir

mapFile=$1
outDir=$2

module use /cvmfs/alice.gsi.de/modules
module purge
#module load ALICE/${vers}
module use -a /hera/alice/wiechula/software/modules
module load TPCdev

declare -i job=$SGE_TASK_ID
job=$job-1

mapName=$(basename $mapFile .root)
outFile=$outDir/${mapName}.$(printf "%03d" $job).root

root.exe -l -b -q $ALICE_ROOT/TPC/Upgrade/macros/{loadlibs.C,ConfigOCDB.C} $ALICE_ROOT/TPC/Upgrade/CreateLookup.C\(\"$1\"\,\"$outFile\",$job)