///
/// \file PWGCF/FEMTOSCOPY/macros/Train/LambdaKaonFemto/AddTaskLambdaKaon.C
/// \author Jesse Buxton, Ohio State University, jesse.thomas.buxton@cern.ch
///
/// \ but based largely off of work done by Andrew Kubera in
/// \ file PWGCF/FEMTOSCOPY/macros/Train/PionPionFemto/AddTaskPionPion.C
/// \   Andrew Kubera, Ohio State University, andrew.kubera@cern.ch
///
//## Documentation from Andrew Kubera 
//## \brief Adds an AliAnalysisTaskFemto analysis object, constructed
//##        with parameters provided, to the global AliAnalysisManager.
//##
//## This macro creates and returns an AliAnalysisTaskFemto object.
//## The task object is given a macro
//## is given the config macro "Train/PionPionFemto/ConfigFemtoAnalysis.C"
//## which is run to create the analysis objects. This is fixed (for now), and
//## if an alternative is required, you should use the general AddTaskFemto.C
//## macro.
//##
//## Subwagons are supported, the name of which will be appended to the task
//## name. The task name by default is "TaskPionPionFemto" which cannot be changed.
//##
//## The output container name is fixed at the standard "femtolist".
//##
//## \param configuration
//##     A string containing commands to execute, separated by semicolons.
//##     Assign the old parameters using this command.
//##     Single quotes are turned to double quotes.
//##
//##     * macro_path: Path to the FemtoConfig macro to load; "%%" is expaneded
//##                   to directory containing this file.
//##     * output_filename: Name of the output file to produce.
//##                   Default generated by AliAnalysisManager::GetCommonFileName()
//##     * output_container: Name of top-level ROOT directory in the output file.
//##                   Default PWG2FEMTO.
//##     * container_name: Name of the AliAnalysis container.
//##     * task_name: Name of the AliAnalysisTask - May need to be unique...
//##     * verbose: Task created in verbose mode
//##
//## \param params
//##     A string forwarded to the ConfigFemtoAnalysis macro for parsing.
//##     This string is wrapped in double-quotes so escaping some to
//##     ensure results is a string is unneccessary.
//##
//## \param subwagon_suffix
//##     If this macro is run in a train with subwagons, this will be
//##     set with the identifier.
//##

AliAnalysisTaskFemto* AddTaskLambdaKaon(TString aConfiguration,
                                        TString aParams,
                                        TString aSubwagonSuffix="")
{ // Adds a Lambda-Kaon Femtoscopy task to the manager

  const TString AUTO_DIRECTORY = "$ALICE_PHYSICS/PWGCF/FEMTOSCOPY/macros/Train/LambdaKaonFemto"
              , DEFAULT_MACRO = "%%/ConfigFemtoAnalysis.C"
              , DEFAULT_CONTAINER_NAME = "LambdaKaon_femtolist"
              , DEFAULT_OUTPUT_CONTAINER = "PWG2FEMTO"
              , DEFAULT_TASK_NAME = "TaskLambdaKaon"
              ;


  // Get the pointer to the existing analysis manager via the static access method.
  AliAnalysisManager *mgr = AliAnalysisManager::GetAnalysisManager();
  if (!mgr) {
    Error("AddTaskLambdaKaon", "No analysis manager to connect to.");
    return NULL;
  }

  // Check the analysis type using the event handlers connected to the analysis
  // manager. The availability of MC handler cann also be checked here.
  if (!mgr->GetInputEventHandler()) {
    ::Error("AddTaskFemto", "This task requires an input event handler");
    return NULL;
  }
  TString type = mgr->GetInputEventHandler()->GetDataType(); // can be "ESD" or "AOD"
  cout << "Found " <<type << " event handler" << endl;

  TString tMacroPath = DEFAULT_MACRO
        , tOutputFilename = mgr->GetCommonFileName()
        , tTaskName = DEFAULT_TASK_NAME
        , tContainerName = DEFAULT_CONTAINER_NAME
        , tOutputContainerName = DEFAULT_OUTPUT_CONTAINER
        ;

  bool tVerbose = kFALSE;

  TObjArray* tLines = aConfiguration.Tokenize("\n;");
  TIter tNextLine(tLines);
  TObject *tLineObj = NULL;

  while(tLineObj = tNextLine())
  {
    TString tCmd = ((TObjString*)tLineObj)->String().Strip(TString::kBoth, ' ');
    tCmd.ReplaceAll("'", '"');
    gROOT->ProcessLineFast(tCmd + ';');
  }


  // Replace %% with this directory for convenience
  tMacroPath.ReplaceAll("%%", AUTO_DIRECTORY);

  cout << "[AddTaskLambdaKaon]\n"
          "   output: '" << tOutputFilename << "'\n"
          "   macro: '" << tMacroPath << "'\n"
          "   params: '" << aParams << "'\n";

  // The analysis config macro for LambdaKaonFemto accepts a single string
  // argument, which it interprets.
  // This line escapes some escapable characters (backslash, newline, tab)
  // and wraps that string in double quotes, ensuring that the interpreter
  // reads a string when passing to the macro.
  const TString tAnalysisParams = '"' + aParams.ReplaceAll("\\", "\\\\")
                                               .ReplaceAll("\n", "\\n")
                                               .ReplaceAll("\t", "\\t") + '"';

  AliAnalysisTaskFemto *tTaskFemto = new AliAnalysisTaskFemto(
    tTaskName,
    tMacroPath,
    tAnalysisParams,
    tVerbose
  );

  tTaskFemto->SelectCollisionCandidates(AliVEvent::kMB | AliVEvent::kCentral | AliVEvent::kSemiCentral);
  mgr->AddTask(tTaskFemto);

  const TString tOutputFile = (tOutputContainerName == "")
                            ? tOutputFilename
                            : TString::Format("%s:%s", tOutputFilename.Data(), tOutputContainerName.Data());

  AliAnalysisDataContainer *tOutContainer = mgr->CreateContainer(tContainerName,
                                                                 TList::Class(),
                                                                 AliAnalysisManager::kOutputContainer,
                                                                 tOutputFile);

  // connect task to the containers
  mgr->ConnectInput(tTaskFemto, 0, mgr->GetCommonInputContainer());
  mgr->ConnectOutput(tTaskFemto, 0, tOutContainer);

  // Return the task pointer
  return tTaskFemto;


}
