//_____________________________________________________________________
AliAnalysisTaskEmcalJetDijetMass *AddTaskEmcalJetDijetMass(
                                    const char *ntracks            = "usedefault",
                                    const char *nclusters          = "usedefault",
                                    const char* ncells             = "usedefault",
                                    const char *suffix             = "",
                                    TString taskName,
                                    Bool_t isMC,
                                    TString sJCatalyst        = "JCatalystTask",
                                    TString sJCatalystDetMC   = "JCatalystDetMCTask",
                                    UInt_t flags              = 0,
                                    TString centBins          = "0.0 5.0 10.0 20.0 30.0 40.0 50.0 60.0 70.0",
                                    double jetCone            = 0.4,
                                    double ktjetCone          = 0.4,
                                    int ktScheme              = 1,
                                    int antiktScheme          = 1,
                                    Bool_t usePionMass        = false,
                                    Bool_t useDeltaPhiBGSubtr = true,
                                    double particleEtaCut     = 0.8,
                                    double particlePtCut      = 0.15,
                                    double leadingJetCut      = 20.0,
                                    double subleadingJetCut   = 20.0,
                                    double minJetPt           = 10.0,
                                    double constituentCut     = 5.0,
                                    double deltaPhiCut        = 2.0,
                                    double matchingR          = 0.2,
                                    double trackingIneff      = 0.0){
  return AliAnalysisTaskEmcalJetDijetMass::AddTaskEmcalJetDijetMass(
      ntracks,
      nclusters,
      ncells,
      suffix,
      taskName,
      isMC,
      sJCatalyst,
      sJCatalystDetMC,
      flags,
      centBins,
      jetCone,
      ktScheme,
      antiktScheme,
      usePionMass,
      useDeltaPhiBGSubtr,
      particleEtaCut,
      particlePtCut,
      leadingJetCut,
      subleadingJetCut,
      minJetPt,
      constituentCut,
      deltaPhiCut,
      matchingR
      trackingIneff
      );
}
