/**
 * @file   MakeMultDistsTrain.C
 * @author Christian Holm Christensen <cholm@master.hehi.nbi.dk>
 * @date   Fri Jun  1 13:51:26 2012
 * 
 * @brief  
 * 
 * @ingroup pwglf_forward_trains_specific
 * 
 */

#include "TrainSetup.C"

//====================================================================
/**
 * Analysis train to make @f$ dN/d\eta@f$
 * 
 *
 * @ingroup pwglf_forward_dndeta
 * @ingroup pwglf_forward_trains_specific
 */
class MakeMultDistsTrain : public TrainSetup
{
public:
  /** 
   * Constructor.  
   * 
   * @param name     Name of train (free form)
   */
  MakeMultDistsTrain(const char* name)
  : TrainSetup(name)
  {
    fOptions.Add("trig",       "TYPE", "Trigger type", "V0AND");
    fOptions.Add("vzMin",      "CENTIMETER", "Min Ip Z", -4);
    fOptions.Add("vzMax",      "CENTIMETER", "Max Ip Z", +4);
    fOptions.Add("max-n",      "NUMBER", "Maximum Nch", 150);
    fOptions.Add("phi-acc",    "Use stored phi acceptance", true);
    fOptions.Add("asymmetric", "Make asymmetric (+/-) bins", true);
  }
protected:
  /** 
   * Create the tasks 
   * 
   */
  void CreateTasks(AliAnalysisManager*)
  {
    // --- Output file name ------------------------------------------
    AliAnalysisManager::SetCommonFileName("forward_multdists.root");

    // --- Load libraries/pars ---------------------------------------
    fHelper->LoadLibrary("PWGLFforward2");
    
    // --- Set load path ---------------------------------------------
    gROOT->SetMacroPath(Form("%s:$(ALICE_ROOT)/PWGLF/FORWARD/analysis2",
			     gROOT->GetMacroPath()));

    // --- Get parameters --------------------------------------------
    TString  trig   = fOptions.AsString("trig", "V0AND");
    Double_t vzMin  = fOptions.AsDouble("vzmin", -4);
    Double_t vzMax  = fOptions.AsDouble("vzmax", +4);
    Int_t    maxN   = fOptions.AsInt("max-n", 150);
    Bool_t   phiAcc = fOptions.AsBool("phi-acc");
    Bool_t   aSymm  = fOptions.AsBool("asymmetric");

    // --- Form arguments --------------------------------------------
    TString args;
    args.Form("\"%s\",%f,%f,%d,%d,%d",
	      trig.Data(), vzMin, vzMax, maxN, phiAcc, aSymm);
    // --- Add the task ----------------------------------------------
    gROOT->Macro(Form("AddTaskForwardMultDists.C(%s);", args.Data()));
  }
  //__________________________________________________________________
  /** 
   * Do not the centrality selection
   */
  //__________________________________________________________________
  void CreateCentralitySelection(Bool_t, AliAnalysisManager*) {}
  /** 
   * Do not create MC input handler 
   * 
   * @return Always null
   */
  AliVEventHandler* CreateMCHandler(UShort_t, bool) { return 0; }
  //__________________________________________________________________
  /** 
   * Crete output handler - we don't want one here. 
   * 
   * @return 0
   */
  AliVEventHandler* CreateOutputHandler(UShort_t) { return 0; }
  //__________________________________________________________________
  const char* ClassName() const { return "MakeMultDistsTrain"; }
  //__________________________________________________________________
  /** 
   * Overloaded to create new draw.C 
   * 
   * @param asShellScript 
   */
  void SaveSetup(Bool_t asShellScript)
  {
    TrainSetup::SaveSetup(asShellScript);

    SaveSummarize();
  }
  void SaveSummarize()
  {
    std::ofstream f("Summarize.C");
    if (!f) { 
      Error("SaveSummarize", "Failed to open Summarize.C script");
      return;
    }
    f << "// Generated by " << ClassName() << "\n"
      << "// WHAT is a bit mask of\n"
      << "//   0x001     Forward\n"
      << "//   0x002     Central\n"
      << "//   0x004     Sums\n"
      << "//   0x008     Results\n"
      << "//   0x010     Only min-bias (no centrality)\n"
      << "//   0x020     Landscape\n"
      << "//   0x040     Pause\n"
      << "//\n"
      << "void Summarize(const char* filename=\"forward_multdists.root\",\n"
      << "               UShort_t what=0xF)\n"
      << "{\n"
      << "  gROOT->LoadMacro(\"$ALICE_ROOT/PWGLF/FORWARD/analysis2/DrawMultDistsSummary.C\");\n"
      << "  DrawMultDistsSummary(filename,what);\n"
      << "}\n"
      << "// EOF" << std::endl;
    f.close();
  }
};
//
// EOF
//
