/**
 * @file   MakeFMDELossTrain.C
 * @author Christian Holm Christensen <cholm@master.hehi.nbi.dk>
 * @date   Fri Jun  1 13:53:02 2012
 * 
 * @brief  
 * 
 * 
 * @ingroup pwglf_forward_trains_specific
 */
#include "TrainSetup.C"

//====================================================================
/**
 * Analysis train to do energy loss fits
 * 
 * @ingroup pwglf_forward_trains_specific
 * @ingroup pwglf_forward_eloss
 */
class MakeFMDELossTrain : public TrainSetup
{
public:
  /** 
   * Constructor.  
   * 
   * @param name     Name of train 
   */
  MakeFMDELossTrain(const char* name  = "FMD Energy Loss")
    : TrainSetup(name)
  {
    fOptions.Add("cent", "Use centrality");
  }
protected:
  //------------------------------------------------------------------
  /** 
   * Create the analysis manager 
   * 
   * @param name Name of the analysis 
   * 
   * @return Created analysis manager 
   */
  virtual AliAnalysisManager* CreateAnalysisManager(const char* name)
  {
    AliAnalysisManager* mgr = TrainSetup::CreateAnalysisManager(name);
    // mgr->SetAutoBranchLoading(false);
    return mgr;
  }
  //__________________________________________________________________
  /** 
   * Create the tasks 
   * 
   * @param mgr  Analysis manager 
   */
  void CreateTasks(AliAnalysisManager* mgr)
  {
    // --- Output file name ------------------------------------------
    AliAnalysisManager::SetCommonFileName("forward_eloss.root");

    // --- Load libraries/pars ---------------------------------------
    fHelper->LoadLibrary("PWGLFforward2");
    
    // --- Set load path ---------------------------------------------
    gROOT->SetMacroPath(Form("%s:$(ALICE_ROOT)/PWGLF/FORWARD/analysis2",
			     gROOT->GetMacroPath()));

    // --- Check if this is MC ---------------------------------------
    Bool_t mc   = mgr->GetMCtruthEventHandler() != 0;
    Bool_t cent = fOptions.Has("cent");

    // --- Add the task ----------------------------------------------
    gROOT->Macro(Form("AddTaskFMDELoss.C(%d,%d)", mc, cent));
  }
  /** 
   * Create entrality selection if enabled 
   * 
   * @param mc   Whether this is MC or not
   * @param mgr  Analysis manager 
   */
  virtual void CreateCentralitySelection(Bool_t mc, AliAnalysisManager* mgr)
  {
    if (!fOptions.Has("cent")) return;

    const char* name = "CentralitySelection";
    gROOT->Macro("AddTaskCentrality.C");
    AliCentralitySelectionTask* ctask = 
      dynamic_cast<AliCentralitySelectionTask*>(mgr->GetTask(name));
    if (!ctask) return;
    // ctask->SetPass(fESDPass);
    if (mc) ctask->SetMCInput();
  }
  /** 
   * Crete output handler - we don't want one here. 
   * 
   * @return 0
   */
  AliVEventHandler* CreateOutputHandler(UShort_t) { return 0; }

  //__________________________________________________________________
  const char* ClassName() const { return "MakeFMDElossTrain"; }
  //__________________________________________________________________
  /** 
   * Overloaded to create new Extract.C in the output 
   * directory
   * 
   * @param asShellScript 
   */
  void SaveSetup(Bool_t asShellScript)
  {
    TrainSetup::SaveSetup(asShellScript);

    std::ofstream f("Extract.C");
    if (!f) { 
      Error("SaveSetup", "Failed to open Extract.C");
      return;
    }
    f << "// Generated by " << ClassName() << "\n"
      << "void Extract()\n"
      << "{\n"
      << "  gROOT->LoadMacro(\"$ALICE_ROOT/PWGLF/FORWARD/analysis2/corrs/ExtractELoss.C\");\n"
      << "  ExtractELoss(\"forward_eloss.root\"," 
      <<  fHelper->IsMC() << ");\n"
      << "}\n"
      << "// EOF" << std::endl;
    f.close();
  }
};

//
// EOF
//
