/**
 * @file   MakedNdetaTrain.C
 * @author Christian Holm Christensen <cholm@master.hehi.nbi.dk>
 * @date   Fri Jun  1 13:51:26 2012
 * 
 * @brief  
 * 
 * @ingroup pwglf_forward_trains_specific
 * 
 */

#include "TrainSetup.C"

//====================================================================
/**
 * Analysis train to make @f$ dN/d\eta@f$
 * 
 *
 * @ingroup pwglf_forward_dndeta
 * @ingroup pwglf_forward_trains_specific
 */
class MakedNdetaTrain : public TrainSetup
{
public:
  /** 
   * Constructor.  
   * 
   * @param name     Name of train (free form)
   */
  MakedNdetaTrain(const char* name)
  : TrainSetup(name)
  {
    fOptions.Add("trig",     "TYPE", "Trigger type", "INEL");
    fOptions.Add("vzMin",    "CENTIMETER", "Min Ip Z", "-10");
    fOptions.Add("vzMax",    "CENTIMETER", "Max Ip Z", "+10");
    fOptions.Add("scheme",   "SCHEME", "Normalization scheme", "");
    fOptions.Add("trigEff",  "EFFICENCY", "Trigger effeciency", "1");
    fOptions.Add("trigEff0", "EFFICENCY", "0-bin trigger effeciency", "1");
    fOptions.Add("cent",     "Use centrality");
    fOptions.Add("cut-edges", "Cut acceptance edges");
    fOptions.Add("corr-empty", "Correct for empty bins (deprecated)");
    fOptions.Add("mc",       "Also make dN/deta for MC truth");
    fOptions.Add("mc-corr",  "FILE", "MC corrections file", "");
    fOptions.Add("satellite","Restrict analysis to satellite events", false);
  }
protected:
  /** 
   * Create the tasks 
   * 
   */
  void CreateTasks(AliAnalysisManager*)
  {
    // --- Output file name ------------------------------------------
    AliAnalysisManager::SetCommonFileName("forward_dndeta.root");

    // --- Load libraries/pars ---------------------------------------
    fHelper->LoadLibrary("PWGLFforward2");
    
    // --- Set load path ---------------------------------------------
    gROOT->SetMacroPath(Form("%s:$(ALICE_ROOT)/PWGLF/FORWARD/analysis2",
			     gROOT->GetMacroPath()));

    // --- Get parameters --------------------------------------------
    TString  trig    = fOptions.Get("trig");
    TString  scheme  = fOptions.Get("scheme");
    Double_t vzMin   = fOptions.AsDouble("vzmin", -10);
    Double_t vzMax   = fOptions.AsDouble("vzmax", +10);
    Double_t effT    = fOptions.AsDouble("trigEff", 1);
    Double_t effT0   = fOptions.AsDouble("trigEff0", 1);
    Bool_t   cent    = fOptions.Has("cent");
    Bool_t   edges   = fOptions.Has("cut-edges");
    Bool_t   corrEm  = fOptions.Has("corr-empty");
    Bool_t   mc      = fOptions.Has("mc");
    TString  mccorr  = fOptions.AsString("mc-corr", "");
    Bool_t   satonly = fOptions.AsBool("satellite");

    // --- Form arguments --------------------------------------------
    TString args;
    args.Form("\"%s\",%f,%f,%d,\"%s\",%d,%g,%g,%d",
	      trig.Data(), vzMin, vzMax, cent, scheme.Data(),
	      edges, effT, effT0, corrEm);
    TString fargs(args);
    fargs.Append(Form(",%d,\"%s\"",satonly, mccorr.Data()));

    // --- Add the task ----------------------------------------------
    gROOT->Macro(Form("AddTaskForwarddNdeta.C(%s);", fargs.Data()));
    gROOT->Macro(Form("AddTaskCentraldNdeta.C(%s);", args.Data()));
    if (mc) 
      gROOT->Macro(Form("AddTaskMCTruthdNdeta.C(%s);", args.Data()));
  }
  //__________________________________________________________________
  /** 
   * Do not the centrality selection
   */
  //__________________________________________________________________
  void CreateCentralitySelection(Bool_t, AliAnalysisManager*) {}
  /** 
   * Do not create MC input handler 
   * 
   * @return Always null
   */
  AliVEventHandler* CreateMCHandler(UShort_t, bool) { return 0; }
  //__________________________________________________________________
  /** 
   * Crete output handler - we don't want one here. 
   * 
   * @return 0
   */
  AliVEventHandler* CreateOutputHandler(UShort_t) { return 0; }
  //__________________________________________________________________
  const char* ClassName() const { return "MakedNdetaTrain"; }
  //__________________________________________________________________
  /** 
   * Overloaded to create new draw.C 
   * 
   * @param asShellScript 
   */
  void SaveSetup(Bool_t asShellScript)
  {
    TrainSetup::SaveSetup(asShellScript);

    SaveDraw();
    SaveSummarize();
  }
  void SaveSummarize()
  {
    std::ofstream f("Summarize.C");
    if (!f) { 
      Error("SaveSummarize", "Failed to open Summarize.C script");
      return;
    }
    f << "// Generated by " << ClassName() << "\n"
      << "// WHAT is a bit mask of\n"
      << "//   0x001     Forward\n"
      << "//   0x002     Central\n"
      << "//   0x004     Sums\n"
      << "//   0x008     Results\n"
      << "//   0x010     Only min-bias (no centrality)\n"
      << "//   0x080     Assume simulation results\n"
      << "//   0x100     Landscape\n"
      << "//   0x200     Pause\n"
      << "//   0x400     Also draw single result canvas\n"
      << "//\n"
      << "void Summarize(const char* filename=\"forward_dndeta.root\",\n"
      << "               UShort_t what=0x10F)\n"
      << "{\n"
      << "  const char* fwd=\"$ALICE_ROOT/PWGLF/FORWARD/analysis2\";\n"
      << "  gROOT->LoadMacro(Form(\"%s/DrawdNdetaSummary.C\",fwd));\n"
      << "  DrawdNdetaSummary(filename,what & 0x3FF);\n"
      << "\n"
      << "  if (!(what & 0x400)) return;\n"
      << "  gROOT->SetMacroPath(Form(\"../:%s\",gROOT->GetMacroPath()));\n"
      << "  gROOT->Macro(\"Draw.C\");\n"
      << "}\n"
      << "// EOF" << std::endl;
    f.close();
  }
  /** 
   * Make a ROOT script to draw results 
   * 
   */
  void SaveDraw()
  {
    std::ofstream o("Draw.C");
    if (!o) { 
      Error("MakedNdetaTrain::SaveSetup", "Failed to open Draw.C");
      return;
    }

    o << "// Created by " << ClassName() << "\n"
      << "// \n"
      << "// Will draw dN/deta results from produced file\n"
      << "// \n"
      << "// Options can be specified as needed. To get help, pass the\n"
      << "// string \"help\" for the title:\n"
      << "// \n"
      << "//   root -l Draw.C\\(\\\"help\\\"\\)\n"
      << "// \n";
    o << "void Draw(const TString& title=\"" << fName << "\",\n"
      << "          UShort_t       rebin=5,\n"
      << "          UShort_t       others=0xf,\n"
      << "          UShort_t       flags=0xCE07,\n"
      << "          UShort_t       sNN=0,\n"
      << "          UShort_t       sys=0,\n"
      << "          UShort_t       trg=0,\n"
      << "          Float_t        eff=0,\n"
      << "          UShort_t       centMin=0,\n"
      << "          UShort_t       centMax=100,\n"
      << "          Float_t        vzMin=999,\n"
      << "          Float_t        vzMax=-999)\n"
      << "{\n"
      << "  const char* fwd=\"$ALICE_ROOT/PWGLF/FORWARD/analysis2\";\n"
      << "  gROOT->LoadMacro(Form(\"%s/DrawdNdeta.C++\",fwd));\n"
      << "  if (title.EqualTo(\"help\",TString::kIgnoreCase)) {\n"
      << "    DrawdNdeta(\"help\"); // Get the help\n"
      << "    return;\n"
      << "  }\n\n"
      << "  DrawdNdeta(\"forward_dndeta.root\",\n"
      << "             title,\n"
      << "             rebin,\n"
      << "             others,\n"
      << "             flags,\n"
      << "             sNN,\n"
      << "             sys,\n"
      << "             trg,\n"
      << "             eff,\n"
      << "             centMin,\n"
      << "             centMax,\n"
      << "             vzMin,\n"
      << "             vzMax,\n"
      <<"              \"dNdeta_<trig>\");\n"
      << "}\n"
      << "//\n"
      << "// EOF\n"
      << "//" << std::endl;
    o.close();
  }
  void PostShellCode(std::ostream& f)
  {
    f << "  echo \"=== Summarizing results ...\"\n"
      << "  aliroot -l -b -q ${prefix}Summarize.C\n"
      << "  echo \"=== Draw results ...\"\n"
      << "  aliroot -l -b -q ${prefix}Draw.C\n"
      << std::endl;
  }
};
//
// EOF
//
