EmcalTriggerJets::AliAnalysisTaskEmcalTriggerJets *EmcalTriggerJets::AliAnalysisTaskEmcalTriggerCorrelationMC::AddTaskEmcalTriggerCorrelationMC(const char *suffix){
  return EmcalTriggerJets::AliAnalysisTaskEmcalTriggerCorrelationMC::AddTaaskEmcalTriggerCorrelationMC(suffix);
}
