EMCalTriggerPtAnalysis::AliAnalysisTaskEmcalClusterNoiseTriggers *AddTaskEmcalClusterNoiseTriggers(const char *suffix){
  return EMCalTriggerPtAnalysis::AliAnalysisTaskEmcalClusterNoiseTriggers::AddTaskEmcalClusterNoiseTriggers(suffix);
}