/*********************************************************************************************************
  Example macro to launch analysis plugin for rsn analysis
  Created by fbellini@cern.ch, 19/09/2014

Usage: 
- Modify the main settings (see description below) 
  IMPORTANT: the plugin needs you to configure the global variables,
  please DON'T SKIP THIS PASSAGE!!!
- Launch with AliRoot
  $ aliroot -l -b -q -x RunGridRsnTrain.C"(<mode>, <Grid User>, <suffix>, <ROOT>, <ALIROOT>, <ALIPHYSICS>)"

  <mode> can be "test", "full" or "terminate" - MANDATORY
  <Grid User> is your grid username - MANDATORY
  <suffix> is an additional string which identifies the names of the executables and jdl - OPTIONAL
           if it is empty (e.g., "") all files created by the plugin will have the same name 
  <ROOT>, <ALIROOT>, <ALIPHYSICS> must be compatible versions of the packages (check on Monalisa)
**********************************************************************************************************/

#ifndef __CINT__
#include <TSystem.h>
#include <TROOT.h>
#include <Rtypes.h>
#include <TString.h>
#include <TNamed.h>
#include <TList.h>
#include <ANALYSIS/AliAnalysisManager.h>
#include <TObjArray.h>
#include <TObjString.h>
#include <AliMultiInputEventHandler.h>
#include <AliAODHandler.h>
#endif

class AliAnalysisGrid;


/***************************************************************/
/***   !!! THE USER HAVE TO SET THE FOLLOWING VARIABLES!!!   ***/
/***************************************************************/
/* Define here the input dataset */
Int_t year = 2010;
TString prod = "LHC10c";
TString ppass = "pass2";

/* AOD number. 
   Set aodN = 0 for AOD produced with reconstruction, which have no number.
   Set aodN = -1 for ESDs */
Int_t aodN = -1;

/* Define the run list and the run range for the analysis.
   Example with run list for LHC13c pass2 (p-Pb data) */
Int_t runNmin=0;
Int_t runNmax=1;
Int_t runList[30]={121040, 121039, 120829, 120824, 120823, 120741, 120671, 120617, 120616, 120505, 
		   120503, 120079, 120076, 120073, 120072, 120069, 120067, 119849, 119846, 119845, 
		   119844, 119163, 119161, 119159, 118561, 118560, 118558, 118556, 118518, 118506};

/* The following flags are needed to configure the analysis */
Bool_t isPP = 1;
Bool_t isMC = 0;
Bool_t isESD = 1;
Bool_t useTender = kFALSE;
Int_t nmix=10; 

/* Define data path */
TString myGridDataDir="";
TString myDataPattern="";

/* Define output directory and names of the files generated by the plugin.
Omit the extension of the files, it will be automatically set by the SetupIO function */
TString myWorkDir = "RsnOut";
TString myOutDir  = "Example";
TString myJDLname = "jobRsnAnalysisExample";
TString myExecutableName = "RunRsnAnalysisExample";
TString myMacroName = "RunRsnAnalysisExample";

/* the macros are normally in the Rsn Package */
TString loadMacroPath = "${ALICE_PHYSICS}/PWGLF/RESONANCES/macros/mini";

/* Set the usage of the alien plugin to kTRUE to run the analysis on grid or in test mode,
   set it to kFALSE to run test locally */
Bool_t useAlienPlugin = 1;

/* If you want to run merging via plugin, disable the local merge when running in "full" mode or "terminate" mode (multiple merging stages are possible).
   Enable the local merge at the last step of the "terminate" to download locally the final merged output.
   Otherwise, local merge is always possible. */
Bool_t isLocalMerge = 0;

/* Run Rsn monitoring for QA only - keep disabled as default to run also the analysis */
Bool_t runMonOnly= kFALSE;

/***************************************************************/
void LoadLibraries()
{
  gSystem->SetIncludePath("-I. -I$ROOTSYS/include  -I$ALICE_ROOT/include -I$ALICE_PHYSICS/include -I$ALICE_ROOT/STEER/STEER -I$ALICE_ROOT/STEER/STEERbase -I$ALICE_ROOT/ANALYSIS -I$ALICE_ROOT/ANALYSISalice -I$ALICE_PHYSICS/EVENTMIX -g"); 
  printf("%s\n",gSystem->GetIncludePath());
  Printf("Loading libs");
  gSystem->Load("libTree.so");
  gSystem->Load("libGeom.so");
  gSystem->Load("libVMC.so");
  gSystem->Load("libPhysics.so");
  gSystem->Load("libSTEERBase");
  gSystem->Load("libESD");
  gSystem->Load("libAOD");
  gSystem->Load("libANALYSIS");
  gSystem->Load("libOADB");
  gSystem->Load("libANALYSISalice.so");
  gSystem->Load("libEventMixing.so");
  gSystem->Load("libPWGLFresonances.so");
}

/***************************************************************/
void RunGridRsnTrain(TString pluginmode="test", 
		     TString username="fbellini", 
		     TString suffix="_Example",
		     TString rootVer = "v5-34-08-7", 
		     TString aliRootVer = "v5-06-03", 
		     TString aliPhysicsVer = "vAN-20150222") { 
  
  Long64_t nentries=100000, firstentry=0; //needed to read input when running locally
  TString analysisMode  = "grid"; 

  // Connect to AliEn only if needed
  if(analysisMode=="grid") {
    TGrid::Connect("alien://");
  } 
  
  //load include path for necessary libraries to configure analysis and plugin
  LoadLibraries();
  SetupIO(suffix.Data());

  // Create Alien plugin, if requested
  if(useAlienPlugin) {  
    AliAnalysisGrid *alienHandler = CreateAlienHandler(pluginmode.Data(),username.Data(), rootVer.Data(), aliRootVer.Data(), aliPhysicsVer.Data());
    if(!alienHandler) return;
  }
  
  //read input file for local tests
  //The file added to the chain can also be a file on the grid, e.g. alien://<full path on grid>/AliESDs.root
  TChain *chain = 0;
  if(!useAlienPlugin) {
    if (isESD){
      chain=new TChain("esdTree");
      chain->Add("AliESDs.root");  
    } else {
      chain=new TChain("aodTree");
      chain->Add("AliAOD.root"); 
    }
  }
  if (chain) Printf("Input chain has %d entries\n",(Int_t)chain->GetEntries());
  
  /***************************************************************
    call the AnalysisSetup.C macro which:
    - loads missing libraries for the analysis
    - set config params (beam type, ESD/AOD, w/wo tender)
    - add tasks (including non-rsn tasks)
    - creates analysis manager and input handler
  ****************************************************************/
  Bool_t isAOD049 = 0;
  (aodN==49) ? isAOD049 = kTRUE :  isAOD049 = kFALSE;
  
  //  gROOT->LoadMacro("$ALICE_PHYSICS/PWGLF/RESONANCES/macros/mini/steer/AnalysisSetup.C");
  gROOT->LoadMacro("./AnalysisSetup.C");
  TString options;
  if (isMC) options="MC"; else options="DATA";
  if (isPP) options.Append("_PP"); else options.Append("_PBPB");
  if (isESD) options.Append("_ESD");
  if (useTender) options.Append("_TENDER");
  
  TString out = "";
  out = AnalysisSetup(nmix, options, Form("RsnTask%s.root",suffix.Data()), loadMacroPath, isAOD049, kTRUE, runMonOnly, isMC, "NoSIGN");
  if (out.Length() < 1) return;
  
  // add plugin to analysis manager
  AliAnalysisManager *mgr = AliAnalysisManager::GetAnalysisManager();
  if (!mgr) return;
  if (useAlienPlugin)
    mgr->SetGridHandler(alienHandler);
  
  if(!mgr->InitAnalysis()) {
    printf("Error: Analysis manager failed to be initialized. Nothing done!\n");
    return;
  }
  
  mgr->PrintStatus();
  if(analysisMode=="grid" && !useAlienPlugin) 
    analysisMode="local";
 
  //start analysis
  mgr->StartAnalysis(analysisMode.Data(),chain,nentries,firstentry);  
  return;
}


/***************************************************************/
AliAnalysisGrid* CreateAlienHandler(TString pluginmode, 
				    TString username, 
				    TString rootVer = "v5-34-08-7", 
				    TString aliRootVer = "v5-06-03", 
				    TString aliPhysicsVer = "vAN-20150222")
{
  
  AliAnalysisAlien *plugin = new AliAnalysisAlien();
  plugin->SetRunMode(pluginmode.Data());
  plugin->SetUser(username.Data());
  plugin->SetAPIVersion("V1.1x");
  plugin->SetROOTVersion(rootVer.Data()); 
  plugin->SetAliROOTVersion(aliRootVer.Data()); 
  plugin->SetAliPhysicsVersion(aliPhysicsVer.Data()); 
  plugin->SetGridWorkingDir(myWorkDir.Data()); 
  plugin->SetGridOutputDir(myOutDir.Data()); 
  plugin->SetCheckCopy(kTRUE);
  plugin->SetGridDataDir(myGridDataDir.Data());
  plugin->SetDataPattern(myDataPattern.Data());
  if (!isMC) plugin->SetRunPrefix("000");
  
  for (Int_t irun=runNmin;irun<runNmax;irun++){
    plugin->AddRunNumber((Int_t )runList[irun]);
  }

  /****change this to se the number of files to be used in "test" mode ****/
  plugin->SetNtestFiles(2); 
  
  /**** change this not to have the output run-by-run ****/
  plugin->SetOutputToRunNo(1); 
  plugin->SetNrunsPerMaster(1);
  
  /**** feel free to modify the list of include paths and libraries according to your need! ****/
  plugin->AddIncludePath("-I. -I$ROOTSYS/include -I$ALICE_ROOT -I$ALICE_ROOT/include -I$ALICE_PHYSICS/include -I$ALICE_ROOT/STEER -I$ALICE_ROOT/TOF -I/$ALICE_ROOT/ANALYSIS -I/$ALICE_ROOT/ANALYSISalice -I/$ALICE_PHYSICS/EVENTMIX -I/$ALICE_PHYSICS/PWGLF/RESONANCES -g"); 
  plugin->SetAdditionalLibs("AnalysisSetup.C libGui.so libProof.so libMinuit.so libANALYSIS.so libOADB.so libANALYSISalice.so libEventMixing.so libPWGLFresonances.so");

  /**** these have to be customized ****/
  plugin->SetAnalysisMacro(myMacroName.Data()); 
  plugin->SetExecutable(myExecutableName.Data()); 
  plugin->SetJDLName(myJDLname);
  
  /**** more job option ****/
  plugin->SetDefaultOutputs(kTRUE);
  plugin->SetExecutableCommand("aliroot -b -q");
  plugin->SetMaxInitFailed(15);
  plugin->SetMasterResubmitThreshold(10);
  plugin->SetTTL(50000);
  plugin->SetInputFormat("xml-single");
  plugin->SetSplitMaxInputFileNumber(30);
  plugin->SetSplitMode("se");
  
  /**** Set properly the global flac to enable/disable local or plugin merging ****/     
  plugin->SetMergeViaJDL(!isLocalMerge);
  
  /**** Force a single merging stage or define multiple stages ****/     
  // plugin->SetOneStageMerging(kTRUE);                          
  plugin->SetMaxMergeStages(2); // adapt n to your expected number of files              
  
  return plugin;
}

/***************************************************************/
TChain *CreateESDChain(TString esdpath=".",Int_t ifirst=-1,Int_t ilast=-1) {


  TChain *chainESD = new TChain("esdTree");

  if(ifirst<0) {
    chainESD->Add("AliESDs.root");
  } else {
    for(Int_t i=ifirst; i<=ilast; i++) {
      TString esdfile=esdpath; esdfile+=i; esdfile.Append("/AliESDs.root");
      chainESD->Add(esdfile.Data());
    }
  }
  
  return chainESD;
}

/***************************************************************/
void SetupIO(TString suffix="_Example")
{
  //Setup I/O paths and file names
  if (!isESD && aodN<0) {
    Printf("WARNING: AOD analysis is required but no valid AOD number is provided. Switching to ESD analysis");
    isESD = kTRUE;
  }
  
  myGridDataDir = "/alice";
  if (isMC) myGridDataDir.Append(Form("/sim"));
  else myGridDataDir.Append(Form("/data/%i",year));
  if (isMC && year>=2013) myGridDataDir.Append(Form("/%i",year));
  myGridDataDir.Append(Form("/%s",prod.Data()));
  
  if (isESD) {
    if (isMC) myDataPattern="*AliESDs.root";
    else myDataPattern=Form("*ESDs/%s/*AliESDs.root",ppass.Data());
  } else {
    if (aodN>0) myDataPattern=Form("AOD%03i/*AliAOD.root",aodN);
    else myDataPattern="AOD/*AliAOD.root";
    if (!isMC) myDataPattern.Prepend(Form("*ESDs/%s/",ppass.Data())); 
  }
  
  myJDLname.Append(suffix.Data()); myJDLname.Append(".jdl");
  myExecutableName.Append(suffix.Data()); myExecutableName.Append(".sh");
  myMacroName.Append(suffix.Data()); myMacroName.Append(".C");

  Printf("=========================================  Setup I/O:");
  Printf("myGridDataDir = %s", myGridDataDir.Data());
  Printf("myDataPattern = %s", myDataPattern.Data());
  Printf("myWorkDir = %s", myWorkDir.Data());
  Printf("myOutDir = %s", myOutDir.Data());
  Printf("myJDLname = %s", myJDLname.Data());
  Printf("myExecutableName = %s", myExecutableName.Data());
  Printf("myMacroName = %s", myMacroName.Data());
  Printf("=======================================================");
}
