/**
 * @file 
 * 
 * Scripts to draw energy loss fits from correction object file 
 *
 * @ingroup pwg2_forward_analysis_scripts
 */
/** 
 * Clear canvas 
 * 
 * @param c Canvas to clear 
 *
 * @ingroup pwg2_forward_analysis_scripts
 */
void
ClearCanvas(TCanvas* c)
{
  c->SetLeftMargin(.1);
  c->SetRightMargin(.05);
  c->SetBottomMargin(.1);
  c->SetTopMargin(.05);
  c->Clear();
}

/** 
 * Draw energy loss fits to a multi-page PDF. 
 *
 * @par Input: 
 * The input file is expected to contain a AliFMDCorrELossFit object
 * named @i elossfits in the top level directory.
 * 
 * @para Output: 
 * A multi-page PDF.  Note, that the PDF generated by ROOT in this way
 * is broken (cannot be read by Acrobat Reader on Windows and MacOSX)
 * and one should pass it through a filter to correct these problems.
 * 
 * @param fname   File name 
 * @param option  Drawing options 
 *
 * @ingroup pwg2_forward_analysis_scripts
 */
void
DrawCorrSecMap2(const char* fname, const char* option="colz")
{
  //__________________________________________________________________
  // Load libraries and object 
  gROOT->Macro("$ALICE_ROOT/PWG2/FORWARD/analysis2/scripts/LoadLibs.C");

  TFile* file = TFile::Open(fname, "READ");
  if (!file) { 
    Error("DrawCorrSecMap", "Failed to open %s", fname);
    return;
  }
  TString pname(fname);
  pname.ReplaceAll(".root", ".png");
  pname = gSystem->BaseName(pname);

  const char* objName = 
    AliForwardCorrectionManager::Instance()
    .GetObjectName(AliForwardCorrectionManager::kSecondaryMap);
  AliFMDCorrSecondaryMap* corr = 
    static_cast<AliFMDCorrSecondaryMap*>(file->Get(objName));
  if (!corr) { 
    Error("DrawCorrSecMap", "Object '%s' not found in %s", objName, fname);
    return;
  }

  //__________________________________________________________________
  // Create a canvas
  TCanvas* c = new TCanvas("c", "c", 800, 800 / TMath::Sqrt(2));
  c->SetFillColor(0);
  c->SetBorderSize(0);
  c->SetBorderMode(0);
  // c->Print(Form("%s[", pname.Data()));
  
  gStyle->SetOptStat(0);
  gStyle->SetTitleColor(0);
  gStyle->SetTitleStyle(0);
  gStyle->SetTitleBorderSize(0);
  gStyle->SetTitleX(.1);
  gStyle->SetTitleY(1);
  gStyle->SetTitleW(.8);
  gStyle->SetTitleH(.09);
  gStyle->SetFrameFillColor(kWhite);
  gStyle->SetFrameBorderSize(1);
  gStyle->SetFrameBorderMode(1);
  gStyle->SetPalette(1);

  ClearCanvas(c);
  //__________________________________________________________________
  // Draw all corrections
  const TAxis& vtxAxis = corr->GetVertexAxis();
  Int_t        nVtx    = vtxAxis.GetNbins();
  c->Divide((nVtx+2)/3, 3, 0, 0);
  Int_t ipad = 0;
  for (UShort_t v=1; v <= nVtx; v++) { 
    ipad++;
    if (ipad == 1 || ipad == 12) ipad++;
    
    TVirtualPad* p = c->cd(ipad);
    p->SetFillColor(kWhite);
    THStack* stack = new THStack(Form("vtxBin%02d", v), 
				 Form("%-4.1f<v_{z}<%4.1f", 
				      vtxAxis.GetBinLowEdge(v), 
				      vtxAxis.GetBinUpEdge(v))); 

    for (UShort_t d = 1; d <= 3; d++) {
      UShort_t     nQ = (d == 1 ? 1 : 2);
      for (UShort_t q = 0; q < nQ; q++) { 
	Char_t r = (q == 0 ? 'I' : 'O');
	
	TH2*   h1 = corr->GetCorrection(d, r, v);
	if (!h1) { 
	  Warning("DrawCorrSecMap", "No correction for r=%c, v=%d", r, v);
	  continue;
	}

	// Info("DrawCorrSecMap2", "Getting FMD%d%c vtxbin %d", d, r, v);
	TH1D*  pr = h1->ProjectionX(Form("FMD%d%c", d, r), -1, -1, "e");
	pr->SetDirectory(0);
	pr->SetTitle(Form("FMD%d%c", d, r));
	pr->Scale(1. / (q == 0 ? 20 : 40));
	pr->SetMarkerColor(AliForwardUtil::RingColor(d, r));
	
	stack->Add(pr);
      }
    }
    stack->SetMaximum(3.2);
    stack->Draw("nostack");
  }
  
  //__________________________________________________________________
  // Close output file 
  c->SaveAs(pname.Data());
  
}
//
// EOF
//
