set(CTEST_PROJECT_NAME "AliRoot")
set(CTEST_NIGHTLY_START_TIME "00:00:00 EST")
set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "alirootbuildcmake.cern.ch")
set(CTEST_DROP_LOCATION "/~johny/submit.php?project=AliRoot")
set(CTEST_DROP_SITE_CDASH TRUE)
