*
* $Id$
*
* $Log$
* Revision 1.1.1.1  1996/03/06 10:46:55  mclareni
* Zebra
*
*
#ifndef CERNLIB_ZEBRA_JZC_INC
#define CERNLIB_ZEBRA_JZC_INC
*
*
* jzc.inc
*
                             PARAMETER (JQMFLW=10)
      COMMON /JZC/   JQTIME,JQMLEV,JQCBNL,JQCBND,JQNACC,JQEALL,JQREOD
     +,              NQME(6), JQSTJZ,IXSTJZ,IXDVJZ,JQLLEV
     +,              IAMID,IAFLDW,IANAN,IANCR,IANLSV,IANDSV,IANFL

#endif
