*
* $Id$
*
* $Log$
* Revision 1.1.1.1  1996/03/06 10:46:57  mclareni
* Zebra
*
*
#ifndef CERNLIB_ZEBRA_ZBCDK_INC
#define CERNLIB_ZEBRA_ZBCDK_INC
*
*         BCD symbols in CHARACTER representation
*
* zbcdk.inc
*
      PARAMETER (MPOSAQ= 1 ,MPOSBQ= 2 ,MPOSCQ= 3 ,MPOSDQ= 4 ,MPOSEQ= 5
     X          ,MPOSFQ= 6 ,MPOSGQ= 7 ,MPOSHQ= 8 ,MPOSIQ= 9 ,MPOSJQ=10
     X          ,MPOSKQ=11, MPOSLQ=12 ,MPOSMQ=13 ,MPOSNQ=14 ,MPOSOQ=15
     X          ,MPOSPQ=16, MPOSQQ=17 ,MPOSRQ=18 ,MPOSSQ=19 ,MPOSTQ=20
     X          ,MPOSUQ=21, MPOSVQ=22 ,MPOSWQ=23 ,MPOSXQ=24 ,MPOSYQ=25
     X          ,MPOSZQ=26                                            )

#endif
