gridWorkingDir:			workingdir
gridOutputDir:			outputdir_19i3a1_pthat1
aliPhysicsVersion:      vAN-20200629_ROOT6-1
package:                fastjet::v3.2.1_1.024-alice3-71
package:                boost::v1.72.0-alice1-1
# package:                GCC-Toolchain::v7.3.0-alice2-7
# aliROOTVersion:         v5-09-54a-2
gridDataDir:			/alice/data/2018/LHC18q
dataPattern:      /pass3/AOD/*/AliAOD.root
runPrefix:        000
runNumber:			  [295913]
trackCutsPeriod:  lhc18q
emcalCorrection:    emcal_correction_embed.yaml
emcalGeometryFilename:  	geometry_2015.root
emcalLocal2MasterFilename:  	EMCALlocal2master.root
skimClusterMinE:        15.0
splitMaxInputFileNumber: 2
isMC: false
isEmbed: true

# settings for embedding - only one should be active at a time
# file list for running locally - do not use alien
# embedLocalFileList:      pp-filelist-19i3a.txt
# file pattern for running on grid - do not run in test mode
embedGridFilePattern:   alien:///alice/sim/2019/LHC19i3a1/1