*
* $Id$
*
* $Log$
* Revision 1.1.1.1  1995/10/24 10:20:38  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_DEPNUC_INC
#define CERNLIB_GEANT321_DEPNUC_INC
*
*
* depnuc.inc
*
*                                                                     *
*=== depnuc ==========================================================*
*                                                                     *
      LOGICAL LLASTN, LLAST1
      COMMON /FKDEPN/    EKLAST, AMLAST, PXLAST, PYLAST, PZLAST,
     &                   EKINC , AMINC , PXXINC, PYYINC, PZZINC,
     &                   KTLAST, KTINC , LLASTN, LLAST1
 

#endif
