*
* $Id$
*
* $Log$
* Revision 1.1.1.1  1995/10/24 10:20:38  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_EVA1_INC
#define CERNLIB_GEANT321_EVA1_INC
*
*
* eva1.inc
*
*                                                                      *
*=== eva1 =============================================================*
*                                                                      *
      COMMON /FKEVA1/ NPART(6),EPART(100,6),COSEVP(3,100,6),HEVSUM
 

#endif
