*
* $Id$
*
* $Log$
* Revision 1.1.1.1  1995/10/24 10:20:39  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_FORCN_INC
#define CERNLIB_GEANT321_FORCN_INC
*
*
* forcn.inc
*
*                                                                      *
*=== forcn ============================================================*
*                                                                      *
      COMMON /FKFORC/ FKEY
 

#endif
