*
* $Id$
*
* $Log$
* Revision 1.8  1998/02/11 09:47:00  japost
*   Updated version number to 3.21/11.
*
* Revision 1.7  1997/11/13 13:04:45  mclareni
* Increase cradle no. to 0.10
*
* Revision 1.6  1997/10/17 10:26:24  mclareni
* Increase cradle no. to 0.09
*
* Revision 1.5  1997/06/20 18:40:53  japost
*   Updating the version number after commiting several changes:
*   to gthion, gflufin, ghetun
*   Remaining problem: gdrawp, ghadr?
*
* Revision 1.4  1997/01/06 17:08:17  cernlib
* Increase cradle no. to 0.07
*
* Revision 1.3  1996/11/19 11:28:53  ravndal
* *** empty log message ***
*
* Revision 1.2  1996/04/15 14:10:08  ravndal
* Update cradel number
*
* Revision 1.1.1.1  1995/10/24 10:20:45  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_GVERSC_INC
#define CERNLIB_GEANT321_GVERSC_INC
*
*
* gversc.inc
*
#if !defined(CERNLIB_INCLUDE)
      GVERSC = 0.11
#endif

#endif
