*
* $Id$
*
* $Log$
* Revision 1.1.1.1  1995/10/24 10:20:39  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_HETC7_INC
#define CERNLIB_GEANT321_HETC7_INC
*
*
* hetc7.inc
*
*                                                                      *
*=== hetc7 ============================================================*
*                                                                      *
      COMMON /FKHET7/ COSKS,SINKS, COSTH,SINTH, COSPHI,SINPHI
 

#endif
