*
* $Id$
*
* $Log$
* Revision 1.1.1.1  1995/10/24 10:20:40  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_INPDAT2_INC
#define CERNLIB_GEANT321_INPDAT2_INC
*
*
* inpdat2.inc
*
*
*=== inpdat2 ==========================================================*
*
*----------------------------------------------------------------------*
*     include file: inpdat2 copy          created 29/3/90 by A. Ferrari
*     changes: none
*     included in the following subroutines or functions: not updated
*
*     T H I S   I S   A   C O P Y   O F   I N P D A T   C R E A T E D
*     T O   A V O I D   T O   D I R T Y   T H E   B A M J E T
*     P A R A M E T E R S !!!!!!!!!!!!
*
*     description of the common block(s) and variable(s)
*
*----------------------------------------------------------------------*
*
      COMMON /FKINPD/ A1BAMJ, B1BAMJ, B2BAMJ, B3BAMJ, BETBAM, ASBAMJ,
     &                B8BAMJ, AMEBAM, DIQBAM, IMPS (6,6), IMVE (6,6),
     &                IB08 (6,21), IB10 (6,21), IA08 (6,21),
     &                IA10 (6,21), LTBAMJ, LEBAMJ, ISUBAM
 

#endif
