*
* $Id$
*
* $Log$
* Revision 1.1.1.1  1995/10/24 10:20:40  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_INPFLG_INC
#define CERNLIB_GEANT321_INPFLG_INC
*
*
* inpflg.inc
*
*                                                                      *
*=== inpflg ===========================================================*
*                                                                      *
      COMMON /FKINPF/ IANG,IFISS,IB0,IGEOM,ISTRAG,KEYDK
 

#endif
