*CMZ :          02/11/94  13.23.19  by  John Apostolakis CERN GP-MIMD 2
*-- Author :    John Apostolakis CERN GP-MIMD 2   13/07/94
C   Include the file which defines all the MPI (Message Passing Interface)
C   constants. The name of this file must be "mpif.h" but it will reside
C   in different places on different machines/implementations/sites and
C   the way of including it will also depend on the compiler used.
C   For the Chimp/MPI implementation from EPCC and Sun's Fortran 77. May 1995
C     Ensure that the output filename is something.F  (not something.f)
C     (In CMZ, use  "kuip/set_show/filecase keep" to do this).
#include "mpif.h"
