*
* $Id$
*
* $Log$
* Revision 1.1.1.1  1995/10/24 10:20:43  cernlib
* Geant
*
*
#ifndef CERNLIB_GEANT321_S_DEFCOM_INC
#define CERNLIB_GEANT321_S_DEFCOM_INC
*
*
* s_defcom.inc
*
#include "geant321/mxgkgh.inc"
#include "geant321/s_consts.inc"
#include "geant321/s_curpar.inc"
#include "geant321/s_result.inc"
#include "geant321/s_mat.inc"
#include "geant321/s_event.inc"
#include "geant321/s_prntfl.inc"
#include "geant321/s_errcom.inc"
#include "geant321/s_blank.inc"
C

#endif
