// -*- C++ -*-

TString classNames[] = {
  "CINT7-B-NOPF-FASTNOTRD",
  "CINT7-I1-NOPF-FASTNOTRD",
  "CINT7-I2-NOPF-FASTNOTRD",
  "CINT7-I3-NOPF-FASTNOTRD",
  "CINT7-I4-NOPF-FASTNOTRD",
  "CINT7-I5-NOPF-FASTNOTRD",
  "CINT7-I6-NOPF-FASTNOTRD",
  "CINT7-I7-NOPF-FASTNOTRD",
  "CINT7-I8-NOPF-FASTNOTRD",

  "CINT5-B-NOPF-FASTNOTRD",

  "C0TVX-B-NOPF-FASTNOTRD",
  "C0TVX-I1-NOPF-FASTNOTRD",
  "C0TVX-I2-NOPF-FASTNOTRD",
  "C0TVX-I3-NOPF-FASTNOTRD",
  "C0TVX-I4-NOPF-FASTNOTRD",
  "C0TVX-I5-NOPF-FASTNOTRD",
  "C0TVX-I6-NOPF-FASTNOTRD",
  "C0TVX-I7-NOPF-FASTNOTRD",
  "C0TVX-I8-NOPF-FASTNOTRD",

  "CADAND-B-NOPF-FASTNOTRD",
  "CADAND-I1-NOPF-FASTNOTRD",
  "CADAND-I2-NOPF-FASTNOTRD",
  "CADAND-I3-NOPF-FASTNOTRD",
  "CADAND-I4-NOPF-FASTNOTRD",
  "CADAND-I5-NOPF-FASTNOTRD",
  "CADAND-I6-NOPF-FASTNOTRD",
  "CADAND-I7-NOPF-FASTNOTRD",
  "CADAND-I8-NOPF-FASTNOTRD",

  "CVBANOTC-I1-NOPF-FASTNOTRD",
  "CVBANOTC-I2-NOPF-FASTNOTRD",
  "CVBANOTC-I3-NOPF-FASTNOTRD",
  "CVBANOTC-I4-NOPF-FASTNOTRD",
  "CVBANOTC-I5-NOPF-FASTNOTRD",
  "CVBANOTC-I6-NOPF-FASTNOTRD",
  "CVBANOTC-I7-NOPF-FASTNOTRD",
  "CVBANOTC-I8-NOPF-FASTNOTRD",

  "CVBCNOTA-I1-NOPF-FASTNOTRD",
  "CVBCNOTA-I2-NOPF-FASTNOTRD",
  "CVBCNOTA-I3-NOPF-FASTNOTRD",
  "CVBCNOTA-I4-NOPF-FASTNOTRD",
  "CVBCNOTA-I5-NOPF-FASTNOTRD",
  "CVBCNOTA-I6-NOPF-FASTNOTRD",
  "CVBCNOTA-I7-NOPF-FASTNOTRD",
  "CVBCNOTA-I8-NOPF-FASTNOTRD",

  "CADANOTC-I1-NOPF-FASTNOTRD",
  "CADANOTC-I2-NOPF-FASTNOTRD",
  "CADANOTC-I3-NOPF-FASTNOTRD",
  "CADANOTC-I4-NOPF-FASTNOTRD",
  "CADANOTC-I5-NOPF-FASTNOTRD",
  "CADANOTC-I6-NOPF-FASTNOTRD",
  "CADANOTC-I7-NOPF-FASTNOTRD",
  "CADANOTC-I8-NOPF-FASTNOTRD",

  "CADCNOTA-I1-NOPF-FASTNOTRD",
  "CADCNOTA-I2-NOPF-FASTNOTRD",
  "CADCNOTA-I3-NOPF-FASTNOTRD",
  "CADCNOTA-I4-NOPF-FASTNOTRD",
  "CADCNOTA-I5-NOPF-FASTNOTRD",
  "CADCNOTA-I6-NOPF-FASTNOTRD",
  "CADCNOTA-I7-NOPF-FASTNOTRD",
  "CADCNOTA-I8-NOPF-FASTNOTRD",

  "CT0ANOTC-I1-NOPF-FASTNOTRD",
  "CT0ANOTC-I2-NOPF-FASTNOTRD",
  "CT0ANOTC-I3-NOPF-FASTNOTRD",
  "CT0ANOTC-I4-NOPF-FASTNOTRD",
  "CT0ANOTC-I5-NOPF-FASTNOTRD",
  "CT0ANOTC-I6-NOPF-FASTNOTRD",
  "CT0ANOTC-I7-NOPF-FASTNOTRD",
  "CT0ANOTC-I8-NOPF-FASTNOTRD",

  "CT0CNOTA-I1-NOPF-FASTNOTRD",
  "CT0CNOTA-I2-NOPF-FASTNOTRD",
  "CT0CNOTA-I3-NOPF-FASTNOTRD",
  "CT0CNOTA-I4-NOPF-FASTNOTRD",
  "CT0CNOTA-I5-NOPF-FASTNOTRD",
  "CT0CNOTA-I6-NOPF-FASTNOTRD",
  "CT0CNOTA-I7-NOPF-FASTNOTRD",
  "CT0CNOTA-I8-NOPF-FASTNOTRD"
};

const Int_t nClasses = sizeof(classNames)/sizeof(TString);

TTree *TT = new TTree;

void ExtractCTPScalers_4269()
{
  gROOT->LoadMacro("AnalyzeCTPRecords.C+");
  gROOT->LoadMacro("ExtractRateFromCTPScalers.C+");

  // AnalyzeCTPRecords(234040, 2015, classNames, nClasses);
  // AnalyzeCTPRecords(234045, 2015, classNames, nClasses);

  const TString classIDs[] = { "CADAND" };
  const TString bunchIDs[] = { "B", "I1", "I2", "I3", "I4", "I5", "I6", "I7", "I8" };
  const Int_t   nBunches[] = {  27,   1,    1,    1,    1,    1,    1,    1,    1  };

  // AD ratios
  // 11/1/2015 Martino: I computed the ratios from the analysis of run 234039 (mu  ~0.01): I got AnotC / A&C = 11.6%, CnotA / A&C = 26.6%. 
  const Double_t ratioA = 0.116;
  const Double_t ratioC = 0.266;
  for (Int_t i=0; i<sizeof(classIDs)/sizeof(TString); ++i) {
    for (Int_t j=0; j<sizeof(bunchIDs)/sizeof(TString); ++j) {
      ExtractRateFromCTPScalers(classIDs[i], bunchIDs[j], 234040, "txt/4269/ScanXY.txt",     nBunches[j], 4269, ratioA, ratioC,
				"root/4269/IntensityDecay.root", "root/4269/SatelliteContamination.root", -1, TT);
      ExtractRateFromCTPScalers(classIDs[i], bunchIDs[j], 234045, "txt/4269/ScanOffset.txt", nBunches[j], 4269, ratioA, ratioC,
				"",                              "root/4269/SatelliteContamination.root", -1, TT);
    }
  }
  TFile::Open("root/4269/RatesAndSep_4269_BB2.root", "RECREATE");
  TT->Write("TT");
  gFile->Write();
  gFile->Close();
}
