// -*- C++ -*-

TString classNames[] = {
  "CINT7-B-NOPF-FASTNOTRD",
  "CINT7-I1-NOPF-FASTNOTRD",
  "CINT7-I2-NOPF-FASTNOTRD",
  "CINT7-I3-NOPF-FASTNOTRD",
  "CINT7-I4-NOPF-FASTNOTRD",
  "CINT7-I5-NOPF-FASTNOTRD",
  "CINT7-I6-NOPF-FASTNOTRD",
  "CINT7-I7-NOPF-FASTNOTRD",
  "CINT7-I8-NOPF-FASTNOTRD",
  
  "CINT5-B-NOPF-FASTNOTRD",

  "C0TVX-B-NOPF-FASTNOTRD",
  "C0TVX-I1-NOPF-FASTNOTRD",
  "C0TVX-I2-NOPF-FASTNOTRD",
  "C0TVX-I3-NOPF-FASTNOTRD",
  "C0TVX-I4-NOPF-FASTNOTRD",
  "C0TVX-I5-NOPF-FASTNOTRD",
  "C0TVX-I6-NOPF-FASTNOTRD",
  "C0TVX-I7-NOPF-FASTNOTRD",
  "C0TVX-I8-NOPF-FASTNOTRD",

  "CADAND-B-NOPF-FASTNOTRD",
  "CADAND-I1-NOPF-FASTNOTRD",
  "CADAND-I2-NOPF-FASTNOTRD",
  "CADAND-I3-NOPF-FASTNOTRD",
  "CADAND-I4-NOPF-FASTNOTRD",
  "CADAND-I5-NOPF-FASTNOTRD",
  "CADAND-I6-NOPF-FASTNOTRD",
  "CADAND-I7-NOPF-FASTNOTRD",
  "CADAND-I8-NOPF-FASTNOTRD",

  "CVBANOTC-I1-NOPF-FASTNOTRD",
  "CVBANOTC-I2-NOPF-FASTNOTRD",
  "CVBANOTC-I3-NOPF-FASTNOTRD",
  "CVBANOTC-I4-NOPF-FASTNOTRD",
  "CVBANOTC-I5-NOPF-FASTNOTRD",
  "CVBANOTC-I6-NOPF-FASTNOTRD",
  "CVBANOTC-I7-NOPF-FASTNOTRD",
  "CVBANOTC-I8-NOPF-FASTNOTRD",

  "CVBCNOTA-I1-NOPF-FASTNOTRD",
  "CVBCNOTA-I2-NOPF-FASTNOTRD",
  "CVBCNOTA-I3-NOPF-FASTNOTRD",
  "CVBCNOTA-I4-NOPF-FASTNOTRD",
  "CVBCNOTA-I5-NOPF-FASTNOTRD",
  "CVBCNOTA-I6-NOPF-FASTNOTRD",
  "CVBCNOTA-I7-NOPF-FASTNOTRD",
  "CVBCNOTA-I8-NOPF-FASTNOTRD",

  "CADANOTC-I1-NOPF-FASTNOTRD",
  "CADANOTC-I2-NOPF-FASTNOTRD",
  "CADANOTC-I3-NOPF-FASTNOTRD",
  "CADANOTC-I4-NOPF-FASTNOTRD",
  "CADANOTC-I5-NOPF-FASTNOTRD",
  "CADANOTC-I6-NOPF-FASTNOTRD",
  "CADANOTC-I7-NOPF-FASTNOTRD",
  "CADANOTC-I8-NOPF-FASTNOTRD",

  "CADCNOTA-I1-NOPF-FASTNOTRD",
  "CADCNOTA-I2-NOPF-FASTNOTRD",
  "CADCNOTA-I3-NOPF-FASTNOTRD",
  "CADCNOTA-I4-NOPF-FASTNOTRD",
  "CADCNOTA-I5-NOPF-FASTNOTRD",
  "CADCNOTA-I6-NOPF-FASTNOTRD",
  "CADCNOTA-I7-NOPF-FASTNOTRD",
  "CADCNOTA-I8-NOPF-FASTNOTRD",

  "CT0ANOTC-I1-NOPF-FASTNOTRD",
  "CT0ANOTC-I2-NOPF-FASTNOTRD",
  "CT0ANOTC-I3-NOPF-FASTNOTRD",
  "CT0ANOTC-I4-NOPF-FASTNOTRD",
  "CT0ANOTC-I5-NOPF-FASTNOTRD",
  "CT0ANOTC-I6-NOPF-FASTNOTRD",
  "CT0ANOTC-I7-NOPF-FASTNOTRD",
  "CT0ANOTC-I8-NOPF-FASTNOTRD",

  "CT0CNOTA-I1-NOPF-FASTNOTRD",
  "CT0CNOTA-I2-NOPF-FASTNOTRD",
  "CT0CNOTA-I3-NOPF-FASTNOTRD",
  "CT0CNOTA-I4-NOPF-FASTNOTRD",
  "CT0CNOTA-I5-NOPF-FASTNOTRD",
  "CT0CNOTA-I6-NOPF-FASTNOTRD",
  "CT0CNOTA-I7-NOPF-FASTNOTRD",
  "CT0CNOTA-I8-NOPF-FASTNOTRD"
};

const Int_t nClasses = sizeof(classNames)/sizeof(TString);

void ExtractCTPScalers_4269()
{
  gROOT->LoadMacro("AnalyzeCTPRecords.C+");

//   AnalyzeCTPRecords(234040, 2015, classNames, nClasses);
//   AnalyzeCTPRecords(234045, 2015, classNames, nClasses);

}
