# General task configuration
mc_mode: false
calculate_only_efficiency: false #ignore background, saves space in MC
keep_all_candidates: true #ignores the requirement of having both D meson and electron in the same event

d_meson_species: 'D0'


event:
    properties:
        zvxt_range: [-10.,10.]
    multiplicity:
        estimator: "ZNA"
        multiplicity_range: [-2.,101.]

D_meson:
    selection:
        cut_file: "PreselectionDHFe.root" 
        cut_name: "D0toKpiCuts"
        min_pt: 2.0
        max_pt_pid: 5.0

main_electron:
    track:
        pt_range: [0.5,10.0]
        eta_range: [-0.8,0.8] 
        filter_bit: kTrkGlobalNoDCA #as defined in AliAODTrack
        min_TPC_cls: 70
        min_TPC_cls_dedx: 80
        min_ITS_hits: 2
        pixel_req: kAny #check possibilities in AliAnalysisTaskDHFeCorr::ITSPixel_t
        recalculate_dca: true
        dca_z: 5.0
        dca_xy: 5.0
    PID:
        TPC_selection: [-1.0,3.0]
        TOF_selection: [-3.0,3.0]
        require_TOF: false

partner_electron:
    track:
        pt_range: [0.2,100.0]
        eta_range: [-0.8,0.8] 
        filter_bit: kTrkGlobalNoDCA #as defined in AliAODTrack
        min_TPC_cls: 80
        min_TPC_cls_dedx: 60
        min_ITS_hits: 2
        pixel_req: kAny #check possibilities in AliAnalysisTaskDHFeCorr::ITSPixel_t
        recalculate_dca: true
        dca_z: 5.0
        dca_xy: 5.0
    PID:
        TPC_selection: [-3.0,3.0]
        TOF_selection: [-3.0,3.0]
        require_TOF: false

output:
    electron_qa:
        pt_bins: [0.2,0.3,0.4,0.5,0.75,1.0,1.5,2.0,3.0,4.0,6.0,8.0,10.0]
        p_bins: [0.5,0.55,0.6,0.65,0.70,0.75,0.8,0.9,1.0,1.25,1.5,2.0,2.5,3.0,3.5,4.0,5.0,6.0,7.0,8.0,10.0]
        n_eta_bins: 16 # bins have the same size
        n_phi_bins: 20 
        n_bins_TPC_cls: 40
        n_bins_n_sigma: 100
    d_meson_qa:
        pt_bins: [0.,1.,1.5,2.,3.,4.,5.,6.,7.,8.,10.,12.,16.,20.,24.,32.,50.,100.]
        inv_mass_range: [1.4,2.2]
        n_bins_inv_mass: 100
        n_eta_bins: 16 # bins have the same size
        n_phi_bins: 20 

