//if like define a different number of signal for TPC PID

//by default the task is anyway computing 1, 2 and 3 sigmas

const Bool_t theRareOn = kTRUE;

const Bool_t anaType   = 1;//0 HD; 1 UU;

const Bool_t doImp   = kFALSE;// imp par studies

//----------------------------------------------------



AliAnalysisTaskSEDStarSpectra *AddTaskDStarSpectra(Int_t system=0/*0=pp,1=PbPb*/,

						   Float_t minC=0, Float_t maxC=100,

						   const char * cutsfile="DStartoKpipiCuts.root",

						   Bool_t theMCon=kFALSE)

{



  AliAnalysisManager *mgr = AliAnalysisManager::GetAnalysisManager();

  if (!mgr) {

    ::Error("AddTaskDStarSpectra", "No analysis manager to connect to.");

    return NULL;

  }  

  

  // cuts are stored in a TFile generated by makeTFile4CutsDStartoKpipi.C in ./macros/

  // set there the cuts!!!!!

  Bool_t stdcuts=kFALSE;

  TFile* filecuts=new TFile("DStartoKpipiCuts.root");

  if(!filecuts->IsOpen()){

    cout<<"Input file not found: exit"<<endl;

    stdcuts=kTRUE;

  }





  AliRDHFCutsDStartoKpipi* RDHFDStartoKpipi=new AliRDHFCutsDStartoKpipi();

  if(stdcuts) {

    if(system==0) RDHFDStartoKpipi->SetStandardCutsPP2010();

    else if(system==1) {

      RDHFDStartoKpipi->SetStandardCutsPbPb2010();

      RDHFDStartoKpipi->SetMinCentrality(minC);

      RDHFDStartoKpipi->SetMinCentrality(maxC);

      RDHFDStartoKpipi->SetUseAOD049(kTRUE);

      RDHFDStartoKpipi->SetUseCentrality(AliRDHFCuts::kCentV0M);

    }

  }

  else RDHFDStartoKpipi = (AliRDHFCutsDStartoKpipi*)filecuts->Get("DStartoKpipiCuts");

  RDHFDStartoKpipi->SetName("DStartoKpipiCuts");



  // mm let's see if everything is ok

  if(!RDHFDStartoKpipi){

    cout<<"Specific AliRDHFCuts not found"<<endl;

    return;

  }

 

  //CREATE THE TASK

  printf("CREATE TASK\n");

  // create the task

  AliAnalysisTaskSEDStarSpectra *task = new AliAnalysisTaskSEDStarSpectra("AliAnalysisTaskSEDStarSpectra",RDHFDStartoKpipi);

  task->SetAnalysisType(anaType);

  task->SetMC(theMCon);

  task->SetRareSearch(theRareOn);

  task->SetDoImpactParameterHistos(doImp);

  task->SetDebugLevel(0);



  mgr->AddTask(task);



  // Create and connect containers for input/output

  

  TString outputfile = AliAnalysisManager::GetCommonFileName();

  outputfile += ":PWG3_D2H_DStarSpectra";

  

  // ------ input data ------



  //AliAnalysisDataContainer *cinput0  = mgr->GetCommonInputContainer();

  AliAnalysisDataContainer *cinput0  =  mgr->CreateContainer("indstar",TChain::Class(), 

							     AliAnalysisManager::kInputContainer);





 // ----- output data -----

  AliAnalysisDataContainer *coutput1 = mgr->CreateContainer(Form("chist1%d%d",minC,maxC),TList::Class(),AliAnalysisManager::kOutputContainer,outputfile.Data());

  AliAnalysisDataContainer *coutputDStar1 = mgr->CreateContainer(Form("DStarAll%d%d",minC,maxC),TList::Class(),AliAnalysisManager::kOutputContainer,outputfile.Data());

  AliAnalysisDataContainer *coutputDStar2 = mgr->CreateContainer(Form("DStarPID%d%d",minC,maxC),TList::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data());

  AliAnalysisDataContainer *coutputDStar3 = mgr->CreateContainer(Form("cuts%d%d",minC,maxC),AliRDHFCutsDStartoKpipi::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data()); //cuts

  AliAnalysisDataContainer *coutputDstarNorm = mgr->CreateContainer(Form("coutputDstarNorm%d%d",minC,maxC),AliNormalizationCounter::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data());



  mgr->ConnectInput(task,0,mgr->GetCommonInputContainer());

  mgr->ConnectOutput(task,1,coutput1);

  mgr->ConnectOutput(task,2,coutputDStar1);

  mgr->ConnectOutput(task,3,coutputDStar2);

  mgr->ConnectOutput(task,4,coutputDStar3);

  mgr->ConnectOutput(task,5,coutputDstarNorm);

  

  return task;

}



