//if like define a different number of signal for TPC PID
//by default the task is anyway computing 1, 2 and 3 sigmas
const Bool_t theRareOn = kFALSE;
const Bool_t anaType   = 1;//0 HD; 1 UU;
//----------------------------------------------------

AliAnalysisTaskSEDStarSpectra *AddTaskDStarSpectra(Bool_t theMCon=kFALSE)
{
  
  AliAnalysisManager *mgr = AliAnalysisManager::GetAnalysisManager();
  if (!mgr) {
    ::Error("AddTaskDStarSpectra", "No analysis manager to connect to.");
    return NULL;
  }  
  
  // cuts are stored in a TFile generated by makeTFile4CutsDStartoKpipi.C in ./macros/
  // set there the cuts!!!!!
  Bool_t stdcuts=kFALSE;
  TFile* filecuts=new TFile("DStartoKpipiCuts.root");
  if(!filecuts->IsOpen()){
    cout<<"Input file not found: exit"<<endl;
    stdcuts=kTRUE;
  }

  AliRDHFCutsDStartoKpipi* RDHFDStartoKpipi=new AliRDHFCutsDStartoKpipi();
  if(stdcuts) RDHFDStartoKpipi->SetStandardCutsPP2010();
  else RDHFDStartoKpipi = (AliRDHFCutsDStartoKpipi*)filecuts->Get("DStartoKpipiCuts");
  RDHFDStartoKpipi->SetName("DStartoKpipiCuts");

  // mm let's see if everything is ok
  if(!RDHFDStartoKpipi){
    cout<<"Specific AliRDHFCuts not found"<<endl;
    return;
  }
 
  //CREATE THE TASK
  printf("CREATE TASK\n");
  // create the task
  AliAnalysisTaskSEDStarSpectra *task = new AliAnalysisTaskSEDStarSpectra("AliAnalysisTaskSEDStarSpectra",RDHFDStartoKpipi);
  task->SetAnalysisType(anaType);
  task->SetMC(theMCon);
  task->SetRareSearch(theRareOn);
  task->SetDebugLevel(0);

  mgr->AddTask(task);

  // Create and connect containers for input/output
  
  TString outputfile = AliAnalysisManager::GetCommonFileName();
  outputfile += ":PWG3_D2H_DStarSpectra";
  
  // ------ input data ------

  //AliAnalysisDataContainer *cinput0  = mgr->GetCommonInputContainer();
  AliAnalysisDataContainer *cinput0  =  mgr->CreateContainer("indstar",TChain::Class(), 
							     AliAnalysisManager::kInputContainer);
  // ----- output data -----
  
  AliAnalysisDataContainer *coutput1 = mgr->CreateContainer("chist1",TList::Class(),AliAnalysisManager::kOutputContainer,outputfile.Data());
  AliAnalysisDataContainer *coutputDStar1 = mgr->CreateContainer("DStarAll",TList::Class(),AliAnalysisManager::kOutputContainer,outputfile.Data());
  AliAnalysisDataContainer *coutputDStar2 = mgr->CreateContainer("DStarPID",TList::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputDStar3 = mgr->CreateContainer("cuts",AliRDHFCutsDStartoKpipi::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data()); //cuts
  AliAnalysisDataContainer *coutputDstarNorm = mgr->CreateContainer("coutputDstarNorm",AliNormalizationCounter::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data());

  mgr->ConnectInput(task,0,mgr->GetCommonInputContainer());

  mgr->ConnectOutput(task,1,coutput1);
  mgr->ConnectOutput(task,2,coutputDStar1);
  mgr->ConnectOutput(task,3,coutputDStar2);
  mgr->ConnectOutput(task,4,coutputDStar3);
  mgr->ConnectOutput(task,5,coutputDstarNorm);
  
  return task;
}

