# --------------------------------------------------------------
# GNUmakefile for examples module.  Sara Vanini,  13/III/00
# --------------------------------------------------------------

name := mainFLUGG
G4TARGET := $(name)
G4EXLIB := true

ifndef FLUGGINSTALL
  FLUGGINSTALL = ../../..
endif

.PHONY: all
all: lib bin

include $(FLUGGINSTALL)/config/binmake.gmk
