#!/bin/bash
if [ "x$SCRIPTDIR" == "x" ]; then
  echo 
  echo please run:
  echo export SCRIPTDIR=whatever is you path
  echo
  exit 1
fi
source $SCRIPTDIR/guiEnv.sh
test -d $GUI_OUTDIR_RUNS || mkdir -p $GUI_OUTDIR_RUNS
aliroot $SCRIPTDIR/loadlibsREC.C $SCRIPTDIR/ConfigOCDB.C\(119037\) $ALICE_ROOT/TPC/scripts/startGUItime.C\(\"$1\"\) $SCRIPTDIR/guiAlias.C
