#!/bin/bash

#parameters
#1: listfile
#2: outfile
#3: bindir

. $3/guiEnv.sh

#temporary working directory
dirID=/tmp/$(whoami)/$(date +%F.%H.%M.%S.%N)_$(basename $1)

test -d $dirID || mkdir -p $dirID
cd $dirID
root.exe -q -b $3/loadlibsREC.C $3/ConfigOCDB.C $ALICE_ROOT/TPC/CalibMacros/CalibEnv.C+\(\"$1\"\)
mv dcsTime.root $2
rmdir $dirID
