# $Id$

############################### AliGeant4 Makefile #############################

# Include Geant4 specific definitions

include $(G4INSTALL)/config/architecture.gmk

# Include machine specific definitions

include $(ALICE_ROOT)/conf/GeneralDef
include $(ALICE_ROOT)/conf/MachineDef.$(ALICE_TARGET)

# Include Alice Geant4 specific definitions

NEED_G4_LIBS := 1
include $(ALICE_ROOT)/conf/Geant4.gmk

PACKAGE = AliGeant4
TARGET  = aligeant4

# C++ sources

SRCS           = $(wildcard *.cxx)
SRCS          := $(filter-out $(TARGET).cxx,$(SRCS))

# C++ Headers

HDRS          =  $(wildcard *.icc) $(wildcard *.h)

# Library Root dictionary
# only for selected classes
# (temporarily excluded for OSF1 due to compilation errors)

ifneq ($(ALICE_TARGET),OSF1)
DICT          = AliGeant4Cint.cxx
DICTH         = AliRunConfiguration.h AliGeant4LinkDef.h
DICTO         = $(patsubst %.cxx,tgt_$(ALICE_TARGET)/%.o,$(DICT))
endif

# C++ Objects

OBJS          = $(patsubst %.cxx,tgt_$(ALICE_TARGET)/%.o,$(SRCS)) $(DICTO)

# Program C++ source, objects

PSRC          = $(TARGET).cxx
POBJ          = $(patsubst %.cxx,tgt_$(ALICE_TARGET)/%.o,$(PSRC))

# C++ compilation flags

CXXFLAGS      = $(CXXOPTS) -I$(ROOTSYS)/include -I. -I$(ALICE_ROOT)/include \
	        -I$(ALICE)/geant4_vmc/source/global/include \
		-I$(ALICE)/geant4_vmc/source/geometry/include \
		-I$(ALICE)/geant4_vmc/source/digits+hits/include \
		-I$(ALICE)/geant4_vmc/source/physics/include \
		-I$(ALICE)/geant4_vmc/source/event/include \
		-I$(ALICE)/geant4_vmc/source/run/include \
		-I$(ALICE)/geant4_vmc/source/interfaces/include \
		-I$(ALICE)/geant4_vmc/source/visualization/include
##### TARGETS #####
 
# Target

SLIBRARY	= $(LIBDIR)/libAliGeant4.$(SL)
ALIBRARY	= $(LIBDIR)/libAliGeant4.a
PROGRAM		= $(BINDIR)/$(TARGET)

default:	$(SLIBRARY) $(PROGRAM)
archived:	$(ALIBRARY)

$(LIBDIR)/libAliGeant4.$(SL):		$(OBJS)
$(LIBDIR)/libAliGeant4.a:		$(OBJS)

$(BINDIR)/$(TARGET):			$(POBJ)

$(DICT):				$(DICTH)

depend:					$(SRCS)

clean: macroclean

#HEADERS =	$(filter-out %LinkDef.h,$(HDRS))

# filter-out Geant3 dependent libraries (ZDC requires symbols from G3)
# and add Geant4 dependent ones
ALILIBS := $(filter-out -lgeant321,$(ALILIBS))
ALILIBS := $(filter-out -lgeant3,$(ALILIBS))
ALILIBS := $(filter-out -lZDC,$(ALILIBS))
ALILIBS := $(filter-out -lITS,$(ALILIBS))
ALILIBS += -lAliGeant4 -L$(ALICE)/geant4_vmc/lib/tgt_$(ALICE_TARGET) -lgeant4vmc

LIBS = $(ALILIBS) $(CLIBS) $(GLIBS) -lEG -lEGPythia6 -lpythia6 -lpdf \
	-lTHijing -lhijing  -lTMevSim -lmevsim -lTHbtp -lHBTP \
	-lTHerwig -lherwig $(G4LDLIBS) \
	-L$(MINSTALL)/lib/Linux-g++ -lplane -lsector -lmotif -lbasic

TOCLEAN	      = $(OBJS) $(POBJ) *Cint.cxx *Cint.h

CHECKS        = $(patsubst %.cxx,check/%.viol,$(SRCS))

############################### General Macros ################################

include $(ALICE_ROOT)/conf/GeneralMacros


# Geant4 specific compiler flags

CXXFLAGS += $(CPPFLAGS)


############################ Dependencies #####################################

-include tgt_$(ALICE_TARGET)/Make-depend 
