#!/bin/bash
if [ "x$SCRIPTDIR" == "x" ]; then
  echo 
  echo please run:
  echo export SCRIPTDIR=whatever is you path
  echo
  exit 1
fi
source $SCRIPTDIR/guiEnv.sh
test -d $GUI_OUTDIR_RUNS || mkdir -p $GUI_OUTDIR_RUNS
root.exe $SCRIPTDIR/loadlibsREC.C $SCRIPTDIR/ConfigOCDB.C $SCRIPTDIR/startGUItime.C\(\"$1\"\) $ALICE_ROOT/TPC/CalibMacros/guiAlias.C
