#!/bin/csh 
#################################################################
# script to run epos ; argumentS: file name ;  version number
#################################################################

if ( -e $OPT/$1.optns ) then
else
echo $OPT/$1.optns "does not exist"
exit
endif

if ( -e $OPT/$1.def ) then
source $OPT/$1.def
endif

rm -f $CHK/z-$1.check 
rm -f $CHK/z-$1.data 
rm -f $CHK/z-$1.copy 
rm -f $CHK/z-$1.log 

if ( $OPT == '.' ) then 
    setenv odir `pwd`
else
    setenv odir $OPT
endif

setenv seedj `date  '+%S%M%d%m%y%H%M%S'`    

#---------------------------------------------------------------------
time $OBJ/$SYSTEM/Xepos -n << END
!echo off
!uncomment the following line to get random seed
!set seedj $seedj
echo on
input $odir/$1.optns
!input  $EPO/epos.param
runprogram
stopprogram
END
if ( -s $CHK/z-$1.data ) then
  echo "###############################################################"
  echo "      output written to $CHK/z-$1.data"
  echo "###############################################################"
else
#  rm -f $CHK/z-$1.data
endif
if ( -s $CHK/z-$1.check ) then
else
  rm -f $CHK/z-$1.check
endif
if ( -s $HTO/$1.histo ) then
else
  rm -f $HTO/$1.histo
endif
rm -f $CHK/z-$1.log
rm -f $CHK/z-$1.copy
#rm -f gmon.out
date
exit

