#!/bin/csh 
#################################################################
# script to run epos ; argumentS: file name ;  version number
#################################################################

if ( -e $OPT/$1.optns ) then
else
echo $OPT/$1.optns "does not exist"
exit
endif

rm -f $CHK/z-$1.check 
rm -f $CHK/z-$1.data 
rm -f $CHK/z-$1.copy 
rm -f $CHK/z-$1.log 

if ( $OPT == '.' ) then 
    setenv odir `pwd`
else
    setenv odir $OPT
endif

#---------------------------------------------------------------------
time $OBJ/$SYSTEM/Xepos -n << END
echo off
set seedj $seedj
fname pathnx $EPO/
fname histo  $HTO/.s/z-$1.histo
fname check  $CHK/z-$1.check
fname copy   $CHK/z-$1.copy
fname log    $CHK/z-$1.log
fname data   $CHK/z-$1.data
fname initl  $EPO/epos.initl
fname inidi  $EPO/epos.inidi              
fname inidr  $EPO/epos.inidr              
fname iniev  $EPO/epos.iniev   
fname inirj  $EPO/epos.inirj
fname inics  $EPO/epos.inics
fname inigrv $EPO/epos.inigrv
fqgsjet dat   $EPO/qgsjet/qgsjet.dat
fqgsjet ncs   $EPO/qgsjet/qgsjet.ncs
fqgsjetII dat   $EPO/qgsjetII/qgsdat-II-03
fqgsjetII ncs   $EPO/qgsjetII/sectnu-II-03
nodecay 120
nodecay -120
nodecay 130
nodecay -130
nodecay -20
nodecay 14
nodecay -14
echo on
input $odir/$1.optns
echo off
input  $EPO/epos.param
runprogram
stopprogram
END
if ( -s $CHK/z-$1.data ) then
  echo "###############################################################"
  echo "      output written to $CHK/z-$1.data"
  echo "###############################################################"
else
  rm -f $CHK/z-$1.data
endif
if ( -s $CHK/z-$1.check ) then
else
  rm -f $CHK/z-$1.check
endif
if ( -s $HTO/.s/z-$1.histo ) then
else
  rm -f $HTO/.s/z-$1.histo
endif
rm -f $CHK/z-$1.log
rm -f $CHK/z-$1.copy
rm -f gmon.out
echo -n "Worker (nanpcw41-nanpcw65) : "
hostname
date
exit

