*
* $Id$
*
* $Log$
* Revision 1.1.1.1  1996/03/06 10:47:08  mclareni
* Zebra
*
*
*     Options for FZFILE
*
* fzficc.inc
*
      EQUIVALENCE    (IOPTM, IOPTVF(5)),  (IOPTX, IOPTVF(15))
     +,              (IOPTC, IOPTVF(6)),  (IOPTN, IOPTVF(16))
     +,              (IOPTA, IOPTVF(7)),  (IOPTS, IOPTVF(17))
     +,              (IOPTD, IOPTVF(8)),  (IOPTU, IOPTVF(18))
     +,              (IOPTT, IOPTVF(9)),  (IOPTI, IOPTVF(19))
     +,              (IOPTAS,IOPTVF(10)), (IOPTO, IOPTVF(20))
     +,              (IOPTK, IOPTVF(11)), (IOPTR, IOPTVF(21))
     +,              (IOPTL, IOPTVF(12)), (IOPTP, IOPTVF(22))
     +,              (IOPTY, IOPTVF(13)), (IOPTQ, IOPTVF(23))
     +,              (IOPTF, IOPTVF(14)), (IFLERR,IOPTVF(24))
