///
/// \file TestKinematics.C
/// \ingroup EMCAL_TestData
/// \brief Example read MC output in Kinematic.root file
///
/// Example macro to extract generated particles output from
/// Kinematics.root file
///
/// \author Gustavo Conesa Balbastre, <Gustavo.Conesa.Balbastre@cern.ch>, LPSC-CNRS
///

#if !defined(__CINT__) || defined(__MAKECINT__)

// Root include files 
#include <Riostream.h>
#include <TFile.h>
//#include <TSystem.h>
#include <TParticle.h>

// AliRoot include files 
#include "AliRunLoader.h"
#include "AliStack.h"

#endif

///
/// Main method
///
void TestKinematics()
{
  // Open galice.root
  AliRunLoader *rl = AliRunLoader::Open("galice.root",AliConfig::GetDefaultEventFolderName(),  "read");
  
  if (rl == 0x0)
  cout<<"Can not instantiate the Run Loader"<<endl;
  
  // Load Kinematics  
  rl->LoadKinematics();  
  
  // Get maximum number of events
  Int_t maxevent =  rl->GetNumberOfEvents();
  cout<<"Number of events "<<maxevent<<endl;
  
  // Event loop
  for ( Int_t iEvent=0; iEvent<maxevent; iEvent++)
  {
    // Load Event
    rl->GetEvent(iEvent);
    cout <<  " ======> Event " << iEvent << "  "<<rl->GetEventNumber() <<endl ;
    
    // Call kinematic stack
    AliStack *sta=rl->Stack();
    
    cout << "# tracks in runloader " << sta->GetNtrack()   // Number of all generated particles by the event generator + particles (secondaries) generated by GEANT 
	   << " # primaries in runloader " << sta->GetNprimary() // Number of all generated particles by the event generator
	   << endl;
    
    // Loop only on particles generated (no secondaries)
    for (Int_t  iprim=0; iprim<sta->GetNprimary() ; iprim++)
    {
      TParticle * primary=sta->Particle(iprim);
      
      Float_t phi = primary->Phi()*TMath::RadToDeg();
      
      if ( TMath::Abs(primary->Eta()) < 0.7     && 
          ( (phi >= 80  && phi <= 187)    || (phi >= 260  && phi <= 327)    ) &&  
          ( primary->GetStatusCode() == 1 || primary->GetStatusCode() == 21 ) && // physical primary or prompt/fragment photon
          primary->GetPdgCode() == 22     && primary->Pt() > 3                  )
      {
        cout
        <<"primary "<<iprim
        <<"; pdg "<<primary->GetPdgCode()
        <<"; status"<<primary->GetStatusCode()
        <<"; Energy "<<primary->Energy()
        <<"; pT "<<primary->Pt()
        <<"; phi "<<phi
        <<"; Eta "<<primary->Eta()
        << 
        endl;
      }
    }
  }
}
