AliHLTConsumerDescriptor Class Reference
#include <AliHLTConsumerDescriptor.h>
Detailed Description
Helper class to describe a consumer component.
There is unfortunately no unique determination of the data type from the component itself possible, thats why both component and data type have to be initialized and are stored in a compound. The class is intended to make bookkeeping easier.
Note: This class is only used for the HLT integration into AliRoot(p.).
Definition at line 30 of file AliHLTConsumerDescriptor.h.
Public Member Functions
AliHLTConsumerDescriptor ()
AliHLTConsumerDescriptor (AliHLTComponent *pConsumer)
AliHLTConsumerDescriptor (const AliHLTConsumerDescriptor &)
AliHLTConsumerDescriptor & operator= (const AliHLTConsumerDescriptor &)
~AliHLTConsumerDescriptor ()
AliHLTComponent * GetComponent ()
int SetActiveDataSegment (AliHLTUInt32_t offset, AliHLTUInt32_t size)
int CheckActiveDataSegment (AliHLTUInt32_t offset, AliHLTUInt32_t size)
int GetNofActiveSegments ()
int ReleaseActiveDataSegment (AliHLTUInt32_t offset, AliHLTUInt32_t size)
Private Attributes
AliHLTComponent * fpConsumer
vector< AliHLTDataBuffer::AliHLTDataSegment > fSegments
transient
Constructor & Destructor Documentation
AliHLTConsumerDescriptor::AliHLTConsumerDescriptor ()
standard constructur
AliHLTConsumerDescriptor::AliHLTConsumerDescriptor (AliHLTComponent * pConsumer)
constructur
Parameters:
pConsumer pointer to the consumer component
Definition at line 46 of file AliHLTConsumerDescriptor.cxx.
References fSegments.
47   :
48   fpConsumer(pConsumer),
49   fSegments()
50 {
51   // see header file for function documentation
52   fSegments.clear();
53 }
AliHLTConsumerDescriptor::AliHLTConsumerDescriptor (const AliHLTConsumerDescriptor &)
not a valid copy constructor, defined according to effective C++ style
Definition at line 55 of file AliHLTConsumerDescriptor.cxx.
56   :
57   TObject(),
58   AliHLTLogging(),
59   fpConsumer(desc.fpConsumer),
60   fSegments()
61 {
62   // see header file for function documentation
63 
64   // we can simply transfer the pointer to th new object since there are no
65   // release actions in the destructor
66 }
AliHLTConsumerDescriptor::~AliHLTConsumerDescriptor ()
destructor
Definition at line 78 of file AliHLTConsumerDescriptor.cxx.
References fSegments.
79 {
80   // see header file for function documentation
81   if (fSegments.size()>0) {
82     //HLTWarning("unreleased data segments found");
83   }
84 }
Member Function Documentation
int AliHLTConsumerDescriptor::CheckActiveDataSegment (AliHLTUInt32_t offset, AliHLTUInt32_t size)
Check whether there is an active data segment of certain size with certain offset.
Parameters:
offset offset of the data segment in the data buffer
size size of the data segment in the data buffer
Returns: > if existend, 0 if not
Definition at line 96 of file AliHLTConsumerDescriptor.cxx.
References fSegments.
Referenced by AliHLTDataBuffer::Release().
97 {
98   // see header file for function documentation
99   int iResult=0;
100   if (fSegments.size()>0) {
101     vector<AliHLTDataBuffer::AliHLTDataSegment>::iterator segment=fSegments.begin();
102     while (segment!=fSegments.end()) {
103       if ((iResult=((*segment).fSegmentOffset==offset && (*segment).fSegmentSize==size))>0) {
104         break;
105       }
106       segment++;
107     }
108   } else {
109     //HLTWarning("no data segment active for consumer %p", this);
110     iResult=-ENODATA;
111   }
112   return iResult;
113 }
AliHLTComponent* AliHLTConsumerDescriptor::GetComponent () [inline]
Get the component of this descriptor.
Returns: pointer to the component
Definition at line 49 of file AliHLTConsumerDescriptor.h.
49 {return fpConsumer;}
int AliHLTConsumerDescriptor::GetNofActiveSegments () [inline]
get the number of active segments for this consumer
Returns: number of active segments
Definition at line 81 of file AliHLTConsumerDescriptor.h.
References fSegments.
Referenced by AliHLTDataBuffer::Release().
81 {return fSegments.size();};
AliHLTConsumerDescriptor & AliHLTConsumerDescriptor::operator= (const AliHLTConsumerDescriptor &)
not a valid assignment op, but defined according to effective C++ style
Definition at line 68 of file AliHLTConsumerDescriptor.cxx.
References fpConsumer.
69 { 
70   // see header file for function documentation
71 
72   // we can simply transfer the pointer to th new object since there are no
73   // release actions in the destructor
74   fpConsumer=desc.fpConsumer;
75   return *this;
76 }
int AliHLTConsumerDescriptor::ReleaseActiveDataSegment (AliHLTUInt32_t offset, AliHLTUInt32_t size)
Definition at line 115 of file AliHLTConsumerDescriptor.cxx.
References fSegments.
Referenced by AliHLTDataBuffer::Release().
116 {
117   // see header file for function documentation
118   int iResult=0;
119   if (fSegments.size()>0) {
120     vector<AliHLTDataBuffer::AliHLTDataSegment>::iterator segment=fSegments.begin();
121     while (segment!=fSegments.end()) {
122       if ((iResult=((*segment).fSegmentOffset==offset && (*segment).fSegmentSize==size))>0) {
123         fSegments.erase(segment);
124         break;
125       }
126       segment++;
127     }
128     if (iResult==0) {
129       //HLTWarning("no data segment (%d:%d) active for consumer %p", offset, size, this);
130       iResult=-ENOENT;
131     }
132   } else {
133     //HLTWarning("no data segment active for consumer %p", this);
134     iResult=-ENODATA;
135   }
136   return iResult;
137 }
int AliHLTConsumerDescriptor::SetActiveDataSegment (AliHLTUInt32_t offset, AliHLTUInt32_t size)
Set an active data segment. the pointer will be handled in a container, no allocation, copy or cleanup.
Parameters:
offset offset of the segment in the buffer
size size of the segment in the buffer
Returns: >=0 if succeeded
Definition at line 86 of file AliHLTConsumerDescriptor.cxx.
References fSegments.
Referenced by AliHLTDataBuffer::Subscribe().
87 {
88   // see header file for function documentation
89   int iResult=0;
90   AliHLTDataBuffer::AliHLTDataSegment segment(offset, size);
91   fSegments.push_back(segment);
92   //HLTDebug("set active segment (%d:%d) for consumer %p", offset, size, this);
93   return iResult;
94 }
Member Data Documentation
AliHLTComponent* AliHLTConsumerDescriptor::fpConsumer [private]
consumer object
Definition at line 89 of file AliHLTConsumerDescriptor.h.
Referenced by operator=().
vector<AliHLTDataBuffer::AliHLTDataSegment> AliHLTConsumerDescriptor::fSegments [private]
transient
list of data segments
Definition at line 92 of file AliHLTConsumerDescriptor.h.
Referenced by AliHLTConsumerDescriptor(), CheckActiveDataSegment(), GetNofActiveSegments(), ReleaseActiveDataSegment(), SetActiveDataSegment(), and ~AliHLTConsumerDescriptor().
The documentation for this class was generated from the following files:
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTConsumerDescriptor.h
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTConsumerDescriptor.cxx