AliHLTDataSource Class Reference
#include <AliHLTDataSource.h>
Detailed Description
Base class of HLT data source components. The class provides a common interface for the implementation of HLT data source components. The child class must implement the functions:
DoInit(p.) (optional)
DoDeinit(p.) (optional)
GetEvent(p.)
GetComponentID(p.)
GetOutputDataType(p.)
GetOutputDataSize(p.)
Spawn(p.)
Definition at line 33 of file AliHLTDataSource.h.
Public Member Functions
AliHLTDataSource ()
virtual ~AliHLTDataSource ()
int DoProcessing (const AliHLTComponentEventData &evtData, const AliHLTComponentBlockData *blocks, AliHLTComponentTriggerData &trigData, AliHLTUInt8_t *outputPtr, AliHLTUInt32_t &size, vector< AliHLTComponentBlockData > &outputBlocks, AliHLTComponentEventDoneData *&edd)
TComponentType GetComponentType ()
void GetInputDataTypes (vector< AliHLTComponentDataType > &list)
Private Member Functions
virtual int GetEvent (const AliHLTComponentEventData &evtData, AliHLTComponentTriggerData &trigData, AliHLTUInt8_t *outputPtr, AliHLTUInt32_t &size, vector< AliHLTComponentBlockData > &outputBlocks)
virtual int GetEvent (const AliHLTComponentEventData &evtData, AliHLTComponentTriggerData &trigData)
Constructor & Destructor Documentation
AliHLTDataSource::AliHLTDataSource ()
standard constructor
AliHLTDataSource::~AliHLTDataSource () [virtual]
standard destructor
Definition at line 41 of file AliHLTDataSource.cxx.
42 { 
43   // see header file for class documentation
44 }
Member Function Documentation
int AliHLTDataSource::DoProcessing (const AliHLTComponentEventData & evtData, const AliHLTComponentBlockData * blocks, AliHLTComponentTriggerData & trigData, AliHLTUInt8_t * outputPtr, AliHLTUInt32_t & size, vector< AliHLTComponentBlockData > & outputBlocks, AliHLTComponentEventDoneData *& edd) [virtual]
Event processing function. The method is called by the framework to process one event. After preparation of data structures. The call is redirected to GetEvent.
Returns: neg. error code if failed
Implements AliHLTComponent (p.).
Definition at line 53 of file AliHLTDataSource.cxx.
References AliHLTComponentEventData::fBlockCnt, AliHLTComponent::GetComponentID(), GetEvent(), HLTDebug, and HLTWarning.
60 {
61   // see header file for class documentation
62   int iResult=0;
63   if (blocks) {
64     // this is currently just to get rid of the warning "unused parameter"
65   }
66   if (evtData.fBlockCnt > 0) {
67     HLTWarning("Data source component skips input data blocks");
68   }
69   iResult=GetEvent(evtData, trigData, outputPtr, size, outputBlocks);
70   HLTDebug("component %s (%p) GetEvent finished (%d)", GetComponentID(), this, iResult);
71   edd = NULL;
72   return iResult;
73 }
TComponentType AliHLTDataSource::GetComponentType () [inline, virtual]
Return AliHLTComponent::kSource(p.) type as component type.
Returns: component type id
Implements AliHLTComponent (p.).
Definition at line 60 of file AliHLTDataSource.h.
60 { return AliHLTComponent::kSource;}
int AliHLTDataSource::GetEvent (const AliHLTComponentEventData & evtData, AliHLTComponentTriggerData & trigData) [private, virtual]
The high-level data processing method. This is the default processing method; the method is called if no low level GetEvent(p.) method is overloaded by the component.
Parameters:
evtData event data structure
trigData trigger data structure
Returns: neg. error code if failed
Definition at line 86 of file AliHLTDataSource.cxx.
References HLTFatal.
87 {
88   HLTFatal("no processing method implemented");
89   return -ENOSYS;
90 }
int AliHLTDataSource::GetEvent (const AliHLTComponentEventData & evtData, AliHLTComponentTriggerData & trigData, AliHLTUInt8_t * outputPtr, AliHLTUInt32_t & size, vector< AliHLTComponentBlockData > & outputBlocks) [private, virtual]
The low-level data processing method for the component. This is the custom processing method and can be overloaded by the component.
Parameters:
evtData event data structure
trigData trigger data structure
outputPtr pointer to target buffer
size input: size of target buffer output:size of produced data
outputBlocks list to receive output block descriptors
Returns: neg. error code if failed
Definition at line 75 of file AliHLTDataSource.cxx.
Referenced by DoProcessing().
80 {
81   // we just forward to the high level method, all other parameters already
82   // have been stored internally
83   return GetEvent(evtData, trigData);
84 }
void AliHLTDataSource::GetInputDataTypes (vector< AliHLTComponentDataType > & list) [virtual]
Default implementation for all data sources. There are no input data types.
Implements AliHLTComponent (p.).
Definition at line 46 of file AliHLTDataSource.cxx.
47 {
48   // see header file for class documentation
49   list.clear(); // there are no input data types
50 }
The documentation for this class was generated from the following files:
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTDataSource.h
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTDataSource.cxx