AliHLTPHOSRawAnalyzer Class Reference
#include <AliHLTPHOSRawAnalyzer.h>
Public Member Functions
AliHLTPHOSRawAnalyzer ()
virtual ~AliHLTPHOSRawAnalyzer ()
AliHLTPHOSRawAnalyzer (double *dataPtr, double fs)
AliHLTPHOSRawAnalyzer (const AliHLTPHOSRawAnalyzer &)
AliHLTPHOSRawAnalyzer & operator= (const AliHLTPHOSRawAnalyzer &)
void BaselineCorrection (double *dataPtr, int N)
void BaselineCorrection (double *dataPtr, double baselineValue)
int FindStartIndex (double treshold)
float GetTiming ()
float GetEnergy ()
void SetData (double *data)
void SetSampleFreq (double freq)
void SetStartIndex (int startIndex)
void MakeInitialGuess ()
void MakeInitialGuess (int treshold)
virtual void SetTVector (Double_t *tVector, Int_t size)
virtual void SetAVector (Double_t *aVector, Int_t size)
virtual void Evaluate (int start=0, int lenght=100)=0
Double_t GetMaxValue (Double_t *dta, Int_t size)
Protected Attributes
Double_t * fFloatDataPtr
double fSampleFrequency
double fDTofGuess
double fDAmplGuess
double fTau
double fDTof
double fDAmpl
int fStartIndex
Constructor & Destructor Documentation
AliHLTPHOSRawAnalyzer::AliHLTPHOSRawAnalyzer ()
Definition at line 24 of file AliHLTPHOSRawAnalyzer.cxx.
References fFloatDataPtr.
24                                              :fFloatDataPtr(0), fSampleFrequency(10), fTau(2), fDTof(99999), fDAmpl(99999)
25 {
26   fFloatDataPtr = new double[1008];
27 }
AliHLTPHOSRawAnalyzer::~AliHLTPHOSRawAnalyzer () [virtual]
Definition at line 29 of file AliHLTPHOSRawAnalyzer.cxx.
30 {
31 
32 }
AliHLTPHOSRawAnalyzer::AliHLTPHOSRawAnalyzer (double * dtaPtr, double fs)
Main constructor
Parameters:
dataPtr Data array for wich a subarray will be taken to perform the fit
fs the sampling frequency in entities of MHz. Needed in order to calculate physical time
Definition at line 44 of file AliHLTPHOSRawAnalyzer.cxx.
References fFloatDataPtr, and fSampleFrequency.
44                                                                      :fFloatDataPtr(0), fSampleFrequency(10), fTau(2), fDTof(99999), fDAmpl(99999), fStartIndex(0)
45 {
46   fFloatDataPtr = dtaPtr;  
47   fSampleFrequency = fs;
48 } //end  
AliHLTPHOSRawAnalyzer::AliHLTPHOSRawAnalyzer (const AliHLTPHOSRawAnalyzer &)
Definition at line 34 of file AliHLTPHOSRawAnalyzer.cxx.
34                                                                         :fFloatDataPtr(0), fSampleFrequency(10), fTau(2), fDTof(99999), fDAmpl(99999), fStartIndex(0)
35 {
36 
37 }
Member Function Documentation
void AliHLTPHOSRawAnalyzer::BaselineCorrection (double * dataPtr, double baselineValue)
Shifts the baseline with the amount given by baselineValue If pretrigger samples are not present then the basline correction will be incorrect.
Parameters:
dataPtr array for wich to correct the basline
BaslineValue the basline value to subtract..
Definition at line 75 of file AliHLTPHOSRawAnalyzer.cxx.
References fFloatDataPtr.
76 {
77   fFloatDataPtr = dataPtr;   
78   printf("\nbaselineValue = %f\n", baselineValue);
79   cout << "Baseline correction not yet implemeted" << endl;
80 } //end BaslineCorrection
void AliHLTPHOSRawAnalyzer::BaselineCorrection (double * dataPtr, int N)
Attemps to level the basline to zero. The baseline will be calculated from the pretrigger samples and subtracted from the data array. If pretrigger samples are not present then the basline correction will be incorrect.
Parameters:
dataPtr array for wich to correct the basline
N the number of pretrigger samples used to calculate the baseline.
Definition at line 60 of file AliHLTPHOSRawAnalyzer.cxx.
References fFloatDataPtr.
61 {
62   fFloatDataPtr = dataPtr;  
63   //  n=N;
64   cout << "Baseline correction not yet implemeted" << endl;
65 } //end BaselineCorrection
virtual void AliHLTPHOSRawAnalyzer::Evaluate (int start = 0, int lenght = 100) [pure virtual]
Implemented in AliHLTPHOSRawAnalyzerChiSquareFit (p.), AliHLTPHOSRawAnalyzerCrude (p.), AliHLTPHOSRawAnalyzerKLevel (p.), and AliHLTPHOSRawAnalyzerLMS (p.).
int AliHLTPHOSRawAnalyzer::FindStartIndex (double treshold)
Definition at line 124 of file AliHLTPHOSRawAnalyzer.cxx.
125 {
126   printf("\ntreshold = %f \n", treshold);
127   cout << "Find Start index not yet implemented" << endl;
128   return 0;
129 } //end FindStartIndex
float AliHLTPHOSRawAnalyzer::GetEnergy ()
Gives the time in entities of ADC channels (quantization levels). Absolute enrgy is found by multiplying with offline calibration constants.
Definition at line 99 of file AliHLTPHOSRawAnalyzer.cxx.
Referenced by main().
100 {
101   return fDAmpl;
102 } //end GetEnergy
Double_t AliHLTPHOSRawAnalyzer::GetMaxValue (Double_t * dta, Int_t size)
Definition at line 176 of file AliHLTPHOSRawAnalyzer.cxx.
177 {
178 
179   Double_t tmpMax = 0;
180 
181   for(int i = 0; i < size; i++)
182     {
183       if(dta[i] > tmpMax)
184         {
185           tmpMax = dta[i];
186         }
187 
188     }
189   
190   return tmpMax;
191 
192 }
float AliHLTPHOSRawAnalyzer::GetTiming ()
Gives the timing in entities of sample indexes Physical time is found by multiplying with the sampling intervall (Ts).
Definition at line 88 of file AliHLTPHOSRawAnalyzer.cxx.
Referenced by main().
89 {
90   return fDTof;
91 } //end GetTiming
void AliHLTPHOSRawAnalyzer::MakeInitialGuess (int treshold)
This function applies only to the Chi and Least mean square fit. An initial guess is made based on the average of the first 5 samples and the first value exeeding threshold + this value.
Parameters:
treshold The index of the first value above treshold is ntaken to be the first value.
Definition at line 149 of file AliHLTPHOSRawAnalyzer.cxx.
150 {
151   printf("\ntreshold = %d\n", treshold);
152   cout << "Make initial guess not yet implemeted" << endl;  
153 }
void AliHLTPHOSRawAnalyzer::MakeInitialGuess ()
This function applies only to the Chi and Least mean square fit. An initial guess is made based on the average of the first 5 samples and the first value exeeding this value.
Definition at line 137 of file AliHLTPHOSRawAnalyzer.cxx.
138 {
139   cout << "Make initial guess not yet implemeted" << endl;
140 }
AliHLTPHOSRawAnalyzer& AliHLTPHOSRawAnalyzer::operator= (const AliHLTPHOSRawAnalyzer &) [inline]
Definition at line 17 of file AliHLTPHOSRawAnalyzer.h.
18     {
19       return *this;
20     }
void AliHLTPHOSRawAnalyzer::SetAVector (Double_t * aVector, Int_t size) [virtual]
Reimplemented in AliHLTPHOSRawAnalyzerPeakFinder (p.).
Definition at line 169 of file AliHLTPHOSRawAnalyzer.cxx.
Referenced by AliHLTPHOSRawAnalyzerPeakFinderComponent::LoadPFVector().
170 {
171  cout <<"ERROR: AliHLTPHOSRawAnalyzer::SetAVector:  You cannot set the peakfindervector here, must be set in derived class peakfinder"<<endl;
172 }
void AliHLTPHOSRawAnalyzer::SetData (double * data)
Set data array. Overrides data data array set in the constructor.
Definition at line 109 of file AliHLTPHOSRawAnalyzer.cxx.
References fFloatDataPtr.
Referenced by main().
110 {
111   //  double *dta;
112   //  dta = data;
113   fFloatDataPtr = data;
114   //  cout << "Set data not yet implemented" << endl;
115 }
void AliHLTPHOSRawAnalyzer::SetSampleFreq (double freq)
Definition at line 118 of file AliHLTPHOSRawAnalyzer.cxx.
References fSampleFrequency.
Referenced by main().
119 {
120   fSampleFrequency = freq;
121 }
void AliHLTPHOSRawAnalyzer::SetStartIndex (int startIndex)
Definition at line 156 of file AliHLTPHOSRawAnalyzer.cxx.
References fStartIndex.
157 {
158   fStartIndex = index;
159 }
void AliHLTPHOSRawAnalyzer::SetTVector (Double_t * tVector, Int_t size) [virtual]
Reimplemented in AliHLTPHOSRawAnalyzerPeakFinder (p.).
Definition at line 162 of file AliHLTPHOSRawAnalyzer.cxx.
Referenced by AliHLTPHOSRawAnalyzerPeakFinderComponent::LoadPFVector().
163 {
164   cout <<"ERROR: AliHLTPHOSRawAnalyzer::SetTVector:  You cannot set the peakfindervector here, must be set in derived class peakfinder"<<endl;
165 }
Member Data Documentation
double AliHLTPHOSRawAnalyzer::fDAmpl [protected]
Amplitude in entities of ADC levels
Definition at line 44 of file AliHLTPHOSRawAnalyzer.h.
double AliHLTPHOSRawAnalyzer::fDAmplGuess [protected]
Initial guess for amplitude
Definition at line 41 of file AliHLTPHOSRawAnalyzer.h.
double AliHLTPHOSRawAnalyzer::fDTof [protected]
Time of flight in entities of sample intervals
Definition at line 43 of file AliHLTPHOSRawAnalyzer.h.
double AliHLTPHOSRawAnalyzer::fDTofGuess [protected]
Initial guess for t0
Definition at line 40 of file AliHLTPHOSRawAnalyzer.h.
Double_t* AliHLTPHOSRawAnalyzer::fFloatDataPtr [protected]
Float representation of data that should be fitted
Definition at line 38 of file AliHLTPHOSRawAnalyzer.h.
Referenced by AliHLTPHOSRawAnalyzer(), BaselineCorrection(), and SetData().
double AliHLTPHOSRawAnalyzer::fSampleFrequency [protected]
The ADC sample frequency in MHz used under data taking
Definition at line 39 of file AliHLTPHOSRawAnalyzer.h.
Referenced by AliHLTPHOSRawAnalyzer(), and SetSampleFreq().
int AliHLTPHOSRawAnalyzer::fStartIndex [protected]
Definition at line 46 of file AliHLTPHOSRawAnalyzer.h.
Referenced by SetStartIndex().
double AliHLTPHOSRawAnalyzer::fTau [protected]
The risetime in micro seconds
Definition at line 42 of file AliHLTPHOSRawAnalyzer.h.
The documentation for this class was generated from the following files:
AliHLTPHOSRawAnalyzer.h
AliHLTPHOSRawAnalyzer.cxx