AliHLTPHOSRawAnalyzerPeakFinderComponent Class Reference
#include <AliHLTPHOSRawAnalyzerPeakFinderComponent.h>
Public Member Functions
AliHLTPHOSRawAnalyzerPeakFinderComponent ()
~AliHLTPHOSRawAnalyzerPeakFinderComponent ()
virtual const char * GetComponentID ()
virtual AliHLTComponent * Spawn ()
virtual int DoInit (int argc, const char **argv)
virtual int Deinit ()
virtual int DoDeinit ()
void DumpData (int gain)
void DumpData ()
void DumpChannelData (Double_t *data)
void SetEquippmentID (AliHLTUInt32_t id)
int GetEquippmentID ()
void SetCoordinates (AliHLTUInt32_t equippmentID)
virtual void GetInputDataTypes (std::vector< AliHLTComponentDataType, std::allocator< AliHLTComponentDataType > > &)
virtual AliHLTComponentDataType GetOutputDataType ()
virtual void GetOutputDataSize (unsigned long &constBase, double &inputMultiplier)
virtual int DoEvent (const AliHLTComponentEventData &, const AliHLTComponentBlockData *, AliHLTComponentTriggerData &, AliHLTUInt8_t *, AliHLTUInt32_t &, std::vector< AliHLTComponentBlockData, std::allocator< AliHLTComponentBlockData > > &)
Static Public Attributes
AliHLTPHOSRawAnalyzerPeakFinderComponent gAliHLTPHOSRawAnalyzerPeakFinderComponent
Protected Attributes
AliHLTPHOSRawAnalyzer * analyzerPtr
Private Member Functions
Bool_t LoadPFVector ()
Bool_t LoadPFVector (int startindex, int Nsamples, int tau, int fs)
AliHLTPHOSRawAnalyzerPeakFinderComponent (const AliHLTPHOSRawAnalyzerPeakFinderComponent &)
AliHLTPHOSRawAnalyzerPeakFinderComponent & operator= (const AliHLTPHOSRawAnalyzerPeakFinderComponent)
Constructor & Destructor Documentation
AliHLTPHOSRawAnalyzerPeakFinderComponent::AliHLTPHOSRawAnalyzerPeakFinderComponent ()
Definition at line 27 of file AliHLTPHOSRawAnalyzerPeakFinderComponent.cxx.
References LoadPFVector().
27                                                                                   :AliHLTPHOSRawAnalyzerComponent()
28 {
29   analyzerPtr = new AliHLTPHOSRawAnalyzerPeakFinder();
30 
31   if(LoadPFVector() == kFALSE)
32     {
33       //      cout << "Warning, could not load PF vectors" << endl;
34     }
35   else 
36     {
37       //    cout << "Loaded PF vectors" << endl;
38     }
39 
40 } 
AliHLTPHOSRawAnalyzerPeakFinderComponent::~AliHLTPHOSRawAnalyzerPeakFinderComponent ()
Definition at line 42 of file AliHLTPHOSRawAnalyzerPeakFinderComponent.cxx.
43 {
44 
45 }
AliHLTPHOSRawAnalyzerPeakFinderComponent::AliHLTPHOSRawAnalyzerPeakFinderComponent (const AliHLTPHOSRawAnalyzerPeakFinderComponent &) [private]
Definition at line 49 of file AliHLTPHOSRawAnalyzerPeakFinderComponent.cxx.
49                                                                                                                                     : AliHLTPHOSRawAnalyzerComponent()
50 {
51 
52 }
Member Function Documentation
int AliHLTPHOSRawAnalyzerComponent::Deinit () [virtual, inherited]
Definition at line 76 of file AliHLTPHOSRawAnalyzerComponent.cxx.
77 {
78   return 0;
79 }
int AliHLTPHOSRawAnalyzerComponent::DoDeinit () [virtual, inherited]
Definition at line 87 of file AliHLTPHOSRawAnalyzerComponent.cxx.
References AliHLTPHOSRawAnalyzerComponent::fPHOSRawStream, and AliHLTPHOSRawAnalyzerComponent::fRawMemoryReader.
88 {
89   Logging(kHLTLogInfo, "HLT", "PHOS", ",AliHLTPHOSRawAnalyzerComponen DoDeinit");
90 
91   if(fRawMemoryReader !=0)
92     {
93       delete fRawMemoryReader;
94     }
95     
96   if(fPHOSRawStream != 0)
97     {
98       delete fPHOSRawStream;
99     }
100   return 0;
101 
102 }
virtual int AliHLTPHOSRawAnalyzerComponent::DoEvent (const AliHLTComponentEventData &, const AliHLTComponentBlockData *, AliHLTComponentTriggerData &, AliHLTUInt8_t *, AliHLTUInt32_t &, std::vector< AliHLTComponentBlockData, std::allocator< AliHLTComponentBlockData > > &) [virtual, inherited]
int AliHLTPHOSRawAnalyzerComponent::DoInit (int argc, const char ** argv) [virtual, inherited]
Definition at line 263 of file AliHLTPHOSRawAnalyzerComponent.cxx.
References AliHLTPHOSRawAnalyzerComponent::fPHOSRawStream, AliHLTPHOSRawAnalyzerComponent::fRawMemoryReader, AliHLTPHOSRawAnalyzerComponent::Reset(), AliHLTPHOSRawAnalyzerComponent::SetCoordinates(), and AliHLTPHOSRawAnalyzerComponent::SetEquippmentID().
264 {
265   int equippmentID = atoi(argv[6]);
266   cout << "AliHLTPHOSRawAnalyzerComponent::DoIni  Setting EquipmentID to" << equippmentID << endl;
267   Reset();
268   fRawMemoryReader = new AliRawReaderMemory();
269   fPHOSRawStream = new  AliCaloRawStream(fRawMemoryReader,"PHOS");
270   fPHOSRawStream->SetOldRCUFormat(kFALSE);
271   fRawMemoryReader->SetEquipmentID(equippmentID); 
272   SetEquippmentID(equippmentID);
273   SetCoordinates(equippmentID);
274   if (argc==0 && argv==NULL) {
275     // this is currently just to get rid of the warning "unused parameter"
276   }
277   return 0;
278 }
void AliHLTPHOSRawAnalyzerComponent::DumpChannelData (Double_t * data) [inherited]
Definition at line 307 of file AliHLTPHOSRawAnalyzerComponent.cxx.
308 {
309       cout << endl;
310       
311       for(int i=0; i<  ALTRO_MAX_SAMPLES; i++)
312         {
313           if (data[i] != 0)
314             {
315               cout <<i <<"\t";
316             }
317         }
318       cout << endl;
319       
320       for(int i=0; i<  ALTRO_MAX_SAMPLES; i++)
321         {
322           if (data[i] != 0)
323             {
324               cout <<data[i] <<"\t";
325             }
326         }
327       
328       cout << endl;
329 }
void AliHLTPHOSRawAnalyzerComponent::DumpData () [inherited]
Definition at line 301 of file AliHLTPHOSRawAnalyzerComponent.cxx.
302 {
303   DumpData(0);
304 }
void AliHLTPHOSRawAnalyzerComponent::DumpData (int gain) [inherited]
Definition at line 281 of file AliHLTPHOSRawAnalyzerComponent.cxx.
References AliHLTPHOSRawAnalyzerComponent::fMaxValues.
282 {
283   for(int mod = 0; mod < N_MODULES; mod ++)
284     {
285       printf("\n ***********  MODULE %d ************\n", mod);
286       for(int row = 0; row <  N_ROWS_MOD; row ++)
287         {
288           for(int col = 0; col <  N_COLUMNS_MOD; col ++)
289             {
290               if( fMaxValues[mod][row][col][0] != 0)
291                 { 
292                   cout << fMaxValues[mod][row][col][gain] << "\t";
293                 }
294             }
295         } 
296     }
297 }
const char * AliHLTPHOSRawAnalyzerPeakFinderComponent::GetComponentID () [virtual]
Implements AliHLTPHOSRawAnalyzerComponent (p.).
Definition at line 56 of file AliHLTPHOSRawAnalyzerPeakFinderComponent.cxx.
57 {
58   return "PhosRawPeakFinder";
59 }
int AliHLTPHOSRawAnalyzerComponent::GetEquippmentID () [inherited]
Definition at line 391 of file AliHLTPHOSRawAnalyzerComponent.cxx.
392 {
393   return  fEquippmentID;
394 }
virtual void AliHLTPHOSRawAnalyzerComponent::GetInputDataTypes (std::vector< AliHLTComponentDataType, std::allocator< AliHLTComponentDataType > > &) [virtual, inherited]
void AliHLTPHOSRawAnalyzerComponent::GetOutputDataSize (unsigned long & constBase, double & inputMultiplier) [virtual, inherited]
Definition at line 132 of file AliHLTPHOSRawAnalyzerComponent.cxx.
134 {
135   constBase = 30;
136   inputMultiplier = 0.1;
137 }
AliHLTComponentDataType AliHLTPHOSRawAnalyzerComponent::GetOutputDataType () [virtual, inherited]
Definition at line 126 of file AliHLTPHOSRawAnalyzerComponent.cxx.
127 {
128   return AliHLTPHOSDefinitions::gkCellEnergyDataType;
129 }
Bool_t AliHLTPHOSRawAnalyzerPeakFinderComponent::LoadPFVector (int startindex, int Nsamples, int tau, int fs) [private]
Definition at line 69 of file AliHLTPHOSRawAnalyzerPeakFinderComponent.cxx.
References PF_VECTOR_DIR, AliHLTPHOSRawAnalyzer::SetAVector(), and AliHLTPHOSRawAnalyzer::SetTVector().
70 {
71   char tmpPFPath[PF_MAX_PATH_LENGTH];
72   Double_t tmpAVector[nSamples];
73   Double_t tmpTVector[nSamples]; 
74   sprintf(tmpPFPath,"%s%s/start%dN%dtau%dfs%d.txt", getenv("ALICE_ROOT"), PF_VECTOR_DIR, startIndex, nSamples, tau, fs);
75   //  cout <<"PF PATH =" << tmpPFPath << endl;
76 
77   FILE *fp;
78 
79   fp = fopen(tmpPFPath, "r");
80   
81   if(fp != 0)
82     {
83       for(int i=0; i <  nSamples; i++)
84         {
85           fscanf(fp, "%lf", &tmpAVector[i]);
86         }
87 
88 
89       fscanf(fp, "\n");
90 
91       for(int i=0; i < nSamples; i++)
92         {
93                   fscanf(fp, "%lf", &tmpTVector[i]);
94         }
95 
96       analyzerPtr->SetAVector(tmpAVector,  nSamples);
97       analyzerPtr->SetTVector(tmpTVector,  nSamples);
98 
99       fclose(fp);
100       return kTRUE;
101 
102     }
103   
104   else
105     {
106       HLTFatal("ERROR: could not  open PF vector file");
107       return kFALSE;
108     }
109 }
Bool_t AliHLTPHOSRawAnalyzerPeakFinderComponent::LoadPFVector () [private]
Definition at line 62 of file AliHLTPHOSRawAnalyzerPeakFinderComponent.cxx.
References DEFAULT_FS, DEFAULT_TAU, PF_DEFAULT_N_SAMPLES, and PF_DEFAULT_STARTINDEX.
Referenced by AliHLTPHOSRawAnalyzerPeakFinderComponent().
63 {
64   return LoadPFVector(PF_DEFAULT_STARTINDEX,  PF_DEFAULT_N_SAMPLES, DEFAULT_TAU, DEFAULT_FS );
65 }
AliHLTPHOSRawAnalyzerPeakFinderComponent& AliHLTPHOSRawAnalyzerPeakFinderComponent::operator= (const AliHLTPHOSRawAnalyzerPeakFinderComponent) [inline, private]
Definition at line 21 of file AliHLTPHOSRawAnalyzerPeakFinderComponent.h.
22     {
23       return *this;
24     };
void AliHLTPHOSRawAnalyzerComponent::SetCoordinates (AliHLTUInt32_t equippmentID) [inherited]
Definition at line 397 of file AliHLTPHOSRawAnalyzerComponent.cxx.
References AliHLTPHOSRawAnalyzerComponent::fEquippmentID, AliHLTPHOSRawAnalyzerComponent::fModuleID, AliHLTPHOSRawAnalyzerComponent::fRcuColOffeset, AliHLTPHOSRawAnalyzerComponent::fRcuRowOffeset, AliHLTPHOSRawAnalyzerComponent::fRcuX, and AliHLTPHOSRawAnalyzerComponent::fRcuZ.
Referenced by AliHLTPHOSRawAnalyzerComponent::DoInit().
398 {
399   int rcuIndex =  (fEquippmentID - 1792)%4;
400   fModuleID = (fEquippmentID  -1792 -rcuIndex)/5;
401 
402   if(rcuIndex == 0)
403     {
404       fRcuX = 0; 
405       fRcuZ = 0;
406     }
407 
408   if(rcuIndex == 1)
409     {
410       fRcuX = 0; 
411       fRcuZ = 1;
412     }
413  
414   if(rcuIndex == 2)
415     {
416       fRcuX = 1; 
417       fRcuZ = 0;
418     }
419 
420 
421   if(rcuIndex == 3)
422     {
423       fRcuX = 1; 
424       fRcuZ = 1;
425     }
426 
427   fRcuRowOffeset = 32*fRcuX;
428   fRcuColOffeset = 28*fRcuZ;
429 
430 }
void AliHLTPHOSRawAnalyzerComponent::SetEquippmentID (AliHLTUInt32_t id) [inherited]
Definition at line 385 of file AliHLTPHOSRawAnalyzerComponent.cxx.
References AliHLTPHOSRawAnalyzerComponent::fEquippmentID.
Referenced by AliHLTPHOSRawAnalyzerComponent::DoInit().
386 {
387   fEquippmentID = id;
388 }
AliHLTComponent * AliHLTPHOSRawAnalyzerPeakFinderComponent::Spawn () [virtual]
Implements AliHLTPHOSRawAnalyzerComponent (p.).
Definition at line 114 of file AliHLTPHOSRawAnalyzerPeakFinderComponent.cxx.
115 {
116   return new AliHLTPHOSRawAnalyzerPeakFinderComponent;
117 }
Member Data Documentation
AliHLTPHOSRawAnalyzer* AliHLTPHOSRawAnalyzerComponent::analyzerPtr [protected, inherited]
Definition at line 45 of file AliHLTPHOSRawAnalyzerComponent.h.
AliHLTPHOSRawAnalyzerPeakFinderComponent AliHLTPHOSRawAnalyzerPeakFinderComponent::gAliHLTPHOSRawAnalyzerPeakFinderComponent [static]
Definition at line 16 of file AliHLTPHOSRawAnalyzerPeakFinderComponent.h.
The documentation for this class was generated from the following files:
AliHLTPHOSRawAnalyzerPeakFinderComponent.h
AliHLTPHOSRawAnalyzerPeakFinderComponent.cxx