AliHLTOfflineInterface Class Reference
#include <AliHLTOfflineInterface.h>
Detailed Description
The class implements the basic interface to the AliRoot objects during reconstructions. It serves as a base class for offline source and sink interface components and provides access methods for the AliRunLoader, AliRawReader and AliESD objects. The AliRunLoader and the AliRawReader are fixed during one run, while the AliESD object will be changed from event to event.
 Note: The digits and clusters trees are not available through this interface class as they are completetly detector (AliLoader) dependend.
Note: This class is only used for the HLT integration into AliRoot(p.).
Definition at line 40 of file AliHLTOfflineInterface.h.
Public Member Functions
AliHLTOfflineInterface ()
AliHLTOfflineInterface (AliRunLoader *pRunLoader, AliRawReader *pRawReader)
AliHLTOfflineInterface (const AliHLTOfflineInterface &)
AliHLTOfflineInterface & operator= (const AliHLTOfflineInterface &)
virtual ~AliHLTOfflineInterface ()
AliRunLoader * GetRunLoader () const
AliRawReader * GetRawReader () const
int SetESD (Int_t eventNo, AliESD *pESD)
AliESD * GetESD () const
int SetParams (AliRunLoader *runLoader, AliRawReader *rawReader)
int Reset ()
virtual int FillESD (int eventNo, AliRunLoader *runLoader, AliESD *esd)=0
Static Public Member Functions
int SetParamsToComponents (AliRunLoader *runLoader, AliRawReader *rawReader)
int FillComponentESDs (int eventNo, AliRunLoader *runLoader, AliESD *esd)
int ResetComponents ()
Static Protected Member Functions
int Register (AliHLTOfflineInterface *me)
int Unregister (AliHLTOfflineInterface *me)
Private Member Functions
ClassDef (AliHLTOfflineInterface, 1)
transient
Private Attributes
AliRunLoader * fpRunLoader
transient
AliRawReader * fpRawReader
transient
AliESD * fpESD
transient
Static Private Attributes
TList fgList
TObjLink * fgCurrentLnk = NULL
AliRunLoader * fgpRunLoader = NULL
AliRawReader * fgpRawReader = NULL
transient
Constructor & Destructor Documentation
AliHLTOfflineInterface::AliHLTOfflineInterface ()
standard constructor
AliHLTOfflineInterface::AliHLTOfflineInterface (AliRunLoader * pRunLoader, AliRawReader * pRawReader)
constructor
Parameters:
pRunLoader pointer to AliRoot run loader
pRawReader pointer to AliRoot raw reader
Definition at line 48 of file AliHLTOfflineInterface.cxx.
49   :
50   fpRunLoader(pRunLoader),
51   fpRawReader(pRawReader),
52   fpESD(NULL)
53 {
54 }
AliHLTOfflineInterface::AliHLTOfflineInterface (const AliHLTOfflineInterface &)
not a valid copy constructor, defined according to effective C++ style
Definition at line 56 of file AliHLTOfflineInterface.cxx.
57   :
58   TObject(),
59   fpRunLoader(NULL),
60   fpRawReader(NULL),
61   fpESD(NULL)
62 {
63   // see header file for class documentation
64   //HLTFatal("copy constructor untested");
65 }
AliHLTOfflineInterface::~AliHLTOfflineInterface () [virtual]
destructor
Definition at line 74 of file AliHLTOfflineInterface.cxx.
75 {
76 }
Member Function Documentation
AliHLTOfflineInterface::ClassDef (AliHLTOfflineInterface, 1) [private]
transient
int AliHLTOfflineInterface::FillComponentESDs (int eventNo, AliRunLoader * runLoader, AliESD * esd) [static]
Fill ESD for one event. The FillESD method of all active AliHLTOfflineDataSink's is called in order to fill the ESD with the previously reconstructed data. This method works on the global list.
Parameters:
eventNo event No. Note: this is an internal enumeration of the processed events.
runLoader the AliRoot runloader
esd an AliESD instance
Returns: neg. error code if failed
Definition at line 169 of file AliHLTOfflineInterface.cxx.
References fgCurrentLnk, fgList, FillESD(), GetRunLoader(), and SetESD().
Referenced by AliHLTSystem::FillESD().
170 {
171   // see header file for class documentation
172   int iResult=0;
173   fgCurrentLnk=fgList.FirstLink();
174   while (fgCurrentLnk!=NULL) {
175     AliHLTOfflineInterface* pComponent=reinterpret_cast<AliHLTOfflineInterface*>(fgCurrentLnk->GetObject());
176     int iLocal=0;
177     if (pComponent) {
178       pComponent->SetESD(eventNo, esd);
179       if (pComponent->GetRunLoader()!=runLoader) {
180         //HLTWarning("runLoader missmatch: component %p was reconstructed with runLoader %p, but got %p now", pComponent, pComponent->GetRunLoader(), runLoader);
181       }
182       iLocal=pComponent->FillESD(eventNo, runLoader, esd);
183     }
184     if (iLocal<0) {
185       if (iResult>=0) iResult=iLocal;
186     }
187     fgCurrentLnk=fgCurrentLnk->Next();
188   }
189   return iResult;
190 }
virtual int AliHLTOfflineInterface::FillESD (int eventNo, AliRunLoader * runLoader, AliESD * esd) [pure virtual]
Fill ESD for one event. Fill the ESD with the previously reconstructed data. It must be implmented by the child class.
Parameters:
eventNo event No. Note: this is an internal enumeration of the processed events.
runLoader the AliRoot runloader
esd an AliESD instance
Returns: neg. error code if failed
Implemented in AliHLTOfflineDataSource (p.).
Referenced by FillComponentESDs().
AliESD * AliHLTOfflineInterface::GetESD () const
Get the AliRoot ESD
Definition at line 94 of file AliHLTOfflineInterface.cxx.
95 {
96   return fpESD;
97 }
AliRawReader * AliHLTOfflineInterface::GetRawReader () const
Get the AliRoot raw reader
Definition at line 83 of file AliHLTOfflineInterface.cxx.
References fpRawReader.
84 {
85   return fpRawReader!=NULL?fpRawReader:fgpRawReader;
86 }
AliRunLoader * AliHLTOfflineInterface::GetRunLoader () const
Get the AliRoot run loader.
Definition at line 78 of file AliHLTOfflineInterface.cxx.
References fpRunLoader.
Referenced by FillComponentESDs().
79 {
80   return fpRunLoader!=NULL?fpRunLoader:fgpRunLoader;
81 }
AliHLTOfflineInterface & AliHLTOfflineInterface::operator= (const AliHLTOfflineInterface &)
not a valid assignment op, but defined according to effective C++ style
Definition at line 67 of file AliHLTOfflineInterface.cxx.
68 { 
69   // see header file for class documentation
70   //HLTFatal("assignment operator untested");
71   return *this;
72 }
int AliHLTOfflineInterface::Register (AliHLTOfflineInterface * me) [static, protected]
Register an OfflineInterface.
Parameters:
me instance of AliHLTOfflineInterface
Returns: neg. error code if failed
Definition at line 192 of file AliHLTOfflineInterface.cxx.
References fgList.
Referenced by AliHLTOfflineDataSink::AliHLTOfflineDataSink().
193 {
194   // see header file for function documentation
195   int iResult=0;
196   if (fgList.FindObject(me->GetName())==NULL) {
197     fgList.Add(me);
198   } else {
199   }
200   return iResult;
201 }
int AliHLTOfflineInterface::Reset ()
Reset AliRoot internal params.
Definition at line 114 of file AliHLTOfflineInterface.cxx.
References fpESD, fpRawReader, and fpRunLoader.
Referenced by ResetComponents().
115 {
116   // see header file for class documentation
117   int iResult=0;
118   fpRunLoader=NULL;
119   fpRawReader=NULL;
120   fpESD=NULL;
121   return iResult;
122 }
int AliHLTOfflineInterface::ResetComponents () [static]
Reset AliRoot internal params of all active components. This method works on the global list.
Definition at line 152 of file AliHLTOfflineInterface.cxx.
References fgCurrentLnk, fgList, and Reset().
153 {
154   // see header file for class documentation
155   int iResult=0;
156   fgCurrentLnk=fgList.FirstLink();
157   while (fgCurrentLnk!=NULL) {
158     AliHLTOfflineInterface* pComponent=reinterpret_cast<AliHLTOfflineInterface*>(fgCurrentLnk->GetObject());
159     int iLocal=0;
160     if (pComponent) iLocal=pComponent->Reset();
161     if (iLocal<0) {
162       if (iResult>=0) iResult=iLocal;
163     }
164     fgCurrentLnk=fgCurrentLnk->Next();
165   }
166   return iResult;
167 }
int AliHLTOfflineInterface::SetESD (Int_t eventNo, AliESD * pESD)
Set AliRoot ESD for the current event.
Definition at line 88 of file AliHLTOfflineInterface.cxx.
References fpESD.
Referenced by FillComponentESDs().
89 {
90   fpESD=pESD;
91   return 0;
92 }
int AliHLTOfflineInterface::SetParams (AliRunLoader * runLoader, AliRawReader * rawReader)
Set AliRoot external params.
Parameters:
runLoader the AliRoot runloader
rawReader the AliRoot RawReader
Returns: neg. error code if failed
Definition at line 99 of file AliHLTOfflineInterface.cxx.
References fpRawReader, and fpRunLoader.
Referenced by SetParamsToComponents().
100 {
101   // see header file for class documentation
102   int iResult=0;
103   if (fpRunLoader!=NULL && fpRunLoader!=runLoader) {
104     //HLTWarning("overriding previous instance of Run Loader %p with %p", fpRunLoader, runLoader);
105   }
106   fpRunLoader=runLoader;
107   if (fpRawReader!=NULL && fpRawReader!=rawReader) {
108     //HLTWarning("overriding previous instance of RawReader %p with %p", fpRawReader, rawReader);
109   }
110   fpRawReader=rawReader;
111   return iResult;
112 }
int AliHLTOfflineInterface::SetParamsToComponents (AliRunLoader * runLoader, AliRawReader * rawReader) [static]
Set AliRoot external params. This method works on the global list.
Parameters:
runLoader the AliRoot runloader
rawReader the AliRoot RawReader
Returns: neg. error code if failed
Definition at line 124 of file AliHLTOfflineInterface.cxx.
References fgCurrentLnk, fgList, fgpRawReader, fgpRunLoader, kHLTLogWarning, AliHLTLogging::LoggingVarargs(), and SetParams().
Referenced by AliHLTSystem::Reconstruct().
125 {
126   // see header file for class documentation
127   AliHLTLogging log;
128   int iResult=0;
129   int count=0;
130   fgpRunLoader=runLoader;
131   fgpRawReader=rawReader;
132   fgCurrentLnk=fgList.FirstLink();
133   while (fgCurrentLnk!=NULL) {
134     AliHLTOfflineInterface* pComponent=reinterpret_cast<AliHLTOfflineInterface*>(fgCurrentLnk->GetObject());
135     int iLocal=0;
136     if (pComponent) iLocal=pComponent->SetParams(runLoader, rawReader);
137     if (iLocal<0) {
138       log.LoggingVarargs(kHLTLogWarning, "AliHLTOfflineInterface","SetParamsToComponents", __FILE__, __LINE__,
139                         "parameter initialization failed for component %p with result %d", pComponent, iLocal);
140       if (iResult>=0) iResult=iLocal;
141     }
142     count++;
143     fgCurrentLnk=fgCurrentLnk->Next();
144   }
145   if (iResult>=0) {
146 //       log.LoggingVarargs(kHLTLogInfo, "AliHLTOfflineInterface","SetParamsToComponents", __FILE__, __LINE__,
147 //                      "parameters set to %d offline interface component(s)", count);
148   }
149   return iResult;
150 }
int AliHLTOfflineInterface::Unregister (AliHLTOfflineInterface * me) [static, protected]
Unregister an OfflineInterface.
Parameters:
me instance of AliHLTOfflineInterface
Returns: neg. error code if failed
Definition at line 203 of file AliHLTOfflineInterface.cxx.
References fgList.
Referenced by AliHLTOfflineDataSink::~AliHLTOfflineDataSink(), and AliHLTOfflineDataSource::~AliHLTOfflineDataSource().
204 {
205   // see header file for function documentation
206   int iResult=0;
207   if (fgList.FindObject(me)!=NULL) {
208     fgList.Remove(me);
209   } else {
210   }
211   return iResult;
212 }
Member Data Documentation
TObjLink * AliHLTOfflineInterface::fgCurrentLnk = NULL [static, private]
the current object link (list position)
Definition at line 44 of file AliHLTOfflineInterface.cxx.
Referenced by FillComponentESDs(), ResetComponents(), and SetParamsToComponents().
TList AliHLTOfflineInterface::fgList [static, private]
the list of active interfaces
Definition at line 43 of file AliHLTOfflineInterface.cxx.
Referenced by FillComponentESDs(), Register(), ResetComponents(), SetParamsToComponents(), and Unregister().
AliRawReader * AliHLTOfflineInterface::fgpRawReader = NULL [static, private]
transient
global AliRoot raw reader instance (for all components)
Definition at line 46 of file AliHLTOfflineInterface.cxx.
Referenced by SetParamsToComponents().
AliRunLoader * AliHLTOfflineInterface::fgpRunLoader = NULL [static, private]
global AliRoot run loader instance (for all components)
Definition at line 45 of file AliHLTOfflineInterface.cxx.
Referenced by SetParamsToComponents().
AliESD* AliHLTOfflineInterface::fpESD [private]
transient
AliRoot HLT ESD instance
Definition at line 162 of file AliHLTOfflineInterface.h.
Referenced by Reset(), and SetESD().
AliRawReader* AliHLTOfflineInterface::fpRawReader [private]
transient
private AliRoot raw reader instance
Definition at line 160 of file AliHLTOfflineInterface.h.
Referenced by GetRawReader(), Reset(), and SetParams().
AliRunLoader* AliHLTOfflineInterface::fpRunLoader [private]
transient
private AliRoot run loader instance
Definition at line 158 of file AliHLTOfflineInterface.h.
Referenced by GetRunLoader(), Reset(), and SetParams().
The documentation for this class was generated from the following files:
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTOfflineInterface.h
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTOfflineInterface.cxx