AliHLTPHOSHistogramProducerComponent Class Reference
#include <AliHLTPHOSHistogramProducerComponent.h>
Public Member Functions
AliHLTPHOSHistogramProducerComponent ()
virtual ~AliHLTPHOSHistogramProducerComponent ()
AliHLTPHOSHistogramProducerComponent (const AliHLTPHOSHistogramProducerComponent &)
AliHLTPHOSHistogramProducerComponent & operator= (const AliHLTPHOSHistogramProducerComponent &)
virtual int DoInit (int argc=0, const char **argv=0)
virtual int Deinit ()
virtual int DoDeinit ()
virtual int DoEvent (const AliHLTComponentEventData &evtData, const AliHLTComponentBlockData *blocks, AliHLTComponentTriggerData &trigData, AliHLTUInt8_t *outputPtr, AliHLTUInt32_t &size, vector< AliHLTComponentBlockData > &outputBlocks)
void DumpData (int gain=0)
const int GetEquippmentId () const
virtual const char * GetComponentID ()
virtual void GetInputDataTypes (std::vector< AliHLTComponentDataType > &)
virtual AliHLTComponentDataType GetOutputDataType ()
virtual void GetOutputDataSize (unsigned long &constBase, double &inputMultiplier)
void SetEquippmentId (int id=0)
virtual AliHLTComponent * Spawn ()
Protected Member Functions
void Reset ()
void ResetDataPtr ()
Private Attributes
Double_t fEnergyAverageValues [N_ZROWS_MOD][N_XCOLUMNS_MOD][N_GAINS]
Double_t fAccumulatedValues [N_ZROWS_MOD][N_XCOLUMNS_MOD][N_GAINS]
AliHLTUInt32_t fHits [N_ZROWS_MOD][N_XCOLUMNS_MOD][N_GAINS]
int fEventCount
AliHLTUInt32_t fEquippmentID
Double_t fTmpChannelData [ALTRO_MAX_SAMPLES]
AliHLTPHOSModuleCellAccumulatedEnergyDataStruct * fOutPtr
Static Private Attributes
const AliHLTComponentDataType fgkInputDataTypes [] = {kAliHLTVoidDataType,{0,``,``}}
const AliHLTComponentDataType fgkOutputDataType = kAliHLTVoidDataType
Constructor & Destructor Documentation
AliHLTPHOSHistogramProducerComponent::AliHLTPHOSHistogramProducerComponent ()
Default constructor
Definition at line 41 of file AliHLTPHOSHistogramProducerComponent.cxx.
References Reset().
41                                                                            :AliHLTProcessor(), fEventCount(0),  fEquippmentID(0)
42 {
46   Reset();
47 } 
AliHLTPHOSHistogramProducerComponent::~AliHLTPHOSHistogramProducerComponent () [virtual]
Default destructor
Definition at line 50 of file AliHLTPHOSHistogramProducerComponent.cxx.
51 {
55 }
AliHLTPHOSHistogramProducerComponent::AliHLTPHOSHistogramProducerComponent (const AliHLTPHOSHistogramProducerComponent &)
Copy constructor
Definition at line 58 of file AliHLTPHOSHistogramProducerComponent.cxx.
58                                                                                                                          : AliHLTProcessor(), fEventCount(0),  fEquippmentID(0)
59 {
63 }
Member Function Documentation
int AliHLTPHOSHistogramProducerComponent::Deinit () [virtual]
See base class for documenation
Reimplemented from AliHLTProcessor (p.).
Definition at line 67 of file AliHLTPHOSHistogramProducerComponent.cxx.
68 {
72   return 0;
73 }
int AliHLTPHOSHistogramProducerComponent::DoDeinit () [virtual]
Default method for the internal clean-up. The method is called by Deinit(p.)
Reimplemented from AliHLTComponent (p.).
Definition at line 77 of file AliHLTPHOSHistogramProducerComponent.cxx.
References kHLTLogInfo, and AliHLTLogging::Logging().
78 {
79   Logging(kHLTLogInfo, "HLT", "PHOS", ",AliHLTPHOSHistogramProducer DoDeinit");
80   return 0;
81 }
int AliHLTPHOSHistogramProducerComponent::DoEvent (const AliHLTComponentEventData & evtData, const AliHLTComponentBlockData * blocks, AliHLTComponentTriggerData & trigData, AliHLTUInt8_t * outputPtr, AliHLTUInt32_t & size, vector< AliHLTComponentBlockData > & outputBlocks) [virtual]
This fucntion takes as input cell energies as input and accumulates Energy and the number of hits on a per channel basis and fills a four dimensional array [N_MODULES][N_ROWS_MOD][N_COLUMNS_MOD][N_GAINS]. Energy distribution histograms (root) are updatet continioulsy and written to root files at the end of run command (actually the `stop` command)
Reimplemented from AliHLTProcessor (p.).
Definition at line 130 of file AliHLTPHOSHistogramProducerComponent.cxx.
References AliHLTUInt8_t, AliHLTPHOSModuleCellAccumulatedEnergyDataStruct::fAccumulatedEnergies, fAccumulatedValues, AliHLTComponentEventData::fBlockCnt, AliHLTPHOSRcuCellEnergyDataStruct::fCnt, AliHLTComponentBlockData::fDataType, AliHLTPHOSValidCellDataStruct::fEnergy, fEventCount, AliHLTPHOSValidCellDataStruct::fGain, AliHLTPHOSModuleCellAccumulatedEnergyDataStruct::fHits, fHits, AliHLTComponent::FillBlockData(), AliHLTPHOSModuleCellAccumulatedEnergyDataStruct::fModuleID, AliHLTPHOSRcuCellEnergyDataStruct::fModuleID, AliHLTComponentBlockData::fOffset, fOutPtr, AliHLTComponentBlockData::fPtr, AliHLTPHOSRcuCellEnergyDataStruct::fRcuX, AliHLTPHOSRcuCellEnergyDataStruct::fRcuZ, AliHLTComponentBlockData::fSize, AliHLTComponentBlockData::fSpecification, AliHLTPHOSRcuCellEnergyDataStruct::fValidData, AliHLTPHOSValidCellDataStruct::fX, AliHLTPHOSValidCellDataStruct::fZ, kHLTLogFatal, AliHLTLogging::Logging(), N_XCOLUMNS_RCU, and N_ZROWS_RCU.
133 {
142   unsigned long ndx;
143   UInt_t offset           = 0; 
144   UInt_t mysize           = 0;
145   UInt_t tSize            = 0;
146 
147   const AliHLTComponentBlockData* iter = NULL;   
148   AliHLTPHOSRcuCellEnergyDataStruct *cellDataPtr;
149   AliHLTUInt8_t* outBPtr;
150   outBPtr = outputPtr;
151   fOutPtr =  (AliHLTPHOSModuleCellAccumulatedEnergyDataStruct*)outBPtr;
152 
153   int tmpCnt;
154   AliHLTUInt8_t tmpModuleID;
155   AliHLTUInt8_t tmpRcuX;
156   AliHLTUInt8_t tmpRcuZ;
157 
158   for( ndx = 0; ndx < evtData.fBlockCnt; ndx++ )
159     {
160       iter = blocks+ndx;
161       cellDataPtr = (AliHLTPHOSRcuCellEnergyDataStruct*)( iter->fPtr);
162       tmpCnt =  cellDataPtr->fCnt;
163 
164       tmpModuleID = cellDataPtr->fModuleID;
165       tmpRcuX     = cellDataPtr->fRcuX ;
166       tmpRcuZ     = cellDataPtr->fRcuZ;
167       fOutPtr->fModuleID = tmpModuleID;
168       int tmpGain;
169       int tmpZ;
170       int tmpX;
171 
172       //      for(int i= 0; i< tmpCnt; i ++)
173       for(int i= 0; i <= tmpCnt; i ++)
174         {
175           tmpZ =  cellDataPtr->fValidData[i].fZ + N_ZROWS_RCU*tmpRcuZ;
176           tmpX =  cellDataPtr->fValidData[i].fX + N_XCOLUMNS_RCU*tmpRcuX;
177 
178           if(cellDataPtr->fValidData[i].fGain == HIGH_GAIN)
179             {
180               fAccumulatedValues[tmpZ][tmpX][HIGH_GAIN] +=  cellDataPtr->fValidData[i].fEnergy;
181               fHits[tmpZ][tmpX][HIGH_GAIN] ++;
182             }
183           else if(cellDataPtr->fValidData[i].fGain == LOW_GAIN)
184             {
185               fAccumulatedValues[tmpZ][tmpX][LOW_GAIN] +=  cellDataPtr->fValidData[i].fEnergy;
186               fHits[tmpZ][tmpX][LOW_GAIN] ++;
187             }
188         }
189     }
190 
191 
192   for(int z=0;  z < N_ZROWS_MOD; z ++ )
193     {
194       for(int x = 0; x < N_XCOLUMNS_MOD; x ++)
195         {
196           for(int gain =0; gain < N_GAINS; gain ++)
197             {
198               fOutPtr->fAccumulatedEnergies[z][x][gain] = fAccumulatedValues[z][x][gain];
199               fOutPtr->fHits[z][x][gain] = fHits[z][x][gain];
200             }
201         } 
202     }
203 
204 
205   //pushing data to shared output memory
206   mysize += sizeof(AliHLTPHOSModuleCellAccumulatedEnergyDataStruct);
207   AliHLTComponentBlockData bd;
208   FillBlockData( bd );
209   bd.fOffset = offset;
210   bd.fSize = mysize;
211   bd.fDataType = AliHLTPHOSDefinitions::gkCellAccumulatedEnergyDataType;
212   bd.fSpecification = 0xFFFFFFFF;
213   outputBlocks.push_back( bd );
214   tSize += mysize;
215   outBPtr += mysize;
216 
217   if( tSize > size )
218     {
219       Logging( kHLTLogFatal, "HLT::AliHLTHistogramProducerComponent::DoEvent", "Too much data",
220                "Data written over allowed buffer. Amount written: %lu, allowed amount: %lu."
221                , tSize, size );
222       return EMSGSIZE;
223     }
224 
225   fEventCount++; 
226   return 0;
227 }//end DoEvent
int AliHLTPHOSHistogramProducerComponent::DoInit (int argc = 0, const char ** argv = 0) [virtual]
Default method for the internal initialization. The method is called by Init(p.)
Reimplemented from AliHLTComponent (p.).
Definition at line 231 of file AliHLTPHOSHistogramProducerComponent.cxx.
References Reset().
232 {
233   Reset();
234   if (argc==0 && argv==NULL) {
235     // this is currently just to get rid of the warning "unused parameter"
236   }
237   return 0;
238 }
void AliHLTPHOSHistogramProducerComponent::DumpData (int gain = 0)
Definition at line 242 of file AliHLTPHOSHistogramProducerComponent.cxx.
References fAccumulatedValues, and N_GAINS.
243 {
244 
245   if(gain < 0 || gain >  N_GAINS)
246     {
247       cout <<"AliHLTPHOSHistogramProducerComponent::DumpDat: Error, gain must be between " << 0 << "and" << N_GAINS << endl;
248     }
249   
250   for(int mod = 0; mod < N_MODULES; mod ++)
251     {
252       if(gain == HIGH_GAIN)
253         {
254           cout << endl <<" ***********  MODULE" << mod << "****HIGH_GAIN" <<"************" << endl;
255         }
256       else if(gain == LOW_GAIN)
257         {
258           cout << endl <<" ***********  MODULE" << mod << "****LOW_GAIN" <<"************" << endl;
259         }
260       
261       for(int row = 0; row < N_ROWS_MOD; row ++)
262         {
263           for(int col = 0; col < N_COLUMNS_MOD; col ++)
264             {
265               if(fAccumulatedValues[row][col][0] != 0)
266                 { 
267                   cout << fAccumulatedValues[row][col][0] << "\t";
268                 }
269             }
270         } 
271     }
272 }
const char * AliHLTPHOSHistogramProducerComponent::GetComponentID () [virtual]
See base class for documenation
Implements AliHLTComponent (p.).
Definition at line 85 of file AliHLTPHOSHistogramProducerComponent.cxx.
86 {
90   return "HistogramProducer";
91 }
const int AliHLTPHOSHistogramProducerComponent::GetEquippmentId () const
Definition at line 317 of file AliHLTPHOSHistogramProducerComponent.cxx.
318 {
319   return  fEquippmentID;
320 }
void AliHLTPHOSHistogramProducerComponent::GetInputDataTypes (std::vector< AliHLTComponentDataType > & list) [virtual]
See base class for documenation
Definition at line 95 of file AliHLTPHOSHistogramProducerComponent.cxx.
References AliHLTComponentDataType::fID.
96 {
100   const AliHLTComponentDataType* pType=fgkInputDataTypes;
101   while (pType->fID!=0) 
102     {
103       list.push_back(*pType);
104       pType++;
105     }
106 }
void AliHLTPHOSHistogramProducerComponent::GetOutputDataSize (unsigned long & constBase, double & inputMultiplier) [virtual]
See base class for documenation
Implements AliHLTComponent (p.).
Definition at line 120 of file AliHLTPHOSHistogramProducerComponent.cxx.
121 {
125   constBase = 30;
126   inputMultiplier = 1;
127 }
AliHLTComponentDataType AliHLTPHOSHistogramProducerComponent::GetOutputDataType () [virtual]
See base class for documenation
Implements AliHLTComponent (p.).
Definition at line 110 of file AliHLTPHOSHistogramProducerComponent.cxx.
111 {
115   return AliHLTPHOSDefinitions::gkCellEnergyDataType;
116 }
AliHLTPHOSHistogramProducerComponent& AliHLTPHOSHistogramProducerComponent::operator= (const AliHLTPHOSHistogramProducerComponent &) [inline]
Definition at line 21 of file AliHLTPHOSHistogramProducerComponent.h.
22    {
23       return *this;
24    };
void AliHLTPHOSHistogramProducerComponent::Reset () [protected]
Definition at line 277 of file AliHLTPHOSHistogramProducerComponent.cxx.
References fAccumulatedValues, fHits, and fTmpChannelData.
Referenced by AliHLTPHOSHistogramProducerComponent(), and DoInit().
278 {
279   for(int mod = 0; mod < N_MODULES; mod ++)
280     {
281       for(int row = 0; row <  N_ROWS_MOD; row ++)
282         {
283           for(int col = 0; col < N_COLUMNS_MOD; col ++)
284             {
285               for(int gain = 0; gain < N_GAINS; gain ++ )
286                 { 
287                   fAccumulatedValues[row][col][gain] = 0;
288                   fHits[row][col][gain] = 0;      
289                 }
290             }
291         }
292     }
293 
294   for(int i = 0 ; i<  ALTRO_MAX_SAMPLES; i++)
295     {
296       fTmpChannelData[i] = 0;
297     }
298 } // end Reset
void AliHLTPHOSHistogramProducerComponent::ResetDataPtr () [protected]
Definition at line 301 of file AliHLTPHOSHistogramProducerComponent.cxx.
References fTmpChannelData.
302 {
303   for(int i = 0 ; i<  ALTRO_MAX_SAMPLES; i++)
304     {
305       fTmpChannelData[i] = 0;
306     }
307 }
void AliHLTPHOSHistogramProducerComponent::SetEquippmentId (int id = 0)
Definition at line 311 of file AliHLTPHOSHistogramProducerComponent.cxx.
References fEquippmentID.
312 {
313   fEquippmentID = id;
314 }
AliHLTComponent * AliHLTPHOSHistogramProducerComponent::Spawn () [virtual]
Spawn function. Each component must implement a spawn function to create a new instance of the class. Basically the function must return new my_class_name.
Returns: new class instance
Implements AliHLTComponent (p.).
Definition at line 324 of file AliHLTPHOSHistogramProducerComponent.cxx.
325 {
326   return new AliHLTPHOSHistogramProducerComponent;
327 }
Member Data Documentation
Double_t AliHLTPHOSHistogramProducerComponent::fAccumulatedValues[N_ZROWS_MOD][N_XCOLUMNS_MOD][N_GAINS] [private]
Accumulated energy for each readout channel of one RCU
Definition at line 50 of file AliHLTPHOSHistogramProducerComponent.h.
Referenced by DoEvent(), DumpData(), and Reset().
Double_t AliHLTPHOSHistogramProducerComponent::fEnergyAverageValues[N_ZROWS_MOD][N_XCOLUMNS_MOD][N_GAINS] [private]
Accumulated energy divided by the number of hits for each readout channel
Definition at line 49 of file AliHLTPHOSHistogramProducerComponent.h.
AliHLTUInt32_t AliHLTPHOSHistogramProducerComponent::fEquippmentID [private]
Eguippment ID as defined by ALICE
Definition at line 54 of file AliHLTPHOSHistogramProducerComponent.h.
Referenced by SetEquippmentId().
int AliHLTPHOSHistogramProducerComponent::fEventCount [private]
Event counter, (mainly used for debugging)
Reimplemented from AliHLTComponent (p.).
Definition at line 53 of file AliHLTPHOSHistogramProducerComponent.h.
Referenced by DoEvent().
const AliHLTComponentDataType AliHLTPHOSHistogramProducerComponent::fgkInputDataTypes = {kAliHLTVoidDataType,{0,``,``}} [static, private]
List of datatypes that can be given to this component
Definition at line 28 of file AliHLTPHOSHistogramProducerComponent.cxx.
const AliHLTComponentDataType AliHLTPHOSHistogramProducerComponent::fgkOutputDataType = kAliHLTVoidDataType [static, private]
Output datatype produced by this component
Definition at line 29 of file AliHLTPHOSHistogramProducerComponent.cxx.
AliHLTUInt32_t AliHLTPHOSHistogramProducerComponent::fHits[N_ZROWS_MOD][N_XCOLUMNS_MOD][N_GAINS] [private]
Total number of hits for each cell of one RCU
Definition at line 52 of file AliHLTPHOSHistogramProducerComponent.h.
Referenced by DoEvent(), and Reset().
AliHLTPHOSModuleCellAccumulatedEnergyDataStruct* AliHLTPHOSHistogramProducerComponent::fOutPtr [private]
Pointer to outputbuffer to write results from the component into shared memory
Definition at line 56 of file AliHLTPHOSHistogramProducerComponent.h.
Referenced by DoEvent().
Double_t AliHLTPHOSHistogramProducerComponent::fTmpChannelData[ALTRO_MAX_SAMPLES] [private]
Array to temporarily store dat fro a single altro channel
Definition at line 55 of file AliHLTPHOSHistogramProducerComponent.h.
Referenced by Reset(), and ResetDataPtr().
The documentation for this class was generated from the following files:
AliHLTPHOSHistogramProducerComponent.h
AliHLTPHOSHistogramProducerComponent.cxx