AliHLTDataBuffer Class Reference
#include <AliHLTDataBuffer.h>
Detailed Description
Handling of data buffers for the HLT.
The class provides handling of data buffers for HLT tasks. Each task gets its own Data Buffer instance. The buffer is grouped into different data segments according to the output of the component.
 The Data Buffer keeps control over the data requests of the 'child' components. Each component can subscribe to a certain segment of the data buffer. It's state is then changed from 'reserved' to 'active'. After the data processing, the component has to release the segment and it's state is set to 'processed'. If all components have requested and released their data, the Raw Buffer is released and pushed back in the list of available buffers.
Note: This class is only used for the HLT integration into AliRoot(p.).
Definition at line 41 of file AliHLTDataBuffer.h.
Public Member Functions
AliHLTDataBuffer ()
AliHLTDataBuffer (const AliHLTDataBuffer &)
AliHLTDataBuffer & operator= (const AliHLTDataBuffer &)
virtual ~AliHLTDataBuffer ()
int SetConsumer (AliHLTComponent *pConsumer)
int FindMatchingDataBlocks (const AliHLTComponent *pConsumer, vector< AliHLTComponentDataType > *tgtList=NULL)
int Subscribe (const AliHLTComponent *pConsumer, AliHLTComponentBlockData *arrayBlockDesc, int iArraySize)
int Release (AliHLTComponentBlockData *pBlockDesc, const AliHLTComponent *pConsumer)
AliHLTUInt8_t * GetTargetBuffer (int iMinSize)
int SetSegments (AliHLTUInt8_t *pTgt, AliHLTComponentBlockData *arraySegments, int iSize)
int IsEmpty ()
int GetNofSegments ()
int GetNofConsumers ()
int GetNofActiveConsumers ()
int FindConsumer (AliHLTComponent *pConsumer, int bAllLists=1)
int Reset ()
Private Member Functions
int FindMatchingDataSegments (const AliHLTComponent *pConsumer, vector< AliHLTDataBuffer::AliHLTDataSegment > &tgtList)
int ResetDataBuffer ()
AliHLTConsumerDescriptor * FindConsumer (const AliHLTComponent *pConsumer, vector< AliHLTConsumerDescriptor * > &list) const
transient///////////////////////////////////////////////////////////////////////////
int ChangeConsumerState (AliHLTConsumerDescriptor *pDesc, vector< AliHLTConsumerDescriptor * > &srcList, vector< AliHLTConsumerDescriptor * > &tgtList)
int CleanupConsumerList ()
Static Private Member Functions
AliHLTRawBuffer * CreateRawBuffer (AliHLTUInt32_t size)
int ReleaseRawBuffer (AliHLTRawBuffer *pBuffer)
int DeleteRawBuffers ()
Private Attributes
vector< AliHLTDataSegment > fSegments
vector< AliHLTConsumerDescriptor * > fConsumers
vector< AliHLTConsumerDescriptor * > fActiveConsumers
vector< AliHLTConsumerDescriptor * > fReleasedConsumers
AliHLTRawBuffer * fpBuffer
AliHLTUInt32_t fFlags
transient
Static Private Attributes
int fgNofInstances = 0
vector< AliHLTRawBuffer * > fgFreeBuffers
vector< AliHLTRawBuffer * > fgActiveBuffers
AliHLTUInt32_t fgMargin = 1024
AliHLTLogging fgLogging
const Int_t fgkSafetyPatternSize = 16
const char fgkSafetyPattern [] = {0x28, 0x63, 0x29, 0x4d, 0x52, 0x49, 0x43, 0x48, 0x54, 0x45, 0x52, 0x20, 0x32, 0x30, 0x30, 0x37}
Constructor & Destructor Documentation
AliHLTDataBuffer::AliHLTDataBuffer ()
AliHLTDataBuffer::AliHLTDataBuffer (const AliHLTDataBuffer &)
not a valid copy constructor, defined according to effective C++ style
Definition at line 59 of file AliHLTDataBuffer.cxx.
References HLTFatal.
60   :
61   TObject(),
62   AliHLTLogging(),
63   fSegments(),
64   fConsumers(),
65   fActiveConsumers(),
66   fReleasedConsumers(),
67   fpBuffer(NULL),
68   fFlags(0)
69 {
70   // see header file for function documentation
71   HLTFatal("copy constructor untested");
72 }
AliHLTDataBuffer::~AliHLTDataBuffer () [virtual]
destructor
Definition at line 89 of file AliHLTDataBuffer.cxx.
References CleanupConsumerList(), DeleteRawBuffers(), and fgNofInstances.
90 {
91   // see header file for function documentation
92   if (--fgNofInstances<=0) {
93     DeleteRawBuffers();
94   }
95   CleanupConsumerList();
96 }
Member Function Documentation
int AliHLTDataBuffer::ChangeConsumerState (AliHLTConsumerDescriptor * pDesc, vector< AliHLTConsumerDescriptor * > & srcList, vector< AliHLTConsumerDescriptor * > & tgtList) [private]
Change the state of a consumer. The state of a consumer is determined by the list it is strored in, the method moves a consumer from the source to the target list.
Parameters:
pDesc pointer to consumer descriptor
srcList list where the consumer is currently to be found
tgtList list where to move the consumer
Definition at line 526 of file AliHLTDataBuffer.cxx.
References HLTError.
Referenced by Release(), and Subscribe().
527 {
528   // see header file for function documentation
529   int iResult=-ENOENT;
530   if (pDesc) {
531     vector<AliHLTConsumerDescriptor*>::iterator desc=srcList.begin();
532     while (desc!=srcList.end()) {
533       if ((*desc)==pDesc) {
534         srcList.erase(desc);
535         tgtList.push_back(pDesc);
536         iResult=0;
537         break;
538       }
539       desc++;
540     }
541     if (iResult<0) {
542       HLTError("can not find consumer descriptor %p in list", pDesc);
543     }
544   } else {
545     HLTError("invalid parameter");
546     iResult=-EINVAL;
547   }
548   return iResult;
549 }
int AliHLTDataBuffer::CleanupConsumerList () [private]
Cleanup a consumer list. Release all allocated data structures. Note: Not the component itself!
Definition at line 551 of file AliHLTDataBuffer.cxx.
References fConsumers, and ResetDataBuffer().
Referenced by ~AliHLTDataBuffer().
552 {
553   // see header file for function documentation
554   int iResult=0;
555   ResetDataBuffer();
556   vector<AliHLTConsumerDescriptor*>::iterator desc=fConsumers.begin();
557   while (desc!=fConsumers.end()) {
558     delete *desc;
559     fConsumers.erase(desc);
560     desc=fConsumers.begin();
561   }
562   return iResult;
563 }
AliHLTDataBuffer::AliHLTRawBuffer * AliHLTDataBuffer::CreateRawBuffer (AliHLTUInt32_t size) [static, private]
Create a raw buffer of a certain size. The function tries to find a buffer of the given size (or a bit bigger by a certain margin fgMargin(p.)) from the list of free buffers. If no buffer is available, a new one is created and added to the buffer handling.
Parameters:
size min. size of the requested buffer
Returns: pointer to raw buffer
Definition at line 348 of file AliHLTDataBuffer.cxx.
References fgActiveBuffers, fgFreeBuffers, fgkSafetyPattern, fgLogging, AliHLTDataBuffer::AliHLTRawBuffer::fPtr, AliHLTDataBuffer::AliHLTRawBuffer::fSize, AliHLTDataBuffer::AliHLTRawBuffer::fTotalSize, kHLTLogDebug, kHLTLogError, and AliHLTLogging::Logging().
Referenced by GetTargetBuffer().
349 {
350   // see header file for function documentation
351   AliHLTRawBuffer* pRawBuffer=NULL;
352   unsigned int reqSize=size+fgkSafetyPatternSize;
353   vector<AliHLTRawBuffer*>::iterator buffer=fgFreeBuffers.begin();
354   while (buffer!=fgFreeBuffers.end() && pRawBuffer==NULL) {
355     if ((*buffer)->fTotalSize>=reqSize && ((*buffer)->fTotalSize-reqSize)<fgMargin) {
356       // assign this element
357       pRawBuffer=*buffer;
358       pRawBuffer->fSize=size;
359       fgFreeBuffers.erase(buffer);
360       fgLogging.Logging(kHLTLogDebug, "AliHLTDataBuffer::CreateRawBuffer", "data buffer handling", "raw buffer container %p provided for request of %d bytes (total %d available in buffer %p)", pRawBuffer, size, pRawBuffer->fTotalSize, pRawBuffer->fPtr);
361       fgActiveBuffers.push_back(pRawBuffer);
362       break;
363     }
364     buffer++;
365   }
366   if (pRawBuffer==NULL) {
367     // no buffer found, create a new one
368     pRawBuffer=new AliHLTRawBuffer;
369     if (pRawBuffer) {
370       pRawBuffer->fPtr=malloc(reqSize);
371       if (pRawBuffer->fPtr) {
372         pRawBuffer->fSize=size;
373         pRawBuffer->fTotalSize=reqSize;
374         fgActiveBuffers.push_back(pRawBuffer);
375         fgLogging.Logging(kHLTLogDebug, "AliHLTDataBuffer::CreateRawBuffer", "data buffer handling", "new raw buffer %p of size %d created (container %p)", pRawBuffer->fPtr, pRawBuffer->fTotalSize, pRawBuffer);
376         if (fgkSafetyPatternSize>0) {
377           memcpy(((char*)pRawBuffer->fPtr)+pRawBuffer->fSize, fgkSafetyPattern, fgkSafetyPatternSize);
378         }
379       } else {
380         delete pRawBuffer;
381         pRawBuffer=NULL;
382         fgLogging.Logging(kHLTLogError, "AliHLTDataBuffer::CreateRawBuffer", "data buffer handling", "memory allocation failed");
383       } 
384     } else {
385       fgLogging.Logging(kHLTLogError, "AliHLTDataBuffer::CreateRawBuffer", "data buffer handling", "memory allocation failed");
386     }
387   }
388   return pRawBuffer;
389 }
int AliHLTDataBuffer::DeleteRawBuffers () [static, private]
Deletes all the raw buffers. When the last Data Buffer object is destructed, all raw data buffers are relesed.
Definition at line 421 of file AliHLTDataBuffer.cxx.
References fgActiveBuffers, fgFreeBuffers, fgLogging, kHLTLogWarning, and AliHLTLogging::Logging().
Referenced by ~AliHLTDataBuffer().
422 {
423   // see header file for function documentation
424   int iResult=0;
425   vector<AliHLTRawBuffer*>::iterator buffer=fgFreeBuffers.begin();
426   while (buffer!=fgFreeBuffers.end()) {
427     free((*buffer)->fPtr);
428     delete *buffer;
429     fgFreeBuffers.erase(buffer);
430     buffer=fgFreeBuffers.begin();
431   }
432   buffer=fgActiveBuffers.begin();
433   while (buffer!=fgActiveBuffers.end()) {
434     fgLogging.Logging(kHLTLogWarning, "AliHLTDataBuffer::ReleaseRawBuffer", "data buffer handling", "request to delete active raw buffer container (raw buffer %p, size %d)", (*buffer)->fPtr, (*buffer)->fTotalSize);
435     free((*buffer)->fPtr);
436     delete *buffer;
437     fgActiveBuffers.erase(buffer);
438     buffer=fgActiveBuffers.begin();
439   }
440   return iResult;
441 }
AliHLTConsumerDescriptor * AliHLTDataBuffer::FindConsumer (const AliHLTComponent * pConsumer, vector< AliHLTConsumerDescriptor * > & list) const [private]
transient///////////////////////////////////////////////////////////////////////////
Find the consumer descriptor for a certain component and data type in a list of consumers.
 Note: There are three lists which contain the consumers in the different states.
Parameters:
pConsumer pointer to consumer component
list list where to search for the consumer
Definition at line 443 of file AliHLTDataBuffer.cxx.
444 {
445   // see header file for function documentation
446   AliHLTConsumerDescriptor* pDesc=NULL;
447   vector<AliHLTConsumerDescriptor*>::iterator desc=list.begin();
448   while (desc!=list.end() && pDesc==NULL) {
449     if ((pConsumer==NULL || (*desc)->GetComponent()==pConsumer)) {
450       pDesc=*desc;
451     }
452     desc++;
453   }
454   return pDesc;
455 }
int AliHLTDataBuffer::FindConsumer (AliHLTComponent * pConsumer, int bAllLists = 1)
Check if a consumer is already in the list
Parameters:
pConsumer pointer to consumer component
bAllLists search in all lists if 1 search only in fConsumer list if 0
Returns: 1 if found, 0 if not
Definition at line 565 of file AliHLTDataBuffer.cxx.
References fActiveConsumers, fConsumers, and fReleasedConsumers.
Referenced by Release(), SetConsumer(), and Subscribe().
566 {
567   // see header file for function documentation
568   vector<AliHLTConsumerDescriptor*>::iterator desc=fConsumers.begin();
569   while (desc!=fConsumers.end()) {
570     if ((*desc)->GetComponent()==pConsumer)
571       return 1;
572     desc++;
573   }
574   if (bAllLists==0) return 0;
575 
576   desc=fActiveConsumers.begin();
577   while (desc!=fActiveConsumers.end()) {
578     if ((*desc)->GetComponent()==pConsumer)
579       return 1;
580     desc++;
581   }
582   desc=fReleasedConsumers.begin();
583   while (desc!=fReleasedConsumers.end()) {
584     if ((*desc)->GetComponent()==pConsumer)
585       return 1;
586     desc++;
587   }
588   return 0;
589 }
int AliHLTDataBuffer::FindMatchingDataBlocks (const AliHLTComponent * pConsumer, vector< AliHLTComponentDataType > * tgtList = NULL)
Determine the number of matching data blocks for the component and a consumer component.
 The first approach will support only one output data type for processing components.
Parameters:
pConsumer the component which subscribes to the buffer
tgtList (optional) the list to receive the data types
Returns: : number of data blocks which match the input data types of the consumer, neg. error code if failed
 -EINVAL invalid parameter
Definition at line 121 of file AliHLTDataBuffer.cxx.
References FindMatchingDataSegments().
Referenced by AliHLTTask::GetNofMatchingDataBlocks().
122 {
123   // see header file for function documentation
124   int iResult=0;
125   if (pConsumer) {
126     vector<AliHLTDataBuffer::AliHLTDataSegment> segments;
127     if ((iResult=FindMatchingDataSegments(pConsumer, segments))>=0) {
128       if (tgtList) {
129         vector<AliHLTDataBuffer::AliHLTDataSegment>::iterator segment=segments.begin();
130         while (segment!=segments.end()) {
131           tgtList->push_back((*segment).fDataType);
132           segment++;
133         }
134       }
135       iResult=segments.size();
136     }
137   } else {
138     iResult=-EINVAL;
139   }
140   return iResult;
141 }
int AliHLTDataBuffer::FindMatchingDataSegments (const AliHLTComponent * pConsumer, vector< AliHLTDataBuffer::AliHLTDataSegment > & tgtList) [private]
Find those data segments which match the input types of a component.
Parameters:
pConsumer the component which subscribes to the buffer
tgtList the list to receive the data segment descriptors
Returns: : number of data blocks which match the input data types of the consumer, neg. error code if failed
 -EINVAL invalid parameter
Definition at line 143 of file AliHLTDataBuffer.cxx.
References fSegments.
Referenced by FindMatchingDataBlocks(), and Subscribe().
144 {
145   // see header file for function documentation
146   int iResult=0;
147   if (pConsumer) {
148     vector<AliHLTComponentDataType> dtlist;
149     ((AliHLTComponent*)pConsumer)->GetInputDataTypes(dtlist);
150     vector<AliHLTDataBuffer::AliHLTDataSegment>::iterator segment=fSegments.begin();
151     while (segment!=fSegments.end()) {
152       vector<AliHLTComponentDataType>::iterator type=dtlist.begin();
153       while (type!=dtlist.end()) {
154         if ((*segment).fDataType==(*type) ||
155             (*type)==kAliHLTAnyDataType) {
156           tgtList.push_back(*segment);
157           iResult++;
158           break;
159         }
160         type++;
161       }
162       segment++;
163     }
164   } else {
165     iResult=-EINVAL;
166   }
167   return iResult;
168 }
int AliHLTDataBuffer::GetNofActiveConsumers ()
Get the number of active consumers
Returns: number of active consumers
Definition at line 341 of file AliHLTDataBuffer.cxx.
References fActiveConsumers.
Referenced by GetNofConsumers(), and Release().
342 {
343   // see header file for function documentation
344   int iResult=fActiveConsumers.size();
345   return iResult;
346 }
int AliHLTDataBuffer::GetNofConsumers ()
Get the number of consumers
Returns: number of consumers
Definition at line 334 of file AliHLTDataBuffer.cxx.
References fConsumers, fReleasedConsumers, and GetNofActiveConsumers().
335 {
336   // see header file for function documentation
337   int iResult=fConsumers.size() + GetNofActiveConsumers() + fReleasedConsumers.size();
338   return iResult;
339 }
int AliHLTDataBuffer::GetNofSegments ()
Get the number of segments
Returns: number of segments
Definition at line 327 of file AliHLTDataBuffer.cxx.
References fSegments.
Referenced by IsEmpty().
328 {
329   // see header file for function documentation
330   int iResult=fSegments.size();
331   return iResult;
332 }
AliHLTUInt8_t * AliHLTDataBuffer::GetTargetBuffer (int iMinSize)
Get a target buffer of minimum size iMinSize. The method is used by the component which owns the Data Buffer to allocate a buffer for the data it is going to produce.
Parameters:
iMinSize minumum size of the requested buffer
Returns: : pointer to target buffer if
Definition at line 270 of file AliHLTDataBuffer.cxx.
References AliHLTUInt8_t, CreateRawBuffer(), fpBuffer, AliHLTDataBuffer::AliHLTRawBuffer::fPtr, and HLTError.
Referenced by AliHLTTask::ProcessTask().
271 {
272   // see header file for function documentation
273   AliHLTUInt8_t* pTargetBuffer=NULL;
274   fpBuffer=CreateRawBuffer(iMinSize);
275   if (fpBuffer) {
276     pTargetBuffer=(AliHLTUInt8_t*)fpBuffer->fPtr;
277   } else {
278     HLTError("can not create raw buffer");
279   }
280   return pTargetBuffer;
281 }
int AliHLTDataBuffer::IsEmpty ()
Check if the data buffer is empty.
Returns: 1 if empty, 0 if not
Definition at line 320 of file AliHLTDataBuffer.cxx.
References fpBuffer, and GetNofSegments().
321 {
322   // see header file for function documentation
323   int iResult=fpBuffer==NULL || GetNofSegments()==0;
324   return iResult;
325 }
AliHLTDataBuffer & AliHLTDataBuffer::operator= (const AliHLTDataBuffer &)
not a valid assignment op, but defined according to effective C++ style
Definition at line 74 of file AliHLTDataBuffer.cxx.
References HLTFatal.
75 { 
76   // see header file for function documentation
77   HLTFatal("assignment operator untested");
78   return *this;
79 }
int AliHLTDataBuffer::Release (AliHLTComponentBlockData * pBlockDesc, const AliHLTComponent * pConsumer)
Release an instance of the data buffer. Resets the variables of the block descriptor. If all buffer segments are released, the Data Buffer is reseted and the Raw Buffer released.
 The method is used by the consumer component.
Parameters:
pBlockDesc descriptor of the data segment
pConsumer the component which subscribes to the buffer
Returns: : >0 if success, negative error code if failed
 -EACCESS the consumer state can not be changed (de-activated) -ENOENT consumer has not subscribed to the buffer
 -EINVAL invalid parameter
Definition at line 231 of file AliHLTDataBuffer.cxx.
References ChangeConsumerState(), AliHLTConsumerDescriptor::CheckActiveDataSegment(), fActiveConsumers, FindConsumer(), AliHLTComponentBlockData::fOffset, AliHLTComponentBlockData::fPtr, fReleasedConsumers, AliHLTComponentBlockData::fSize, GetNofActiveConsumers(), AliHLTConsumerDescriptor::GetNofActiveSegments(), HLTError, HLTWarning, AliHLTConsumerDescriptor::ReleaseActiveDataSegment(), and ResetDataBuffer().
Referenced by AliHLTTask::Release().
232 {
233   // see header file for function documentation
234   int iResult=0;
235   if (pBlockDesc && pConsumer) {
236     AliHLTConsumerDescriptor* pDesc=FindConsumer(pConsumer, fActiveConsumers);
237     if (pDesc) {
238       if ((iResult=pDesc->CheckActiveDataSegment(pBlockDesc->fOffset, pBlockDesc->fSize))!=1) {
239         HLTWarning("data segment missmatch, component %p has not subscribed to a segment with offset %#x and size %d", pConsumer, pBlockDesc->fOffset, pBlockDesc->fSize);
240         // TODO: appropriate error handling, but so far optional
241         iResult=0;
242       } else {
243         pDesc->ReleaseActiveDataSegment(pBlockDesc->fOffset, pBlockDesc->fSize);
244         pBlockDesc->fOffset=0;
245         pBlockDesc->fPtr=NULL;
246         pBlockDesc->fSize=0;
247       }
248       if (pDesc->GetNofActiveSegments()==0) {
249         if ((iResult=ChangeConsumerState(pDesc, fActiveConsumers, fReleasedConsumers))>=0) {
250           if (GetNofActiveConsumers()==0) {
251             // this is the last consumer, reset the consumer list and release the raw buffer
252             ResetDataBuffer();
253           }
254         } else {
255           HLTError("can not deactivate consumer %p for data buffer %p", pConsumer, this);
256           iResult=-EACCES;
257         }
258       }
259     } else {
260       HLTWarning("component %p has currently not subscribed to the data buffer %p", pConsumer, this);
261       iResult=-ENOENT;
262     }
263   } else {
264     HLTError("inavalid parameter: pBlockDesc=%p pConsumer=%p", pBlockDesc, pConsumer);
265     iResult=-EINVAL;
266   }
267   return iResult;
268 }
int AliHLTDataBuffer::ReleaseRawBuffer (AliHLTRawBuffer * pBuffer) [static, private]
Mark a buffer as free. After the Data Buffer has finnished using the raw buffer, it is released and added to the list of available buffers.
Parameters:
pBuffer the raw buffer to release
Returns: >=0 if succeeded, neg. error code if failed
Definition at line 391 of file AliHLTDataBuffer.cxx.
References fgActiveBuffers, fgFreeBuffers, fgkSafetyPattern, fgkSafetyPatternSize, fgLogging, kHLTLogError, kHLTLogFatal, kHLTLogWarning, and AliHLTLogging::Logging().
Referenced by ResetDataBuffer().
392 {
393   // see header file for function documentation
394   int iResult=0;
395   if (pBuffer) {
396     vector<AliHLTRawBuffer*>::iterator buffer=fgActiveBuffers.begin();
397     while (buffer!=fgActiveBuffers.end() && (*buffer)!=pBuffer) {
398       buffer++;
399     }
400     if (buffer!=fgActiveBuffers.end()) {
401       if (fgkSafetyPatternSize>0) {
402         if (memcmp(((char*)(*buffer)->fPtr)+(*buffer)->fSize, fgkSafetyPattern, fgkSafetyPatternSize)!=0) {
403           fgLogging.Logging(kHLTLogFatal, "AliHLTDataBuffer::ReleaseRawBuffer", "data buffer handling", "component has written beyond end of data buffer %p size %d", (*buffer)->fPtr, (*buffer)->fSize);
404         }
405       }
406       (*buffer)->fSize=0;
407       fgFreeBuffers.push_back(*buffer);
408       fgActiveBuffers.erase(buffer);
409     } else {
410       fgLogging.Logging(kHLTLogWarning, "AliHLTDataBuffer::ReleaseRawBuffer", "data buffer handling", "can not find raw buffer container %p in the list of active containers", pBuffer);
411       iResult=-ENOENT;
412     }
413   } else {
414     fgLogging.Logging(kHLTLogError, "AliHLTDataBuffer::ReleaseRawBuffer", "data buffer handling", "invalid parameter");
415     iResult=-EINVAL;
416   }
417   return iResult;
418 }
int AliHLTDataBuffer::Reset ()
Public method to reset the buffer. Eventually with some additional checks. In normal operation, an external reset should not be necessary.
Definition at line 495 of file AliHLTDataBuffer.cxx.
References ResetDataBuffer().
Referenced by AliHLTTask::ProcessTask().
496 {
497   // see header file for function documentation
498   return ResetDataBuffer();
499 }
int AliHLTDataBuffer::ResetDataBuffer () [private]
Reset the data buffer. Removes all consumers back to the fConsumers(p.) list, deletes segments and releases the Raw Buffer.
Definition at line 457 of file AliHLTDataBuffer.cxx.
References fActiveConsumers, fConsumers, fpBuffer, fReleasedConsumers, fSegments, HLTWarning, and ReleaseRawBuffer().
Referenced by CleanupConsumerList(), Release(), and Reset().
458 {
459   // see header file for function documentation
460   int iResult=0;
461   AliHLTRawBuffer* pBuffer=fpBuffer;
462   fpBuffer=NULL;
463 
464   // cleanup consumer states
465   vector<AliHLTConsumerDescriptor*>::iterator desc=fReleasedConsumers.begin();
466   while (desc!=fReleasedConsumers.end()) {
467     AliHLTConsumerDescriptor* pDesc=*desc;
468     fReleasedConsumers.erase(desc);
469     desc=fReleasedConsumers.begin();
470     fConsumers.push_back(pDesc);
471   }
472   desc=fActiveConsumers.begin();
473   while (desc!=fActiveConsumers.end()) {
474     AliHLTConsumerDescriptor* pDesc=*desc;
475     HLTWarning("consumer %p was not released", pDesc);
476     fActiveConsumers.erase(desc);
477     desc=fActiveConsumers.begin();
478     fConsumers.push_back(pDesc);
479   }
480 
481   // cleanup segments
482   vector<AliHLTDataBuffer::AliHLTDataSegment>::iterator segment=fSegments.begin();
483   while (segment!=fSegments.end()) {
484     fSegments.erase(segment);
485     segment=fSegments.begin();
486   }
487 
488   // cleanup raw buffer
489   if (pBuffer) {
490     ReleaseRawBuffer(pBuffer);
491   }
492   return iResult;
493 }
int AliHLTDataBuffer::SetConsumer (AliHLTComponent * pConsumer)
Add component to the list of consumers
Parameters:
pConsumer - a consumer of type AliHLTComponent(p.)
Definition at line 98 of file AliHLTDataBuffer.cxx.
References fConsumers, FindConsumer(), AliHLTComponent::GetComponentID(), HLTDebug, HLTError, and HLTWarning.
Referenced by AliHLTTask::StartRun().
99 {
100   // see header file for function documentation
101   int iResult=0;
102   if (pConsumer) {
103     if (FindConsumer(pConsumer)) {
104       HLTWarning("consumer %s (%p) already set to data buffer %p", pConsumer->GetComponentID(), pConsumer, this);
105     }
106     AliHLTConsumerDescriptor* pDesc=new AliHLTConsumerDescriptor(pConsumer);
107     if (pDesc) {
108       fConsumers.push_back(pDesc);
109       HLTDebug("set consumer %s (%p) to data buffer %p", pConsumer->GetComponentID(), pConsumer, this);
110     } else {
111       HLTError("memory allocation failed");
112       iResult=-ENOMEM;
113     }
114   } else {
115     HLTError("invalid parameter: consumer component (nil)");
116     iResult=-EINVAL;
117   }
118   return iResult;
119 }
int AliHLTDataBuffer::SetSegments (AliHLTUInt8_t * pTgt, AliHLTComponentBlockData * arraySegments, int iSize)
Set the segments for the data buffer. This is usually done after the component has written the data to the buffer, which was requested by the GetTargetBuffer(p.) method. The component might produce different types of data, for each type a segment has to be defined which describes the data inside the buffer.
 The AliHLTComponentBlockData(p.) segment descriptor comes directly from the AliHLTComponent::ProcessEvent(p.) method.
Parameters:
pTgt the target buffer which the segments refer to
arraySegments the output block descriptors of the component
iSize size of the array
Definition at line 283 of file AliHLTDataBuffer.cxx.
References AliHLTComponentBlockData::fDataType, AliHLTDataBuffer::AliHLTDataSegment::fDataType, AliHLTComponentBlockData::fOffset, fpBuffer, AliHLTDataBuffer::AliHLTRawBuffer::fPtr, AliHLTDataBuffer::AliHLTDataSegment::fSegmentOffset, fSegments, AliHLTDataBuffer::AliHLTDataSegment::fSegmentSize, AliHLTDataBuffer::AliHLTRawBuffer::fSize, AliHLTComponentBlockData::fSize, AliHLTComponentBlockData::fSpecification, AliHLTDataBuffer::AliHLTDataSegment::fSpecification, HLTDebug, HLTError, and HLTFatal.
Referenced by AliHLTTask::ProcessTask().
284 {
285   // see header file for function documentation
286   int iResult=0;
287   if (pTgt && arrayBlockData && iSize>=0) {
288     if (fpBuffer) {
289       if (fpBuffer->fPtr==(void*)pTgt) {
290         AliHLTDataBuffer::AliHLTDataSegment segment;
291         for (int i=0; i<iSize; i++) {
292           if (arrayBlockData[i].fOffset+arrayBlockData[i].fSize<=fpBuffer->fSize) {
293             segment.fSegmentOffset=arrayBlockData[i].fOffset;
294             segment.fSegmentSize=arrayBlockData[i].fSize;
295             segment.fDataType=arrayBlockData[i].fDataType;
296             segment.fSpecification=arrayBlockData[i].fSpecification;
297             fSegments.push_back(segment);
298             HLTDebug("set segment %s with size %d at offset %d", AliHLTComponent::DataType2Text(segment.fDataType).data(), segment.fSegmentSize, segment.fSegmentOffset);
299           } else {
300             HLTError("block data specification %#d (%s) exceeds size of data buffer", i, AliHLTComponent::DataType2Text(arrayBlockData[i].fDataType).data());
301             HLTError("block offset=%d, block size=%d, buffer size=%d", arrayBlockData[i].fOffset, arrayBlockData[i].fSize, fpBuffer->fSize);
302             iResult=-E2BIG;
303           }
304         }
305       } else {
306         HLTError("this data buffer (%p) does not match the internal data buffer %p of raw buffer %p", pTgt, fpBuffer->fPtr, fpBuffer);
307         iResult=-EINVAL;
308       }
309     } else {
310       HLTFatal("internal data structur missmatch");
311       iResult=-EFAULT;
312     }
313   } else {
314     HLTError("invalid parameter: pTgtBuffer=%p arrayBlockData=%p", pTgt, arrayBlockData);
315     iResult=-EINVAL;
316   }
317   return iResult;
318 }
int AliHLTDataBuffer::Subscribe (const AliHLTComponent * pConsumer, AliHLTComponentBlockData * arrayBlockDesc, int iArraySize)
Subscribe to a segment of the data buffer. The function prepares the block descriptor for subsequent use with the AliHLTComponent::ProcessEvent(p.) method, the method can prepare several block descriptors up to the array size specified by iArraySize. The return value is independent from the array size the number of block descriptors which would have been prepared if there was enough space in the array
 The method is used by the consumer component.
Parameters:
pConsumer the component which subscribes to the buffer
arrayBlockDesc pointer to block descriptor to be filled
iArraySize size of the block descriptor array
Returns: : number of matching data blocks, neg. error code if failed
 -EACCESS the consumer state can't be changed (activated) -EBADF unresolved data segments
 -ENOENT consumer component not found
 -ENODATA data buffer does not have raw data
 -EINVAL invalid parameter
Definition at line 170 of file AliHLTDataBuffer.cxx.
References ChangeConsumerState(), fActiveConsumers, fConsumers, AliHLTComponentBlockData::fDataType, FindConsumer(), FindMatchingDataSegments(), AliHLTComponentBlockData::fOffset, fpBuffer, AliHLTDataBuffer::AliHLTRawBuffer::fPtr, AliHLTComponentBlockData::fPtr, AliHLTComponentShmData::fShmID, AliHLTComponentBlockData::fShmKey, AliHLTComponentShmData::fShmType, AliHLTComponentBlockData::fSize, AliHLTComponentBlockData::fSpecification, AliHLTComponentShmData::fStructSize, AliHLTComponentBlockData::fStructSize, HLTDebug, HLTError, and AliHLTConsumerDescriptor::SetActiveDataSegment().
Referenced by AliHLTTask::Subscribe().
171 {
172   // see header file for function documentation
173   int iResult=0;
174   if (pConsumer && arrayBlockDesc) {
175     if (fpBuffer) {
176       AliHLTConsumerDescriptor* pDesc=FindConsumer(pConsumer, fConsumers);
177       if (pDesc) {
178         vector<AliHLTDataBuffer::AliHLTDataSegment> tgtList;
179         /* TODO: think about a good policy for this check
180          * is it enough that at least one segment is available, or have all to be available?
181          * or is it possible to have optional segments?
182          */
183         if ((iResult=FindMatchingDataSegments(pConsumer, tgtList))>0) {
184           int i =0;
185           vector<AliHLTDataBuffer::AliHLTDataSegment>::iterator segment=tgtList.begin();
186           while (segment!=tgtList.end() && i<iArraySize) {
187             // fill the block data descriptor
188             arrayBlockDesc[i].fStructSize=sizeof(AliHLTComponentBlockData);
189             // the shared memory key is not used in AliRoot
190             arrayBlockDesc[i].fShmKey.fStructSize=sizeof(AliHLTComponentShmData);
191             arrayBlockDesc[i].fShmKey.fShmType=gkAliHLTComponentInvalidShmType;
192             arrayBlockDesc[i].fShmKey.fShmID=gkAliHLTComponentInvalidShmID;
193             arrayBlockDesc[i].fOffset=(*segment).fSegmentOffset;
194             arrayBlockDesc[i].fPtr=fpBuffer->fPtr;
195             arrayBlockDesc[i].fSize=(*segment).fSegmentSize;
196             arrayBlockDesc[i].fDataType=(*segment).fDataType;
197             arrayBlockDesc[i].fSpecification=(*segment).fSpecification;
198             pDesc->SetActiveDataSegment(arrayBlockDesc[i].fOffset, arrayBlockDesc[i].fSize);
199             HLTDebug("component %p (%s) subscribed to segment #%d offset %d", pConsumer, ((AliHLTComponent*)pConsumer)->GetComponentID(), i, arrayBlockDesc[i].fOffset);
200             i++;
201             segment++;
202           }
203           // move this consumer to the active list
204           if (ChangeConsumerState(pDesc, fConsumers, fActiveConsumers)>=0) {
205             HLTDebug("component %p (%s) subscribed to data buffer %p", pConsumer, ((AliHLTComponent*)pConsumer)->GetComponentID(), this);
206           } else {
207             // TODO: cleanup the consumer descriptor correctly
208             memset(arrayBlockDesc, 0, iArraySize*sizeof(AliHLTComponentBlockData));
209             HLTError("can not activate consumer %p for data buffer %p", pConsumer, this);
210             iResult=-EACCES;
211           }
212         } else {
213           HLTError("unresolved data segment(s) for component %p (%s)", pConsumer, ((AliHLTComponent*)pConsumer)->GetComponentID());
214           iResult=-EBADF;
215         }
216       } else {
217         HLTError("component %p is not a data consumer of data buffer %s", pConsumer, this);
218         iResult=-ENOENT;
219       }
220     } else {
221       HLTError("data buffer %p is empty", this);
222       iResult=-ENODATA;
223     }
224   } else {
225     HLTError("invalid parameter");
226     iResult=-EINVAL;
227   }
228   return iResult;
229 }
Member Data Documentation
vector<AliHLTConsumerDescriptor*> AliHLTDataBuffer::fActiveConsumers [private]
Definition at line 283 of file AliHLTDataBuffer.h.
Referenced by FindConsumer(), GetNofActiveConsumers(), Release(), ResetDataBuffer(), and Subscribe().
vector<AliHLTConsumerDescriptor*> AliHLTDataBuffer::fConsumers [private]
Definition at line 281 of file AliHLTDataBuffer.h.
Referenced by CleanupConsumerList(), FindConsumer(), GetNofConsumers(), ResetDataBuffer(), SetConsumer(), and Subscribe().
AliHLTUInt32_t AliHLTDataBuffer::fFlags [private]
transient
Definition at line 291 of file AliHLTDataBuffer.h.
vector< AliHLTDataBuffer::AliHLTRawBuffer * > AliHLTDataBuffer::fgActiveBuffers [static, private]
global list of currently active raw buffers
Definition at line 83 of file AliHLTDataBuffer.cxx.
Referenced by CreateRawBuffer(), DeleteRawBuffers(), and ReleaseRawBuffer().
vector< AliHLTDataBuffer::AliHLTRawBuffer * > AliHLTDataBuffer::fgFreeBuffers [static, private]
global list of free raw buffers
Definition at line 82 of file AliHLTDataBuffer.cxx.
Referenced by CreateRawBuffer(), DeleteRawBuffers(), and ReleaseRawBuffer().
const char AliHLTDataBuffer::fgkSafetyPattern = {0x28, 0x63, 0x29, 0x4d, 0x52, 0x49, 0x43, 0x48, 0x54, 0x45, 0x52, 0x20, 0x32, 0x30, 0x30, 0x37} [static, private]
the safety pattern
Definition at line 87 of file AliHLTDataBuffer.cxx.
Referenced by CreateRawBuffer(), and ReleaseRawBuffer().
const Int_t AliHLTDataBuffer::fgkSafetyPatternSize = 16 [static, private]
size of the safety pattern
Definition at line 86 of file AliHLTDataBuffer.cxx.
Referenced by ReleaseRawBuffer().
AliHLTLogging AliHLTDataBuffer::fgLogging [static, private]
global instance to HLT logging class for static methods
Definition at line 85 of file AliHLTDataBuffer.cxx.
Referenced by CreateRawBuffer(), DeleteRawBuffers(), and ReleaseRawBuffer().
AliHLTUInt32_t AliHLTDataBuffer::fgMargin = 1024 [static, private]
determines the raw buffer size margin at buffer requests
Definition at line 84 of file AliHLTDataBuffer.cxx.
int AliHLTDataBuffer::fgNofInstances = 0 [static, private]
Number of instances of AliHLTDataBuffer. The statice variable is incremented and decremented in the constructor/ destructor. All internal data structures are cleaned up when the last instance is exiting.
Definition at line 81 of file AliHLTDataBuffer.cxx.
Referenced by ~AliHLTDataBuffer().
AliHLTRawBuffer* AliHLTDataBuffer::fpBuffer [private]
Definition at line 288 of file AliHLTDataBuffer.h.
Referenced by GetTargetBuffer(), IsEmpty(), ResetDataBuffer(), SetSegments(), and Subscribe().
vector<AliHLTConsumerDescriptor*> AliHLTDataBuffer::fReleasedConsumers [private]
Definition at line 285 of file AliHLTDataBuffer.h.
Referenced by FindConsumer(), GetNofConsumers(), Release(), and ResetDataBuffer().
vector<AliHLTDataSegment> AliHLTDataBuffer::fSegments [private]
Definition at line 278 of file AliHLTDataBuffer.h.
Referenced by FindMatchingDataSegments(), GetNofSegments(), ResetDataBuffer(), and SetSegments().
The documentation for this class was generated from the following files:
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTDataBuffer.h
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTDataBuffer.cxx