AliHLTConfiguration Class Reference
#include <AliHLTConfiguration.h>
Detailed Description
Description of HLT processing chains.
This class describes a certain configuration af an HLT processing step by the following parameters:
a unique id string/name
the id of the component
the ids of the configurations it requires input from
the arguments, which are passed to the component when it is initialized
The setup of a configuration requires simply the creation of a global object of AliHLTConfiguration(p.). The Configuration is automatically registered in the list of available configurations maintained by the AliHLTConfigurationHandler(p.). The list is used by to resolve the dependencies on other configurations. Hierarchies can be built up in an easy way.
A configuration is interpreted by the AliHLTConfigurationHandler(p.) and transformed into a Task List.
Note: This class is only used for the HLT integration into AliRoot(p.).
Definition at line 49 of file AliHLTConfiguration.h.
Public Member Functions
AliHLTConfiguration ()
AliHLTConfiguration (const char *id, const char *component, const char *sources, const char *arguments)
AliHLTConfiguration (const AliHLTConfiguration &src)
AliHLTConfiguration & operator= (const AliHLTConfiguration &src)
virtual ~AliHLTConfiguration ()
const char * GetName () const
const char * GetComponentID () const
void PrintStatus ()
AliHLTConfiguration * GetSource (const char *id)
int FollowDependency (const char *id, TList *pTgtList=NULL)
int GetNofSources ()
int SourcesResolved (int bAuto=0)
AliHLTConfiguration * GetFirstSource ()
AliHLTConfiguration * GetNextSource ()
int InvalidateSource (AliHLTConfiguration *pConf)
int InvalidateSources ()
int GetArguments (const char ***pArgv)
Static Public Member Functions
int GlobalInit (AliHLTConfigurationHandler *pHandler)
int GlobalDeinit (AliHLTConfigurationHandler *pHandler)
Private Member Functions
int ExtractSources ()
int ExtractArguments ()
int InterpreteString (const char *arg, vector< char * > &argList)
ClassDef (AliHLTConfiguration, 0)
transient
Private Attributes
TString fID
TString fComponent
TString fStringSources
int fNofSources
vector< AliHLTConfiguration * > fListSources
vector< AliHLTConfiguration * >::iterator fListSrcElement
TString fArguments
int fArgc
char ** fArgv
Static Private Attributes
AliHLTConfigurationHandler * fgConfigurationHandler = NULL
Constructor & Destructor Documentation
AliHLTConfiguration::AliHLTConfiguration ()
standard constructor. The configuration is automatically registered in the global configuration manager
AliHLTConfiguration::AliHLTConfiguration (const char * id, const char * component, const char * sources, const char * arguments)
constructor. The configuration is automatically registered in the global configuration manager
Parameters:
id unique id of the configuration
component component id
sources blank separated list of source configuration ids
arguments argument string passed to the component at initialization
Definition at line 57 of file AliHLTConfiguration.cxx.
References fgConfigurationHandler, fListSources, fListSrcElement, HLTError, and AliHLTConfigurationHandler::RegisterConfiguration().
58   :
59   fID(id),
60   fComponent(component),
61   fStringSources(sources),
62   fNofSources(-1),
63   fListSources(),
64   fListSrcElement(),
65   fArguments(arguments),
66   fArgc(-1),
67   fArgv(NULL)
68 {
69   // see header file for function documentation
70   fListSrcElement=fListSources.begin();
71   if (id && component) {
72     if (fgConfigurationHandler) {
73       fgConfigurationHandler->RegisterConfiguration(this);
74     } else {
75       HLTError("no configuration handler set, abort registration");
76     }
77   }
78 }
AliHLTConfiguration::AliHLTConfiguration (const AliHLTConfiguration & src)
copy constructor
Definition at line 80 of file AliHLTConfiguration.cxx.
References fListSources, and fListSrcElement.
81   :
82   TObject(),
83   AliHLTLogging(),
84   fID(src.fID),
85   fComponent(src.fComponent),
86   fStringSources(src.fStringSources),
87   fNofSources(-1),
88   fListSources(),
89   fListSrcElement(),
90   fArguments(src.fArguments),
91   fArgc(-1),
92   fArgv(NULL)
93 { 
94   // see header file for function documentation
95   fListSrcElement=fListSources.begin();
96 }
AliHLTConfiguration::~AliHLTConfiguration () [virtual]
destructor
Definition at line 111 of file AliHLTConfiguration.cxx.
References fArgc, fArgv, fgConfigurationHandler, fID, AliHLTConfigurationHandler::FindConfiguration(), fListSources, and AliHLTConfigurationHandler::RemoveConfiguration().
112 {
113   // see header file for function documentation
114   if (fgConfigurationHandler) {
115     if (fgConfigurationHandler->FindConfiguration(fID.Data())!=NULL) {
116       fgConfigurationHandler->RemoveConfiguration(this);
117     }
118   }
119   if (fArgv != NULL) {
120     if (fArgc>0) {
121       for (int i=0; i<fArgc; i++) {
122         delete[] fArgv[i];
123       }
124     }
125     delete[] fArgv;
126     fArgv=NULL;
127   }
128 
129   vector<AliHLTConfiguration*>::iterator element=fListSources.begin();
130   while (element!=fListSources.end()) {
131     fListSources.erase(element);
132     element=fListSources.begin();
133   }
134 }
Member Function Documentation
AliHLTConfiguration::ClassDef (AliHLTConfiguration, 0) [private]
transient
int AliHLTConfiguration::ExtractArguments () [private]
Definition at line 326 of file AliHLTConfiguration.cxx.
References fArgc, fArguments, fArgv, and InterpreteString().
Referenced by GetArguments().
327 {
328   // see header file for function documentation
329   int iResult=0;
330   if (!fArguments.IsNull()) {
331     vector<char*> tgtList;
332     if ((iResult=InterpreteString(fArguments, tgtList))>=0) {
333       fArgc=tgtList.size();
334       //HLTDebug("configuration %s: extracted %d arguments from \"%s\"", GetName(), fArgc, fArguments);
335       if (fArgc>0) {
336         fArgv = new char*[fArgc];
337         if (fArgv) {
338           vector<char*>::iterator element=tgtList.begin();
339           int i=0;
340           while (element!=tgtList.end()) {
341             //HLTDebug("assign arguments %d (%s)", i, *element);
342             fArgv[i++]=(*element);
343             element++;
344           }
345         } else {
346           iResult=-ENOMEM;
347         }
348       }
349     }
350   } else {
351     // there are zero arguments
352     fArgc=0;
353   }
354   return iResult;
355 }
int AliHLTConfiguration::ExtractSources () [private]
Definition at line 292 of file AliHLTConfiguration.cxx.
References fgConfigurationHandler, AliHLTConfigurationHandler::FindConfiguration(), fListSources, fListSrcElement, fNofSources, fStringSources, HLTError, HLTFatal, and InterpreteString().
Referenced by GetFirstSource(), and SourcesResolved().
293 {
294   // see header file for function documentation
295   int iResult=0;
296   fNofSources=0;
297   if (!fStringSources.IsNull()) {
298     vector<char*> tgtList;
299     fListSources.clear();
300     if ((iResult=InterpreteString(fStringSources.Data(), tgtList))>=0) {
301       fNofSources=tgtList.size();
302       vector<char*>::iterator element=tgtList.begin();
303       while ((element=tgtList.begin())!=tgtList.end()) {
304         if (fgConfigurationHandler) {
305           AliHLTConfiguration* pConf=fgConfigurationHandler->FindConfiguration(*element);
306           if (pConf) {
307             //HLTDebug("configuration %s (%p): source \"%s\" (%p) inserted", GetName(), this, pConf->GetName(), pConf);
308             fListSources.push_back(pConf);
309           } else {
310             HLTError("can not find source \"%s\"", (*element));
311             iResult=-ENOENT;
312           }
313         } else if (iResult>=0) {
314           iResult=-EFAULT;
315           HLTFatal("global configuration handler not initialized, can not resolve sources");
316         }
317         delete[] (*element);
318         tgtList.erase(element);
319       }
320       fListSrcElement=fListSources.begin();
321     }
322   }
323   return iResult;
324 }
int AliHLTConfiguration::FollowDependency (const char * id, TList * pTgtList = NULL)
Try to find a dependency recursively in the list of sources.
Parameters:
id the source to search for
pTgtList (optional) target list to receive the dependency tree
Returns: 0 if not found n found in the n-th level dependency list in the target list
Definition at line 393 of file AliHLTConfiguration.cxx.
References GetFirstSource(), GetNextSource(), and GetSource().
Referenced by AliHLTSystem::BuildTaskList(), and AliHLTTask::PrintDependencyTree().
394 {
395   // see header file for function documentation
396   int iResult=0;
397   if (id) {
398     AliHLTConfiguration* pDep=NULL;
399     if ((pDep=GetSource(id))!=NULL) {
400       if (pTgtList) pTgtList->Add(pDep);
401       iResult++;
402     } else {
403       pDep=GetFirstSource();
404       while (pDep && iResult==0) {
405         if ((iResult=pDep->FollowDependency(id, pTgtList))>0) {
406           if (pTgtList) pTgtList->AddFirst(pDep);
407           iResult++;
408         }
409         pDep=GetNextSource();
410       }
411     }
412   } else {
413     iResult=-EINVAL;
414   }
415   return iResult;
416 }
int AliHLTConfiguration::GetArguments (const char *** pArgv)
Get the arguments array.
Parameters:
pArgv pointer to receive argument array pointer
Returns: argc if succeeded, neg. error code if failed
Definition at line 268 of file AliHLTConfiguration.cxx.
References ExtractArguments(), fArgc, GetName(), and HLTError.
Referenced by AliHLTTask::Init().
269 {
270   // see header file for function documentation
271   int iResult=0;
272   if (pArgv) {
273     if (fArgc==-1) {
274       if ((iResult=ExtractArguments())<0) {
275         HLTError("error extracting arguments for configuration %s", GetName());
276         fArgc=-EINVAL;
277       }
278     } else if (fArgc<0) {
279       HLTError("previous argument extraction failed");
280     }
281     //HLTDebug("%s fArgc %d", GetName(), fArgc);
282     iResult=fArgc;
283     *pArgv=(const char**)fArgv;
284   } else {
285     HLTError("invalid parameter");
286     iResult=-EINVAL;
287   }
288   return iResult;
289 }
const char* AliHLTConfiguration::GetComponentID () const [inline]
Get id of the component. The id is a unique string.
Returns: id of the component
Definition at line 104 of file AliHLTConfiguration.h.
Referenced by AliHLTTask::Init().
104 {return fComponent;}
AliHLTConfiguration * AliHLTConfiguration::GetFirstSource ()
Start iteration and get the first source.
Returns: pointer to the first configuration descriptor
Definition at line 193 of file AliHLTConfiguration.cxx.
References ExtractSources(), fListSources, fListSrcElement, and fNofSources.
Referenced by AliHLTSystem::BuildTaskList(), AliHLTTask::CheckDependencies(), FollowDependency(), GetSource(), AliHLTTask::PrintStatus(), and PrintStatus().
194 {
195   // see header file for function documentation
196   AliHLTConfiguration* pSrc=NULL;
197   if (fNofSources>=0 || ExtractSources()) {
198     fListSrcElement=fListSources.begin();
199     if (fListSrcElement!=fListSources.end()) pSrc=*fListSrcElement;
200   } 
201   return pSrc;
202 }
const char * AliHLTConfiguration::GetName () const
Get configuration id, a unique name This is an overridden TObject function in order to return the configuration name instead of the class name. Enables use of TList standard functions.
Returns: configuration id
Definition at line 163 of file AliHLTConfiguration.cxx.
References fID.
Referenced by AliHLTSystem::BuildTaskList(), AliHLTTask::CheckDependencies(), GetArguments(), AliHLTTask::GetName(), GetSource(), AliHLTTask::Init(), AliHLTTask::PrintStatus(), PrintStatus(), AliHLTConfigurationHandler::RegisterConfiguration(), AliHLTConfigurationHandler::RemoveConfiguration(), and AliHLTConfigurationHandler::~AliHLTConfigurationHandler().
164 {
165   // see header file for function documentation
166   if (!fID.IsNull())
167     return fID.Data();
168   return TObject::GetName();
169 }
AliHLTConfiguration * AliHLTConfiguration::GetNextSource ()
Continue iteration and get the next source.
Returns: pointer to the next configuration descriptor in the list
Definition at line 204 of file AliHLTConfiguration.cxx.
References fListSources, fListSrcElement, and fNofSources.
Referenced by AliHLTSystem::BuildTaskList(), AliHLTTask::CheckDependencies(), FollowDependency(), GetSource(), AliHLTTask::PrintStatus(), and PrintStatus().
205 {
206   // see header file for function documentation
207   AliHLTConfiguration* pSrc=NULL;
208   if (fNofSources>0) {
209     if (fListSrcElement!=fListSources.end() && (++fListSrcElement)!=fListSources.end()) 
210       pSrc=*fListSrcElement;
211   } 
212   return pSrc;
213 }
int AliHLTConfiguration::GetNofSources () [inline]
Get the number of resolved sources.
Returns: number of resolved sources
Definition at line 134 of file AliHLTConfiguration.h.
References fListSources.
134 {return fListSources.size();}
AliHLTConfiguration * AliHLTConfiguration::GetSource (const char * id)
Get a certain source.
Parameters:
id of the source configuration
Returns: pointer to the corresponding configuration descriptor
Definition at line 171 of file AliHLTConfiguration.cxx.
References fListSources, fListSrcElement, GetFirstSource(), GetName(), and GetNextSource().
Referenced by AliHLTTask::Depends(), and FollowDependency().
172 {
173   // see header file for function documentation
174   AliHLTConfiguration* pSrc=NULL;
175   if (id) {
176     // first check the current element
177     if (fListSrcElement!=fListSources.end() && strcmp(id, (*fListSrcElement)->GetName())==0) {
178       pSrc=*fListSrcElement;
179       } else {
180       // check the list
181 
182       pSrc=GetFirstSource();
183       while (pSrc) {
184         if (strcmp(id, pSrc->GetName())==0)
185           break;
186         pSrc=GetNextSource();
187       }
188     }
189   }
190   return pSrc;
191 }
int AliHLTConfiguration::GlobalDeinit (AliHLTConfigurationHandler * pHandler) [static]
Global de-init and cleanup of the global configuration handler
Definition at line 151 of file AliHLTConfiguration.cxx.
References fgConfigurationHandler, HLT_DEFAULT_LOG_KEYWORD, kHLTLogWarning, and AliHLTLogging::Logging().
Referenced by AliHLTSystem::~AliHLTSystem().
152 {
153   // see header file for function documentation
154   int iResult=0;
155   if (pHandler!=NULL && fgConfigurationHandler!=pHandler) {
156     fgConfigurationHandler->Logging(kHLTLogWarning, "AliHLTConfiguration::GlobalDeinit", HLT_DEFAULT_LOG_KEYWORD, "handler %p is not set, skip ...", pHandler);
157     return -EBADF;
158   }
159   fgConfigurationHandler=NULL;
160   return iResult;
161 }
int AliHLTConfiguration::GlobalInit (AliHLTConfigurationHandler * pHandler) [static]
Global initialization of the configuration handler.
Definition at line 140 of file AliHLTConfiguration.cxx.
References fgConfigurationHandler, HLT_DEFAULT_LOG_KEYWORD, kHLTLogWarning, and AliHLTLogging::Logging().
Referenced by ClassImp().
141 {
142   // see header file for function documentation
143   int iResult=0;
144   if (fgConfigurationHandler!=NULL) {
145     fgConfigurationHandler->Logging(kHLTLogWarning, "AliHLTConfiguration::GlobalInit", HLT_DEFAULT_LOG_KEYWORD, "configuration handler already initialized, overriding object %p with %p", fgConfigurationHandler, pHandler);
146   }
147   fgConfigurationHandler=pHandler;
148   return iResult;
149 }
int AliHLTConfiguration::InterpreteString (const char * arg, vector< char * > & argList) [private]
Helper function to build a vector from an argument string
Parameters:
arg pointer to argument string
argList target to receive the argument list
Definition at line 357 of file AliHLTConfiguration.cxx.
Referenced by ExtractArguments(), and ExtractSources().
358 {
359   // see header file for function documentation
360   int iResult=0;
361   if (arg) {
362     //HLTDebug("interprete \"%s\"", arg);
363     int i=0;
364     int prec=-1;
365     int bQuote=0;
366     do {
367       //HLTDebug("%d %x", i, arg[i]);
368       if (arg[i]=='\'' && bQuote==0) {
369         bQuote=1;
370       } else if (arg[i]==0 || 
371                  (arg[i]==' ' && bQuote==0) ||
372                  (arg[i]=='\'' && bQuote==1)) {
373         bQuote=0;
374         if (prec>=0) {
375           char* pEntry= new char[i-prec+1];
376           if (pEntry) {
377             strncpy(pEntry, &arg[prec], i-prec);
378             pEntry[i-prec]=0; // terminate string
379             //HLTDebug("create string \"%s\", insert at %d", pEntry, argList.size());
380             argList.push_back(pEntry);
381           } else 
382             iResult=-ENOMEM;
383           prec=-1;
384         }
385       } else if (prec==-1) prec=i;
386     } while (arg[i++]!=0 && iResult>=0); 
387   } else {
388     iResult=-EINVAL;
389   }
390   return iResult;
391 }
int AliHLTConfiguration::InvalidateSource (AliHLTConfiguration * pConf)
Invalidate a dependency and mark the configuration to be re-evaluted.
Parameters:
pConf pointer to configuration descriptor
Definition at line 227 of file AliHLTConfiguration.cxx.
References fListSources, and fListSrcElement.
Referenced by AliHLTConfigurationHandler::RemoveConfiguration().
228 {
229   // see header file for function documentation
230   int iResult=0;
231   if (pConf) {
232     vector<AliHLTConfiguration*>::iterator element=fListSources.begin();
233     while (element!=fListSources.end()) {
234       if (*element==pConf) {
235         fListSources.erase(element);
236         fListSrcElement=fListSources.end();
237         // there is no need to re-evaluate until there was a new configuration registered
238         // -> postpone the invalidation, its done in AliHLTConfigurationHandler::RegisterConfiguration
239         //InvalidateSources();
240         break;
241       }
242       element++;
243     }
244   } else {
245     iResult=-EINVAL;
246   }
247   return iResult;
248 }
int AliHLTConfiguration::InvalidateSources () [inline]
Mark the configuration to be re-evaluted.
Definition at line 164 of file AliHLTConfiguration.h.
References fNofSources.
Referenced by AliHLTConfigurationHandler::RegisterConfiguration(), and AliHLTTask::UnsetDependency().
164 {fNofSources=-1; return 0;}
AliHLTConfiguration & AliHLTConfiguration::operator= (const AliHLTConfiguration & src)
assignment op
Definition at line 98 of file AliHLTConfiguration.cxx.
References fArgc, fArguments, fArgv, fComponent, fID, fNofSources, and fStringSources.
99 { 
100   // see header file for function documentation
101   fID=src.fID;
102   fComponent=src.fComponent;
103   fStringSources=src.fStringSources;
104   fNofSources=-1;
105   fArguments=src.fArguments;
106   fArgc=-1;
107   fArgv=NULL;
108   return *this;
109 }
void AliHLTConfiguration::PrintStatus ()
Print status info. Short summary on id, component, sources and unresolved sources.
Definition at line 250 of file AliHLTConfiguration.cxx.
References fComponent, fStringSources, GetFirstSource(), GetName(), GetNextSource(), HLTLogKeyword, HLTMessage, and SourcesResolved().
251 {
252   // see header file for function documentation
253   HLTLogKeyword("configuration status");
254   HLTMessage("status of configuration \"%s\" (%p)", GetName(), this);
255   if (!fComponent.IsNull()) HLTMessage("  - component: \"%s\"", fComponent.Data());
256   else HLTMessage("  - component string invalid");
257   if (!fStringSources.IsNull()) HLTMessage("  - sources: \"%s\"", fStringSources.Data());
258   else HLTMessage("  - no sources");
259   if (SourcesResolved(1)<=0)
260     HLTMessage("    there are unresolved sources");
261   AliHLTConfiguration* pSrc=GetFirstSource();
262   while (pSrc) {
263     HLTMessage("    source \"%s\" (%p) resolved", pSrc->GetName(), pSrc);
264     pSrc=GetNextSource();
265   }
266 }
int AliHLTConfiguration::SourcesResolved (int bAuto = 0)
Check resolving status.
Parameters:
bAuto resolve if ==1
Returns: 1 if all sources resolved
Definition at line 215 of file AliHLTConfiguration.cxx.
References ExtractSources(), fListSources, and fNofSources.
Referenced by AliHLTSystem::BuildTaskList(), PrintStatus(), and AliHLTConfigurationHandler::RegisterConfiguration().
216 {
217   // see header file for function documentation
218   int iResult=0;
219   if (fNofSources>=0 || bAuto && (iResult=ExtractSources())>=0) {
220     //HLTDebug("fNofSources=%d", fNofSources);
221     //HLTDebug("list size = %d", fListSources.size());
222     iResult=fNofSources==(int)fListSources.size();
223   }
224   return iResult;
225 }
Member Data Documentation
int AliHLTConfiguration::fArgc [private]
number of arguments
Definition at line 214 of file AliHLTConfiguration.h.
Referenced by ExtractArguments(), GetArguments(), operator=(), and ~AliHLTConfiguration().
TString AliHLTConfiguration::fArguments [private]
The argument string as passed to the constructor. Specifies the arguments for the Analysys component. The string will be parsed and the separated arguments stored in the fArgv(p.) array and fArgc(p.) member.
Definition at line 212 of file AliHLTConfiguration.h.
Referenced by ExtractArguments(), and operator=().
char** AliHLTConfiguration::fArgv [private]
argument array
Definition at line 216 of file AliHLTConfiguration.h.
Referenced by ExtractArguments(), operator=(), and ~AliHLTConfiguration().
TString AliHLTConfiguration::fComponent [private]
component id of this configuration
Definition at line 195 of file AliHLTConfiguration.h.
Referenced by operator=(), and PrintStatus().
AliHLTConfigurationHandler * AliHLTConfiguration::fgConfigurationHandler = NULL [static, private]
the instance of the global configuration handler
Definition at line 138 of file AliHLTConfiguration.cxx.
Referenced by AliHLTConfiguration(), ExtractSources(), GlobalDeinit(), GlobalInit(), and ~AliHLTConfiguration().
TString AliHLTConfiguration::fID [private]
id of this configuration
Definition at line 193 of file AliHLTConfiguration.h.
Referenced by GetName(), operator=(), and ~AliHLTConfiguration().
vector<AliHLTConfiguration*> AliHLTConfiguration::fListSources [private]
list of sources
Definition at line 202 of file AliHLTConfiguration.h.
Referenced by AliHLTConfiguration(), ExtractSources(), GetFirstSource(), GetNextSource(), GetNofSources(), GetSource(), InvalidateSource(), SourcesResolved(), and ~AliHLTConfiguration().
vector<AliHLTConfiguration*>::iterator AliHLTConfiguration::fListSrcElement [private]
iterator for the above list
Definition at line 204 of file AliHLTConfiguration.h.
Referenced by AliHLTConfiguration(), ExtractSources(), GetFirstSource(), GetNextSource(), GetSource(), and InvalidateSource().
int AliHLTConfiguration::fNofSources [private]
number of resolved sources, -1 indicates re-evaluation
Definition at line 200 of file AliHLTConfiguration.h.
Referenced by ExtractSources(), GetFirstSource(), GetNextSource(), InvalidateSources(), operator=(), and SourcesResolved().
TString AliHLTConfiguration::fStringSources [private]
the sources string as passed to the constructor
Definition at line 198 of file AliHLTConfiguration.h.
Referenced by ExtractSources(), operator=(), and PrintStatus().
The documentation for this class was generated from the following files:
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTConfiguration.h
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTConfiguration.cxx