AliHLTPHOSRawAnalyzerComponent Class Reference
#include <AliHLTPHOSRawAnalyzerComponent.h>
Detailed Description
Base class of PHOS HLT online raw analysis component. The class provides a common interface for the implementation of PHOS HLT raw data processors components. The class is intended for processing of arrays of raw data samples to evaluate energy and timing. The Energy will be given in entities of ADC leves ranging from 0 to 1023. Timing will be given in entities of samples periods. Drived clases must implement the fucntions
GetComponentID(p.)
Spawn(p.)
Definition at line 22 of file AliHLTPHOSRawAnalyzerComponent.h.
Public Member Functions
AliHLTPHOSRawAnalyzerComponent ()
virtual ~AliHLTPHOSRawAnalyzerComponent ()
AliHLTPHOSRawAnalyzerComponent (const AliHLTPHOSRawAnalyzerComponent &)
AliHLTPHOSRawAnalyzerComponent & operator= (const AliHLTPHOSRawAnalyzerComponent &)
virtual int DoInit (int argc=0, const char **argv=0)
virtual int Deinit ()
virtual int DoDeinit ()
void DumpData (int gain=0) const
void DumpChannelData (Double_t *data=0) const
void SetEquippmentID (AliHLTUInt16_t id=0)
const AliHLTUInt16_t GetEquippmentID () const
void SetCoordinates (AliHLTUInt16_t equippmentID=0)
virtual const char * GetComponentID ()=0
virtual void GetInputDataTypes (std::vector< AliHLTComponentDataType > &)
virtual AliHLTComponentDataType GetOutputDataType ()
virtual void GetOutputDataSize (unsigned long &constBase, double &inputMultiplier)
virtual AliHLTComponent * Spawn ()=0
Protected Attributes
AliHLTPHOSRawAnalyzer * fAnalyzerPtr
Private Member Functions
virtual int DoEvent (const AliHLTComponentEventData &evtData, const AliHLTComponentBlockData *blocks, AliHLTComponentTriggerData &trigData, AliHLTUInt8_t *outputPtr, AliHLTUInt32_t &size, vector< AliHLTComponentBlockData > &outputBlocks)
void Reset ()
void ResetDataPtr (int startindex=0, int sampleCnt=0)
Private Attributes
const AliHLTUInt16_t fEquippmentID
AliHLTUInt8_t fModuleID
AliHLTUInt8_t fRcuX
AliHLTUInt8_t fRcuZ
AliHLTUInt8_t fRcuZOffset
AliHLTUInt8_t fRcuXOffset
Bool_t fPrintInfo
Bool_t fSendChannelData
Double_t fTmpChannelData [ALTRO_MAX_SAMPLES]
Double_t fMaxValues [N_MODULES][N_ROWS_MOD][N_COLUMNS_MOD][N_GAINS]
int fPrintInfoFrequncy
AliCaloRawStream * fPHOSRawStream
AliRawReaderMemory * fRawMemoryReader
AliHLTPHOSRcuCellEnergyDataStruct * fOutPtr
Static Private Attributes
int fgEventCount = 0
const AliHLTComponentDataType fgkInputDataTypes [] = {kAliHLTVoidDataType,{0,``,``}}
Constructor & Destructor Documentation
AliHLTPHOSRawAnalyzerComponent::AliHLTPHOSRawAnalyzerComponent ()
Default constructor
Definition at line 50 of file AliHLTPHOSRawAnalyzerComponent.cxx.
50                                                               :AliHLTProcessor(), fAnalyzerPtr(0), 
51 fEquippmentID(0), fModuleID(0), fRcuX(0), fRcuZ(0),fRcuZOffset(0), fRcuXOffset(0),fPrintInfo(kFALSE),fSendChannelData(kFALSE),fPrintInfoFrequncy(1000), 
52 fPHOSRawStream(0), fRawMemoryReader(0), fOutPtr(0)
53 {
57 } 
AliHLTPHOSRawAnalyzerComponent::~AliHLTPHOSRawAnalyzerComponent () [virtual]
Default destructor
Definition at line 60 of file AliHLTPHOSRawAnalyzerComponent.cxx.
References fPHOSRawStream, and fRawMemoryReader.
61 {
65   if(fRawMemoryReader != 0)
66     {
67       delete fRawMemoryReader;
68     }
69     if(fPHOSRawStream != 0)
70     {
71       delete fPHOSRawStream;
72     }
73 }
AliHLTPHOSRawAnalyzerComponent::AliHLTPHOSRawAnalyzerComponent (const AliHLTPHOSRawAnalyzerComponent &)
Copy Constructor
Definition at line 76 of file AliHLTPHOSRawAnalyzerComponent.cxx.
76                                                                                                       : AliHLTProcessor(), fAnalyzerPtr(0), 
77 fEquippmentID(0), fModuleID(0), fRcuX(0), fRcuZ(0),fRcuZOffset(0), fRcuXOffset(0),fPrintInfo(kFALSE),fSendChannelData(kFALSE),fPrintInfoFrequncy(1000), 
78 fPHOSRawStream(0), fRawMemoryReader(0), fOutPtr(0)
79 {
83 }
Member Function Documentation
int AliHLTPHOSRawAnalyzerComponent::Deinit () [virtual]
Clean-up function to terminate data processing. Clean-up of common data structures after data processing. The call is redirected to the internal method DoDeinit(p.) which can be overridden by the child class.
Reimplemented from AliHLTProcessor (p.).
Definition at line 86 of file AliHLTPHOSRawAnalyzerComponent.cxx.
87 {
88   //See base class for documentation
89   cout <<  "Deinit" << endl;
90   return 0;
91 }
int AliHLTPHOSRawAnalyzerComponent::DoDeinit () [virtual]
Default method for the internal clean-up. The method is called by Deinit(p.)
Reimplemented from AliHLTComponent (p.).
Definition at line 94 of file AliHLTPHOSRawAnalyzerComponent.cxx.
References fPHOSRawStream, fRawMemoryReader, kHLTLogInfo, and AliHLTLogging::Logging().
95 {
96   //See base class for documentation
97   cout << "DoDeinit" << endl;
98   Logging(kHLTLogInfo, "HLT", "PHOS", ",AliHLTPHOSRawAnalyzerComponen DoDeinit");
99 
100   if(fRawMemoryReader !=0)
101     {
102       delete fRawMemoryReader;
103     }
104     
105   if(fPHOSRawStream != 0)
106     {
107       delete fPHOSRawStream;
108     }
109   return 0;
110 
111 }
int AliHLTPHOSRawAnalyzerComponent::DoEvent (const AliHLTComponentEventData & evtData, const AliHLTComponentBlockData * blocks, AliHLTComponentTriggerData & trigData, AliHLTUInt8_t * outputPtr, AliHLTUInt32_t & size, vector< AliHLTComponentBlockData > & outputBlocks) [private, virtual]
The low-level data processing method for the component. This is the custom processing method and can be overloaded by the component.
Parameters:
evtData event data structure
blocks input data block descriptors
trigData trigger data structure
outputPtr pointer to target buffer
size input: size of target buffer output:size of produced data
outputBlocks list to receive output block descriptors
Returns: neg. error code if failed
Reimplemented from AliHLTProcessor (p.).
Definition at line 150 of file AliHLTPHOSRawAnalyzerComponent.cxx.
References AliHLTUInt8_t, AliHLTPHOSRawAnalyzer::Evaluate(), fAnalyzerPtr, AliHLTComponentEventData::fBlockCnt, AliHLTPHOSRcuCellEnergyDataStruct::fCnt, AliHLTComponentBlockData::fDataType, AliHLTPHOSValidCellDataStruct::fEnergy, fEquippmentID, AliHLTPHOSValidCellDataStruct::fGain, fgEventCount, AliHLTComponent::FillBlockData(), AliHLTPHOSRcuCellEnergyDataStruct::fModuleID, AliHLTComponentBlockData::fOffset, fOutPtr, fPHOSRawStream, fPrintInfo, fPrintInfoFrequncy, AliHLTComponentBlockData::fPtr, fRawMemoryReader, AliHLTPHOSRcuCellEnergyDataStruct::fRcuX, AliHLTPHOSRcuCellEnergyDataStruct::fRcuZ, AliHLTComponentBlockData::fSize, AliHLTComponentBlockData::fSpecification, AliHLTPHOSValidCellDataStruct::fTime, fTmpChannelData, AliHLTPHOSRcuCellEnergyDataStruct::fValidData, AliHLTPHOSValidCellDataStruct::fX, AliHLTPHOSValidCellDataStruct::fZ, AliHLTPHOSRawAnalyzer::GetEnergy(), AliHLTPHOSRawAnalyzer::GetTiming(), kHLTLogFatal, AliHLTLogging::Logging(), ResetDataPtr(), and AliHLTPHOSRawAnalyzer::SetData().
151 {
152   AliHLTUInt8_t tmpMod    = 0;
153   AliHLTUInt8_t tmpZ      = 0;
154   AliHLTUInt8_t tmpX      = 0;
155   AliHLTUInt8_t tmpGain   = 0;
156   Int_t sampleCnt         = 0;
157   Int_t processedChannels = 0;
158   UInt_t offset           = 0; 
159   UInt_t mysize           = 0;
160   UInt_t tSize            = 0;
161   Int_t tmpChannelCnt     = 0;
162   Int_t tmpStartIndex     = 0;
163   AliHLTUInt8_t* outBPtr;
164   unsigned long first;
165   unsigned long last;
166   outBPtr = outputPtr;
167   const AliHLTComponentBlockData* iter = NULL; 
168   unsigned long ndx;
169 
170   for( ndx = 0; ndx < evtData.fBlockCnt; ndx++ )
171     {
172       iter = blocks+ndx;
173       mysize = 0;
174       offset = tSize;
175 
176       if ( iter->fDataType != AliHLTPHOSDefinitions::gkDDLPackedRawDataType )
177         {
178           continue;
179         }
180 
181       fRawMemoryReader->SetMemory( reinterpret_cast<UChar_t*>( iter->fPtr ), iter->fSize );
182       fAnalyzerPtr->SetData(fTmpChannelData);
183       fOutPtr =  (AliHLTPHOSRcuCellEnergyDataStruct*)outBPtr;
184       mysize += sizeof(AliHLTPHOSRcuCellEnergyDataStruct);
185       fOutPtr->fRcuX = fRcuX;
186       fOutPtr->fRcuZ = fRcuZ;
187       fOutPtr->fModuleID = fModuleID;
188       tmpChannelCnt = 0;
189 
190       while(fPHOSRawStream->Next())
191         {
192           if (fPHOSRawStream->IsNewHWAddress())
193             {
194               if(processedChannels > 0)
195                 {
196                   fAnalyzerPtr->SetData(fTmpChannelData);
197                   fAnalyzerPtr->Evaluate(0, sampleCnt);
198                   fOutPtr->fValidData[tmpChannelCnt].fGain = tmpGain;
199                   fOutPtr->fValidData[tmpChannelCnt].fZ  = tmpZ;
200                   fOutPtr->fValidData[tmpChannelCnt].fX  = tmpX; 
201                   fOutPtr->fValidData[tmpChannelCnt].fEnergy  = (float)fAnalyzerPtr->GetEnergy();
202                   fOutPtr->fValidData[tmpChannelCnt].fTime    = (float)fAnalyzerPtr->GetTiming();
203                   ResetDataPtr(tmpStartIndex, sampleCnt);
204                   tmpChannelCnt ++;
205                   sampleCnt = 0;
206                 }
207 
208               tmpMod  = (AliHLTUInt8_t)fPHOSRawStream->GetModule() ;
209               tmpX  =(AliHLTUInt8_t)fPHOSRawStream->GetRow() - fRcuXOffset;
210               tmpZ  =(AliHLTUInt8_t)fPHOSRawStream->GetColumn() - fRcuZOffset;
211               tmpGain =  fPHOSRawStream->IsLowGain(); 
212               processedChannels ++;
213             }
214           
215           if(sampleCnt == 0)
216             {
217               tmpStartIndex = fPHOSRawStream->GetTime();
218             }
219           
220           fTmpChannelData[fPHOSRawStream->GetTime()] =  fPHOSRawStream->GetSignal();
221           sampleCnt ++;
222         }
223 
224       tmpChannelCnt ++;
225       fAnalyzerPtr->SetData(fTmpChannelData);
226       fAnalyzerPtr->Evaluate(0, sampleCnt);
227       fOutPtr->fValidData[tmpChannelCnt].fGain = tmpGain;
228       fOutPtr->fValidData[tmpChannelCnt].fZ  = tmpZ;
229       fOutPtr->fValidData[tmpChannelCnt].fX  = tmpX; 
230       fOutPtr->fValidData[tmpChannelCnt].fEnergy  = fAnalyzerPtr->GetEnergy();
231       fOutPtr->fValidData[tmpChannelCnt].fTime    = fAnalyzerPtr->GetTiming();
232       ResetDataPtr(tmpStartIndex, sampleCnt);
233 
234       sampleCnt = 0;
235 
236       fOutPtr->fCnt =  tmpChannelCnt;
237       AliHLTComponentBlockData bd;
238       FillBlockData( bd );
239       bd.fOffset = offset;
240       bd.fSize = mysize;
241       bd.fDataType = AliHLTPHOSDefinitions::gkCellEnergyDataType;
242       bd.fSpecification = 0xFFFFFFFF;
243       outputBlocks.push_back( bd );
244       tSize += mysize;
245       outBPtr += mysize;
246  
247       if( tSize > size )
248         {
249           cout <<"kHLTLogFatal, HLT::AliHLTPHOSRawAnalyzerComponent::DoEvent Too much data Data written over allowed buffer. Amount written:" << tSize << " allowed" << size << endl;
250           Logging( kHLTLogFatal, "HLT::AliHLTPHOSRawAnalyzerComponent::DoEvent", "Too much data",
251                    "Data written over allowed buffer. Amount written: %lu, allowed amount: %lu."
252                    , tSize, size );
253           return EMSGSIZE;
254         }
255 
256     }
257   
258   fgEventCount++; 
259 
260   if(fPrintInfo == kTRUE)
261     {
262       if(fgEventCount%fPrintInfoFrequncy == 0)
263         {
264           cout <<"Analyzing event " <<  fgEventCount  << "for Equippment " << fEquippmentID << endl; 
265         }  
266     }
267   size = tSize;
268   return 0;
269 }//end DoEvent
int AliHLTPHOSRawAnalyzerComponent::DoInit (int argc = 0, const char ** argv = 0) [virtual]
See base class for documentation
Reimplemented from AliHLTComponent (p.).
Definition at line 274 of file AliHLTPHOSRawAnalyzerComponent.cxx.
References AliHLTUInt16_t, fEquippmentID, fPHOSRawStream, fPrintInfo, fPrintInfoFrequncy, fRawMemoryReader, fSendChannelData, kHLTLogFatal, AliHLTLogging::Logging(), Reset(), SetCoordinates(), and SetEquippmentID().
275 {
277   fSendChannelData = kFALSE;
278   fPrintInfo = kFALSE;
279   Reset();
280   fRawMemoryReader = new AliRawReaderMemory();
281   fPHOSRawStream = new  AliCaloRawStream(fRawMemoryReader,"PHOS");
282   fPHOSRawStream->SetOldRCUFormat(kFALSE);
283   int iResult=0;
284   TString argument="";
285   Bool_t isSetEquippmentID = kFALSE;
286 
287   for(int i=0; i<argc && iResult>=0; i++) 
288     {
289       argument=argv[i];
290       
291       if (argument.IsNull()) 
292         {
293           continue;
294         }
295                          
296     if (argument.CompareTo("-equipmentID") == 0) 
297         {
298           cout << "AliHLTPHOSRawAnalyzerComponent:DoInit  argument = -equipmentID   "  <<endl;  
299           if(i+1 <= argc)
300             {
301               SetEquippmentID((AliHLTUInt16_t)atoi(argv[i+1]));
302               cout << "AliHLTPHOSRawAnalyzerComponent:DoInit  setting equippment ID to  " << fEquippmentID <<endl;
303               fRawMemoryReader->SetEquipmentID(fEquippmentID); 
304               SetCoordinates(fEquippmentID);
305               isSetEquippmentID = kTRUE;
306             }
307           else
308             {
309                iResult= -1;
310                Logging( kHLTLogFatal, "HLT::AliHLTPHOSRcuHistogramProducerComponent::DoInt( int argc, const char** argv )", "Missing argument",
311                         "The argument -equippmentID expects a number");
312                return  iResult;   
313             }
314         }
315       
316     
317     if (argument.CompareTo("-datatype") == 0) 
318       {
319         if(i+1 <= argc)
320           {
321             argument=argv[i+1];
322             if(argument.CompareTo("channeldata") == 0)
323               {
324                 cout << "AliHLTPHOSRawAnalyzerComponent::DoIni  setting sendChannelData = kTRUE "<< endl; 
325                 fSendChannelData = kTRUE;
326               }
327           }     
328       }
329 
330     if (argument.CompareTo("-printinfo") == 0) 
331       {
332         if(i+1 <= argc)
333           {
334             argument=argv[i+1];
335             fPrintInfoFrequncy = atoi(argv[i+1]);
336             fPrintInfo = kTRUE;
337             cout << "AliHLTPHOSRawAnalyzerComponent::DoIni  setting printinfo = kTRUE, with update frequency every  "<< fPrintInfoFrequncy << "th event" <<endl; 
338           }
339         else
340           {
341             cout << "WARNING: asking for event info, but no update frequency is specified, otipn is ignored" << endl;
342           }
343       }
344  
345     }
346 
347 
348   if(isSetEquippmentID == kFALSE)
349     {
350       Logging( kHLTLogFatal, "HLT::AliHLTPHOSRcuHistogramProducerComponent::DoInt( int argc, const char** argv )", "Missing argument",
351                "The argument equippmentID is not set: set it with a component argumet like this: -equippmentID  <number>");
352       iResult = -2; 
353     }
354 
355   return 0;
356 }
void AliHLTPHOSRawAnalyzerComponent::DumpChannelData (Double_t * data = 0) const
Definition at line 381 of file AliHLTPHOSRawAnalyzerComponent.cxx.
382 {
383   //shutting up the code checker 
384      cout << endl;
385       for(int i=0; i<  ALTRO_MAX_SAMPLES; i++)
386         {
387           if (data[i] != 0)
388             {
389               cout <<i <<"\t";
390             }
391         }
392       cout << endl;
393       
394       for(int i=0; i<  ALTRO_MAX_SAMPLES; i++)
395         {
396           if (data[i] != 0)
397             {
398               cout <<data[i] <<"\t";
399             }
400         }
401       
402       cout << endl;
403 }
void AliHLTPHOSRawAnalyzerComponent::DumpData (int gain = 0) const
Definition at line 360 of file AliHLTPHOSRawAnalyzerComponent.cxx.
References fMaxValues.
361 {
362   //Dumping data to std out
363   for(int mod = 0; mod < N_MODULES; mod ++)
364     {
365       printf("\n ***********  MODULE %d ************\n", mod);
366       for(int row = 0; row <  N_ROWS_MOD; row ++)
367         {
368           for(int col = 0; col <  N_COLUMNS_MOD; col ++)
369             {
370               if( fMaxValues[mod][row][col][0] != 0)
371                 { 
372                   cout << fMaxValues[mod][row][col][gain] << "\t";
373                 }
374             }
375         } 
376     }
377 }
const char * AliHLTPHOSRawAnalyzerComponent::GetComponentID () [pure virtual]
Returns the component ID
Implements AliHLTComponent (p.).
Implemented in AliHLTPHOSRawAnalyzerCrudeComponent (p.), and AliHLTPHOSRawAnalyzerPeakFinderComponent (p.).
Definition at line 114 of file AliHLTPHOSRawAnalyzerComponent.cxx.
115 {
117   return "AliPhosTestRaw";
118 }
const AliHLTUInt16_t AliHLTPHOSRawAnalyzerComponent::GetEquippmentID () const
Definition at line 451 of file AliHLTPHOSRawAnalyzerComponent.cxx.
452 {
453   //shutting up the code checker
454   return  fEquippmentID;
455 }
void AliHLTPHOSRawAnalyzerComponent::GetInputDataTypes (std::vector< AliHLTComponentDataType > &) [virtual]
Definition at line 122 of file AliHLTPHOSRawAnalyzerComponent.cxx.
References AliHLTComponentDataType::fID.
123 {
124   //See Base class for documentation
125   const AliHLTComponentDataType* pType=fgkInputDataTypes;
126   while (pType->fID!=0) {
127     list.push_back(*pType);
128     pType++;
129   }
130 }
void AliHLTPHOSRawAnalyzerComponent::GetOutputDataSize (unsigned long & constBase, double & inputMultiplier) [virtual]
Get a ratio by how much the data volume is shrinked or enhanced. The function is pure virtual and must be implemented by the child class.
Parameters:
constBase return: additive part, independent of the input data volume
inputMultiplier return: multiplication ratio
Returns: values in the reference variables
Implements AliHLTComponent (p.).
Definition at line 140 of file AliHLTPHOSRawAnalyzerComponent.cxx.
142 {
143   //See Base class for documentation 
144   constBase = 30;
145   //  inputMultiplier = 0.1;
146   inputMultiplier = 1;
147 }
AliHLTComponentDataType AliHLTPHOSRawAnalyzerComponent::GetOutputDataType () [virtual]
Get the output data type of the component. The function is pure virtual and must be implemented by the child class.
Returns: output data type
Implements AliHLTComponent (p.).
Definition at line 133 of file AliHLTPHOSRawAnalyzerComponent.cxx.
134 {
135   //See Base class for documentation 
136   return AliHLTPHOSDefinitions::gkCellEnergyDataType;
137 }
AliHLTPHOSRawAnalyzerComponent& AliHLTPHOSRawAnalyzerComponent::operator= (const AliHLTPHOSRawAnalyzerComponent &) [inline]
Definition at line 28 of file AliHLTPHOSRawAnalyzerComponent.h.
29    {
30       return *this;
31    };
void AliHLTPHOSRawAnalyzerComponent::Reset () [private]
Definition at line 407 of file AliHLTPHOSRawAnalyzerComponent.cxx.
References ALTRO_MAX_SAMPLES, fMaxValues, and ResetDataPtr().
Referenced by DoInit().
408 {
409   //shutting code checker
410   for(int mod = 0; mod < N_MODULES; mod ++)
411     {
412       for(int row = 0; row < N_ROWS_MOD; row ++)
413         {
414           for(int col = 0; col < N_COLUMNS_MOD; col ++)
415             {
416               for(int gain = 0; gain < N_GAINS; gain ++ )
417                 {
418                   fMaxValues[mod][row][col][gain] = 0;
419                 }
420             }
421         }
422     }
423 
424   ResetDataPtr(0, ALTRO_MAX_SAMPLES);
425 
426 } // end Reset
void AliHLTPHOSRawAnalyzerComponent::ResetDataPtr (int startindex = 0, int sampleCnt = 0) [private]
Definition at line 429 of file AliHLTPHOSRawAnalyzerComponent.cxx.
References fTmpChannelData.
Referenced by DoEvent(), and Reset().
430 {
431   //shutting up the code checker
432   for(int i = startindex ; i< sampleCnt; i++)
433     {
434       fTmpChannelData[i] = 0;
435     }
436 }
void AliHLTPHOSRawAnalyzerComponent::SetCoordinates (AliHLTUInt16_t equippmentID = 0)
Definition at line 458 of file AliHLTPHOSRawAnalyzerComponent.cxx.
References fEquippmentID, fModuleID, fRcuX, fRcuXOffset, fRcuZ, fRcuZOffset, N_XCOLUMNS_RCU, and N_ZROWS_RCU.
Referenced by DoInit().
459 {
460  //shutting up the code checker
461   int rcuIndex =  (fEquippmentID - 1792)%N_RCUS_PER_MODULE;
462   fModuleID = (fEquippmentID  -1792 -rcuIndex)/N_RCUS_PER_MODULE;
463   
464   if(rcuIndex == 0)
465     {
466       fRcuX = 0; 
467       fRcuZ = 0;
468     }
469 
470   if(rcuIndex == 1)
471     {
472       fRcuX = 0; 
473       fRcuZ = 1;
474     }
475  
476   if(rcuIndex == 2)
477     {
478       fRcuX = 1; 
479       fRcuZ = 0;
480     }
481 
482   if(rcuIndex == 3)
483     {
484       fRcuX = 1; 
485       fRcuZ = 1;
486     }
487 
488   fRcuZOffset =  N_ZROWS_RCU*fRcuZ;
489   fRcuXOffset =  N_XCOLUMNS_RCU*fRcuX;
490 
491   cout <<"********InitInfo************"<< endl;
492   cout <<"AliHLTPHOSRawAnalyzerComponent::SetCoordinate casted"<< endl;
493   cout <<"Equpippment ID =\t"<< fEquippmentID <<endl;
494   cout <<"Module ID =\t"<<  (int)fModuleID<<endl;
495   cout <<"RCUX =\t\t" << (int)fRcuX << endl;
496   cout <<"RCUZ =\t\t" << (int)fRcuZ << endl;
497   cout <<"RcuZOffset = \t" <<  (int)fRcuZOffset << endl;
498   cout <<"RcuXOffset = \t" <<  (int)fRcuXOffset << endl << endl;
499 }
void AliHLTPHOSRawAnalyzerComponent::SetEquippmentID (AliHLTUInt16_t id = 0)
Changing the value of the constant fEquippmentID by virue of const_cast as it should only be set once and then remain constant. It caannot be set in the class constructor because it should be set in the DoInit fucntion.
Definition at line 439 of file AliHLTPHOSRawAnalyzerComponent.cxx.
References AliHLTUInt16_t.
Referenced by DoInit().
440 {
445   AliHLTUInt16_t  &ref = const_cast<AliHLTUInt16_t&>(fEquippmentID); 
446   ref = id;
447 }
virtual AliHLTComponent* AliHLTPHOSRawAnalyzerComponent::Spawn () [pure virtual]
Spawn function. Each component must implement a spawn function to create a new instance of the class. Basically the function must return new my_class_name.
Returns: new class instance
Implements AliHLTComponent (p.).
Implemented in AliHLTPHOSRawAnalyzerCrudeComponent (p.), and AliHLTPHOSRawAnalyzerPeakFinderComponent (p.).
Member Data Documentation
AliHLTPHOSRawAnalyzer* AliHLTPHOSRawAnalyzerComponent::fAnalyzerPtr [protected]
Pointer to an analyzer object used for raw data anlysis
Definition at line 50 of file AliHLTPHOSRawAnalyzerComponent.h.
Referenced by DoEvent().
const AliHLTUInt16_t AliHLTPHOSRawAnalyzerComponent::fEquippmentID [private]
Equippment ID as defined by ALICE
Definition at line 62 of file AliHLTPHOSRawAnalyzerComponent.h.
Referenced by DoEvent(), DoInit(), and SetCoordinates().
int AliHLTPHOSRawAnalyzerComponent::fgEventCount = 0 [static, private]
Global event counter for this component
Definition at line 46 of file AliHLTPHOSRawAnalyzerComponent.cxx.
Referenced by DoEvent().
const AliHLTComponentDataType AliHLTPHOSRawAnalyzerComponent::fgkInputDataTypes = {kAliHLTVoidDataType,{0,``,``}} [static, private]
List of datatypes that can be given to this component
Definition at line 45 of file AliHLTPHOSRawAnalyzerComponent.cxx.
Double_t AliHLTPHOSRawAnalyzerComponent::fMaxValues[N_MODULES][N_ROWS_MOD][N_COLUMNS_MOD][N_GAINS] [private]
array to store cell energies
Definition at line 71 of file AliHLTPHOSRawAnalyzerComponent.h.
Referenced by DumpData(), and Reset().
AliHLTUInt8_t AliHLTPHOSRawAnalyzerComponent::fModuleID [private]
ID of the module this component read data from (0-4)
Definition at line 63 of file AliHLTPHOSRawAnalyzerComponent.h.
Referenced by SetCoordinates().
AliHLTPHOSRcuCellEnergyDataStruct* AliHLTPHOSRawAnalyzerComponent::fOutPtr [private]
Pointer to outputbuffer to write results from the component into shared memory
Definition at line 75 of file AliHLTPHOSRawAnalyzerComponent.h.
Referenced by DoEvent().
AliCaloRawStream* AliHLTPHOSRawAnalyzerComponent::fPHOSRawStream [private]
Streamer for PHOS raw data, used by fPHOSRawMemory reader
Definition at line 73 of file AliHLTPHOSRawAnalyzerComponent.h.
Referenced by DoDeinit(), DoEvent(), DoInit(), and ~AliHLTPHOSRawAnalyzerComponent().
Bool_t AliHLTPHOSRawAnalyzerComponent::fPrintInfo [private]
wether or not to print debugg info to std out
Definition at line 68 of file AliHLTPHOSRawAnalyzerComponent.h.
Referenced by DoEvent(), and DoInit().
int AliHLTPHOSRawAnalyzerComponent::fPrintInfoFrequncy [private]
Defines the update frequency for information printet to std out
Definition at line 72 of file AliHLTPHOSRawAnalyzerComponent.h.
Referenced by DoEvent(), and DoInit().
AliRawReaderMemory* AliHLTPHOSRawAnalyzerComponent::fRawMemoryReader [private]
Decoder to read PHOS raw data on the altro format
Definition at line 74 of file AliHLTPHOSRawAnalyzerComponent.h.
Referenced by DoDeinit(), DoEvent(), DoInit(), and ~AliHLTPHOSRawAnalyzerComponent().
AliHLTUInt8_t AliHLTPHOSRawAnalyzerComponent::fRcuX [private]
X position of RCU the data from this Equippment comes from (0 or 1)
Definition at line 64 of file AliHLTPHOSRawAnalyzerComponent.h.
Referenced by SetCoordinates().
AliHLTUInt8_t AliHLTPHOSRawAnalyzerComponent::fRcuXOffset [private]
offset in therms of towers in the X direction relative to the module
Definition at line 67 of file AliHLTPHOSRawAnalyzerComponent.h.
Referenced by SetCoordinates().
AliHLTUInt8_t AliHLTPHOSRawAnalyzerComponent::fRcuZ [private]
Z position of RCU the data from this Equippment comes from (0 or 1)
Definition at line 65 of file AliHLTPHOSRawAnalyzerComponent.h.
Referenced by SetCoordinates().
AliHLTUInt8_t AliHLTPHOSRawAnalyzerComponent::fRcuZOffset [private]
offset in therms of towers in the Z direction relative to the module
Definition at line 66 of file AliHLTPHOSRawAnalyzerComponent.h.
Referenced by SetCoordinates().
Bool_t AliHLTPHOSRawAnalyzerComponent::fSendChannelData [private]
wether or not to send raw data from the component into shared memory
Definition at line 69 of file AliHLTPHOSRawAnalyzerComponent.h.
Referenced by DoInit().
Double_t AliHLTPHOSRawAnalyzerComponent::fTmpChannelData[ALTRO_MAX_SAMPLES] [private]
temporary variable to store raw samples from a single altro channel
Definition at line 70 of file AliHLTPHOSRawAnalyzerComponent.h.
Referenced by DoEvent(), and ResetDataPtr().
The documentation for this class was generated from the following files:
AliHLTPHOSRawAnalyzerComponent.h
AliHLTPHOSRawAnalyzerComponent.cxx