AliHLTComponent::AliHLTStopwatchGuard Class Reference
#include <AliHLTComponent.h>
Detailed Description
Helper class for starting and stopping a stopwatch. The guard can be used by instantiating an object in a function. The specified stopwatch is started and the previous stopwatch put on hold. When the function is terminated, the object is deleted automatically deleted, stopping the stopwatch and starting the one on hold.
 IMPORTANT: never create dynamic objects from this guard as this violates the idea of a guard.
Definition at line 396 of file AliHLTComponent.h.
Public Member Functions
AliHLTStopwatchGuard ()
AliHLTStopwatchGuard (TStopwatch *pStart)
AliHLTStopwatchGuard (AliHLTStopwatchGuard &)
~AliHLTStopwatchGuard ()
Private Member Functions
int Hold (TStopwatch *pSucc)
int Resume (TStopwatch *pSucc)
Private Attributes
TStopwatch * fpStopwatch
AliHLTStopwatchGuard * fpPrec
transient
Static Private Attributes
AliHLTStopwatchGuard * fgpCurrent = NULL
transient
Constructor & Destructor Documentation
AliHLTComponent::AliHLTStopwatchGuard::AliHLTStopwatchGuard ()
standard constructor (not for use)
Definition at line 852 of file AliHLTComponent.cxx.
853   :
854   fpStopwatch(NULL),
855   fpPrec(NULL)
856 {
857   // standard constructor (not for use)
858 }
AliHLTComponent::AliHLTStopwatchGuard::AliHLTStopwatchGuard (TStopwatch * pStart)
constructor
Definition at line 860 of file AliHLTComponent.cxx.
References fgpCurrent, fpPrec, fpStopwatch, and Hold().
861   :
862   fpStopwatch(pStopwatch),
863   fpPrec(NULL)
864 {
865   // constructor
866 
867   // check for already existing guard
868   if (fgpCurrent) fpPrec=fgpCurrent;
869   fgpCurrent=this;
870 
871   // stop the preceeding guard if it controls a different stopwatch
872   int bStart=1;
873   if (fpPrec && fpPrec!=this) bStart=fpPrec->Hold(fpStopwatch);
874 
875   // start the stopwatch if the current guard controls a different one
876   if (fpStopwatch && bStart==1) fpStopwatch->Start(kFALSE);
877 }
AliHLTComponent::AliHLTStopwatchGuard::AliHLTStopwatchGuard (AliHLTStopwatchGuard &)
copy constructor (not for use)
Definition at line 879 of file AliHLTComponent.cxx.
880   :
881   fpStopwatch(NULL),
882   fpPrec(NULL)
883 {
884   // copy constructor (not for use)
885 }
AliHLTComponent::AliHLTStopwatchGuard::~AliHLTStopwatchGuard ()
destructor
Definition at line 889 of file AliHLTComponent.cxx.
References fgpCurrent, fpPrec, fpStopwatch, and Resume().
890 {
891   // destructor
892 
893   // resume the preceeding guard if it controls a different stopwatch
894   int bStop=1;
895   if (fpPrec && fpPrec!=this) bStop=fpPrec->Resume(fpStopwatch);
896 
897   // stop the stopwatch if the current guard controls a different one
898   if (fpStopwatch && bStop==1) fpStopwatch->Stop();
899 
900   // resume to the preceeding guard
901   fgpCurrent=fpPrec;
902 }
Member Function Documentation
int AliHLTComponent::AliHLTStopwatchGuard::Hold (TStopwatch * pSucc) [private]
Hold the previous guard for the existence of this guard. Checks whether this guard controls a new stopwatch. In that case, the previous guard and its stopwatch are put on hold.
Parameters:
pSucc instance of the stopwatch of the new guard
Returns: 1 if pSucc is a different stopwatch which should be started
 0 if it controls the same stopwatch
Definition at line 904 of file AliHLTComponent.cxx.
References fpStopwatch.
Referenced by AliHLTStopwatchGuard().
905 {
906   // see header file for function documentation
907   if (fpStopwatch!=NULL && fpStopwatch!=pSucc) fpStopwatch->Stop();
908   return fpStopwatch!=pSucc?1:0;
909 }
int AliHLTComponent::AliHLTStopwatchGuard::Resume (TStopwatch * pSucc) [private]
Resume the previous guard. Checks whether the peceeding guard controls a different stopwatch. In that case, the its stopwatch is resumed.
Parameters:
pSucc instance of the stopwatch of the new guard
Returns: 1 if pSucc is a different stopwatch which should be stopped
 0 if it controls the same stopwatch
Definition at line 911 of file AliHLTComponent.cxx.
References fpStopwatch.
Referenced by ~AliHLTStopwatchGuard().
912 {
913   // see header file for function documentation
914   if (fpStopwatch!=NULL && fpStopwatch!=pSucc) fpStopwatch->Start(kFALSE);
915   return fpStopwatch!=pSucc?1:0;
916 }
Member Data Documentation
AliHLTComponent::AliHLTStopwatchGuard * AliHLTComponent::AliHLTStopwatchGuard::fgpCurrent = NULL [static, private]
transient
active stopwatch guard
Definition at line 887 of file AliHLTComponent.cxx.
Referenced by AliHLTStopwatchGuard(), and ~AliHLTStopwatchGuard().
AliHLTStopwatchGuard* AliHLTComponent::AliHLTStopwatchGuard::fpPrec [private]
transient
previous stopwatch guard, put on hold during existence of the guard
Definition at line 434 of file AliHLTComponent.h.
Referenced by AliHLTStopwatchGuard(), and ~AliHLTStopwatchGuard().
TStopwatch* AliHLTComponent::AliHLTStopwatchGuard::fpStopwatch [private]
the stopwatch controlled by this guard
Definition at line 431 of file AliHLTComponent.h.
Referenced by AliHLTStopwatchGuard(), Hold(), Resume(), and ~AliHLTStopwatchGuard().
The documentation for this class was generated from the following files:
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTComponent.h
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTComponent.cxx