AliHLTComponent Class Reference
#include <AliHLTComponent.h>
Detailed Description
Base class of HLT data processing components. The class provides a common interface for HLT data processing components. The interface can be accessed from the online HLT framework or the AliRoot offline analysis framework.
Component identification and properties
Each component must provide a unique ID, input and output data type indications, and a spawn function.
Required property methods
GetComponentID(p.)
GetInputDataTypes(p.) (see Component type(p.) for default implementations.)
GetOutputDataType(p.) (see Component type(p.) for default implementations.)
GetOutputDataSize(p.) (see Component type(p.) for default implementations.)
Spawn(p.)
Optional handlers
DoInit(p.)
DoDeinit(p.)
Data processing
Component type
Components can be of type
kSource(p.) components which only produce data
kProcessor(p.) components which consume and produce data
kSink(p.) components which only consume data
where data production and consumption refer to the analysis data stream. In order to indicate the type, a child component can overload the GetComponentType(p.) function.
Standard implementations
Components in general do not need to implement this function, standard implementations of the 3 types are available:
AliHLTDataSource(p.) for components of type kSource(p.)
 All types of data sources can inherit from AliHLTDataSource(p.) and must implement the AliHLTDataSource::GetEvent(p.) method. The class also implements a standard method for GetInputDataTypes(p.).
AliHLTProcessor(p.) for components of type kProcessor(p.)
 All types of data processors can inherit from AliHLTDataSource(p.) and must implement the AliHLTProcessor::DoEvent(p.) method.
AliHLTDataSink(p.) for components of type kSink(p.)
 All types of data processors can inherit from AliHLTDataSource(p.) and must implement the AliHLTDataSink::DumpEvent(p.) method. The class also implements a standard method for GetOutputDataType(p.) and GetOutputDataSize(p.).
Running environment
In order to adapt to different environments (on-line/off-line), the component gets an environment structure with function pointers. The base class provides member functions for those environment dependend functions. The member functions are used by the component implementation and are re-mapped to the corresponding functions.
Component interfaces
Each of the 3 standard component base classes AliHLTProcessor(p.), AliHLTDataSource(p.) and AliHLTDataSink(p.) provides it's own processing method (see Standard implementations(p.)), which splits into a high and a low-level method. For the Low-level interface(p.), all parameters are shipped as function arguments, the component is supposed to dump data to the output buffer and handle all block descriptors. The High-level interface(p.) is the standard processing method and will be used whenever the low-level method is not overloaded.
High-level interface
The high-level component interface provides functionality to exchange ROOT structures between components. In contrast to the Low-level interface(p.), a couple of functions can be used to access data blocks of the input stream and send data blocks or ROOT TObject's to the output stream. The functionality is hidden from the user and is implemented by using ROOT's TMessage class.
Interface methods
The interface provides a couple of methods in order to get objects from the input, data blocks (non TObject) from the input, and to push back objects and data blocks to the output. For convenience there are several functions of identical name (and similar behavior) with different parameters defined. Please refer to the function documentation.
GetNumberOfInputBlocks(p.)
 return the number of data blocks in the input stream
GetFirstInputObject(p.)
 get the first object of a specific data type
GetNextInputObject(p.)
 get the next object of same data type as last GetFirstInputObject/Block call
GetFirstInputBlock(p.)
 get the first block of a specific data type
GetNextInputBlock(p.)
 get the next block of same data type as last GetFirstInputBlock/Block call
PushBack(p.)
 insert an object or data buffer into the output
CreateEventDoneData(p.)
 add event information to the output
In addition, the processing methods are simplified a bit by cutting out most of the parameters. The component implementation
See also: AliHLTProcessor(p.) AliHLTDataSource(p.) AliHLTDataSink(p.)
IMPORTANT: objects and block descriptors provided by the high-level interface MUST NOT BE DELETED by the caller.
High-level interface guidelines
Structures must inherit from the ROOT object base class TObject in order be transported by the transportation framework.
all pointer members must be transient (marked //! behind the member definition), i.e. will not be stored/transported, or properly marked (//->) in order to call the streamer of the object the member is pointing to. The latter is not recomended. Structures to be transported between components should be streamlined.
no use of stl vectors/strings, use appropriate ROOT classes instead
Low-level interface
The low-level component interface consists of the specific data processing methods for AliHLTProcessor(p.), AliHLTDataSource(p.), and AliHLTDataSink(p.).
AliHLTProcessor::DoEvent(p.)
AliHLTDataSource::GetEvent(p.)
AliHLTDataSink::DumpEvent(p.)
Component handling
The handling of HLT analysis components is carried out by the AliHLTComponentHandler(p.). Component are registered automatically at load-time of the component shared library under the following suppositions:
the component library has to be loaded from the AliHLTComponentHandler(p.) using the AliHLTComponentHandler::LoadLibrary(p.) method.
the component implementation defines one global object (which is generated when the library is loaded)
General design considerations
The analysis code should be implemented in one or more destict class(es). A component should be implemented which interface the destict analysis code to the component interface. This component generates the analysis object dynamically.
Assume you have an implemetation AliHLTDetMyAnalysis , another class AliHLTDetMyAnalysisComponent contains:
 private:
   AliHLTDetMyAnalysis* fMyAnalysis; //!
 The object should then be instantiated in the DoInit handler of AliHLTDetMyAnalysisComponent , and cleaned in the DoDeinit handler.
Further rules:
avoid big static arrays in the component, allocate the memory at runtime
Class members
Definition at line 197 of file AliHLTComponent.h.
Public Types
enum TComponentType { kUnknown = 0,
kSource = 1,
kProcessor = 2,
kSink = 3
 }
enum AliHLTStopwatchType {
kSWBase,
kSWDA,
kSWInput,
kSWOutput,
kSWTypeCount
 }
Public Member Functions
AliHLTComponent ()
AliHLTComponent (const AliHLTComponent &)
AliHLTComponent & operator= (const AliHLTComponent &)
virtual ~AliHLTComponent ()
virtual int Init (AliHLTComponentEnvironment *environ, void *environParam, int argc, const char **argv)
virtual int Deinit ()
int ProcessEvent (const AliHLTComponentEventData &evtData, const AliHLTComponentBlockData *blocks, AliHLTComponentTriggerData &trigData, AliHLTUInt8_t *outputPtr, AliHLTUInt32_t &size, AliHLTUInt32_t &outputBlockCnt, AliHLTComponentBlockData *&outputBlocks, AliHLTComponentEventDoneData *&edd)
virtual int DoProcessing (const AliHLTComponentEventData &evtData, const AliHLTComponentBlockData *blocks, AliHLTComponentTriggerData &trigData, AliHLTUInt8_t *outputPtr, AliHLTUInt32_t &size, vector< AliHLTComponentBlockData > &outputBlocks, AliHLTComponentEventDoneData *&edd)=0
virtual TComponentType GetComponentType ()=0
virtual const char * GetComponentID ()=0
virtual void GetInputDataTypes (vector< AliHLTComponentDataType > &)=0
virtual AliHLTComponentDataType GetOutputDataType ()=0
virtual void GetOutputDataSize (unsigned long &constBase, double &inputMultiplier)=0
virtual AliHLTComponent * Spawn ()=0
int FindMatchingDataTypes (AliHLTComponent *pConsumer, vector< AliHLTComponentDataType > *tgtList)
void PrintDataTypeContent (AliHLTComponentDataType &dt, const char *format=NULL) const
void PrintComponentDataTypeInfo (const AliHLTComponentDataType &dt)
int SetStopwatch (TObject *pSW, AliHLTStopwatchType type=kSWBase)
int SetStopwatches (TObjArray *pStopwatches)
Static Public Member Functions
int SetGlobalComponentHandler (AliHLTComponentHandler *pCH, int bOverwrite=0)
int UnsetGlobalComponentHandler ()
string DataType2Text (const AliHLTComponentDataType &type)
void FillEventData (AliHLTComponentEventData &evtData)
Protected Member Functions
void FillBlockData (AliHLTComponentBlockData &blockData) const
void FillShmData (AliHLTComponentShmData &shmData) const
void FillDataType (AliHLTComponentDataType &dataType) const
void CopyDataType (AliHLTComponentDataType &tgtdt, const AliHLTComponentDataType &srcdt)
void SetDataType (AliHLTComponentDataType &tgtdt, const char *id, const char *origin)
virtual int DoInit (int argc, const char **argv)
virtual int DoDeinit ()
void * AllocMemory (unsigned long size)
int MakeOutputDataBlockList (const vector< AliHLTComponentBlockData > &blocks, AliHLTUInt32_t *blockCount, AliHLTComponentBlockData **outputBlocks)
int GetEventDoneData (unsigned long size, AliHLTComponentEventDoneData **edd)
void DataType2Text (const AliHLTComponentDataType &type, char output[kAliHLTComponentDataTypefIDsize+kAliHLTComponentDataTypefOriginSize+2]) const
int GetEventCount () const
int GetNumberOfInputBlocks () const
const TObject * GetFirstInputObject (const AliHLTComponentDataType &dt=kAliHLTAnyDataType, const char *classname=NULL, int bForce=0)
const TObject * GetFirstInputObject (const char *dtID, const char *dtOrigin, const char *classname=NULL, int bForce=0)
const TObject * GetNextInputObject (int bForce=0)
AliHLTComponentDataType GetDataType (const TObject *pObject=NULL)
AliHLTUInt32_t GetSpecification (const TObject *pObject=NULL)
const AliHLTComponentBlockData * GetFirstInputBlock (const AliHLTComponentDataType &dt=kAliHLTAnyDataType)
const AliHLTComponentBlockData * GetFirstInputBlock (const char *dtID, const char *dtOrigin)
const AliHLTComponentBlockData * GetInputBlock (int index)
const AliHLTComponentBlockData * GetNextInputBlock ()
AliHLTUInt32_t GetSpecification (const AliHLTComponentBlockData *pBlock=NULL)
int PushBack (TObject *pObject, const AliHLTComponentDataType &dt, AliHLTUInt32_t spec=kAliHLTVoidDataSpec)
int PushBack (TObject *pObject, const char *dtID, const char *dtOrigin, AliHLTUInt32_t spec=kAliHLTVoidDataSpec)
int PushBack (void *pBuffer, int iSize, const AliHLTComponentDataType &dt, AliHLTUInt32_t spec=kAliHLTVoidDataSpec)
int PushBack (void *pBuffer, int iSize, const char *dtID, const char *dtOrigin, AliHLTUInt32_t spec=kAliHLTVoidDataSpec)
int EstimateObjectSize (TObject *pObject) const
int CreateEventDoneData (AliHLTComponentEventDoneData edd)
Private Member Functions
int IncrementEventCounter ()
int FindInputBlock (const AliHLTComponentDataType &dt, int startIdx=-1) const
int FindInputBlock (const AliHLTComponentBlockData *pBlock) const
TObject * CreateInputObject (int idx, int bForce=0)
TObject * GetInputObject (int idx, const char *classname=NULL, int bForce=0)
int CleanupInputObjects ()
int InsertOutputBlock (void *pBuffer, int iSize, const AliHLTComponentDataType &dt, AliHLTUInt32_t spec)
Private Attributes
AliHLTComponentEnvironment fEnvironment
transient
AliHLTEventID_t fCurrentEvent
int fEventCount
int fFailedEvents
AliHLTComponentEventData fCurrentEventData
const AliHLTComponentBlockData * fpInputBlocks
int fCurrentInputBlock
transient
AliHLTComponentDataType fSearchDataType
string fClassName
TObjArray * fpInputObjects
AliHLTUInt8_t * fpOutputBuffer
transient
AliHLTUInt32_t fOutputBufferSize
transient
AliHLTUInt32_t fOutputBufferFilled
vector< AliHLTComponentBlockData > fOutputBlocks
TObjArray * fpStopwatches
Static Private Attributes
AliHLTComponentHandler * fgpComponentHandler = NULL
Member Enumeration Documentation
enum AliHLTComponent::AliHLTStopwatchType
Stopwatch type for benchmarking.
Enumeration values:
kSWBase
 total time for event processing
kSWDA
 detector algorithm w/o interface callbacks
kSWInput
 data sources
kSWOutput
 data sinks
kSWTypeCount
 number of types
Definition at line 374 of file AliHLTComponent.h.
374                            {
376     kSWBase,
378     kSWDA,
380     kSWInput,
382     kSWOutput,
384     kSWTypeCount
385   };
enum AliHLTComponent::TComponentType
component type definitions
Enumeration values:
kUnknown
kSource
kProcessor
kSink
Definition at line 209 of file AliHLTComponent.h.
209 { kUnknown=0, kSource=1, kProcessor=2, kSink=3 };
Constructor & Destructor Documentation
AliHLTComponent::AliHLTComponent ()
standard constructor
Definition at line 49 of file AliHLTComponent.cxx.
References fEnvironment, fgpComponentHandler, kAliHLTVoidDataType, kHLTLogDefault, AliHLTComponentHandler::ScheduleRegister(), and AliHLTLogging::SetLocalLoggingLevel().
50   :
51   fEnvironment(),
52   fCurrentEvent(0),
53   fEventCount(-1),
54   fFailedEvents(0),
55   fCurrentEventData(),
56   fpInputBlocks(NULL),
57   fCurrentInputBlock(-1),
58   fSearchDataType(kAliHLTVoidDataType),
59   fClassName(),
60   fpInputObjects(NULL),
61   fpOutputBuffer(NULL),
62   fOutputBufferSize(0),
63   fOutputBufferFilled(0),
64   fOutputBlocks(),
65   fpStopwatches(new TObjArray(kSWTypeCount))
66 {
67   // see header file for class documentation
68   // or
69   // refer to README to build package
70   // or
71   // visit http://web.ift.uib.no/~kjeks/doc/alice-hlt
72   memset(&fEnvironment, 0, sizeof(AliHLTComponentEnvironment));
73   if (fgpComponentHandler)
74     fgpComponentHandler->ScheduleRegister(this);
75   SetLocalLoggingLevel(kHLTLogDefault);
76 }
AliHLTComponent::AliHLTComponent (const AliHLTComponent &)
not a valid copy constructor, defined according to effective C++ style
Definition at line 78 of file AliHLTComponent.cxx.
References HLTFatal, and kAliHLTVoidDataType.
79   :
80   AliHLTLogging(),
81   fEnvironment(),
82   fCurrentEvent(0),
83   fEventCount(-1),
84   fFailedEvents(0),
85   fCurrentEventData(),
86   fpInputBlocks(NULL),
87   fCurrentInputBlock(-1),
88   fSearchDataType(kAliHLTVoidDataType),
89   fClassName(),
90   fpInputObjects(NULL),
91   fpOutputBuffer(NULL),
92   fOutputBufferSize(0),
93   fOutputBufferFilled(0),
94   fOutputBlocks(),
95   fpStopwatches(NULL)
96 {
97   // see header file for class documentation
98   HLTFatal("copy constructor untested");
99 }
AliHLTComponent::~AliHLTComponent () [virtual]
standard destructor
Definition at line 108 of file AliHLTComponent.cxx.
References CleanupInputObjects(), and fpStopwatches.
109 {
110   // see header file for function documentation
111   CleanupInputObjects();
112   if (fpStopwatches!=NULL) delete fpStopwatches;
113   fpStopwatches=NULL;
114 }
Member Function Documentation
void * AliHLTComponent::AllocMemory (unsigned long size) [protected]
General memory allocation method. All memory which is going to be used 'outside' of the interface must be provided by the framework (online or offline). The method is redirected to a function provided by the current framework. Function pointers are transferred via the AliHLTComponentEnvironment(p.) structure.
Definition at line 249 of file AliHLTComponent.cxx.
References AliHLTComponentEnvironment::fAllocMemoryFunc, fEnvironment, AliHLTComponentEnvironment::fParam, and HLTFatal.
Referenced by MakeOutputDataBlockList().
250 {
251   // see header file for function documentation
252   if (fEnvironment.fAllocMemoryFunc)
253     return (*fEnvironment.fAllocMemoryFunc)(fEnvironment.fParam, size );
254   HLTFatal("no memory allocation handler registered");
255   return NULL;
256 }
int AliHLTComponent::CleanupInputObjects () [private]
Clean the list of input objects. Cleanup is done at the end of each event processing.
Definition at line 564 of file AliHLTComponent.cxx.
References fpInputObjects.
Referenced by ProcessEvent(), and ~AliHLTComponent().
565 {
566   // see header file for function documentation
567   if (!fpInputObjects) return 0;
568   TObjArray* array=fpInputObjects;
569   fpInputObjects=NULL;
570   for (int i=0; i<array->GetEntries(); i++) {
571     TObject* pObj=array->At(i);
572     if (pObj) delete pObj;
573   }
574   delete array;
575   return 0;
576 }
void AliHLTComponent::CopyDataType (AliHLTComponentDataType & tgtdt, const AliHLTComponentDataType & srcdt) [protected]
Copy data type structure Copies the value an AliHLTComponentDataType(p.) structure to another one
Parameters:
$\rightarrow$ tgtdt target structure
$\leftarrow$ srcdt source structure
Definition at line 374 of file AliHLTComponent.cxx.
References AliHLTComponentDataType::fID, AliHLTComponentDataType::fOrigin, kAliHLTComponentDataTypefIDsize, and kAliHLTComponentDataTypefOriginSize.
375 {
376   // see header file for function documentation
377   memcpy(&tgtdt.fID[0], &srcdt.fID[0], kAliHLTComponentDataTypefIDsize);
378   memcpy(&tgtdt.fOrigin[0], &srcdt.fOrigin[0], kAliHLTComponentDataTypefOriginSize);
379 }
int AliHLTComponent::CreateEventDoneData (AliHLTComponentEventDoneData edd) [protected]
Insert event-done data information into the output.
Parameters:
edd event-done data information
Definition at line 790 of file AliHLTComponent.cxx.
References HLTWarning.
791 {
792   // see header file for function documentation
793   int iResult=-ENOSYS;
794   //#warning  function not yet implemented
795   HLTWarning("function not yet implemented");
796   return iResult;
797 }
TObject * AliHLTComponent::CreateInputObject (int idx, int bForce = 0) [private]
Create an object from a specified input block.
Parameters:
idx index of the input block
bForce force the retrieval of an object, error messages are suppressed if bForce is not set
Returns: pointer to TObject, caller must delete the object after use
Definition at line 509 of file AliHLTComponent.cxx.
References AliHLTUInt32_t, AliHLTComponentEventData::fBlockCnt, fCurrentEventData, fpInputBlocks, AliHLTComponentBlockData::fPtr, AliHLTComponentBlockData::fSize, AliHLTMessage::GetClass(), HLTDebug, HLTError, and HLTFatal.
Referenced by GetInputObject().
510 {
511   // see header file for function documentation
512   TObject* pObj=NULL;
513   if (fpInputBlocks!=NULL) {
514     if ((UInt_t)idx<fCurrentEventData.fBlockCnt) {
515       if (fpInputBlocks[idx].fPtr) {
516         AliHLTUInt32_t firstWord=*((AliHLTUInt32_t*)fpInputBlocks[idx].fPtr);
517         if (firstWord==fpInputBlocks[idx].fSize-sizeof(AliHLTUInt32_t)) {
518           HLTDebug("create object from block %d size %d", idx, fpInputBlocks[idx].fSize);
519           AliHLTMessage msg(fpInputBlocks[idx].fPtr, fpInputBlocks[idx].fSize);
520           TClass* objclass=msg.GetClass();
521           pObj=msg.ReadObject(objclass);
522           if (pObj && objclass) {
523             HLTDebug("object %p type %s created", pObj, objclass->GetName());
524           } else {
525           }
526         } else {
527           //    } else if (bForce!=0) {
528           HLTError("size missmatch: block size %d, indicated %d", fpInputBlocks[idx].fSize, firstWord+sizeof(AliHLTUInt32_t));
529         }
530       } else {
531         HLTFatal("block descriptor empty");
532       }
533     } else {
534       HLTError("index %d out of range %d", idx, fCurrentEventData.fBlockCnt);
535     }
536   } else {
537     HLTError("no input blocks available");
538   }
539   
540   return pObj;
541 }
void AliHLTComponent::DataType2Text (const AliHLTComponentDataType & type, char output[kAliHLTComponentDataTypefIDsize+kAliHLTComponentDataTypefOriginSize+2]) const [protected]
Helper function to convert the data type to a string.
Definition at line 216 of file AliHLTComponent.cxx.
References AliHLTComponentDataType::fID, AliHLTComponentDataType::fOrigin, kAliHLTComponentDataTypefIDsize, and kAliHLTComponentDataTypefOriginSize.
217 {
218   // see header file for function documentation
219   memset( output, 0, kAliHLTComponentDataTypefIDsize+kAliHLTComponentDataTypefOriginSize+2 );
220   strncat( output, type.fOrigin, kAliHLTComponentDataTypefOriginSize );
221   strcat( output, ":" );
222   strncat( output, type.fID, kAliHLTComponentDataTypefIDsize );
223 }
string AliHLTComponent::DataType2Text (const AliHLTComponentDataType & type) [static]
Helper function to convert the data type to a string.
Definition at line 225 of file AliHLTComponent.cxx.
References AliHLTComponentDataType::fID, AliHLTComponentDataType::fOrigin, kAliHLTComponentDataTypefIDsize, and kAliHLTComponentDataTypefOriginSize.
Referenced by GetFirstInputObject(), and PrintDataTypeContent().
226 {
227   // see header file for function documentation
228   string out("");
229   
230   if (type==kAliHLTVoidDataType) {
231     out="VOID:VOID";
232   } else {
233     // some gymnastics in order to avoid a '0' which is part of either or both
234     // ID and origin terminating the whole string. Unfortunately, string doesn't
235     // stop appending at the '0' if the number of elements to append was 
236     // explicitely specified
237     string tmp("");
238     tmp.append(type.fOrigin, kAliHLTComponentDataTypefOriginSize);
239     out.append(tmp.c_str());
240     out.append(":");
241     tmp="";
242     tmp.append(type.fID, kAliHLTComponentDataTypefIDsize);
243     out.append(tmp.c_str());
244   }
245   return out;
246 }
int AliHLTComponent::Deinit () [virtual]
Clean-up function to terminate data processing. Clean-up of common data structures after data processing. The call is redirected to the internal method DoDeinit(p.) which can be overridden by the child class.
Reimplemented in AliHLTProcessor (p.), AliHLTPHOSDDLDecoderComponent (p.), AliHLTPHOSHistogramProducerComponent (p.), AliHLTPHOSModuleMergerComponent (p.), AliHLTPHOSRawAnalyzerComponent (p.), and AliHLTPHOSRcuHistogramProducerComponent (p.).
Definition at line 191 of file AliHLTComponent.cxx.
References DoDeinit().
Referenced by AliHLT_C_DestroyComponent(), AliHLTProcessor::Deinit(), and AliHLTTask::Deinit().
192 {
193   // see header file for function documentation
194   int iResult=0;
195   iResult=DoDeinit();
196   return iResult;
197 }
int AliHLTComponent::DoDeinit () [protected, virtual]
Default method for the internal clean-up. The method is called by Deinit(p.)
Reimplemented in AliHLTPHOSDDLDecoderComponent (p.), AliHLTPHOSHistogramProducerComponent (p.), AliHLTPHOSModuleMergerComponent (p.), AliHLTPHOSRawAnalyzerComponent (p.), and AliHLTPHOSRcuHistogramProducerComponent (p.).
Definition at line 209 of file AliHLTComponent.cxx.
References fEventCount.
Referenced by Deinit().
210 {
211   // see header file for function documentation
212   fEventCount=0;
213   return 0;
214 }
int AliHLTComponent::DoInit (int argc, const char ** argv) [protected, virtual]
Default method for the internal initialization. The method is called by Init(p.)
Reimplemented in AliHLTPHOSDDLDecoderComponent (p.), AliHLTPHOSHistogramProducerComponent (p.), AliHLTPHOSModuleMergerComponent (p.), AliHLTPHOSRawAnalyzerComponent (p.), and AliHLTPHOSRcuHistogramProducerComponent (p.).
Definition at line 199 of file AliHLTComponent.cxx.
References fEventCount.
Referenced by Init().
200 {
201   // see header file for function documentation
202   if (argc==0 && argv==NULL) {
203     // this is currently just to get rid of the warning "unused parameter"
204   }
205   fEventCount=0;
206   return 0;
207 }
virtual int AliHLTComponent::DoProcessing (const AliHLTComponentEventData & evtData, const AliHLTComponentBlockData * blocks, AliHLTComponentTriggerData & trigData, AliHLTUInt8_t * outputPtr, AliHLTUInt32_t & size, vector< AliHLTComponentBlockData > & outputBlocks, AliHLTComponentEventDoneData *& edd) [pure virtual]
Internal processing of one event. The method is pure virtual and implemented by the child classes
AliHLTProcessor(p.)
AliHLTDataSource(p.)
AliHLTDataSink(p.)
Parameters:
evtData
blocks
trigData
outputPtr
size
outputBlocks out: the output block array is allocated internally
edd
Returns: neg. error code if failed
Implemented in AliHLTDataSink (p.), AliHLTDataSource (p.), and AliHLTProcessor (p.).
Referenced by ProcessEvent().
int AliHLTComponent::EstimateObjectSize (TObject * pObject) const [protected]
Estimate size of a TObject
Parameters:
pObject
Returns: buffer size in byte
Definition at line 781 of file AliHLTComponent.cxx.
782 {
783   // see header file for function documentation
784   if (!pObject) return -EINVAL;
785     AliHLTMessage msg(kMESS_OBJECT);
786     msg.WriteObject(pObject);
787     return msg.Length();  
788 }
void AliHLTComponent::FillBlockData (AliHLTComponentBlockData & blockData) const [protected]
Fill AliHLTComponentBlockData(p.) structure with default values.
Parameters:
blockData reference to data structure
Definition at line 348 of file AliHLTComponent.cxx.
References AliHLTComponentBlockData::fDataType, FillDataType(), FillShmData(), AliHLTComponentBlockData::fOffset, AliHLTComponentBlockData::fPtr, AliHLTComponentBlockData::fShmKey, AliHLTComponentBlockData::fSize, AliHLTComponentBlockData::fSpecification, and AliHLTComponentBlockData::fStructSize.
Referenced by AliHLTPHOSRcuHistogramProducerComponent::DoEvent(), AliHLTPHOSRawAnalyzerComponent::DoEvent(), AliHLTPHOSHistogramProducerComponent::DoEvent(), AliHLTPHOSDDLDecoderComponent::DoEvent(), and InsertOutputBlock().
349 {
350   // see header file for function documentation
351   blockData.fStructSize = sizeof(blockData);
352   FillShmData( blockData.fShmKey );
353   blockData.fOffset = ~(AliHLTUInt32_t)0;
354   blockData.fPtr = NULL;
355   blockData.fSize = 0;
356   FillDataType( blockData.fDataType );
357   blockData.fSpecification = kAliHLTVoidDataSpec;
358 }
void AliHLTComponent::FillDataType (AliHLTComponentDataType & dataType) const [protected]
Fill AliHLTComponentDataType(p.) structure with default values.
Parameters:
dataType reference to data structure
Definition at line 368 of file AliHLTComponent.cxx.
Referenced by FillBlockData().
369 {
370   // see header file for function documentation
371   dataType=kAliHLTAnyDataType;
372 }
void AliHLTComponent::FillEventData (AliHLTComponentEventData & evtData) [static]
helper function to initialize AliHLTComponentEventData(p.) structure
Definition at line 399 of file AliHLTComponent.cxx.
References AliHLTComponentEventData::fStructSize.
Referenced by AliHLTTask::ProcessTask().
400 {
401   // see header file for function documentation
402   memset(&evtData, 0, sizeof(AliHLTComponentEventData));
403   evtData.fStructSize=sizeof(AliHLTComponentEventData);
404 }
void AliHLTComponent::FillShmData (AliHLTComponentShmData & shmData) const [protected]
Fill AliHLTComponentShmData(p.) structure with default values.
Parameters:
shmData reference to data structure
Definition at line 360 of file AliHLTComponent.cxx.
References AliHLTComponentShmData::fShmID, AliHLTComponentShmData::fShmType, and AliHLTComponentShmData::fStructSize.
Referenced by FillBlockData().
361 {
362   // see header file for function documentation
363   shmData.fStructSize = sizeof(shmData);
364   shmData.fShmType = gkAliHLTComponentInvalidShmType;
365   shmData.fShmID = gkAliHLTComponentInvalidShmID;
366 }
int AliHLTComponent::FindInputBlock (const AliHLTComponentBlockData * pBlock) const [private]
Get index in the array of input bocks. Calculate index and check integrety of a block data structure pointer.
Parameters:
pBlock pointer to block data
Returns: index of the block, -ENOENT if no block found
Definition at line 660 of file AliHLTComponent.cxx.
References AliHLTComponentEventData::fBlockCnt, fCurrentEventData, and fpInputBlocks.
661 {
662   // see header file for function documentation
663   int iResult=-ENOENT;
664   if (fpInputBlocks!=NULL) {
665     if (pBlock) {
666       if (pBlock>=fpInputBlocks && pBlock<fpInputBlocks+fCurrentEventData.fBlockCnt) {
667         iResult=(int)(pBlock-fpInputBlocks);
668       }
669     } else {
670       iResult=-EINVAL;
671     }
672   }
673   return iResult;
674 }
int AliHLTComponent::FindInputBlock (const AliHLTComponentDataType & dt, int startIdx = -1) const [private]
Find the first input block of specified data type beginning at index.
Parameters:
dt data type
startIdx index to start the search
Returns: index of the block, -ENOENT if no block found
Definition at line 494 of file AliHLTComponent.cxx.
References AliHLTComponentEventData::fBlockCnt, fCurrentEventData, AliHLTComponentBlockData::fDataType, fpInputBlocks, and kAliHLTAnyDataType.
Referenced by GetFirstInputBlock(), GetFirstInputObject(), GetNextInputBlock(), GetNextInputObject(), and GetSpecification().
495 {
496   // see header file for function documentation
497   int iResult=-ENOENT;
498   if (fpInputBlocks!=NULL) {
499     int idx=startIdx<0?0:startIdx;
500     for ( ; (UInt_t)idx<fCurrentEventData.fBlockCnt && iResult==-ENOENT; idx++) {
501       if (dt == kAliHLTAnyDataType || fpInputBlocks[idx].fDataType == dt) {
502         iResult=idx;
503       }
504     }
505   }
506   return iResult;
507 }
int AliHLTComponent::FindMatchingDataTypes (AliHLTComponent * pConsumer, vector< AliHLTComponentDataType > * tgtList)
Find matching data types between this component and a consumer component. Currently, a component can produce only one type of data. This restriction is most likely to be abolished in the future.
Parameters:
pConsumer a component and consumer of the data produced by this component
tgtList reference to a vector list to receive the matching data types.
Returns: >= 0 success, neg. error code if failed
Definition at line 300 of file AliHLTComponent.cxx.
References GetOutputDataType().
Referenced by AliHLTTask::GetNofMatchingDataTypes().
301 {
302   // see header file for function documentation
303   int iResult=0;
304   if (pConsumer) {
305     vector<AliHLTComponentDataType> ctlist;
306     ((AliHLTComponent*)pConsumer)->GetInputDataTypes(ctlist);
307     vector<AliHLTComponentDataType>::iterator type=ctlist.begin();
308     //AliHLTComponentDataType ouptdt=GetOutputDataType();
309     //PrintDataTypeContent(ouptdt, "publisher \'%s\'");
310     while (type!=ctlist.end() && iResult==0) {
311       //PrintDataTypeContent((*type), "consumer \'%s\'");
312       if ((*type)==GetOutputDataType() ||
313           (*type)==kAliHLTAnyDataType) {
314         if (tgtList) tgtList->push_back(*type);
315         iResult++;
316         // this loop has to be changed in case of multiple output types
317         break;
318       }
319       type++;
320     }
321   } else {
322     iResult=-EINVAL;
323   }
324   return iResult;
325 }
virtual const char* AliHLTComponent::GetComponentID () [pure virtual]
Get the id of the component. Each component is identified by a unique id. The function is pure virtual and must be implemented by the child class.
Returns: component id (string)
Implemented in AliHLTPHOSDDLDecoderComponent (p.), AliHLTPHOSHistogramProducerComponent (p.), AliHLTPHOSModuleMergerComponent (p.), AliHLTPHOSRawAnalyzerComponent (p.), AliHLTPHOSRawAnalyzerCrudeComponent (p.), AliHLTPHOSRawAnalyzerPeakFinderComponent (p.), and AliHLTPHOSRcuHistogramProducerComponent (p.).
Referenced by AliHLTDataSource::DoProcessing(), AliHLTTask::PrintStatus(), ProcessEvent(), AliHLTTask::ProcessTask(), AliHLTComponentHandler::RegisterComponent(), and AliHLTDataBuffer::SetConsumer().
virtual TComponentType AliHLTComponent::GetComponentType () [pure virtual]
Get the type of the component. The function is pure virtual and must be implemented by the child class.
Returns: component type id
Implemented in AliHLTDataSink (p.), AliHLTDataSource (p.), and AliHLTProcessor (p.).
Referenced by AliHLTSystem::InitBenchmarking(), and AliHLTTask::ProcessTask().
AliHLTComponentDataType AliHLTComponent::GetDataType (const TObject * pObject = NULL) [protected]
Get data type of an input block. Get data type of the object previously fetched via GetFirstInputObject/NextInputObject or the last one if no object specified.
Parameters:
pObject pointer to TObject
Returns: data specification, kAliHLTVoidDataSpec if failed
Definition at line 578 of file AliHLTComponent.cxx.
References ALIHLTCOMPONENT_BASE_STOPWATCH, AliHLTComponentEventData::fBlockCnt, fCurrentEventData, AliHLTComponentBlockData::fDataType, fpInputBlocks, fpInputObjects, HLTError, and HLTFatal.
579 {
580   // see header file for function documentation
581   ALIHLTCOMPONENT_BASE_STOPWATCH();
582   AliHLTComponentDataType dt=kAliHLTVoidDataType;
583   int idx=fCurrentInputBlock;
584   if (pObject) {
585     if (fpInputObjects==NULL || (idx=fpInputObjects->IndexOf(pObject))>=0) {
586     } else {
587       HLTError("unknown object %p", pObject);
588     }
589   }
590   if (idx>=0) {
591     if ((UInt_t)idx<fCurrentEventData.fBlockCnt) {
592       dt=fpInputBlocks[idx].fDataType;
593     } else {
594       HLTFatal("severe internal error, index out of range");
595     }
596   }
597   return dt;
598 }
int AliHLTComponent::GetEventCount () const [protected]
Get event number.
Returns: value of the internal event counter
Definition at line 424 of file AliHLTComponent.cxx.
425 {
426   // see header file for function documentation
427   return fEventCount;
428 }
int AliHLTComponent::GetEventDoneData (unsigned long size, AliHLTComponentEventDoneData ** edd) [protected]
Fill the EventDoneData structure. The method is redirected to a function provided by the current framework. Function pointers are transferred via the AliHLTComponentEnvironment(p.) structure.
Definition at line 292 of file AliHLTComponent.cxx.
References fEnvironment, AliHLTComponentEnvironment::fGetEventDoneDataFunc, and AliHLTComponentEnvironment::fParam.
293 {
294   // see header file for function documentation
295   if (fEnvironment.fGetEventDoneDataFunc)
296     return (*fEnvironment.fGetEventDoneDataFunc)(fEnvironment.fParam, fCurrentEvent, size, edd );
297   return -ENOSYS;
298 }
const AliHLTComponentBlockData * AliHLTComponent::GetFirstInputBlock (const char * dtID, const char * dtOrigin) [protected]
Get the first block of a specific data type from the input data. The method looks for the first block of type specified by the ID and Origin strings in the input stream. It is intended to be used within the high-level interface.
 Note: THE BLOCK DESCRIPTOR MUST NOT BE DELETED by the caller.
Parameters:
dtID data type ID of the block
dtOrigin data type origin of the block
Returns: pointer to AliHLTComponentBlockData(p.)
Definition at line 637 of file AliHLTComponent.cxx.
References ALIHLTCOMPONENT_BASE_STOPWATCH, GetFirstInputBlock(), and SetDataType().
639 {
640   // see header file for function documentation
641   ALIHLTCOMPONENT_BASE_STOPWATCH();
642   AliHLTComponentDataType dt;
643   SetDataType(dt, dtID, dtOrigin);
644   return GetFirstInputBlock(dt);
645 }
const AliHLTComponentBlockData * AliHLTComponent::GetFirstInputBlock (const AliHLTComponentDataType & dt = kAliHLTAnyDataType) [protected]
Get the first block of a specific data type from the input data. The method looks for the first block of type dt in the input stream. It is intended to be used within the high-level interface.
 Note: THE BLOCK DESCRIPTOR MUST NOT BE DELETED by the caller.
Parameters:
dt data type of the block
Returns: pointer to AliHLTComponentBlockData(p.)
Definition at line 622 of file AliHLTComponent.cxx.
References ALIHLTCOMPONENT_BASE_STOPWATCH, fClassName, FindInputBlock(), fpInputBlocks, and fSearchDataType.
Referenced by GetFirstInputBlock().
623 {
624   // see header file for function documentation
625   ALIHLTCOMPONENT_BASE_STOPWATCH();
626   fSearchDataType=dt;
627   fClassName.clear();
628   int idx=FindInputBlock(fSearchDataType, 0);
629   const AliHLTComponentBlockData* pBlock=NULL;
630   if (idx>=0) {
631     // check for fpInputBlocks pointer done in FindInputBlock
632     pBlock=&fpInputBlocks[idx];
633   }
634   return pBlock;
635 }
const TObject * AliHLTComponent::GetFirstInputObject (const char * dtID, const char * dtOrigin, const char * classname = NULL, int bForce = 0) [protected]
Get the first object of a specific data type from the input data. The hight-level methods provide functionality to transfer ROOT data structures which inherit from TObject. The method looks for the first ROOT object of type specified by the ID and Origin strings in the input stream. If also the class name is provided, the object is checked for the right class type. The input data block needs a certain structure, namely the buffer size as first word. If the cross check fails, the retrieval is silently abondoned, unless the bForce parameter is set.
 Note: THE OBJECT MUST NOT BE DELETED by the caller.
Parameters:
dtID data type ID of the object
dtOrigin data type origin of the object
classname class name of the object
bForce force the retrieval of an object, error messages are suppressed if bForce is not set
Returns: pointer to TObject, NULL if no objects of specified type available
Definition at line 467 of file AliHLTComponent.cxx.
References ALIHLTCOMPONENT_BASE_STOPWATCH, GetFirstInputObject(), and SetDataType().
471 {
472   // see header file for function documentation
473   ALIHLTCOMPONENT_BASE_STOPWATCH();
474   AliHLTComponentDataType dt;
475   SetDataType(dt, dtID, dtOrigin);
476   return GetFirstInputObject(dt, classname, bForce);
477 }
const TObject * AliHLTComponent::GetFirstInputObject (const AliHLTComponentDataType & dt = kAliHLTAnyDataType, const char * classname = NULL, int bForce = 0) [protected]
Get the first object of a specific data type from the input data. The hight-level methods provide functionality to transfer ROOT data structures which inherit from TObject. The method looks for the first ROOT object of type dt in the input stream. If also the class name is provided, the object is checked for the right class type. The input data block needs a certain structure, namely the buffer size as first word. If the cross check fails, the retrieval is silently abondoned, unless the bForce parameter is set.
 Note: THE OBJECT MUST NOT BE DELETED by the caller.
Parameters:
dt data type of the object
classname class name of the object
bForce force the retrieval of an object, error messages are suppressed if bForce is not set
Returns: pointer to TObject, NULL if no objects of specified type available
Definition at line 446 of file AliHLTComponent.cxx.
References ALIHLTCOMPONENT_BASE_STOPWATCH, DataType2Text(), fClassName, fCurrentInputBlock, FindInputBlock(), fSearchDataType, GetInputObject(), and HLTDebug.
Referenced by GetFirstInputObject().
449 {
450   // see header file for function documentation
451   ALIHLTCOMPONENT_BASE_STOPWATCH();
452   fSearchDataType=dt;
453   if (classname) fClassName=classname;
454   else fClassName.clear();
455   int idx=FindInputBlock(fSearchDataType, 0);
456   HLTDebug("found block %d when searching for data type %s", idx, DataType2Text(dt).c_str());
457   TObject* pObj=NULL;
458   if (idx>=0) {
459     if ((pObj=GetInputObject(idx, fClassName.c_str(), bForce))!=NULL) {
460       fCurrentInputBlock=idx;
461     } else {
462     }
463   }
464   return pObj;
465 }
const AliHLTComponentBlockData* AliHLTComponent::GetInputBlock (int index) [protected]
Get input block by index.
 Note: THE BLOCK DESCRIPTOR MUST NOT BE DELETED by the caller.
Returns: pointer to AliHLTComponentBlockData(p.), NULL if index out of range
virtual void AliHLTComponent::GetInputDataTypes (vector< AliHLTComponentDataType > &) [pure virtual]
Get the input data types of the component. The function is pure virtual and must be implemented by the child class.
Returns: list of data types in the vector reference
Implemented in AliHLTDataSource (p.).
TObject * AliHLTComponent::GetInputObject (int idx, const char * classname = NULL, int bForce = 0) [private]
Get input object Get object from the input block list. The methods first checks whether the object was already created. If not, it is created by CreateInputObject(p.) and inserted into the list of objects.
Parameters:
idx index in the input block list
classname name of the class, object is checked for correct class name if set
bForce force the retrieval of an object, error messages are suppressed if bForce is not set
Returns: pointer to TObject
Definition at line 543 of file AliHLTComponent.cxx.
References CreateInputObject(), AliHLTComponentEventData::fBlockCnt, fCurrentEventData, fpInputObjects, and HLTFatal.
Referenced by GetFirstInputObject(), and GetNextInputObject().
544 {
545   // see header file for function documentation
546   if (fpInputObjects==NULL) {
547     fpInputObjects=new TObjArray(fCurrentEventData.fBlockCnt);
548   }
549   TObject* pObj=NULL;
550   if (fpInputObjects) {
551     pObj=fpInputObjects->At(idx);
552     if (pObj==NULL) {
553       pObj=CreateInputObject(idx, bForce);
554       if (pObj) {
555         fpInputObjects->AddAt(pObj, idx);
556       }
557     }
558   } else {
559     HLTFatal("memory allocation failed: TObjArray of size %d", fCurrentEventData.fBlockCnt);
560   }
561   return pObj;
562 }
const AliHLTComponentBlockData * AliHLTComponent::GetNextInputBlock () [protected]
Get the next block of a specific data type from the input data. The method looks for the next block of type and class specified to the previous GetFirstInputBlock(p.) call. To be used within the high-level interface.
 Note: THE BLOCK DESCRIPTOR MUST NOT BE DELETED by the caller.
Definition at line 647 of file AliHLTComponent.cxx.
References ALIHLTCOMPONENT_BASE_STOPWATCH, fCurrentInputBlock, FindInputBlock(), fpInputBlocks, and fSearchDataType.
648 {
649   // see header file for function documentation
650   ALIHLTCOMPONENT_BASE_STOPWATCH();
651   int idx=FindInputBlock(fSearchDataType, fCurrentInputBlock+1);
652   const AliHLTComponentBlockData* pBlock=NULL;
653   if (idx>=0) {
654     // check for fpInputBlocks pointer done in FindInputBlock
655     pBlock=&fpInputBlocks[idx];
656   }
657   return pBlock;
658 }
const TObject * AliHLTComponent::GetNextInputObject (int bForce = 0) [protected]
Get the next object of a specific data type from the input data. The hight-level methods provide functionality to transfer ROOT data structures which inherit from TObject. The method looks for the next ROOT object of type and class specified to the previous GetFirstInputObject(p.) call.
 Note: THE OBJECT MUST NOT BE DELETED by the caller.
Parameters:
bForce force the retrieval of an object, error messages are suppressed if bForce is not set
Returns: pointer to TObject, NULL if no more objects available
Definition at line 479 of file AliHLTComponent.cxx.
References ALIHLTCOMPONENT_BASE_STOPWATCH, fClassName, fCurrentInputBlock, FindInputBlock(), fSearchDataType, and GetInputObject().
480 {
481   // see header file for function documentation
482   ALIHLTCOMPONENT_BASE_STOPWATCH();
483   int idx=FindInputBlock(fSearchDataType, fCurrentInputBlock+1);
484   //HLTDebug("found block %d when searching for data type %s", idx, DataType2Text(fSearchDataType).c_str());
485   TObject* pObj=NULL;
486   if (idx>=0) {
487     if ((pObj=GetInputObject(idx, fClassName.c_str(), bForce))!=NULL) {
488       fCurrentInputBlock=idx;
489     }
490   }
491   return pObj;
492 }
int AliHLTComponent::GetNumberOfInputBlocks () const [protected]
Get the number of input blocks.
Returns: number of input blocks
Definition at line 437 of file AliHLTComponent.cxx.
References AliHLTComponentEventData::fBlockCnt, fCurrentEventData, and fpInputBlocks.
438 {
439   // see header file for function documentation
440   if (fpInputBlocks!=NULL) {
441     return fCurrentEventData.fBlockCnt;
442   }
443   return 0;
444 }
virtual void AliHLTComponent::GetOutputDataSize (unsigned long & constBase, double & inputMultiplier) [pure virtual]
Get a ratio by how much the data volume is shrinked or enhanced. The function is pure virtual and must be implemented by the child class.
Parameters:
constBase return: additive part, independent of the input data volume
inputMultiplier return: multiplication ratio
Returns: values in the reference variables
Implemented in AliHLTDataSink (p.), AliHLTPHOSDDLDecoderComponent (p.), AliHLTPHOSHistogramProducerComponent (p.), AliHLTPHOSModuleMergerComponent (p.), AliHLTPHOSRawAnalyzerComponent (p.), and AliHLTPHOSRcuHistogramProducerComponent (p.).
Referenced by AliHLT_C_GetOutputSize(), and AliHLTTask::ProcessTask().
virtual AliHLTComponentDataType AliHLTComponent::GetOutputDataType () [pure virtual]
Get the output data type of the component. The function is pure virtual and must be implemented by the child class.
Returns: output data type
Implemented in AliHLTDataSink (p.), AliHLTPHOSDDLDecoderComponent (p.), AliHLTPHOSHistogramProducerComponent (p.), AliHLTPHOSModuleMergerComponent (p.), AliHLTPHOSRawAnalyzerComponent (p.), and AliHLTPHOSRcuHistogramProducerComponent (p.).
Referenced by AliHLT_C_GetOutputDataType(), FindMatchingDataTypes(), and MakeOutputDataBlockList().
AliHLTUInt32_t AliHLTComponent::GetSpecification (const AliHLTComponentBlockData * pBlock = NULL) [protected]
Get data specification of an input block. Get data specification of the input bblock previously fetched via GetFirstInputObject/NextInputObject or the last one if no block specified.
Parameters:
pBlock pointer to input block
Returns: data specification, kAliHLTVoidDataSpec if failed
Definition at line 676 of file AliHLTComponent.cxx.
References ALIHLTCOMPONENT_BASE_STOPWATCH, AliHLTUInt32_t, FindInputBlock(), fpInputBlocks, fpInputObjects, AliHLTComponentBlockData::fSpecification, and HLTError.
677 {
678   // see header file for function documentation
679   ALIHLTCOMPONENT_BASE_STOPWATCH();
680   AliHLTUInt32_t iSpec=kAliHLTVoidDataSpec;
681   int idx=fCurrentInputBlock;
682   if (pBlock) {
683     if (fpInputObjects==NULL || (idx=FindInputBlock(pBlock))>=0) {
684     } else {
685       HLTError("unknown Block %p", pBlock);
686     }
687   }
688   if (idx>=0) {
689     // check for fpInputBlocks pointer done in FindInputBlock
690     iSpec=fpInputBlocks[idx].fSpecification;
691   }
692   return iSpec;
693 }
AliHLTUInt32_t AliHLTComponent::GetSpecification (const TObject * pObject = NULL) [protected]
Get data specification of an input block. Get data specification of the object previously fetched via GetFirstInputObject/NextInputObject or the last one if no object specified.
Parameters:
pObject pointer to TObject
Returns: data specification, kAliHLTVoidDataSpec if failed
Definition at line 600 of file AliHLTComponent.cxx.
References ALIHLTCOMPONENT_BASE_STOPWATCH, AliHLTUInt32_t, AliHLTComponentEventData::fBlockCnt, fCurrentEventData, fpInputBlocks, fpInputObjects, AliHLTComponentBlockData::fSpecification, HLTError, and HLTFatal.
601 {
602   // see header file for function documentation
603   ALIHLTCOMPONENT_BASE_STOPWATCH();
604   AliHLTUInt32_t iSpec=kAliHLTVoidDataSpec;
605   int idx=fCurrentInputBlock;
606   if (pObject) {
607     if (fpInputObjects==NULL || (idx=fpInputObjects->IndexOf(pObject))>=0) {
608     } else {
609       HLTError("unknown object %p", pObject);
610     }
611   }
612   if (idx>=0) {
613     if ((UInt_t)idx<fCurrentEventData.fBlockCnt) {
614       iSpec=fpInputBlocks[idx].fSpecification;
615     } else {
616       HLTFatal("severe internal error, index out of range");
617     }
618   }
619   return iSpec;
620 }
int AliHLTComponent::IncrementEventCounter () [private]
Increment the internal event counter. To be used by the friend classes AliHLTProcessor(p.), AliHLTDataSource(p.) and AliHLTDataSink(p.).
Returns: new value of the internal event counter
Definition at line 430 of file AliHLTComponent.cxx.
References fEventCount.
Referenced by ProcessEvent().
431 {
432   // see header file for function documentation
433   if (fEventCount>=0) fEventCount++;
434   return fEventCount;
435 }
int AliHLTComponent::Init (AliHLTComponentEnvironment * environ, void * environParam, int argc, const char ** argv) [virtual]
Init function to prepare data processing. Initialization of common data structures for a sequence of events. The call is redirected to the internal method DoInit(p.) which can be overridden by the child class.
 During Init also the environment structure is passed to the component.
Parameters:
environ environment pointer with environment dependend function calls
environParam additionel parameter for function calls, the pointer is passed as it is
argc size of the argument array
argv agument array for component initialization
Reimplemented in AliHLTProcessor (p.).
Definition at line 135 of file AliHLTComponent.cxx.
References AliHLTComponentLogSeverity, DoInit(), fEnvironment, fEventCount, AliHLTComponentEnvironment::fParam, HLTError, and AliHLTLogging::SetLocalLoggingLevel().
Referenced by AliHLTComponentHandler::CreateComponent(), and AliHLTProcessor::Init().
136 {
137   // see header file for function documentation
138   int iResult=0;
139   if (environ) {
140     memcpy(&fEnvironment, environ, sizeof(AliHLTComponentEnvironment));
141     fEnvironment.fParam=environParam;
142   }
143   const char** pArguments=NULL;
144   int iNofChildArgs=0;
145   TString argument="";
146   int bMissingParam=0;
147   if (argc>0) {
148     pArguments=new const char*[argc];
149     if (pArguments) {
150       for (int i=0; i<argc && iResult>=0; i++) {
151         argument=argv[i];
152         if (argument.IsNull()) continue;
153 
154         // benchmark
155         if (argument.CompareTo("benchmark")==0) {
156 
157           // loglevel
158         } else if (argument.CompareTo("loglevel")==0) {
159           if ((bMissingParam=(++i>=argc))) break;
160           TString parameter(argv[i]);
161           parameter.Remove(TString::kLeading, ' '); // remove all blanks
162           if (parameter.BeginsWith("0x") &&
163               parameter.Replace(0,2,"",0).IsHex()) {
164             AliHLTComponentLogSeverity loglevel=kHLTLogNone;
165             sscanf(parameter.Data(),"%x", (unsigned int*)&loglevel);
166             SetLocalLoggingLevel(loglevel);
167           } else {
168             HLTError("wrong parameter for argument %s, hex number expected", argument.Data());
169             iResult=-EINVAL;
170           }
171         } else {
172           pArguments[iNofChildArgs++]=argv[i];
173         }
174       }
175     } else {
176       iResult=-ENOMEM;
177     }
178   }
179   if (bMissingParam) {
180     HLTError("missing parameter for argument %s", argument.Data());
181     iResult=-EINVAL;
182   }
183   if (iResult>=0) {
184     iResult=DoInit(iNofChildArgs, pArguments);
185   }
186   if (iResult>=0) fEventCount=0;
187   if (pArguments) delete [] pArguments;
188   return iResult;
189 }
int AliHLTComponent::InsertOutputBlock (void * pBuffer, int iSize, const AliHLTComponentDataType & dt, AliHLTUInt32_t spec) [private]
Insert a buffer into the output block stream. This is the only method to insert blocks into the output stream, called from all types of the Pushback method. The actual data might have been written to the output buffer already. In that case NULL can be provided as buffer, only the block descriptor will be build.
Parameters:
pBuffer pointer to buffer
iSize size of the buffer in byte
dt data type
spec data specification
Definition at line 745 of file AliHLTComponent.cxx.
References AliHLTUInt8_t, AliHLTComponentBlockData::fDataType, FillBlockData(), AliHLTComponentBlockData::fOffset, fOutputBlocks, fOutputBufferFilled, fOutputBufferSize, fpOutputBuffer, AliHLTComponentBlockData::fPtr, AliHLTComponentBlockData::fSize, AliHLTComponentBlockData::fSpecification, and HLTError.
Referenced by PushBack().
746 {
747   // see header file for function documentation
748   int iResult=0;
749   if (pBuffer) {
750     if (fpOutputBuffer && iSize<=(int)(fOutputBufferSize-fOutputBufferFilled)) {
751       AliHLTUInt8_t* pTgt=fpOutputBuffer+fOutputBufferFilled;
752       AliHLTComponentBlockData bd;
753       FillBlockData( bd );
754       bd.fOffset        = fOutputBufferFilled;
755       bd.fPtr           = pTgt;
756       bd.fSize          = iSize;
757       bd.fDataType      = dt;
758       bd.fSpecification = spec;
759       if (pBuffer!=NULL && pBuffer!=pTgt) {
760         memcpy(pTgt, pBuffer, iSize);
761         //AliHLTUInt32_t firstWord=*((AliHLTUInt32_t*)pBuffer); 
762         //HLTDebug("copy %d bytes from %p to output buffer %p, first word %#x", iSize, pBuffer, pTgt, firstWord);
763       }
764       fOutputBufferFilled+=bd.fSize;
765       fOutputBlocks.push_back( bd );
766       //HLTDebug("buffer inserted to output: size %d data type %s spec %#x", iSize, DataType2Text(dt).c_str(), spec);
767     } else {
768       if (fpOutputBuffer) {
769         HLTError("too little space in output buffer: %d, required %d", fOutputBufferSize-fOutputBufferFilled, iSize);
770       } else {
771         HLTError("output buffer not available");
772       }
773       iResult=-ENOSPC;
774     }
775   } else {
776     iResult=-EINVAL;
777   }
778   return iResult;
779 }
int AliHLTComponent::MakeOutputDataBlockList (const vector< AliHLTComponentBlockData > & blocks, AliHLTUInt32_t * blockCount, AliHLTComponentBlockData ** outputBlocks) [protected]
Helper function to create a monolithic BlockData description block out of a list BlockData descriptors. For convenience, inside the interface vector lists are used, to make the interface pure C style, monilithic blocks must be exchanged. The method is redirected to a function provided by the current framework. Function pointers are transferred via the AliHLTComponentEnvironment(p.) structure.
Definition at line 258 of file AliHLTComponent.cxx.
References AliHLTUInt32_t, AllocMemory(), AliHLTComponentBlockData::fDataType, and GetOutputDataType().
Referenced by ProcessEvent().
260 {
261   // see header file for function documentation
262     if ( blockCount==NULL || outputBlocks==NULL )
263         return -EFAULT;
264     AliHLTUInt32_t count = blocks.size();
265     if ( !count )
266         {
267         *blockCount = 0;
268         *outputBlocks = NULL;
269         return 0;
270         }
271     *outputBlocks = reinterpret_cast<AliHLTComponentBlockData*>( AllocMemory( sizeof(AliHLTComponentBlockData)*count ) );
272     if ( !*outputBlocks )
273         return -ENOMEM;
274     for ( unsigned long i = 0; i < count; i++ ) {
275         (*outputBlocks)[i] = blocks[i];
276         if (blocks[i].fDataType==kAliHLTAnyDataType) {
277           (*outputBlocks)[i].fDataType=GetOutputDataType();
278           /* data type was set to the output data type by the PubSub AliRoot
279              Wrapper component, if data type of the block was ********:****.
280              Now handled by the component base class in order to have same
281              behavior when running embedded in AliRoot
282           memset((*outputBlocks)[i].fDataType.fID, '*', kAliHLTComponentDataTypefIDsize);
283           memset((*outputBlocks)[i].fDataType.fOrigin, '*', kAliHLTComponentDataTypefOriginSize);
284           */
285         }
286     }
287     *blockCount = count;
288     return 0;
289 
290 }
AliHLTComponent & AliHLTComponent::operator= (const AliHLTComponent &)
not a valid assignment op, but defined according to effective C++ style
Definition at line 101 of file AliHLTComponent.cxx.
References HLTFatal.
102 { 
103   // see header file for class documentation
104   HLTFatal("assignment operator untested");
105   return *this;
106 }
void AliHLTComponent::PrintComponentDataTypeInfo (const AliHLTComponentDataType & dt)
Print info on an AliHLTComponentDataType(p.) structure This is just a helper function to examine an AliHLTComponentDataType(p.) structur.
Definition at line 406 of file AliHLTComponent.cxx.
References AliHLTComponentDataType::fID, AliHLTComponentDataType::fOrigin, AliHLTComponentDataType::fStructSize, kHLTLogNone, and AliHLTLogging::Message().
407 {
408   // see header file for function documentation
409   TString msg;
410   msg.Form("AliHLTComponentDataType(%d): ID=\"", dt.fStructSize);
411   for ( int i = 0; i < kAliHLTComponentDataTypefIDsize; i++ ) {
412    if (dt.fID[i]!=0) msg+=dt.fID[i];
413    else msg+="\\0";
414   }
415   msg+="\" Origin=\"";
416   for ( int i = 0; i < kAliHLTComponentDataTypefOriginSize; i++ ) {
417    if (dt.fOrigin[i]!=0) msg+=dt.fOrigin[i];
418    else msg+="\\0";
419   }
420   msg+="\"";
421   AliHLTLogging::Message(NULL, kHLTLogNone, NULL , NULL, msg.Data());
422 }
void AliHLTComponent::PrintDataTypeContent (AliHLTComponentDataType & dt, const char * format = NULL) const
Helper function to print content of data type.
Definition at line 327 of file AliHLTComponent.cxx.
References DataType2Text(), AliHLTComponentDataType::fID, AliHLTComponentDataType::fOrigin, and HLTMessage.
328 {
329   // see header file for function documentation
330   const char* fmt="publisher \'%s\'";
331   if (format) fmt=format;
332   HLTMessage(fmt, (DataType2Text(dt)).c_str());
333   HLTMessage("%x %x %x %x %x %x %x %x : %x %x %x %x", 
334              dt.fID[0],
335              dt.fID[1],
336              dt.fID[2],
337              dt.fID[3],
338              dt.fID[4],
339              dt.fID[5],
340              dt.fID[6],
341              dt.fID[7],
342              dt.fOrigin[0],
343              dt.fOrigin[1],
344              dt.fOrigin[2],
345              dt.fOrigin[3]);
346 }
int AliHLTComponent::ProcessEvent (const AliHLTComponentEventData & evtData, const AliHLTComponentBlockData * blocks, AliHLTComponentTriggerData & trigData, AliHLTUInt8_t * outputPtr, AliHLTUInt32_t & size, AliHLTUInt32_t & outputBlockCnt, AliHLTComponentBlockData *& outputBlocks, AliHLTComponentEventDoneData *& edd)
Processing of one event. The method is the entrance of the event processing. The parameters are cached for uses with the high-level interface and the DoProcessing implementation is called.
Parameters:
evtData
blocks
trigData
outputPtr
size
outputBlockCnt out: size of the output block array, set by the component
outputBlocks out: the output block array is allocated internally
edd
Returns: neg. error code if failed
Definition at line 799 of file AliHLTComponent.cxx.
References ALIHLTCOMPONENT_BASE_STOPWATCH, ALIHLTCOMPONENT_DA_STOPWATCH, CleanupInputObjects(), DoProcessing(), fCurrentEvent, fCurrentEventData, fCurrentInputBlock, AliHLTComponentEventData::fEventID, fOutputBlocks, fOutputBufferFilled, fOutputBufferSize, fpInputBlocks, fpOutputBuffer, fSearchDataType, GetComponentID(), HLTError, HLTFatal, IncrementEventCounter(), and MakeOutputDataBlockList().
Referenced by AliHLT_C_ProcessEvent(), and AliHLTTask::ProcessTask().
807 {
808   // see header file for function documentation
809   ALIHLTCOMPONENT_BASE_STOPWATCH();
810   int iResult=0;
811   fCurrentEvent=evtData.fEventID;
812   fCurrentEventData=evtData;
813   fpInputBlocks=blocks;
814   fCurrentInputBlock=-1;
815   fSearchDataType=kAliHLTAnyDataType;
816   fpOutputBuffer=outputPtr;
817   fOutputBufferSize=size;
818   fOutputBufferFilled=0;
819   fOutputBlocks.clear();
820   
821   vector<AliHLTComponentBlockData> blockData;
822   { // dont delete, sets the scope for the stopwatch guard
823     ALIHLTCOMPONENT_DA_STOPWATCH();
824     iResult=DoProcessing(evtData, blocks, trigData, outputPtr, size, blockData, edd);
825   } // end of the scope of the stopwatch guard
826   if (iResult>=0) {
827     if (fOutputBlocks.size()>0) {
828       //HLTDebug("got %d block(s) via high level interface", fOutputBlocks.size());
829       if (blockData.size()>0) {
830         HLTError("low level and high interface must not be mixed; use PushBack methods to insert data blocks");
831         iResult=-EFAULT;
832       } else {
833         iResult=MakeOutputDataBlockList(fOutputBlocks, &outputBlockCnt, &outputBlocks);
834         size=fOutputBufferFilled;
835       }
836     } else {
837       iResult=MakeOutputDataBlockList(blockData, &outputBlockCnt, &outputBlocks);
838     }
839     if (iResult<0) {
840       HLTFatal("component %s (%p): can not convert output block descriptor list", GetComponentID(), this);
841     }
842   }
843   if (iResult<0) {
844     outputBlockCnt=0;
845     outputBlocks=NULL;
846   }
847   CleanupInputObjects();
848   IncrementEventCounter();
849   return iResult;
850 }
int AliHLTComponent::PushBack (void * pBuffer, int iSize, const char * dtID, const char * dtOrigin, AliHLTUInt32_t spec = kAliHLTVoidDataSpec) [protected]
Insert an object into the output.
Parameters:
pBuffer pointer to buffer
iSize size of the buffer
dtID data type ID of the object
dtOrigin data type origin of the object
spec data specification
Returns: neg. error code if failed
Definition at line 736 of file AliHLTComponent.cxx.
References ALIHLTCOMPONENT_BASE_STOPWATCH, PushBack(), and SetDataType().
737 {
738   // see header file for function documentation
739   ALIHLTCOMPONENT_BASE_STOPWATCH();
740   AliHLTComponentDataType dt;
741   SetDataType(dt, dtID, dtOrigin);
742   return PushBack(pBuffer, iSize, dt, spec);
743 }
int AliHLTComponent::PushBack (void * pBuffer, int iSize, const AliHLTComponentDataType & dt, AliHLTUInt32_t spec = kAliHLTVoidDataSpec) [protected]
Insert an object into the output.
Parameters:
pBuffer pointer to buffer
iSize size of the buffer
dt data type of the object
spec data specification
Returns: neg. error code if failed
Definition at line 729 of file AliHLTComponent.cxx.
References ALIHLTCOMPONENT_BASE_STOPWATCH, and InsertOutputBlock().
730 {
731   // see header file for function documentation
732   ALIHLTCOMPONENT_BASE_STOPWATCH();
733   return InsertOutputBlock(pBuffer, iSize, dt, spec);
734 }
int AliHLTComponent::PushBack (TObject * pObject, const char * dtID, const char * dtOrigin, AliHLTUInt32_t spec = kAliHLTVoidDataSpec) [protected]
Insert an object into the output.
Parameters:
pObject pointer to root object
dtID data type ID of the object
dtOrigin data type origin of the object
spec data specification
Returns: neg. error code if failed
Definition at line 720 of file AliHLTComponent.cxx.
References ALIHLTCOMPONENT_BASE_STOPWATCH, PushBack(), and SetDataType().
721 {
722   // see header file for function documentation
723   ALIHLTCOMPONENT_BASE_STOPWATCH();
724   AliHLTComponentDataType dt;
725   SetDataType(dt, dtID, dtOrigin);
726   return PushBack(pObject, dt, spec);
727 }
int AliHLTComponent::PushBack (TObject * pObject, const AliHLTComponentDataType & dt, AliHLTUInt32_t spec = kAliHLTVoidDataSpec) [protected]
Insert an object into the output.
Parameters:
pObject pointer to root object
dt data type of the object
spec data specification
Returns: neg. error code if failed
Definition at line 695 of file AliHLTComponent.cxx.
References ALIHLTCOMPONENT_BASE_STOPWATCH, HLTDebug, HLTError, InsertOutputBlock(), and AliHLTMessage::SetLength().
Referenced by PushBack().
696 {
697   // see header file for function documentation
698   ALIHLTCOMPONENT_BASE_STOPWATCH();
699   int iResult=0;
700   if (pObject) {
701     AliHLTMessage msg(kMESS_OBJECT);
702     msg.WriteObject(pObject);
703     Int_t iMsgLength=msg.Length();
704     if (iMsgLength>0) {
705       msg.SetLength(); // sets the length to the first (reserved) word
706       iResult=InsertOutputBlock(msg.Buffer(), iMsgLength, dt, spec);
707       if (iResult>=0) {
708         HLTDebug("object %s (%p) size %d inserted to output", pObject->ClassName(), pObject, iMsgLength);
709       }
710     } else {
711       HLTError("object serialization failed for object %p", pObject);
712       iResult=-ENOMSG;
713     }
714   } else {
715     iResult=-EINVAL;
716   }
717   return iResult;
718 }
void AliHLTComponent::SetDataType (AliHLTComponentDataType & tgtdt, const char * id, const char * origin) [protected]
Set the ID and Origin of an AliHLTComponentDataType(p.) structure. The function sets the fStructureSize member and copies the strings to the ID and Origin. Only characters from the valid part of the string are copied, the rest is fille with 0's. Please note that the fID and fOrigin members are not strings, just arrays of chars of size kAliHLTComponentDataTypefIDsize(p.) and kAliHLTComponentDataTypefOriginSize(p.) respectively and not necessarily with a terminating zero.
Parameters:
tgtdt target data type structure
id ID string
origin Origin string
Definition at line 381 of file AliHLTComponent.cxx.
References AliHLTComponentDataType::fID, AliHLTComponentDataType::fOrigin, AliHLTComponentDataType::fStructSize, HLTWarning, kAliHLTComponentDataTypefIDsize, and kAliHLTComponentDataTypefOriginSize.
Referenced by GetFirstInputBlock(), GetFirstInputObject(), and PushBack().
382 {
383   // see header file for function documentation
384   tgtdt.fStructSize = sizeof(AliHLTComponentDataType);
385   memset(&tgtdt.fID[0], 0, kAliHLTComponentDataTypefIDsize);
386   memset(&tgtdt.fOrigin[0], 0, kAliHLTComponentDataTypefOriginSize);
387 
388   if ((int)strlen(id)>kAliHLTComponentDataTypefIDsize) {
389     HLTWarning("data type id %s is too long, truncated to %d", id, kAliHLTComponentDataTypefIDsize);
390   }
391   strncpy(&tgtdt.fID[0], id, kAliHLTComponentDataTypefIDsize);
392 
393   if ((int)strlen(origin)>kAliHLTComponentDataTypefOriginSize) {
394     HLTWarning("data type origin %s is too long, truncated to %d", origin, kAliHLTComponentDataTypefOriginSize);
395   }
396   strncpy(&tgtdt.fOrigin[0], origin, kAliHLTComponentDataTypefOriginSize);
397 }
int AliHLTComponent::SetGlobalComponentHandler (AliHLTComponentHandler * pCH, int bOverwrite = 0) [static]
Set the global component handler. The static method is needed for the automatic registration of components.
Definition at line 118 of file AliHLTComponent.cxx.
References fgpComponentHandler.
Referenced by AliHLTComponentHandler::AddStandardComponents(), AliHLTComponentHandler::LoadLibrary(), and UnsetGlobalComponentHandler().
119 {
120   // see header file for function documentation
121   int iResult=0;
122   if (fgpComponentHandler==NULL || bOverwrite!=0)
123     fgpComponentHandler=pCH;
124   else
125     iResult=-EPERM;
126   return iResult;
127 }
int AliHLTComponent::SetStopwatch (TObject * pSW, AliHLTStopwatchType type = kSWBase)
Set a stopwatch for a given purpose.
Parameters:
pSW stopwatch object
type type of the stopwatch
Definition at line 918 of file AliHLTComponent.cxx.
References fpStopwatches, and HLTWarning.
Referenced by AliHLTSystem::InitBenchmarking(), and SetStopwatches().
919 {
920   // see header file for function documentation
921   int iResult=0;
922   if (pSW!=NULL && type<kSWTypeCount) {
923     if (fpStopwatches) {
924       TObject* pObj=fpStopwatches->At((int)type);
925       if (pSW==NULL        // explicit reset
926           || pObj==NULL) { // explicit set
927         fpStopwatches->AddAt(pSW, (int)type);
928       } else if (pObj!=pSW) {
929         HLTWarning("stopwatch %d already set, reset first", (int)type);
930         iResult=-EBUSY;
931       }
932     }
933   } else {
934     iResult=-EINVAL;
935   }
936   return iResult;
937 }
int AliHLTComponent::SetStopwatches (TObjArray * pStopwatches)
Init a set of stopwatches.
Parameters:
pStopwatches object array of stopwatches
Definition at line 939 of file AliHLTComponent.cxx.
References kSWTypeCount, and SetStopwatch().
Referenced by AliHLTSystem::InitBenchmarking().
940 {
941   // see header file for function documentation
942   if (pStopwatches==NULL) return -EINVAL;
943 
944   int iResult=0;
945   for (int i=0 ; i<(int)kSWTypeCount && pStopwatches->GetEntries(); i++)
946     SetStopwatch(pStopwatches->At(i), (AliHLTStopwatchType)i);
947   return iResult;
948 }
virtual AliHLTComponent* AliHLTComponent::Spawn () [pure virtual]
Spawn function. Each component must implement a spawn function to create a new instance of the class. Basically the function must return new my_class_name.
Returns: new class instance
Implemented in AliHLTPHOSDDLDecoderComponent (p.), AliHLTPHOSHistogramProducerComponent (p.), AliHLTPHOSModuleMergerComponent (p.), AliHLTPHOSRawAnalyzerComponent (p.), AliHLTPHOSRawAnalyzerCrudeComponent (p.), AliHLTPHOSRawAnalyzerPeakFinderComponent (p.), and AliHLTPHOSRcuHistogramProducerComponent (p.).
Referenced by AliHLTComponentHandler::CreateComponent().
int AliHLTComponent::UnsetGlobalComponentHandler () [static]
Clear the global component handler. The static method is needed for the automatic registration of components.
Definition at line 129 of file AliHLTComponent.cxx.
References SetGlobalComponentHandler().
Referenced by AliHLTComponentHandler::AddStandardComponents(), and AliHLTComponentHandler::LoadLibrary().
130 {
131   // see header file for function documentation
132   return SetGlobalComponentHandler(NULL,1);
133 }
Member Data Documentation
string AliHLTComponent::fClassName [private]
name of the class for the object to search for
Definition at line 846 of file AliHLTComponent.h.
Referenced by GetFirstInputBlock(), GetFirstInputObject(), and GetNextInputObject().
AliHLTEventID_t AliHLTComponent::fCurrentEvent [private]
Set by ProcessEvent before the processing starts
Definition at line 825 of file AliHLTComponent.h.
Referenced by ProcessEvent().
AliHLTComponentEventData AliHLTComponent::fCurrentEventData [private]
event data struct of the current event under processing
Definition at line 834 of file AliHLTComponent.h.
Referenced by CreateInputObject(), FindInputBlock(), GetDataType(), GetInputObject(), GetNumberOfInputBlocks(), GetSpecification(), and ProcessEvent().
int AliHLTComponent::fCurrentInputBlock [private]
transient
index of the current input block
Definition at line 840 of file AliHLTComponent.h.
Referenced by GetFirstInputObject(), GetNextInputBlock(), GetNextInputObject(), and ProcessEvent().
AliHLTComponentEnvironment AliHLTComponent::fEnvironment [private]
transient
The environment where the component is running in
Definition at line 822 of file AliHLTComponent.h.
Referenced by AliHLTComponent(), AllocMemory(), GetEventDoneData(), and Init().
int AliHLTComponent::fEventCount [private]
internal event no
Reimplemented in AliHLTPHOSHistogramProducerComponent (p.), AliHLTPHOSModuleMergerComponent (p.), and AliHLTPHOSRcuHistogramProducerComponent (p.).
Definition at line 828 of file AliHLTComponent.h.
Referenced by DoDeinit(), DoInit(), IncrementEventCounter(), and Init().
int AliHLTComponent::fFailedEvents [private]
the number of failed events
Definition at line 831 of file AliHLTComponent.h.
AliHLTComponentHandler * AliHLTComponent::fgpComponentHandler = NULL [static, private]
The global component handler instance
Definition at line 116 of file AliHLTComponent.cxx.
Referenced by AliHLTComponent(), and SetGlobalComponentHandler().
vector<AliHLTComponentBlockData> AliHLTComponent::fOutputBlocks [private]
list of ouput block data descriptors
Definition at line 861 of file AliHLTComponent.h.
Referenced by InsertOutputBlock(), and ProcessEvent().
AliHLTUInt32_t AliHLTComponent::fOutputBufferFilled [private]
size of data written to output buffer
Definition at line 858 of file AliHLTComponent.h.
Referenced by InsertOutputBlock(), and ProcessEvent().
AliHLTUInt32_t AliHLTComponent::fOutputBufferSize [private]
transient
size of the output buffer
Definition at line 855 of file AliHLTComponent.h.
Referenced by InsertOutputBlock(), and ProcessEvent().
const AliHLTComponentBlockData* AliHLTComponent::fpInputBlocks [private]
array of input data blocks of the current event
Definition at line 837 of file AliHLTComponent.h.
Referenced by CreateInputObject(), FindInputBlock(), GetDataType(), GetFirstInputBlock(), GetNextInputBlock(), GetNumberOfInputBlocks(), GetSpecification(), and ProcessEvent().
TObjArray* AliHLTComponent::fpInputObjects [private]
array of generated input objects
Definition at line 849 of file AliHLTComponent.h.
Referenced by CleanupInputObjects(), GetDataType(), GetInputObject(), and GetSpecification().
AliHLTUInt8_t* AliHLTComponent::fpOutputBuffer [private]
transient
the output buffer
Definition at line 852 of file AliHLTComponent.h.
Referenced by InsertOutputBlock(), and ProcessEvent().
TObjArray* AliHLTComponent::fpStopwatches [private]
stopwatch array
Definition at line 864 of file AliHLTComponent.h.
Referenced by SetStopwatch(), and ~AliHLTComponent().
AliHLTComponentDataType AliHLTComponent::fSearchDataType [private]
data type of the last block search
Definition at line 843 of file AliHLTComponent.h.
Referenced by GetFirstInputBlock(), GetFirstInputObject(), GetNextInputBlock(), GetNextInputObject(), and ProcessEvent().
The documentation for this class was generated from the following files:
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTComponent.h
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTComponent.cxx