AliHLTModuleAgent Class Reference
#include <AliHLTModuleAgent.h>
Detailed Description
Agent helper class for HLT sub modules, e.g. PHOS, TPC, Trigger.
This class implements the agent base class for the HLT sub modules. The agent of a library gives information on the features of the library/ components, like the configurations to run and other component libraries it depends on.
Note: There must not be more than one agent per module/library.
All HLT component libraries are loaded on demand through the HLT steering instance (AliHLTSystem(p.)). A library can implement an agent derived from this base class, and has to define one global object of this agent in the code. The agent will be registered automatically, and the features can be queried when required.
This is usually done during running the AliRoot reconstruction (see AliRoot documentation on AliReconstruction). The HLT implemets the AliHLTReconstructor which holds the HLT steering object. Several flags can be specified as options via the SetOption method of AliReconstruction, including the component libraries to be loaded.
Agent interface
The child can implement the following functions:
CreateConfigurations(p.)
 create HLT configuration forming an HLT analysis chain.
GetLocalRecConfigurations(p.)
 configurations run during local event reconstruction.
Note: Local event reconstruction is the first step of the reconstruction chain. All events are processed at once.
GetEventRecConfigurations(p.)
 configurations run during event reconstruction.
Note: This is the reconstruction on event by event basis.
GetRequiredComponentLibraries(p.)
 can indicate further libraries which are required for running the chains (e.g. if components of another library are used).
RegisterComponents(p.)
 register componens, this can be used to avoid the component registration via global objects
See also: Component handling(p.)
References
See also: AliHLTReconstructor interface to the AliRoot reconstruction
AliHLTAgentSample agent for the libAliHLTSample library
Definition at line 74 of file AliHLTModuleAgent.h.
Public Member Functions
AliHLTModuleAgent ()
AliHLTModuleAgent (const AliHLTModuleAgent &)
AliHLTModuleAgent & operator= (const AliHLTModuleAgent &)
virtual ~AliHLTModuleAgent ()
virtual int CreateConfigurations (AliHLTConfigurationHandler *handler, AliRunLoader *runloader=NULL) const
virtual const char * GetLocalRecConfigurations (AliRunLoader *runloader=NULL) const
virtual const char * GetEventRecConfigurations (AliRunLoader *runloader=NULL) const
virtual const char * GetRequiredComponentLibraries () const
virtual int RegisterComponents (AliRunLoader *runloader=NULL) const
const char * GetTopConfigurations (AliRunLoader *runloader=NULL) const
Static Public Member Functions
void PrintStatus (const char *agent=NULL)
AliHLTModuleAgent * GetFirstAgent ()
AliHLTModuleAgent * GetNextAgent ()
Private Member Functions
ClassDef (AliHLTModuleAgent, 0)
Static Private Member Functions
int Register (AliHLTModuleAgent *pAgent)
int Unregister (AliHLTModuleAgent *pAgent)
Static Private Attributes
TList fgAgentList
TObjLink * fgCurrentLnk = NULL
Constructor & Destructor Documentation
AliHLTModuleAgent::AliHLTModuleAgent ()
standard constructor. The agent is automatically registered in the global agent manager
AliHLTModuleAgent::AliHLTModuleAgent (const AliHLTModuleAgent &)
not a valid copy constructor, defined according to effective C++ style
Definition at line 40 of file AliHLTModuleAgent.cxx.
41   :
42   TObject(),
43   AliHLTLogging()
44 {
45   // see header file for function documentation
46 }
AliHLTModuleAgent::~AliHLTModuleAgent () [virtual]
destructor
Definition at line 57 of file AliHLTModuleAgent.cxx.
References Unregister().
58 {
59   // see header file for function documentation
60   Unregister(this);
61 }
Member Function Documentation
AliHLTModuleAgent::ClassDef (AliHLTModuleAgent, 0) [private]
int AliHLTModuleAgent::CreateConfigurations (AliHLTConfigurationHandler * handler, AliRunLoader * runloader = NULL) const [virtual]
Register all configurations belonging to this module with the AliHLTConfigurationHandler(p.). The agent can adapt the configurations to be registered to the current AliRoot setup by checking the runloader.
Parameters:
handler [in] the configuration handler
runloader [in] AliRoot runloader
Returns: neg. error code if failed
Definition at line 92 of file AliHLTModuleAgent.cxx.
Referenced by AliHLTSystem::LoadConfigurations().
94 {
95   // default method, nothing to be done, child classes can overload
96   if (handler==NULL && runloader==NULL) {
97     // get rid of 'unused parameter' warning
98   }
99   return 0;
100 }
const char * AliHLTModuleAgent::GetEventRecConfigurations (AliRunLoader * runloader = NULL) const [virtual]
Get the top configurations for event reconstruction. The same as for GetLocalRecConfigurations(p.), but for the reconstruction on event by event basis.
Parameters:
runloader [in] AliRoot runloader
Returns: string containing the top configurations separated by blanks
Definition at line 111 of file AliHLTModuleAgent.cxx.
112 {
113   // default method, nothing to be done, child classes can overload
114   if (runloader==NULL) {
115     // get rid of 'unused parameter' warning
116   }
117   return NULL;
118 }
AliHLTModuleAgent * AliHLTModuleAgent::GetFirstAgent () [static]
Get the first agent in the list
Returns: pointer to first agent in the list, NULL if empty
Definition at line 135 of file AliHLTModuleAgent.cxx.
References fgAgentList, and fgCurrentLnk.
Referenced by AliHLTSystem::BuildTaskListsFromTopConfigurations(), and AliHLTSystem::LoadConfigurations().
136 {
137   // see header file for function documentation
138   fgCurrentLnk=fgAgentList.FirstLink();
139   if (fgCurrentLnk==NULL) return NULL;
140   return (AliHLTModuleAgent*)fgCurrentLnk->GetObject();
141 }
const char * AliHLTModuleAgent::GetLocalRecConfigurations (AliRunLoader * runloader = NULL) const [virtual]
Get the top configurations for local event reconstruction. A top configuration describes a processing chain. It can simply be described by the last configuration(s) in the chain. The agent can adapt the configurations to be registered to the current AliRoot setup by checking the runloader.
Parameters:
runloader [in] AliRoot runloader
Returns: string containing the top configurations separated by blanks
Definition at line 102 of file AliHLTModuleAgent.cxx.
Referenced by AliHLTSystem::BuildTaskListsFromTopConfigurations(), and GetTopConfigurations().
103 {
104   // default method, nothing to be done, child classes can overload
105   if (runloader==NULL) {
106     // get rid of 'unused parameter' warning
107   }
108   return NULL;
109 }
AliHLTModuleAgent * AliHLTModuleAgent::GetNextAgent () [static]
Get the next agent in the list
Returns: pointer to next agent in the list, NULL if end of list
Definition at line 143 of file AliHLTModuleAgent.cxx.
References fgCurrentLnk.
Referenced by AliHLTSystem::BuildTaskListsFromTopConfigurations(), and AliHLTSystem::LoadConfigurations().
144 {
145   // see header file for function documentation
146   if (fgCurrentLnk==NULL) return NULL;
147   fgCurrentLnk=fgCurrentLnk->Next();
148   if (fgCurrentLnk==NULL) return NULL;
149   return (AliHLTModuleAgent*)fgCurrentLnk->GetObject();
150 }
const char * AliHLTModuleAgent::GetRequiredComponentLibraries () const [virtual]
Component libraries which the configurations of this agent depend on.
Returns: list of component libraries as a blank-separated string.
Definition at line 120 of file AliHLTModuleAgent.cxx.
Referenced by AliHLTSystem::LoadConfigurations().
121 {
122   // default method, nothing to be done, child classes can overload
123   return NULL;
124 }
const char* AliHLTModuleAgent::GetTopConfigurations (AliRunLoader * runloader = NULL) const [inline]
Old method kept for backward compatibility, redirected to GetLocalRecConfigurations(p.).
Definition at line 159 of file AliHLTModuleAgent.h.
References GetLocalRecConfigurations().
159                                                                        {
160     return GetLocalRecConfigurations(runloader);
161   }
AliHLTModuleAgent & AliHLTModuleAgent::operator= (const AliHLTModuleAgent &)
not a valid assignment op, but defined according to effective C++ style
Definition at line 48 of file AliHLTModuleAgent.cxx.
49 {
50   // see header file for function documentation
51   return *this;
52 }
void AliHLTModuleAgent::PrintStatus (const char * agent = NULL) [static]
Print status info. Short summary on registered agents. This function acts globally on the list of agents if no specific agent is specified.
Definition at line 63 of file AliHLTModuleAgent.cxx.
References fgAgentList, kHLTLogInfo, and AliHLTLogging::Logging().
Referenced by AliHLTSystem::Configure().
64 {
65   // see header file for function documentation
66   AliHLTLogging log;
67   if (agent) {
68     TObject* pAgent=fgAgentList.FindObject(agent);
69     if (pAgent) {
70       log.Logging(kHLTLogInfo, "AliHLTModuleAgent::PrintStatus", "module agents", 
71                   "agent %s available", pAgent->GetName());
72     } else {
73       log.Logging(kHLTLogInfo, "AliHLTModuleAgent::PrintStatus", "module agents", 
74                   "agent %s not found", agent);
75     }
76   } else {
77     TObjLink* lnk=fgAgentList.FirstLink();
78     log.Logging(kHLTLogInfo, "AliHLT", "", "-----------------------");
79     log.Logging(kHLTLogInfo, "AliHLT", "", "available module agents");
80     if (lnk==NULL) 
81       log.Logging(kHLTLogInfo, "AliHLT", "", "   none");
82     while (lnk) {
83       TString msg;
84       msg.Form("   %s : %p", ((AliHLTModuleAgent*)lnk->GetObject())->GetName(), lnk->GetObject());
85       log.Logging(kHLTLogInfo, "AliHLT", "", msg.Data());
86       lnk=lnk->Next();
87     }
88     log.Logging(kHLTLogInfo, "AliHLT", "", "-----------------------");
89   }
90 }
int AliHLTModuleAgent::Register (AliHLTModuleAgent * pAgent) [static, private]
Register agent in the global list.
Returns: neg. error code if failed
Definition at line 152 of file AliHLTModuleAgent.cxx.
References fgAgentList, kHLTLogDebug, and AliHLTLogging::Logging().
153 {
154   // see header file for function documentation
155   AliHLTLogging log;
156   if (!pAgent) return -EINVAL;
157   if (fgAgentList.FindObject(pAgent)==NULL) {
158     log.Logging(kHLTLogDebug, "AliHLTModuleAgent::Register", "", "module agent %p registered", pAgent);
159     fgAgentList.Add(pAgent);
160   }
161   return 0;
162 }
int AliHLTModuleAgent::RegisterComponents (AliRunLoader * runloader = NULL) const [virtual]
Register componets. This method can be used to register components for the module instead of the 'static object approach'. Registration is don by passing a sample object to AliHLTComponentHandler::RegisterComponent(p.)
 Note: The sample object is owned by the agent, make sure to delete it.
Definition at line 126 of file AliHLTModuleAgent.cxx.
127 {
128   if (runloader==NULL) {
129     // get rid of 'unused parameter' warning
130   }
131   // default method, nothing to be done, child classes can overload
132   return 0;
133 }
int AliHLTModuleAgent::Unregister (AliHLTModuleAgent * pAgent) [static, private]
Unregister agent in the global list.
Returns: neg. error code if failed
Definition at line 164 of file AliHLTModuleAgent.cxx.
References fgAgentList, kHLTLogDebug, and AliHLTLogging::Logging().
Referenced by ~AliHLTModuleAgent().
165 {
166   // see header file for function documentation
167   AliHLTLogging log;
168   if (!pAgent) return -EINVAL;
169   if (fgAgentList.FindObject(pAgent)!=NULL) {
170     log.Logging(kHLTLogDebug, "AliHLTModuleAgent::Unregister", "", "module agent %p removed", pAgent);
171     fgAgentList.Remove(pAgent);
172   } else {
173   }
174   return 0;
175 }
Member Data Documentation
TList AliHLTModuleAgent::fgAgentList [static, private]
the list of active agents
Definition at line 54 of file AliHLTModuleAgent.cxx.
Referenced by GetFirstAgent(), PrintStatus(), Register(), and Unregister().
TObjLink * AliHLTModuleAgent::fgCurrentLnk = NULL [static, private]
the current object link (list position)
Definition at line 55 of file AliHLTModuleAgent.cxx.
Referenced by GetFirstAgent(), and GetNextAgent().
The documentation for this class was generated from the following files:
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTModuleAgent.h
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTModuleAgent.cxx