AliHLTPHOSRcuHistogramProducerComponent Class Reference
#include <AliHLTPHOSRcuHistogramProducerComponent.h>
Public Member Functions
AliHLTPHOSRcuHistogramProducerComponent ()
virtual ~AliHLTPHOSRcuHistogramProducerComponent ()
virtual int DoInit (int argc, const char **argv)
virtual int Deinit ()
virtual int DoDeinit ()
virtual int DoEvent (const AliHLTComponentEventData &evtData, const AliHLTComponentBlockData *blocks, AliHLTComponentTriggerData &trigData, AliHLTUInt8_t *outputPtr, AliHLTUInt32_t &size, vector< AliHLTComponentBlockData > &outputBlocks)
virtual void GetInputDataTypes (std::vector< AliHLTComponentDataType > &)
virtual AliHLTComponentDataType GetOutputDataType ()
virtual void GetOutputDataSize (unsigned long &constBase, double &inputMultiplier)
virtual AliHLTComponent * Spawn ()
virtual const char * GetComponentID ()
int GetEquippmentId ()
void SetRcuX (AliHLTUInt8_t X)
void SetRcuZ (AliHLTUInt8_t Z)
void SetModuleID (AliHLTUInt8_t moduleID)
void SetEquippmentId (int id)
Private Member Functions
AliHLTPHOSRcuHistogramProducerComponent (const AliHLTPHOSRcuHistogramProducerComponent &)
AliHLTPHOSRcuHistogramProducerComponent & operator= (const AliHLTPHOSRcuHistogramProducerComponent &)
Private Attributes
int fEventCount
AliHLTUInt8_t fRcuX
AliHLTUInt8_t fRcuZ
AliHLTUInt8_t fModuleID
AliHLTPHOSRcuHistogramProducer * fRcuHistoProducerPtr
AliHLTPHOSRcuCellAccumulatedEnergyDataStruct * fOutPtr
int fEquippmentID
Static Private Attributes
const AliHLTComponentDataType inputDataTypes [] = {kAliHLTVoidDataType,{0,``,``}}
const AliHLTComponentDataType outputDataType = kAliHLTVoidDataType
Constructor & Destructor Documentation
AliHLTPHOSRcuHistogramProducerComponent::AliHLTPHOSRcuHistogramProducerComponent ()
Definition at line 39 of file AliHLTPHOSRcuHistogramProducerComponent.cxx.
39                                                                                  :AliHLTProcessor(), fEventCount(0), fRcuHistoProducerPtr(0)
40 {
41   //  Reset();
42 } 
AliHLTPHOSRcuHistogramProducerComponent::~AliHLTPHOSRcuHistogramProducerComponent () [virtual]
Definition at line 46 of file AliHLTPHOSRcuHistogramProducerComponent.cxx.
47 {
48 
49 }
AliHLTPHOSRcuHistogramProducerComponent::AliHLTPHOSRcuHistogramProducerComponent (const AliHLTPHOSRcuHistogramProducerComponent &) [private]
Definition at line 52 of file AliHLTPHOSRcuHistogramProducerComponent.cxx.
52                                                                                                                                   : AliHLTProcessor(), fEventCount(0), fRcuHistoProducerPtr(0)
53 {
54 
55 }
Member Function Documentation
int AliHLTPHOSRcuHistogramProducerComponent::Deinit () [virtual]
Clean-up function to terminate data processing. Clean-up of common data structures after data processing. The call is redirected to the internal method DoDeinit(p.) which can be overridden by the child class.
Reimplemented from AliHLTProcessor (p.).
Definition at line 59 of file AliHLTPHOSRcuHistogramProducerComponent.cxx.
References fRcuHistoProducerPtr, and AliHLTPHOSRcuHistogramProducer::WriteEnergyHistograms().
60 {
61   cout << "AliHLTPHOSRcuHistogramProducerComponent::Deinit()" << endl;
62   fRcuHistoProducerPtr->WriteEnergyHistograms();
63   return 0;
64 }
int AliHLTPHOSRcuHistogramProducerComponent::DoDeinit () [virtual]
Default method for the internal clean-up. The method is called by Deinit(p.)
Reimplemented from AliHLTComponent (p.).
Definition at line 68 of file AliHLTPHOSRcuHistogramProducerComponent.cxx.
References kHLTLogInfo, and AliHLTLogging::Logging().
69 {
70   Logging(kHLTLogInfo, "HLT", "PHOS", ",AliHLTPHOSRcuHistogramProducer DoDeinit");
71   return 0;
72 }
int AliHLTPHOSRcuHistogramProducerComponent::DoEvent (const AliHLTComponentEventData & evtData, const AliHLTComponentBlockData * blocks, AliHLTComponentTriggerData & trigData, AliHLTUInt8_t * outputPtr, AliHLTUInt32_t & size, vector< AliHLTComponentBlockData > & outputBlocks) [virtual]
The low-level data processing method for the component. This is the custom processing method and can be overloaded by the component.
Parameters:
evtData event data structure
blocks input data block descriptors
trigData trigger data structure
outputPtr pointer to target buffer
size input: size of target buffer output:size of produced data
outputBlocks list to receive output block descriptors
Returns: neg. error code if failed
Reimplemented from AliHLTProcessor (p.).
Definition at line 109 of file AliHLTPHOSRcuHistogramProducerComponent.cxx.
References AliHLTUInt8_t, AliHLTPHOSRcuCellAccumulatedEnergyDataStruct::fAccumulatedEnergies, AliHLTComponentEventData::fBlockCnt, AliHLTPHOSRcuCellEnergyDataStruct::fCnt, AliHLTComponentBlockData::fDataType, AliHLTPHOSValidCellDataStruct::fEnergy, fEventCount, AliHLTPHOSValidCellDataStruct::fGain, AliHLTPHOSRcuCellAccumulatedEnergyDataStruct::fHits, AliHLTComponent::FillBlockData(), AliHLTPHOSRcuHistogramProducer::FillEnergy(), AliHLTPHOSRcuCellAccumulatedEnergyDataStruct::fModuleID, AliHLTComponentBlockData::fOffset, fOutPtr, AliHLTComponentBlockData::fPtr, fRcuHistoProducerPtr, AliHLTPHOSRcuCellAccumulatedEnergyDataStruct::fRcuX, AliHLTPHOSRcuCellAccumulatedEnergyDataStruct::fRcuZ, AliHLTComponentBlockData::fSize, AliHLTComponentBlockData::fSpecification, AliHLTPHOSRcuCellEnergyDataStruct::fValidData, AliHLTPHOSValidCellDataStruct::fX, AliHLTPHOSValidCellDataStruct::fZ, AliHLTPHOSRcuHistogramProducer::GetCellAccumulatedEnergies(), kHLTLogFatal, and AliHLTLogging::Logging().
112 {
113   unsigned long ndx       = 0;
114   UInt_t offset           = 0; 
115   UInt_t mysize           = 0;
116   UInt_t tSize            = 0;
117   const AliHLTComponentBlockData* iter = NULL;   
118   AliHLTPHOSRcuCellEnergyDataStruct *cellDataPtr;
119   AliHLTUInt8_t* outBPtr;
120  
121   // outBPtr = outputPtr;
122   // fOutPtr =  (AliHLTPHOSRcuCellAccumulatedEnergyDataStruct*)outBPtr;
123   int tmpCnt;
124 
125   for( ndx = 0; ndx < evtData.fBlockCnt; ndx++ )
126     {
127       iter = blocks+ndx;
128       cellDataPtr = (AliHLTPHOSRcuCellEnergyDataStruct*)( iter->fPtr);
129       tmpCnt =  cellDataPtr->fCnt;
130 
131       for(int i= 0; i <= tmpCnt; i ++)
132         {
133           fRcuHistoProducerPtr->FillEnergy(cellDataPtr->fValidData[i].fX,
134                                            cellDataPtr->fValidData[i].fZ, 
135                                            cellDataPtr->fValidData[i].fGain, 
136                                            cellDataPtr->fValidData[i].fEnergy);
137         }
138     }
139   
140   outBPtr = outputPtr;
141   fOutPtr =  (AliHLTPHOSRcuCellAccumulatedEnergyDataStruct*)outBPtr;
142   const AliHLTPHOSRcuCellAccumulatedEnergyDataStruct  &innPtr = fRcuHistoProducerPtr->GetCellAccumulatedEnergies();
143 
144   fOutPtr->fModuleID = fModuleID;
145   fOutPtr->fRcuX     = fRcuX;
146   fOutPtr->fRcuZ     = fRcuZ;
147 
148 
149   for(int x=0; x < N_XCOLUMNS_RCU; x ++)
150     {
151       for(int z=0; z < N_XCOLUMNS_RCU; z ++)
152         {
153           for(int gain =0;  gain < N_GAINS; gain ++)
154             {
155               fOutPtr->fAccumulatedEnergies[x][z][gain] = innPtr.fAccumulatedEnergies[x][z][gain];
156               fOutPtr->fHits[x][z][gain] = innPtr.fHits[x][z][gain];
157             }
158         }
159     }
160 
161 
162   //pushing data to shared output memory
163   mysize += sizeof(AliHLTPHOSRcuCellAccumulatedEnergyDataStruct);
164   AliHLTComponentBlockData bd;
165   FillBlockData( bd );
166   bd.fOffset = offset;
167   bd.fSize = mysize;
168   bd.fDataType = AliHLTPHOSDefinitions::gkCellAccumulatedEnergyDataType;
169   bd.fSpecification = 0xFFFFFFFF;
170   outputBlocks.push_back( bd );
171   tSize += mysize;
172   outBPtr += mysize;
173 
174   if( tSize > size )
175     {
176       Logging( kHLTLogFatal, "HLT::AliHLTRcuHistogramProducerComponent::DoEvent", "Too much data",
177                "Data written over allowed buffer. Amount written: %lu, allowed amount: %lu."
178                , tSize, size );
179       return EMSGSIZE;
180     }
181 
182   fEventCount++; 
183   return 0;
184 }//end DoEvent
int AliHLTPHOSRcuHistogramProducerComponent::DoInit (int argc, const char ** argv) [virtual]
Default method for the internal initialization. The method is called by Init(p.)
Reimplemented from AliHLTComponent (p.).
Definition at line 188 of file AliHLTPHOSRcuHistogramProducerComponent.cxx.
References AliHLTUInt8_t, fEquippmentID, fRcuHistoProducerPtr, kHLTLogFatal, AliHLTLogging::Logging(), SetModuleID(), SetRcuX(), and SetRcuZ().
189 {
190   int iResult=0;
191   TString argument="";
192   //  fRcuHistoProducerPtr = new AliHLTPHOSRcuHistogramProducer();
193   AliHLTUInt8_t tmpRcuX;
194   AliHLTUInt8_t tmpRcuZ; 
195   AliHLTUInt8_t tmpModuleID;
196   Bool_t isSetEquippmentID = kFALSE;
197 
198   for(int i=0; i<argc && iResult>=0; i++) 
199     {
200       argument=argv[i];
201       
202       if (argument.IsNull()) 
203         {
204           continue;
205         }
206       if (argument.CompareTo("-equipmentID") == 0) 
207         {
208           if(i+1 <= argc)
209             {
210               fEquippmentID = atoi(argv[i+1]);
211               isSetEquippmentID = kTRUE;
212             }
213           else
214             {
215                iResult= -1;
216                Logging( kHLTLogFatal, "HLT::AliHLTPHOSRcuHistogramProducerComponent::DoInt( int argc, const char** argv )", "Missing argument",
217                         "The argument -equippmentID expects a number");
218                return  iResult;   
219             }
220         }
221 
222       int rcuIndex =  (fEquippmentID - 1792)%N_RCUS_PER_MODULE;
223       //     fModuleID = (fEquippmentID  -1792 -rcuIndex)/N_RCUS_PER_MODULE;
224       tmpModuleID = ((fEquippmentID -1792 -rcuIndex)/N_RCUS_PER_MODULE);
225       SetModuleID(tmpModuleID);
226 
227       if(rcuIndex == 0)
228         {
229           tmpRcuX = 0; 
230           tmpRcuZ = 0;
231         }
232       
233       if(rcuIndex == 1)
234         {
235          tmpRcuX = 0; 
236          tmpRcuZ = 1;
237         }
238       
239       if(rcuIndex == 2)
240         {
241           tmpRcuX = 1; 
242           tmpRcuZ = 0;
243         }
244       
245       if(rcuIndex == 3)
246         {
247           tmpRcuX = 1; 
248           tmpRcuZ = 1;
249         }
250 
251       SetRcuX(tmpRcuX);
252       SetRcuZ(tmpRcuZ); 
253       cout <<"********InitInfo************"<< endl;
254       cout <<"AliHLTPHOSRcuHistogramProducerComponent::SetCoordinate"<< endl;
255       cout <<"Equpippment ID =\t"<< fEquippmentID <<endl;
256       cout <<"Module ID =\t"<<  (int) tmpModuleID<<endl;
257       cout <<"RCUX =\t\t" << (int)tmpRcuX << endl;
258       cout <<"RCUZ =\t\t" << (int)tmpRcuZ << endl;
259      }
260 
261   if(isSetEquippmentID == kFALSE)
262     {
263        Logging( kHLTLogFatal, "HLT::AliHLTPHOSRcuHistogramProducerComponent::DoInt( int argc, const char** argv )", "Missing argument",
264                         "The argument equippmentID is not set: set it with a component argumet like this: -equippmentID  <number>");
265        iResult = -2; 
266     }
267 
268   
269   fRcuHistoProducerPtr = new AliHLTPHOSRcuHistogramProducer( tmpModuleID, tmpRcuX, tmpRcuZ);
270 
271 
272   return  iResult;
273 }
const char * AliHLTPHOSRcuHistogramProducerComponent::GetComponentID () [virtual]
Get the id of the component. Each component is identified by a unique id. The function is pure virtual and must be implemented by the child class.
Returns: component id (string)
Implements AliHLTComponent (p.).
Definition at line 76 of file AliHLTPHOSRcuHistogramProducerComponent.cxx.
77 {
78   return "RcuHistogramProducer";
79 }
int AliHLTPHOSRcuHistogramProducerComponent::GetEquippmentId ()
Definition at line 306 of file AliHLTPHOSRcuHistogramProducerComponent.cxx.
307 {
308   return  fEquippmentID;
309 }
void AliHLTPHOSRcuHistogramProducerComponent::GetInputDataTypes (std::vector< AliHLTComponentDataType > &) [virtual]
Definition at line 83 of file AliHLTPHOSRcuHistogramProducerComponent.cxx.
References AliHLTComponentDataType::fID.
84 {
85   const AliHLTComponentDataType* pType=inputDataTypes;
86   while (pType->fID!=0) 
87     {
88       list.push_back(*pType);
89       pType++;
90     }
91 }
void AliHLTPHOSRcuHistogramProducerComponent::GetOutputDataSize (unsigned long & constBase, double & inputMultiplier) [virtual]
Get a ratio by how much the data volume is shrinked or enhanced. The function is pure virtual and must be implemented by the child class.
Parameters:
constBase return: additive part, independent of the input data volume
inputMultiplier return: multiplication ratio
Returns: values in the reference variables
Implements AliHLTComponent (p.).
Definition at line 102 of file AliHLTPHOSRcuHistogramProducerComponent.cxx.
103 {
104   constBase = 30;
105   inputMultiplier = 1;
106 }
AliHLTComponentDataType AliHLTPHOSRcuHistogramProducerComponent::GetOutputDataType () [virtual]
Get the output data type of the component. The function is pure virtual and must be implemented by the child class.
Returns: output data type
Implements AliHLTComponent (p.).
Definition at line 95 of file AliHLTPHOSRcuHistogramProducerComponent.cxx.
96 {
97   return AliHLTPHOSDefinitions::gkCellEnergyDataType;
98 }
AliHLTPHOSRcuHistogramProducerComponent& AliHLTPHOSRcuHistogramProducerComponent::operator= (const AliHLTPHOSRcuHistogramProducerComponent &) [inline, private]
Definition at line 47 of file AliHLTPHOSRcuHistogramProducerComponent.h.
48    {
49       return *this;
50    };
void AliHLTPHOSRcuHistogramProducerComponent::SetEquippmentId (int id)
Definition at line 298 of file AliHLTPHOSRcuHistogramProducerComponent.cxx.
References fEquippmentID, fRcuHistoProducerPtr, and AliHLTPHOSRcuHistogramProducer::SetEquippmentId().
299 {
300   fEquippmentID = id;
301   fRcuHistoProducerPtr->SetEquippmentId(id);
302 }
void AliHLTPHOSRcuHistogramProducerComponent::SetModuleID (AliHLTUInt8_t moduleID)
Definition at line 291 of file AliHLTPHOSRcuHistogramProducerComponent.cxx.
References fModuleID.
Referenced by DoInit().
292 {
293   fModuleID = moduleID;
294 }
void AliHLTPHOSRcuHistogramProducerComponent::SetRcuX (AliHLTUInt8_t X)
Definition at line 277 of file AliHLTPHOSRcuHistogramProducerComponent.cxx.
References fRcuX.
Referenced by DoInit().
278 {
279   fRcuX = X;
280 }
void AliHLTPHOSRcuHistogramProducerComponent::SetRcuZ (AliHLTUInt8_t Z)
Definition at line 284 of file AliHLTPHOSRcuHistogramProducerComponent.cxx.
References fRcuZ.
Referenced by DoInit().
285 {
286   fRcuZ = Z;
287 }
AliHLTComponent * AliHLTPHOSRcuHistogramProducerComponent::Spawn () [virtual]
Spawn function. Each component must implement a spawn function to create a new instance of the class. Basically the function must return new my_class_name.
Returns: new class instance
Implements AliHLTComponent (p.).
Definition at line 313 of file AliHLTPHOSRcuHistogramProducerComponent.cxx.
314 {
315   return new AliHLTPHOSRcuHistogramProducerComponent;
316 }
Member Data Documentation
int AliHLTPHOSRcuHistogramProducerComponent::fEquippmentID [private]
Definition at line 64 of file AliHLTPHOSRcuHistogramProducerComponent.h.
Referenced by DoInit(), and SetEquippmentId().
int AliHLTPHOSRcuHistogramProducerComponent::fEventCount [private]
internal event no
Reimplemented from AliHLTComponent (p.).
Definition at line 51 of file AliHLTPHOSRcuHistogramProducerComponent.h.
Referenced by DoEvent().
AliHLTUInt8_t AliHLTPHOSRcuHistogramProducerComponent::fModuleID [private]
Definition at line 54 of file AliHLTPHOSRcuHistogramProducerComponent.h.
Referenced by SetModuleID().
AliHLTPHOSRcuCellAccumulatedEnergyDataStruct* AliHLTPHOSRcuHistogramProducerComponent::fOutPtr [private]
Definition at line 56 of file AliHLTPHOSRcuHistogramProducerComponent.h.
Referenced by DoEvent().
AliHLTPHOSRcuHistogramProducer* AliHLTPHOSRcuHistogramProducerComponent::fRcuHistoProducerPtr [private]
Definition at line 55 of file AliHLTPHOSRcuHistogramProducerComponent.h.
Referenced by Deinit(), DoEvent(), DoInit(), and SetEquippmentId().
AliHLTUInt8_t AliHLTPHOSRcuHistogramProducerComponent::fRcuX [private]
Definition at line 52 of file AliHLTPHOSRcuHistogramProducerComponent.h.
Referenced by SetRcuX().
AliHLTUInt8_t AliHLTPHOSRcuHistogramProducerComponent::fRcuZ [private]
Definition at line 53 of file AliHLTPHOSRcuHistogramProducerComponent.h.
Referenced by SetRcuZ().
const AliHLTComponentDataType AliHLTPHOSRcuHistogramProducerComponent::inputDataTypes = {kAliHLTVoidDataType,{0,``,``}} [static, private]
Definition at line 27 of file AliHLTPHOSRcuHistogramProducerComponent.cxx.
const AliHLTComponentDataType AliHLTPHOSRcuHistogramProducerComponent::outputDataType = kAliHLTVoidDataType [static, private]
Definition at line 28 of file AliHLTPHOSRcuHistogramProducerComponent.cxx.
The documentation for this class was generated from the following files:
AliHLTPHOSRcuHistogramProducerComponent.h
AliHLTPHOSRcuHistogramProducerComponent.cxx