AliHLTPHOSRawAnalyzerPeakFinder Class Reference
#include <AliHLTPHOSRawAnalyzerPeakFinder.h>
Public Member Functions
AliHLTPHOSRawAnalyzerPeakFinder ()
AliHLTPHOSRawAnalyzerPeakFinder (const AliHLTPHOSRawAnalyzerPeakFinder &)
AliHLTPHOSRawAnalyzerPeakFinder & operator= (const AliHLTPHOSRawAnalyzerPeakFinder)
virtual ~AliHLTPHOSRawAnalyzerPeakFinder ()
virtual void SetTVector (Double_t *tVect, Int_t size)
virtual void SetAVector (Double_t *aVect, Int_t size)
virtual void Evaluate (Int_t start=0, Int_t lenght=100)
void BaselineCorrection (double *dataPtr, int N)
void BaselineCorrection (double *dataPtr, double baselineValue)
int FindStartIndex (double treshold)
float GetTiming ()
float GetEnergy ()
void SetData (double *data)
void SetSampleFreq (double freq)
void SetStartIndex (int startIndex)
void MakeInitialGuess ()
void MakeInitialGuess (int treshold)
virtual void Evaluate (int start=0, int lenght=100)=0
Double_t GetMaxValue (Double_t *dta, Int_t size)
Protected Attributes
Double_t * fFloatDataPtr
double fSampleFrequency
double fDTofGuess
double fDAmplGuess
double fTau
double fDTof
double fDAmpl
int fStartIndex
Private Attributes
Double_t * fTVectorPtr
Double_t * fAVectorPtr
Int_t fTVectorSize
Int_t fAVectorSize
Constructor & Destructor Documentation
AliHLTPHOSRawAnalyzerPeakFinder::AliHLTPHOSRawAnalyzerPeakFinder ()
The AliHLTPHOSPeakfinder class is the class for extracting the basic signal parameters `timing` and `energy` from the PHOS raw data. Physical data will for a given readout channel be a sequense of ADC digitized 10 bit integer values, however for performance reasons all values used in calculation is of type double.
Definition at line 42 of file AliHLTPHOSRawAnalyzerPeakFinder.cxx.
42                                                                 :AliHLTPHOSRawAnalyzer(), fTVectorPtr(0), fAVectorPtr(0), fTVectorSize(0), fAVectorSize(0)
43 {
44   //  cout <<"PeakFinder:You cannot invoke the Fitter without arguments"<<endl;;
45 }
AliHLTPHOSRawAnalyzerPeakFinder::AliHLTPHOSRawAnalyzerPeakFinder (const AliHLTPHOSRawAnalyzerPeakFinder &)
AliHLTPHOSRawAnalyzerPeakFinder::~AliHLTPHOSRawAnalyzerPeakFinder () [virtual]
Definition at line 49 of file AliHLTPHOSRawAnalyzerPeakFinder.cxx.
50 {
51 
52 } //end AliHLTPHOSRawAnalyzerPeakFinder
Member Function Documentation
void AliHLTPHOSRawAnalyzer::BaselineCorrection (double * dataPtr, double baselineValue) [inherited]
Shifts the baseline with the amount given by baselineValue If pretrigger samples are not present then the basline correction will be incorrect.
Parameters:
dataPtr array for wich to correct the basline
BaslineValue the basline value to subtract..
Definition at line 75 of file AliHLTPHOSRawAnalyzer.cxx.
References AliHLTPHOSRawAnalyzer::fFloatDataPtr.
76 {
77   fFloatDataPtr = dataPtr;   
78   printf("\nbaselineValue = %f\n", baselineValue);
79   cout << "Baseline correction not yet implemeted" << endl;
80 } //end BaslineCorrection
void AliHLTPHOSRawAnalyzer::BaselineCorrection (double * dataPtr, int N) [inherited]
Attemps to level the basline to zero. The baseline will be calculated from the pretrigger samples and subtracted from the data array. If pretrigger samples are not present then the basline correction will be incorrect.
Parameters:
dataPtr array for wich to correct the basline
N the number of pretrigger samples used to calculate the baseline.
Definition at line 60 of file AliHLTPHOSRawAnalyzer.cxx.
References AliHLTPHOSRawAnalyzer::fFloatDataPtr.
61 {
62   fFloatDataPtr = dataPtr;  
63   //  n=N;
64   cout << "Baseline correction not yet implemeted" << endl;
65 } //end BaselineCorrection
virtual void AliHLTPHOSRawAnalyzer::Evaluate (int start = 0, int lenght = 100) [pure virtual, inherited]
Implemented in AliHLTPHOSRawAnalyzerChiSquareFit (p.), AliHLTPHOSRawAnalyzerCrude (p.), AliHLTPHOSRawAnalyzerKLevel (p.), and AliHLTPHOSRawAnalyzerLMS (p.).
virtual void AliHLTPHOSRawAnalyzerPeakFinder::Evaluate (Int_t start = 0, Int_t lenght = 100) [virtual]
Referenced by main().
int AliHLTPHOSRawAnalyzer::FindStartIndex (double treshold) [inherited]
Definition at line 124 of file AliHLTPHOSRawAnalyzer.cxx.
125 {
126   printf("\ntreshold = %f \n", treshold);
127   cout << "Find Start index not yet implemented" << endl;
128   return 0;
129 } //end FindStartIndex
float AliHLTPHOSRawAnalyzer::GetEnergy () [inherited]
Gives the time in entities of ADC channels (quantization levels). Absolute enrgy is found by multiplying with offline calibration constants.
Definition at line 99 of file AliHLTPHOSRawAnalyzer.cxx.
Referenced by main().
100 {
101   return fDAmpl;
102 } //end GetEnergy
Double_t AliHLTPHOSRawAnalyzer::GetMaxValue (Double_t * dta, Int_t size) [inherited]
Definition at line 176 of file AliHLTPHOSRawAnalyzer.cxx.
177 {
178 
179   Double_t tmpMax = 0;
180 
181   for(int i = 0; i < size; i++)
182     {
183       if(dta[i] > tmpMax)
184         {
185           tmpMax = dta[i];
186         }
187 
188     }
189   
190   return tmpMax;
191 
192 }
float AliHLTPHOSRawAnalyzer::GetTiming () [inherited]
Gives the timing in entities of sample indexes Physical time is found by multiplying with the sampling intervall (Ts).
Definition at line 88 of file AliHLTPHOSRawAnalyzer.cxx.
Referenced by main().
89 {
90   return fDTof;
91 } //end GetTiming
void AliHLTPHOSRawAnalyzer::MakeInitialGuess (int treshold) [inherited]
This function applies only to the Chi and Least mean square fit. An initial guess is made based on the average of the first 5 samples and the first value exeeding threshold + this value.
Parameters:
treshold The index of the first value above treshold is ntaken to be the first value.
Definition at line 149 of file AliHLTPHOSRawAnalyzer.cxx.
150 {
151   printf("\ntreshold = %d\n", treshold);
152   cout << "Make initial guess not yet implemeted" << endl;  
153 }
void AliHLTPHOSRawAnalyzer::MakeInitialGuess () [inherited]
This function applies only to the Chi and Least mean square fit. An initial guess is made based on the average of the first 5 samples and the first value exeeding this value.
Definition at line 137 of file AliHLTPHOSRawAnalyzer.cxx.
138 {
139   cout << "Make initial guess not yet implemeted" << endl;
140 }
AliHLTPHOSRawAnalyzerPeakFinder& AliHLTPHOSRawAnalyzerPeakFinder::operator= (const AliHLTPHOSRawAnalyzerPeakFinder) [inline]
Definition at line 16 of file AliHLTPHOSRawAnalyzerPeakFinder.h.
17     {
18       return *this; 
19     }
void AliHLTPHOSRawAnalyzerPeakFinder::SetAVector (Double_t * aVect, Int_t size) [virtual]
Reimplemented from AliHLTPHOSRawAnalyzer (p.).
Definition at line 74 of file AliHLTPHOSRawAnalyzerPeakFinder.cxx.
References fAVectorPtr, and fAVectorSize.
Referenced by main().
75 {
76     
77   fAVectorSize = size;
78 
79   if(fAVectorPtr != 0)
80     {
81       delete fAVectorPtr;
82     }
83   
84   fAVectorPtr = new Double_t[size];
85 
86   for(int i=0; i< size; i++)
87     {
88       fAVectorPtr[i] = aVec[i];
89     }
90 }
void AliHLTPHOSRawAnalyzer::SetData (double * data) [inherited]
Set data array. Overrides data data array set in the constructor.
Definition at line 109 of file AliHLTPHOSRawAnalyzer.cxx.
References AliHLTPHOSRawAnalyzer::fFloatDataPtr.
Referenced by main().
110 {
111   //  double *dta;
112   //  dta = data;
113   fFloatDataPtr = data;
114   //  cout << "Set data not yet implemented" << endl;
115 }
void AliHLTPHOSRawAnalyzer::SetSampleFreq (double freq) [inherited]
Definition at line 118 of file AliHLTPHOSRawAnalyzer.cxx.
References AliHLTPHOSRawAnalyzer::fSampleFrequency.
Referenced by main().
119 {
120   fSampleFrequency = freq;
121 }
void AliHLTPHOSRawAnalyzer::SetStartIndex (int startIndex) [inherited]
Definition at line 156 of file AliHLTPHOSRawAnalyzer.cxx.
References AliHLTPHOSRawAnalyzer::fStartIndex.
157 {
158   fStartIndex = index;
159 }
void AliHLTPHOSRawAnalyzerPeakFinder::SetTVector (Double_t * tVect, Int_t size) [virtual]
Reimplemented from AliHLTPHOSRawAnalyzer (p.).
Definition at line 55 of file AliHLTPHOSRawAnalyzerPeakFinder.cxx.
References fTVectorPtr, and fTVectorSize.
Referenced by main().
56 {
57   fTVectorSize = size;
58 
59   if(fTVectorPtr != 0)
60     {
61       delete fTVectorPtr;
62     }
63   
64   fTVectorPtr = new Double_t[size];
65 
66   for(int i=0; i< size; i++)
67     {
68       fTVectorPtr[i] = tVec[i];
69     }
70 }
Member Data Documentation
Double_t* AliHLTPHOSRawAnalyzerPeakFinder::fAVectorPtr [private]
Definition at line 26 of file AliHLTPHOSRawAnalyzerPeakFinder.h.
Referenced by SetAVector().
Int_t AliHLTPHOSRawAnalyzerPeakFinder::fAVectorSize [private]
Definition at line 28 of file AliHLTPHOSRawAnalyzerPeakFinder.h.
Referenced by SetAVector().
double AliHLTPHOSRawAnalyzer::fDAmpl [protected, inherited]
Amplitude in entities of ADC levels
Definition at line 44 of file AliHLTPHOSRawAnalyzer.h.
double AliHLTPHOSRawAnalyzer::fDAmplGuess [protected, inherited]
Initial guess for amplitude
Definition at line 41 of file AliHLTPHOSRawAnalyzer.h.
double AliHLTPHOSRawAnalyzer::fDTof [protected, inherited]
Time of flight in entities of sample intervals
Definition at line 43 of file AliHLTPHOSRawAnalyzer.h.
double AliHLTPHOSRawAnalyzer::fDTofGuess [protected, inherited]
Initial guess for t0
Definition at line 40 of file AliHLTPHOSRawAnalyzer.h.
Double_t* AliHLTPHOSRawAnalyzer::fFloatDataPtr [protected, inherited]
Float representation of data that should be fitted
Definition at line 38 of file AliHLTPHOSRawAnalyzer.h.
Referenced by AliHLTPHOSRawAnalyzer::AliHLTPHOSRawAnalyzer(), AliHLTPHOSRawAnalyzer::BaselineCorrection(), and AliHLTPHOSRawAnalyzer::SetData().
double AliHLTPHOSRawAnalyzer::fSampleFrequency [protected, inherited]
The ADC sample frequency in MHz used under data taking
Definition at line 39 of file AliHLTPHOSRawAnalyzer.h.
Referenced by AliHLTPHOSRawAnalyzer::AliHLTPHOSRawAnalyzer(), and AliHLTPHOSRawAnalyzer::SetSampleFreq().
int AliHLTPHOSRawAnalyzer::fStartIndex [protected, inherited]
Definition at line 46 of file AliHLTPHOSRawAnalyzer.h.
Referenced by AliHLTPHOSRawAnalyzer::SetStartIndex().
double AliHLTPHOSRawAnalyzer::fTau [protected, inherited]
The risetime in micro seconds
Definition at line 42 of file AliHLTPHOSRawAnalyzer.h.
Double_t* AliHLTPHOSRawAnalyzerPeakFinder::fTVectorPtr [private]
Definition at line 25 of file AliHLTPHOSRawAnalyzerPeakFinder.h.
Referenced by SetTVector().
Int_t AliHLTPHOSRawAnalyzerPeakFinder::fTVectorSize [private]
Definition at line 27 of file AliHLTPHOSRawAnalyzerPeakFinder.h.
Referenced by SetTVector().
The documentation for this class was generated from the following files:
AliHLTPHOSRawAnalyzerPeakFinder.h
AliHLTPHOSRawAnalyzerPeakFinder.cxx