AliHLTLogging Class Reference
#include <AliHLTLogging.h>
Public Types
typedef int(* AliHLTDynamicMessage)(AliHLTComponentLogSeverity severity, const char *originClass, const char *originFunc, const char *file, int line, const char *message)
transient
typedef int(* InitAliDynamicMessageCallback)()
Public Member Functions
AliHLTLogging ()
AliHLTLogging (const AliHLTLogging &)
AliHLTLogging & operator= (const AliHLTLogging &)
virtual ~AliHLTLogging ()
void SetDefaultKeyword (const char *keyword)
const char * SetKeyword (const char *keyword)
const char * GetKeyword () const
int Logging (AliHLTComponentLogSeverity severity, const char *origin, const char *keyword, const char *message,...)
int LoggingVarargs (AliHLTComponentLogSeverity severity, const char *originClass, const char *originFunc, const char *file, int line,...) const
int CheckFilter (AliHLTComponentLogSeverity severity) const
void SetLocalLoggingLevel (AliHLTComponentLogSeverity level)
AliHLTComponentLogSeverity GetLocalLoggingLevel ()
virtual void * GetParameter () const
void SwitchAliLog (int sw)
Static Public Member Functions
int Init (AliHLTfctLogging pFun)
int InitAliLogTrap (AliHLTComponentHandler *pHandler)
void SetGlobalLoggingLevel (AliHLTComponentLogSeverity level)
AliHLTComponentLogSeverity GetGlobalLoggingLevel ()
int Message (void *param, AliHLTComponentLogSeverity severity, const char *origin, const char *keyword, const char *message)
const char * BuildLogString (const char *format, va_list ap)
Static Public Attributes
ostringstream fgLogstr
Static Protected Attributes
AliHLTDynamicMessage fgAliLoggingFunc = NULL
Private Attributes
AliHLTComponentLogSeverity fLocalLogFilter
const char * fpDefaultKeyword
const char * fpCurrentKeyword
transient
Static Private Attributes
AliHLTComponentLogSeverity fgGlobalLogFilter = kHLTLogAll
transient
AliHLTfctLogging fgLoggingFunc = NULL
int fgUseAliLog = 1
transient
TArrayC fgAliHLTLoggingTarget
const int fgkALIHLTLOGGINGMAXBUFFERSIZE = 10000
transient
Member Typedef Documentation
typedef int(* AliHLTLogging::AliHLTDynamicMessage)(AliHLTComponentLogSeverity severity, const char *originClass, const char *originFunc, const char *file, int line, const char *message)
transient
The message function for dynamic use. In order to avoid dependencies on AliRoot libraries, libHLTbase loads the library dynamically and looks for the symbol.
Definition at line 178 of file AliHLTLogging.h.
typedef int(* AliHLTLogging::InitAliDynamicMessageCallback)()
The init function of the message callback for dynamic use. In order to avoid dependencies on AliRoot libraries, libHLTbase loads the library dynamically and looks for the symbol.
Definition at line 189 of file AliHLTLogging.h.
Referenced by InitAliLogTrap().
Constructor & Destructor Documentation
AliHLTLogging::AliHLTLogging ()
Definition at line 41 of file AliHLTLogging.cxx.
References kHLTLogAll.
42   :
43   //fLocalLogFilter(kHLTLogDefault),
44   fLocalLogFilter(kHLTLogAll),
45   fpDefaultKeyword(NULL),
46   fpCurrentKeyword(NULL)
47 {
48   // see header file for class documentation
49   // or
50   // refer to README to build package
51   // or
52   // visit http://web.ift.uib.no/~kjeks/doc/alice-hlt
53 }
AliHLTLogging::AliHLTLogging (const AliHLTLogging &)
Definition at line 55 of file AliHLTLogging.cxx.
References HLTFatal, and kHLTLogAll.
56   :
57   fLocalLogFilter(kHLTLogAll),
58   fpDefaultKeyword(NULL),
59   fpCurrentKeyword(NULL)
60 {
61   // see header file for class documentation
62   HLTFatal("copy constructor untested");
63 }
AliHLTLogging::~AliHLTLogging () [virtual]
Definition at line 78 of file AliHLTLogging.cxx.
79 {
80   // see header file for class documentation
81 }
Member Function Documentation
const char * AliHLTLogging::BuildLogString (const char * format, va_list ap) [static]
Build the log string from format specifier and variadac arguments
Parameters:
format format string of printf style
ap opened and initialized argument list
Returns: const char string with the formatted message
Definition at line 200 of file AliHLTLogging.cxx.
References fgAliHLTLoggingTarget.
Referenced by Logging(), and LoggingVarargs().
201 {
202   // see header file for class documentation
203 
204   int iResult=0;
205 #ifdef R__VA_COPY
206   va_list bap;
207   R__VA_COPY(bap, ap);
208 #endif //R__VA_COPY
209 
210   // take the first argument from the list as format string if no
211   // format was given
212   const char* fmt = format;
213   if (fmt==NULL) fmt=va_arg(ap, const char*);
214 
215   fgAliHLTLoggingTarget[0]=0;
216   while (fmt!=NULL) {
217     iResult=vsnprintf(fgAliHLTLoggingTarget.GetArray(), fgAliHLTLoggingTarget.GetSize(), fmt, ap);
218     if (iResult==-1)
219       // for compatibility with older version of vsnprintf
220       iResult=fgAliHLTLoggingTarget.GetSize()*2;
221     else if (iResult<fgAliHLTLoggingTarget.GetSize())
222       break;
223 
224     // terminate if buffer is already at the limit
225     if (fgAliHLTLoggingTarget.GetSize()>=fgkALIHLTLOGGINGMAXBUFFERSIZE) 
226     {
227       fgAliHLTLoggingTarget[fgAliHLTLoggingTarget.GetSize()-1]=0;
228       break;
229     }
230 
231     // check limitation and grow the buffer
232     if (iResult>fgkALIHLTLOGGINGMAXBUFFERSIZE) iResult=fgkALIHLTLOGGINGMAXBUFFERSIZE;
233     fgAliHLTLoggingTarget.Set(iResult+1);
234 
235     // copy the original list and skip the first argument if this was the format string
236 #ifdef R__VA_COPY
237     va_end(ap);
238     R__VA_COPY(ap, bap);
239 #else
240     fgAliHLTLoggingTarget[fgAliHLTLoggingTarget.GetSize()-1]=0;
241     break;
242 #endif //R__VA_COPY
243     if (format==NULL) va_arg(ap, const char*);
244   }     
245 #ifdef R__VA_COPY
246   va_end(bap);
247 #endif //R__VA_COPY
248 
249   return fgAliHLTLoggingTarget.GetArray();
250 }
int AliHLTLogging::CheckFilter (AliHLTComponentLogSeverity severity) const
Apply filter
Returns: 1 if message should pass
Definition at line 311 of file AliHLTLogging.cxx.
References kHLTLogNone.
Referenced by AliHLTSystem::Configure(), Logging(), and LoggingVarargs().
312 {
313   // see header file for class documentation
314 
315   int iResult=severity==kHLTLogNone || (severity&fgGlobalLogFilter)>0 && (severity&fLocalLogFilter)>0;
316   return iResult;
317 }
AliHLTComponentLogSeverity AliHLTLogging::GetGlobalLoggingLevel () [static]
Get global logging level logging filter for all objects
Definition at line 326 of file AliHLTLogging.cxx.
References AliHLTComponentLogSeverity.
327 {
328   // see header file for class documentation
329 
330   return fgGlobalLogFilter;
331 }
const char* AliHLTLogging::GetKeyword () const [inline]
Get the current keyword
Definition at line 75 of file AliHLTLogging.h.
Referenced by LoggingVarargs().
76     {
77       if (fpCurrentKeyword) return fpCurrentKeyword;
78       else if (fpDefaultKeyword) return fpDefaultKeyword;
79       return HLT_DEFAULT_LOG_KEYWORD;
80     }
AliHLTComponentLogSeverity AliHLTLogging::GetLocalLoggingLevel ()
Get local logging level logging filter for individual object
Definition at line 341 of file AliHLTLogging.cxx.
References AliHLTComponentLogSeverity.
Referenced by InitAliLogTrap().
342 {
343   // see header file for class documentation
344 
345   return fLocalLogFilter;
346 }
virtual void* AliHLTLogging::GetParameter () const [inline, virtual]
Get parameter given by the external caller. This functionality is not yet implemented. It is intended to pass the parameter pointer given to the component at initialization back to the caller.
Definition at line 162 of file AliHLTLogging.h.
162 {return NULL;}
int AliHLTLogging::Init (AliHLTfctLogging pFun) [static]
Init the AliLogging class for use from external package. This initializes the logging callback.
 Only deployed by external users of the C wrapper interface, not used when running in AliRoot
Definition at line 88 of file AliHLTLogging.cxx.
References fgLoggingFunc.
Referenced by AliHLTComponentHandler::AliHLTComponentHandler(), and AliHLTComponentHandler::SetEnvironment().
89 {
90   // see header file for class documentation
91   if (fgLoggingFunc!=NULL && fgLoggingFunc!=pFun) {
92     (*fgLoggingFunc)(NULL/*fParam*/, kHLTLogWarning, "AliHLTLogging::Init", "no key", "overriding previously initialized logging function");    
93   }
94   fgLoggingFunc=pFun;
95   
96   return 0;
97 }
int AliHLTLogging::InitAliLogTrap (AliHLTComponentHandler * pHandler) [static]
Init the message trap in AliLog. This initializes the AliLog trap, the AliLog class is the logging mechanism of AliRoot. The trap can fetch log messages written to AliLog, components and detector algorithms can use the AliLog mechanism to be as close as possible to Offline habits.
 Only used with external users of the C wrapper interface, not used when running in AliRoot
Definition at line 99 of file AliHLTLogging.cxx.
References AliHLTComponentLogSeverity, AliHLTComponentHandler::FindSymbol(), GetLocalLoggingLevel(), InitAliDynamicMessageCallback, kHLTLogError, AliHLTComponentHandler::LoadLibrary(), Message(), and SetLocalLoggingLevel().
Referenced by AliHLT_C_Component_InitSystem().
100 {
101   // see header file for class documentation
102   int iResult=0;
103   if (pHandler) {
104     AliHLTComponentLogSeverity loglevel=pHandler->GetLocalLoggingLevel();
105     pHandler->SetLocalLoggingLevel(kHLTLogError);
106     pHandler->LoadLibrary("libAliHLTUtil.so");
107     pHandler->SetLocalLoggingLevel(loglevel);
108     InitAliDynamicMessageCallback pFunc=(InitAliDynamicMessageCallback)pHandler->FindSymbol("libAliHLTUtil.so", "InitAliDynamicMessageCallback"); 
109     if (pFunc) {
110       iResult=(*pFunc)();
111     } else {
112       Message(NULL, kHLTLogError, "AliHLTLogging::InitAliLogTrap", "init logging",
113               "can not initialize AliLog callback");
114       iResult=-ENOSYS;
115     }
116   } else {
117     iResult=-EINVAL;
118   }
119   
120   return iResult;
121 }
int AliHLTLogging::Logging (AliHLTComponentLogSeverity severity, const char * origin, const char * keyword, const char * message, ...)
Genaral logging function
Definition at line 252 of file AliHLTLogging.cxx.
References BuildLogString(), CheckFilter(), fgAliLoggingFunc, fgUseAliLog, and Message().
Referenced by AliHLTDataBuffer::CreateRawBuffer(), AliHLTDataBuffer::DeleteRawBuffers(), AliHLTPHOSRcuHistogramProducerComponent::DoDeinit(), AliHLTPHOSRawAnalyzerComponent::DoDeinit(), AliHLTPHOSModuleMergerComponent::DoDeinit(), AliHLTPHOSHistogramProducerComponent::DoDeinit(), AliHLTPHOSDDLDecoderComponent::DoDeinit(), AliHLTPHOSRcuHistogramProducerComponent::DoEvent(), AliHLTPHOSRawAnalyzerComponent::DoEvent(), AliHLTPHOSHistogramProducerComponent::DoEvent(), AliHLTPHOSDDLDecoderComponent::DoEvent(), AliHLTPHOSRcuHistogramProducerComponent::DoInit(), AliHLTPHOSRawAnalyzerComponent::DoInit(), AliHLTPHOSDDLDecoderComponent::DoInit(), AliHLTConfiguration::GlobalDeinit(), AliHLTConfiguration::GlobalInit(), AliHLTModuleAgent::PrintStatus(), AliHLTModuleAgent::Register(), AliHLTDataBuffer::ReleaseRawBuffer(), and AliHLTModuleAgent::Unregister().
255 {
256   // see header file for class documentation
257   int iResult=CheckFilter(severity);
258   if (iResult>0) {
259     va_list args;
260     va_start(args, format);
261     if (fgLoggingFunc) {
262       iResult = (*fgLoggingFunc)(NULL/*fParam*/, severity, origin, keyword, AliHLTLogging::BuildLogString(format, args ));
263     } else {
264       if (fgUseAliLog!=0 && fgAliLoggingFunc!=NULL)
265         iResult=(*fgAliLoggingFunc)(severity, NULL, origin, NULL, 0, AliHLTLogging::BuildLogString(format, args ));
266       else
267         iResult=Message(NULL/*fParam*/, severity, origin, keyword, AliHLTLogging::BuildLogString(format, args ));
268     }
269     va_end(args);
270   }
271   return iResult;
272 }
int AliHLTLogging::LoggingVarargs (AliHLTComponentLogSeverity severity, const char * originClass, const char * originFunc, const char * file, int line, ...) const
Definition at line 274 of file AliHLTLogging.cxx.
References BuildLogString(), CheckFilter(), fgAliLoggingFunc, fgUseAliLog, GetKeyword(), and Message().
Referenced by AliHLTOfflineInterface::SetParamsToComponents().
277 {
278   // see header file for class documentation
279 
280   if (file==NULL && line==0) {
281     // this is currently just to get rid of the warning "unused parameter"
282   }
283   int iResult=CheckFilter(severity);
284   if (iResult>0) {
285     const char* separator="";
286     TString origin;
287     if (originClass) {
288         origin+=originClass;
289         separator="::";
290     }
291     if (originFunc) {
292         origin+=separator;
293         origin+=originFunc;
294     }
295     va_list args;
296     va_start(args, line);
297 
298     if (fgLoggingFunc) {
299       iResult=(*fgLoggingFunc)(NULL/*fParam*/, severity, origin.Data(), GetKeyword(), AliHLTLogging::BuildLogString(NULL, args ));
300     } else {
301       if (fgUseAliLog!=0 && fgAliLoggingFunc!=NULL)
302         iResult=(*fgAliLoggingFunc)(severity, originClass, originFunc, file, line, AliHLTLogging::BuildLogString(NULL, args ));
303       else
304         iResult=Message(NULL/*fParam*/, severity, origin.Data(), GetKeyword(), AliHLTLogging::BuildLogString(NULL, args ));
305     }
306     va_end(args);
307   }
308   return iResult;
309 }
int AliHLTLogging::Message (void * param, AliHLTComponentLogSeverity severity, const char * origin, const char * keyword, const char * message) [static]
Print message to stdout
Definition at line 123 of file AliHLTLogging.cxx.
References HLT_DEFAULT_LOG_KEYWORD, kHLTLogBenchmark, kHLTLogDebug, kHLTLogError, kHLTLogFatal, kHLTLogInfo, and kHLTLogWarning.
Referenced by InitAliLogTrap(), Logging(), LoggingVarargs(), and AliHLTComponent::PrintComponentDataTypeInfo().
126 {
127   // see header file for class documentation
128   int iResult=0;
129   if (param==NULL) {
130     // this is currently just to get rid of the warning "unused parameter"
131   }
132 
133   const char* strSeverity="";
134   switch (severity) {
135   case kHLTLogBenchmark: 
136     strSeverity="benchmark";
137     break;
138   case kHLTLogDebug:
139     strSeverity="debug";
140     break;
141   case kHLTLogInfo:
142     strSeverity="info";
143     break;
144   case kHLTLogWarning:
145     strSeverity="warning";
146     break;
147   case kHLTLogError:
148     strSeverity="error";
149     break;
150   case kHLTLogFatal:
151     strSeverity="fatal";
152     break;
153   default:
154     break;
155   }
156   TString out="HLT Log ";
157   out+=strSeverity;
158   if (origin && origin[0]!=0) {out+=": <"; out+=origin; out+="> ";}
159   out+=" "; out+=message;
160   if (keyword!=NULL && strcmp(keyword, HLT_DEFAULT_LOG_KEYWORD)!=0) {
161     out+=" ("; out+=keyword; out +=")";
162   }
163   cout << out.Data() << endl;
164   return iResult;
165 }
AliHLTLogging & AliHLTLogging::operator= (const AliHLTLogging &)
Definition at line 65 of file AliHLTLogging.cxx.
References HLTFatal.
66 { 
67   // see header file for class documentation
68   HLTFatal("assignment operator untested");
69   return *this;
70 }
void AliHLTLogging::SetDefaultKeyword (const char * keyword) [inline]
set the default key word the keyword is intended to simplify the use of logging macros
Definition at line 59 of file AliHLTLogging.h.
59 { fpDefaultKeyword=keyword; }
void AliHLTLogging::SetGlobalLoggingLevel (AliHLTComponentLogSeverity level) [static]
Set global logging level logging filter for all objects
Definition at line 319 of file AliHLTLogging.cxx.
References fgGlobalLogFilter.
320 {
321   // see header file for class documentation
322 
323   fgGlobalLogFilter=level;
324 }
const char* AliHLTLogging::SetKeyword (const char * keyword) [inline]
Set a temporary keyword returns the old key value
Definition at line 65 of file AliHLTLogging.h.
66     { 
67       const char* currentKeyword=fpCurrentKeyword;
68       fpCurrentKeyword=keyword;
69       return currentKeyword; 
70     }
void AliHLTLogging::SetLocalLoggingLevel (AliHLTComponentLogSeverity level)
Set local logging level logging filter for individual object
Definition at line 333 of file AliHLTLogging.cxx.
References fLocalLogFilter.
Referenced by AliHLTComponent::AliHLTComponent(), AliHLTComponent::Init(), and InitAliLogTrap().
334 {
335   // see header file for class documentation
336 
337   fLocalLogFilter=level;
338 }
void AliHLTLogging::SwitchAliLog (int sw) [inline]
Switch logging through AliLog on or off
Parameters:
sw 1 = logging through AliLog
Definition at line 168 of file AliHLTLogging.h.
168 {fgUseAliLog=(sw!=0);}
Member Data Documentation
TArrayC AliHLTLogging::fgAliHLTLoggingTarget [static, private]
The global logging buffer. The buffer is created with an initial size and grown dynamically on demand.
Referenced by BuildLogString().
AliHLTLogging::AliHLTDynamicMessage AliHLTLogging::fgAliLoggingFunc = NULL [static, protected]
the AliRoot logging function
Definition at line 75 of file AliHLTLogging.cxx.
Referenced by Logging(), and LoggingVarargs().
AliHLTComponentLogSeverity AliHLTLogging::fgGlobalLogFilter = kHLTLogAll [static, private]
transient
the global logging filter
Definition at line 73 of file AliHLTLogging.cxx.
Referenced by SetGlobalLoggingLevel().
const int AliHLTLogging::fgkALIHLTLOGGINGMAXBUFFERSIZE = 10000 [static, private]
transient
the maximum size of the buffer
Definition at line 86 of file AliHLTLogging.cxx.
AliHLTfctLogging AliHLTLogging::fgLoggingFunc = NULL [static, private]
logging callback from the framework
Definition at line 74 of file AliHLTLogging.cxx.
Referenced by Init().
ostringstream AliHLTLogging::fgLogstr [static]
target stream for AliRoot logging methods
Definition at line 72 of file AliHLTLogging.cxx.
int AliHLTLogging::fgUseAliLog = 1 [static, private]
transient
switch for logging through AliLog, default on
Definition at line 76 of file AliHLTLogging.cxx.
Referenced by Logging(), and LoggingVarargs().
AliHLTComponentLogSeverity AliHLTLogging::fLocalLogFilter [private]
the local logging filter for one class
Definition at line 199 of file AliHLTLogging.h.
Referenced by SetLocalLoggingLevel().
const char* AliHLTLogging::fpCurrentKeyword [private]
transient
current keyword
Definition at line 205 of file AliHLTLogging.h.
const char* AliHLTLogging::fpDefaultKeyword [private]
default keyword
Definition at line 203 of file AliHLTLogging.h.
The documentation for this class was generated from the following files:
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTLogging.h
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTLogging.cxx