AliHLTSystem Class Reference
#include <AliHLTSystem.h>
Detailed Description
Main class for the HLT integration into AliRoot. The class handles a list of configurations. Configurations are translated into task lists which can be executed.
Note: This class is only used for the HLT integration into AliRoot(p.).
Definition at line 43 of file AliHLTSystem.h.
Public Types
enum AliHLTSystemState_t {
kUninitialized = 0x0,
kLibrariesLoaded = 0x1,
kConfigurationLoaded = 0x2,
kTaskListCreated = 0x4,
kReady = 0x7,
kRunning = 0x8,
kError = 0x1000
 }
Public Member Functions
AliHLTSystem ()
AliHLTSystem (const AliHLTSystem &)
AliHLTSystem & operator= (const AliHLTSystem &)
virtual ~AliHLTSystem ()
int AddConfiguration (AliHLTConfiguration *pConf)
transient
int InsertConfiguration (AliHLTConfiguration *pConf, AliHLTConfiguration *pPrec)
int DeleteConfiguration (AliHLTConfiguration *pConf)
int BuildTaskList (const char *pConf)
int BuildTaskList (AliHLTConfiguration *pConf)
int CleanTaskList ()
int InsertTask (AliHLTTask *pTask)
AliHLTTask * FindTask (const char *id)
void PrintTaskList ()
int Run (Int_t iNofEvents=1)
int InitTasks ()
int InitBenchmarking (TObjArray *pStopwatches)
int StartTasks ()
int ProcessTasks (Int_t eventNo)
int StopTasks ()
int DeinitTasks ()
int Reconstruct (int nofEvents, AliRunLoader *runLoader, AliRawReader *rawReader=NULL)
int FillESD (int eventNo, AliRunLoader *runLoader, AliESD *esd)
int LoadComponentLibraries (const char *libs)
void * FindDynamicSymbol (const char *library, const char *symbol)
int Configure (AliRunLoader *runloader=NULL)
int Reset (int bForce=0)
int LoadConfigurations (AliRunLoader *runloader=NULL)
int BuildTaskListsFromTopConfigurations (AliRunLoader *runloader=NULL)
int CheckStatus (int flag)
int GetStatusFlags ()
Static Public Member Functions
void * AllocMemory (void *param, unsigned long size)
Public Attributes
AliHLTComponentHandler * fpComponentHandler
AliHLTConfigurationHandler * fpConfigurationHandler
transient
Private Member Functions
int SetStatusFlags (int flags)
int ClearStatusFlags (int flags)
ClassDef (AliHLTSystem, 2)
Private Attributes
TList fTaskList
int fState
Static Private Attributes
int fgNofInstances = 0
Member Enumeration Documentation
enum AliHLTSystem::AliHLTSystemState_t
Enumeration values:
kUninitialized
kLibrariesLoaded
kConfigurationLoaded
kTaskListCreated
kReady
kRunning
kError
Definition at line 278 of file AliHLTSystem.h.
278                            {
279     kUninitialized       = 0x0,
280     kLibrariesLoaded     = 0x1,
281     kConfigurationLoaded = 0x2,
282     kTaskListCreated     = 0x4,
283     kReady               = 0x7,
284     kRunning             = 0x8,
285     kError               = 0x1000
286   };
Constructor & Destructor Documentation
AliHLTSystem::AliHLTSystem ()
default constructor
AliHLTSystem::AliHLTSystem (const AliHLTSystem &)
not a valid copy constructor, defined according to effective C++ style
Definition at line 87 of file AliHLTSystem.cxx.
References fgNofInstances, HLTFatal, and HLTWarning.
88   :
89   AliHLTLogging(),
90   fpComponentHandler(NULL),
91   fpConfigurationHandler(NULL),
92   fTaskList(),
93   fState(0)
94 {
95   // see header file for class documentation
96   if (fgNofInstances++>0)
97     HLTWarning("multiple instances of AliHLTSystem, you should not use more than one at a time");
98 
99   HLTFatal("copy constructor untested");
100 }
AliHLTSystem::~AliHLTSystem () [virtual]
destructor
Definition at line 109 of file AliHLTSystem.cxx.
References CleanTaskList(), fgNofInstances, fpComponentHandler, fpConfigurationHandler, and AliHLTConfiguration::GlobalDeinit().
110 {
111   // see header file for class documentation
112   fgNofInstances--;
113   CleanTaskList();
114   AliHLTConfiguration::GlobalDeinit(fpConfigurationHandler);
115   if (fpConfigurationHandler) {
116     delete fpConfigurationHandler;
117   }
118   fpConfigurationHandler=NULL;
119   
120   if (fpComponentHandler) {
121     delete fpComponentHandler;
122   }
123   fpComponentHandler=NULL;
124 }
Member Function Documentation
int AliHLTSystem::AddConfiguration (AliHLTConfiguration * pConf)
transient
Add a configuration to the end of the list.
Parameters:
pConf pointer to configuration to add
Definition at line 128 of file AliHLTSystem.cxx.
129 {
130   // see header file for class documentation
131   int iResult=0;
132   if (pConf) {
133   } else {
134     iResult=-EINVAL;
135   }
136   return iResult;
137 }
void * AliHLTSystem::AllocMemory (void * param, unsigned long size) [static]
The memory allocation function for components. This function is part of the running environment of the components.
Definition at line 528 of file AliHLTSystem.cxx.
529 {
530   // see header file for class documentation
531   if (param==NULL) {
532     // get rid of 'unused parameter' warning
533   }
534   return (void*)new char[size];
535 }
int AliHLTSystem::BuildTaskList (AliHLTConfiguration * pConf)
Build task list from a configuration object. This method is kept for backward compatibility. Use the version with the configuration name.
Parameters:
pConf pointer to configuration to build the task list from
Definition at line 186 of file AliHLTSystem.cxx.
References BuildTaskList(), FindTask(), AliHLTConfiguration::FollowDependency(), fTaskList, AliHLTTask::GetConf(), AliHLTConfiguration::GetFirstSource(), AliHLTTask::GetName(), AliHLTConfiguration::GetName(), AliHLTConfiguration::GetNextSource(), HLTError, InsertTask(), AliHLTTask::PrintDependencyTree(), and AliHLTConfiguration::SourcesResolved().
187 {
188   // see header file for class documentation
189   int iResult=0;
190   if (pConf) {
191     AliHLTTask* pTask=NULL;
192     if ((pTask=FindTask(pConf->GetName()))!=NULL) {
193       if (pTask->GetConf()!=pConf) {
194         HLTError("configuration missmatch, there is already a task with configuration name \"%s\", but it is different. Most likely configuration %p is not registered properly", pConf->GetName(), pConf);
195         iResult=-EEXIST;
196         pTask=NULL;
197       }
198     } else if (pConf->SourcesResolved(1)!=1) {
199         HLTError("configuration \"%s\" has unresolved sources, aborting ...", pConf->GetName());
200         iResult=-ENOLINK;
201     } else {
202       pTask=new AliHLTTask(pConf);
203       if (pTask==NULL) {
204         iResult=-ENOMEM;
205       }
206     }
207     if (pTask) {
208       // check for circular dependencies
209       if ((iResult=pConf->FollowDependency(pConf->GetName()))>0) {
210         HLTError("detected circular dependency for configuration \"%s\"", pTask->GetName());
211         pTask->PrintDependencyTree(pTask->GetName(), 1/*use the configuration list*/);
212         HLTError("aborted ...");
213         iResult=-ELOOP;
214       }
215       if (iResult>=0) {
216         // check whether all dependencies are already in the task list
217         // create the missing ones
218         // this step is an iterative process which calls this function again for the missing
219         // configurations, in order to avoid the currently processed task to be created
220         // again it is added to the list temporarily and removed afterwards
221         // This is of high importance to preserve the order of the tasks. Furthermore, the
222         // InsertTask method has to be used in order to set all the cross links right 
223         fTaskList.Add(pTask);
224         AliHLTConfiguration* pDep=pConf->GetFirstSource();
225         while (pDep!=NULL && iResult>=0) {
226           if (FindTask(pDep->GetName())==NULL) {
227             iResult=BuildTaskList(pDep);
228           }
229           pDep=pConf->GetNextSource();
230         }
231         // remove the temporarily added task
232         fTaskList.Remove(pTask);
233 
234         // insert the task and set the cross-links
235         if (iResult>=0) {
236           iResult=InsertTask(pTask);
237         }
238       } else {
239         delete pTask;
240         pTask=NULL;
241       }
242     }
243   } else {
244     iResult=-EINVAL;
245   }
246   return iResult;
247 }
int AliHLTSystem::BuildTaskList (const char * pConf)
Build a task list This method is used to build the tasks from the 'master' configuration objects which are added to the HLT system handler. This is an iterative process since the task might depend upon other configurations. For each configuration object which has not yet been converted into a task, the method will be called iteratively. Finally, after building all tasks which the current one depends on have been created, the task is inserted to the list of tasks with the InsertTask method.
Parameters:
pConf configuration name/id
Definition at line 164 of file AliHLTSystem.cxx.
References AliHLTConfigurationHandler::FindConfiguration(), fpConfigurationHandler, and HLTError.
Referenced by BuildTaskList(), and BuildTaskListsFromTopConfigurations().
165 {
166   // see header file for class documentation
167   int iResult=0;
168   if (id) {
169     if (fpConfigurationHandler) {
170       AliHLTConfiguration* pConf=fpConfigurationHandler->FindConfiguration(id);
171       if (pConf) {
172         iResult=BuildTaskList(pConf);
173       } else {
174         HLTError("unknown configuration \"%s\"", id);
175         iResult=-EEXIST;
176       }
177     } else {
178       iResult=-EFAULT;
179     }
180   } else {
181     iResult=-EINVAL;
182   }
183   return iResult;
184 }
int AliHLTSystem::BuildTaskListsFromTopConfigurations (AliRunLoader * runloader = NULL)
Get the top configurations of all agents and build the task lists.
Returns: neg. error code if failed
Definition at line 665 of file AliHLTSystem.cxx.
References BuildTaskList(), CheckStatus(), AliHLTConfigurationHandler::FindConfiguration(), fpConfigurationHandler, AliHLTModuleAgent::GetFirstAgent(), AliHLTModuleAgent::GetLocalRecConfigurations(), AliHLTModuleAgent::GetNextAgent(), HLTDebug, HLTError, HLTWarning, kConfigurationLoaded, kRunning, kTaskListCreated, and SetStatusFlags().
Referenced by Configure().
666 {
667   // see header file for class documentation
668   if (CheckStatus(kRunning)) {
669     HLTError("HLT system in running state, can not configure");
670     return -EBUSY;
671   }
672   if (!CheckStatus(kConfigurationLoaded)) {
673     HLTWarning("configurations not yet loaded");
674     return 0;
675   }
676 
677   int iResult=0;
678   AliHLTModuleAgent* pAgent=AliHLTModuleAgent::GetFirstAgent();
679   while (pAgent && iResult>=0) {
680     TString tops=pAgent->GetLocalRecConfigurations(runloader);
681     HLTDebug("top configurations for agent %s (%p): %s", pAgent->GetName(), pAgent, tops.Data());
682     TObjArray* pTokens=tops.Tokenize(" ");
683     if (pTokens) {
684       int iEntries=pTokens->GetEntries();
685       for (int i=0; i<iEntries && iResult>=0; i++) {
686         const char* pCID=((TObjString*)pTokens->At(i))->GetString().Data();
687         AliHLTConfiguration* pConf=fpConfigurationHandler->FindConfiguration(pCID);
688         if (pConf) {
689           iResult=BuildTaskList(pConf);
690         } else {
691           HLTWarning("can not find top configuration %s", pCID);
692         }
693       }
694       delete pTokens;
695     }
696     
697     pAgent=AliHLTModuleAgent::GetNextAgent();
698   }
699   if (iResult>=0) SetStatusFlags(kTaskListCreated);
700 
701   return iResult;
702 }
int AliHLTSystem::CheckStatus (int flag)
Check status of the system.
Parameters:
flag AliHLTSystemState_t value to check for
Returns: 1 if set, 0 if not
Definition at line 704 of file AliHLTSystem.cxx.
References fState, and kUninitialized.
Referenced by BuildTaskListsFromTopConfigurations(), Configure(), LoadConfigurations(), Reconstruct(), and Reset().
705 {
706   // see header file for class documentation
707   if (flag==kUninitialized && flag==fState) return 1;
708   if ((fState&flag)==flag) return 1;
709   return 0;
710 }
AliHLTSystem::ClassDef (AliHLTSystem, 2) [private]
int AliHLTSystem::CleanTaskList ()
Clean the list of tasks and delete all the task objects.
Definition at line 249 of file AliHLTSystem.cxx.
References fTaskList.
Referenced by Reset(), and ~AliHLTSystem().
250 {
251   // see header file for class documentation
252   int iResult=0;
253   TObjLink* lnk=NULL;
254   while ((lnk=fTaskList.LastLink())!=NULL) {
255     delete (lnk->GetObject());
256     fTaskList.Remove(lnk);
257   }
258   return iResult;
259 }
int AliHLTSystem::ClearStatusFlags (int flags) [private]
clear status flags.
Definition at line 725 of file AliHLTSystem.cxx.
References fState.
Referenced by Configure(), LoadComponentLibraries(), Reset(), and Run().
726 {
727   // see header file for class documentation
728   fState&=~flags;
729   return fState;
730 }
int AliHLTSystem::Configure (AliRunLoader * runloader = NULL)
Prepare the HLT system for running.
module agents are requested to register configurations
task lists are built from the top configurations of the modules
Returns: neg. error code if failed
 -EBUSY system is in kRunning state
Definition at line 604 of file AliHLTSystem.cxx.
References BuildTaskListsFromTopConfigurations(), AliHLTLogging::CheckFilter(), CheckStatus(), ClearStatusFlags(), HLTError, kConfigurationLoaded, kError, kHLTLogDebug, kRunning, kTaskListCreated, LoadConfigurations(), AliHLTModuleAgent::PrintStatus(), and SetStatusFlags().
605 {
606   // see header file for class documentation
607   int iResult=0;
608   if (CheckStatus(kRunning)) {
609     HLTError("HLT system in running state, can not configure");
610     return -EBUSY;
611   }
612   if (CheckFilter(kHLTLogDebug))
613     AliHLTModuleAgent::PrintStatus();
614   ClearStatusFlags(kConfigurationLoaded|kTaskListCreated);
615   iResult=LoadConfigurations(runloader);
616   if (iResult>=0) {
617     SetStatusFlags(kConfigurationLoaded);
618     iResult=BuildTaskListsFromTopConfigurations(runloader);
619     if (iResult>=0) {
620       SetStatusFlags(kTaskListCreated);
621     }
622   }
623   if (iResult<0) SetStatusFlags(kError);
624   
625   return iResult;
626 }
int AliHLTSystem::DeinitTasks ()
De-init all tasks from the list. The AliHLTTask::Deinit(p.) method is called for each task, the components will be deleted.
Returns: neg error code if failed
Definition at line 511 of file AliHLTSystem.cxx.
References AliHLTTask::Deinit(), and fTaskList.
Referenced by Run().
512 {
513   // see header file for class documentation
514   int iResult=0;
515   TObjLink *lnk=fTaskList.FirstLink();
516   while (lnk && iResult>=0) {
517     TObject* obj=lnk->GetObject();
518     if (obj) {
519       AliHLTTask* pTask=(AliHLTTask*)obj;
520       iResult=pTask->Deinit();
521     } else {
522     }
523     lnk = lnk->Next();
524   }
525   return iResult;
526 }
int AliHLTSystem::DeleteConfiguration (AliHLTConfiguration * pConf)
Remove a configuration from the list.
Parameters:
pConf pointer to configuration to delete
Definition at line 153 of file AliHLTSystem.cxx.
154 {
155   // see header file for class documentation
156   int iResult=0;
157   if (pConf) {
158   } else {
159     iResult=-EINVAL;
160   }
161   return iResult;
162 }
int AliHLTSystem::FillESD (int eventNo, AliRunLoader * runLoader, AliESD * esd)
Fill ESD for one event. To be called by the AliHLTReconstructor plugin during the event loop and FillESD method of the AliRoot reconstruction. This method is called on event basis, and thus must copy the previously reconstructed data of the event from the 'ESD' recorder. The FillESD method of all active AliHLTOfflineDataSink's is called.
Parameters:
eventNo current event no (Note: this event number is just a processing counter and is not related to the nature/ origin of the event
runLoader the AliRoot runloader
esd an AliESD instance
Returns: neg. error code if failed
Definition at line 558 of file AliHLTSystem.cxx.
References AliHLTOfflineInterface::FillComponentESDs(), HLTError, and HLTInfo.
559 {
560   // see header file for class documentation
561   int iResult=0;
562   if (runLoader) {
563     HLTInfo("Event %d: Run Loader %p, ESD %p", eventNo, runLoader, esd);
564     iResult=AliHLTOfflineInterface::FillComponentESDs(eventNo, runLoader, esd);
565   } else {
566     HLTError("missing run loader/ESD instance(s)");
567     iResult=-EINVAL;
568   }
569   return iResult;
570 }
void * AliHLTSystem::FindDynamicSymbol (const char * library, const char * symbol)
Find a symbol in a dynamically loaded library.
Parameters:
library library
symbol the symbol to find
Returns: void pointer to function
Definition at line 732 of file AliHLTSystem.cxx.
References AliHLTComponentHandler::FindSymbol(), and fpComponentHandler.
733 {
734   if (fpComponentHandler==NULL) return NULL;
735   return fpComponentHandler->FindSymbol(library, symbol);
736 }
AliHLTTask * AliHLTSystem::FindTask (const char * id)
Find a task with an id.
Parameters:
id CONFIGURATION id (not a COMPONENT id!)
Definition at line 299 of file AliHLTSystem.cxx.
References fTaskList.
Referenced by BuildTaskList().
300 {
301   // see header file for class documentation
302   AliHLTTask* pTask=NULL;
303   if (id) {
304     pTask=(AliHLTTask*)fTaskList.FindObject(id); 
305   }
306   return pTask;
307 }
int AliHLTSystem::GetStatusFlags ()
Get the current status.
Returns: status flags of AliHLTSystemState_t(p.)
Definition at line 712 of file AliHLTSystem.cxx.
Referenced by Reconstruct().
713 {
714   // see header file for class documentation
715   return fState;
716 }
int AliHLTSystem::InitBenchmarking (TObjArray * pStopwatches)
Init the stopwatches for all tasks.
Parameters:
pStopwatches object array of stopwatches, for types
See also: AliHLTComponent::AliHLTStopwatchType(p.)
Returns: neg error code if failed
Definition at line 406 of file AliHLTSystem.cxx.
References fTaskList, AliHLTTask::GetComponent(), AliHLTComponent::GetComponentType(), HLTWarning, AliHLTComponent::SetStopwatch(), and AliHLTComponent::SetStopwatches().
Referenced by Run().
407 {
408   // see header file for class documentation
409   if (pStopwatches==NULL) return -EINVAL;
410 
411   int iResult=0;
412   TObjLink *lnk=fTaskList.FirstLink();
413   while (lnk && iResult>=0) {
414     TObject* obj=lnk->GetObject();
415     if (obj) {
416       AliHLTTask* pTask=(AliHLTTask*)obj;
417       AliHLTComponent* pComp=NULL;
418       if (iResult>=0 && (pComp=pTask->GetComponent())!=NULL) {
419         switch (pComp->GetComponentType()) {
420         case AliHLTComponent::kProcessor:
421           pComp->SetStopwatches(pStopwatches);
422           break;
423         case AliHLTComponent::kSource:
424           {
425             // this switch determines whether the time consumption of the
426             // AliHLTComponent base methods should be counted to the input
427             // stopwatch or base stopwatch.
428             //int inputBase=(int)AliHLTComponent::kSWBase;
429             int inputBase=(int)AliHLTComponent::kSWInput;
430             pComp->SetStopwatch(pStopwatches->At(inputBase), AliHLTComponent::kSWBase);
431             pComp->SetStopwatch(pStopwatches->At((int)AliHLTComponent::kSWInput), AliHLTComponent::kSWDA);
432           }
433           break;
434         case AliHLTComponent::kSink:
435           {
436             // this switch determines whether the time consumption of the
437             // AliHLTComponent base methods should be counted to the output
438             // stopwatch or base stopwatch.
439             //int outputBase=(int)AliHLTComponent::kSWBase;
440             int outputBase=(int)AliHLTComponent::kSWOutput;
441             pComp->SetStopwatch(pStopwatches->At(outputBase), AliHLTComponent::kSWBase);
442             pComp->SetStopwatch(pStopwatches->At((int)AliHLTComponent::kSWOutput), AliHLTComponent::kSWDA);
443           }
444           break;
445         default:
446           HLTWarning("unknown component type %d", (int)pComp->GetComponentType());
447         }
448       }
449     } else {
450     }
451     lnk = lnk->Next();
452   }
453   return iResult;
454 }
int AliHLTSystem::InitTasks ()
Init all tasks from the list. The AliHLTTask::Init(p.) method is called for each task, the components will be created.
Returns: neg error code if failed
Definition at line 383 of file AliHLTSystem.cxx.
References fpComponentHandler, fTaskList, HLTWarning, and AliHLTTask::Init().
Referenced by Run().
384 {
385   // see header file for class documentation
386   int iResult=0;
387   TObjLink *lnk=fTaskList.FirstLink();
388   if (lnk==NULL) {
389     HLTWarning("Task list is empty, aborting ...");
390     return -ENOENT;
391   }
392   while (lnk && iResult>=0) {
393     TObject* obj=lnk->GetObject();
394     if (obj) {
395       AliHLTTask* pTask=(AliHLTTask*)obj;
396       iResult=pTask->Init(NULL, fpComponentHandler);
397     } else {
398     }
399     lnk = lnk->Next();
400   }
401   if (iResult<0) {
402   }
403   return iResult;
404 }
int AliHLTSystem::InsertConfiguration (AliHLTConfiguration * pConf, AliHLTConfiguration * pPrec)
Insert a configuration to the end of the list after the specified configuration.
Parameters:
pConf pointer to configuration to insert
pPrec pointer to configuration to insert the new one after
Definition at line 139 of file AliHLTSystem.cxx.
140 {
141   // see header file for class documentation
142   int iResult=0;
143   if (pConf) {
144     if (pPrec) {
145       // find the position
146     }
147   } else {
148     iResult=-EINVAL;
149   }
150   return iResult;
151 }
int AliHLTSystem::InsertTask (AliHLTTask * pTask)
Insert a task to the task list. The method first checks whether all dependencies are resolved (i.e. exist already in the task list). During this iteration the cross links between the tasks are set as well. If all dependencies are resolved, the task is added at the end of the list.
Parameters:
pTask pointer to task to add
Definition at line 261 of file AliHLTSystem.cxx.
References AliHLTTask::CheckDependencies(), AliHLTTask::Depends(), fTaskList, AliHLTTask::GetName(), HLTDebug, HLTError, AliHLTTask::SetDependency(), and AliHLTTask::SetTarget().
Referenced by BuildTaskList().
262 {
263   // see header file for class documentation
264   int iResult=0;
265   TObjLink *lnk = NULL;
266   if ((iResult=pTask->CheckDependencies())>0)
267     lnk=fTaskList.FirstLink();
268   while (lnk && iResult>0) {
269     AliHLTTask* pCurr = (AliHLTTask*)lnk->GetObject();
270     //HLTDebug("checking  \"%s\"", pCurr->GetName());
271     iResult=pTask->Depends(pCurr);
272     if (iResult>0) {
273       iResult=pTask->SetDependency(pCurr);
274       pCurr->SetTarget(pTask);
275       HLTDebug("set dependency  \"%s\" for configuration \"%s\"", pCurr->GetName(), pTask->GetName());
276     }
277     if (pCurr->Depends(pTask)) {
278       // circular dependency
279       HLTError("circular dependency: can not resolve dependencies for configuration \"%s\"", pTask->GetName());
280       iResult=-ELOOP;
281     } else if ((iResult=pTask->CheckDependencies())>0) {
282       lnk = lnk->Next();
283     }
284   }
285   if (iResult==0) {
286       if (lnk) {
287         fTaskList.AddAfter(lnk, pTask);
288       } else {
289         fTaskList.AddFirst(pTask);
290       }
291       HLTDebug("task \"%s\" (%p) inserted (size %d)", pTask->GetName(), pTask, sizeof(AliHLTTask));
292   } else if (iResult>0) {
293     HLTError("can not resolve dependencies for configuration \"%s\" (%d unresolved)", pTask->GetName(), iResult);
294     iResult=-ENOLINK;
295   }
296   return iResult;
297 }
int AliHLTSystem::LoadComponentLibraries (const char * libs)
Load component libraries.
Parameters:
libs string of blank separated library names
Returns: neg. error code if failed
Definition at line 572 of file AliHLTSystem.cxx.
References ClearStatusFlags(), fpComponentHandler, HLTFatal, kLibrariesLoaded, AliHLTComponentHandler::LoadLibrary(), and SetStatusFlags().
Referenced by LoadConfigurations().
573 {
574   // see header file for class documentation
575   int iResult=0;
576   if (libraries) {
577     if (fpComponentHandler) {
578       TString libs(libraries);
579       TObjArray* pTokens=libs.Tokenize(" ");
580       if (pTokens) {
581         int iEntries=pTokens->GetEntries();
582         for (int i=0; i<iEntries && iResult>=0; i++) {
583           iResult=fpComponentHandler->LoadLibrary((((TObjString*)pTokens->At(i))->GetString()).Data());
584         }
585         delete pTokens;
586       }
587       if (iResult>=0) {
588         SetStatusFlags(kLibrariesLoaded);
589       } else {
590         // lets see if we need this, probably not
591         //fpComponentHandler->UnloadLibraries();
592         ClearStatusFlags(kLibrariesLoaded);
593       }
594     } else {
595       iResult=-EFAULT;
596       HLTFatal("no component handler available");
597     }
598   } else {
599     iResult=-EINVAL;
600   }
601   return iResult;
602 }
int AliHLTSystem::LoadConfigurations (AliRunLoader * runloader = NULL)
Load the configurations specified by the module agents. The runLoader is passed to the agent and allows configuration selection.
Returns: neg. error code if failed
Definition at line 641 of file AliHLTSystem.cxx.
References CheckStatus(), AliHLTModuleAgent::CreateConfigurations(), fpConfigurationHandler, AliHLTModuleAgent::GetFirstAgent(), AliHLTModuleAgent::GetNextAgent(), AliHLTModuleAgent::GetRequiredComponentLibraries(), HLTDebug, HLTError, kRunning, and LoadComponentLibraries().
Referenced by Configure().
642 {
643   // see header file for class documentation
644   if (CheckStatus(kRunning)) {
645     HLTError("HLT system in running state, can not configure");
646     return -EBUSY;
647   }
648   int iResult=0;
649   AliHLTModuleAgent* pAgent=AliHLTModuleAgent::GetFirstAgent();
650   while (pAgent && iResult>=0) {
651     const char* deplibs=pAgent->GetRequiredComponentLibraries();
652     if (deplibs) {
653       HLTDebug("load libraries \'%s\' for agent %s (%p)", deplibs, pAgent->GetName(), pAgent);
654       iResult=LoadComponentLibraries(deplibs);
655     }
656     if (iResult>=0) {
657       HLTDebug("load configurations for agent %s (%p)", pAgent->GetName(), pAgent);
658       pAgent->CreateConfigurations(fpConfigurationHandler, runloader);
659       pAgent=AliHLTModuleAgent::GetNextAgent();
660     }
661   }
662   return iResult;
663 }
AliHLTSystem & AliHLTSystem::operator= (const AliHLTSystem &)
not a valid assignment op, but defined according to effective C++ style
Definition at line 102 of file AliHLTSystem.cxx.
References HLTFatal.
103 { 
104   // see header file for class documentation
105   HLTFatal("assignment operator untested");
106   return *this;
107 }
void AliHLTSystem::PrintTaskList ()
Print the task list.
Definition at line 309 of file AliHLTSystem.cxx.
References fTaskList, HLTLogKeyword, HLTMessage, and AliHLTTask::PrintStatus().
310 {
311   // see header file for class documentation
312   HLTLogKeyword("task list");
313   TObjLink *lnk = NULL;
314   HLTMessage("Task List");
315   lnk=fTaskList.FirstLink();
316   while (lnk) {
317     TObject* obj=lnk->GetObject();
318     if (obj) {
319       HLTMessage("  %s - status:", obj->GetName());
320       AliHLTTask* pTask=(AliHLTTask*)obj;
321       pTask->PrintStatus();
322     } else {
323     }
324     lnk = lnk->Next();
325   }
326 }
int AliHLTSystem::ProcessTasks (Int_t eventNo)
Process task list. The AliHLTTask::ProcessTask(p.) method is called for each task.
Returns: neg error code if failed
Definition at line 475 of file AliHLTSystem.cxx.
References fTaskList, AliHLTTask::GetName(), HLTDebug, and AliHLTTask::ProcessTask().
Referenced by Run().
476 {
477   // see header file for class documentation
478   int iResult=0;
479   HLTDebug("processing event no %d", eventNo);
480   TObjLink *lnk=fTaskList.FirstLink();
481   while (lnk && iResult>=0) {
482     TObject* obj=lnk->GetObject();
483     if (obj) {
484       AliHLTTask* pTask=(AliHLTTask*)obj;
485       iResult=pTask->ProcessTask(eventNo);
486       HLTDebug("task %s finnished (%d)", pTask->GetName(), iResult);
487     } else {
488     }
489     lnk = lnk->Next();
490   }
491   return iResult;
492 }
int AliHLTSystem::Reconstruct (int nofEvents, AliRunLoader * runLoader, AliRawReader * rawReader = NULL)
Reconstruction inside AliRoot. To be called by the AliHLTReconstructor plugin during the LocalReconstruction step of the AliRoot reconstruction. The latter means that all events are reconstructed at once, the event loop is internally implemented. In contrast to that, the FillESD method is called event by event. This requires an 'ESD' recorder at the end of the HLT chain, in order to have the reconstructed events available for the FillESD loop. The 'runLoader' and 'rawReader' parameters are set to all active AliHLTOfflineDataSource's and the HLT chain is processed for the given number of events. If the rawReader is NULL, reconstruction is done on simulated data, from real data if a RawReader is specified.
Parameters:
nofEvents number of events
runLoader the AliRoot runloader
rawReader the AliRoot RawReader
Returns: number of reconstructed events, neg. error code if failed
Definition at line 537 of file AliHLTSystem.cxx.
References CheckStatus(), GetStatusFlags(), HLTError, HLTInfo, kReady, Run(), and AliHLTOfflineInterface::SetParamsToComponents().
539 {
540   // see header file for class documentation
541   int iResult=0;
542   if (runLoader) {
543     HLTInfo("Run Loader %p, Raw Reader %p , %d events", runLoader, rawReader, nofEvents);
544     if (CheckStatus(kReady)) {
545       if ((iResult=AliHLTOfflineInterface::SetParamsToComponents(runLoader, rawReader))>=0) {
546         iResult=Run(nofEvents);
547       }
548     } else {
549       HLTError("wrong state %#x, required flags %#x", GetStatusFlags(), kReady);
550     }
551   } else {
552     HLTError("missing run loader instance");
553     iResult=-EINVAL;
554   }
555   return iResult;
556 }
int AliHLTSystem::Reset (int bForce = 0)
Reset the HLT system. Reset is not possible while the system is in running state.
Parameters:
bForce force the reset
Returns: neg. error code if failed
 -EBUSY system is in kRunning state
Definition at line 628 of file AliHLTSystem.cxx.
References CheckStatus(), CleanTaskList(), ClearStatusFlags(), HLTError, kRunning, and kUninitialized.
629 {
630   // see header file for class documentation
631   int iResult=0;
632   if (!bForce && CheckStatus(kRunning)) {
633     HLTError("HLT system in running state, can not configure");
634     return -EBUSY;
635   }
636   CleanTaskList();
637   ClearStatusFlags(~kUninitialized);
638   return iResult;
639 }
int AliHLTSystem::Run (Int_t iNofEvents = 1)
Run the task list. The method checks whether the task list has already been build. If not, or the configuration list has been changed, the BuildTaskList(p.) method is scalled All tasks of the list will be subsequently processed for each event.
Parameters:
iNofEvents number of events
Returns: number of reconstructed events, neg error code if failed
Definition at line 328 of file AliHLTSystem.cxx.
References ClearStatusFlags(), DeinitTasks(), HLTError, HLTInfo, InitBenchmarking(), InitTasks(), kRunning, ProcessTasks(), SetStatusFlags(), StartTasks(), and StopTasks().
Referenced by Reconstruct().
329 {
330   // see header file for class documentation
331   int iResult=0;
332   int iCount=0;
333   SetStatusFlags(kRunning);
334   TStopwatch StopwatchBase; StopwatchBase.Reset();
335   TStopwatch StopwatchDA; StopwatchDA.Reset();
336   TStopwatch StopwatchInput; StopwatchInput.Reset();
337   TStopwatch StopwatchOutput; StopwatchOutput.Reset();
338   TObjArray Stopwatches;
339   Stopwatches.AddAt(&StopwatchBase, (int)AliHLTComponent::kSWBase);
340   Stopwatches.AddAt(&StopwatchDA, (int)AliHLTComponent::kSWDA);
341   Stopwatches.AddAt(&StopwatchInput, (int)AliHLTComponent::kSWInput);
342   Stopwatches.AddAt(&StopwatchOutput, (int)AliHLTComponent::kSWOutput);
343   if ((iResult=InitTasks())>=0 && (iResult=InitBenchmarking(&Stopwatches))>=0) {
344     if ((iResult=StartTasks())>=0) {
345       for (int i=0; i<iNofEvents && iResult>=0; i++) {
346         iResult=ProcessTasks(i);
347         if (iResult>=0) {
348           HLTInfo("Event %d successfully finished (%d)", i, iResult);
349           iResult=0;
350           iCount++;
351         } else {
352           HLTError("Processing of event %d failed (%d)", i, iResult);
353           // TODO: define different running modes to either ignore errors in
354           // event processing or not
355           // currently ignored 
356           //iResult=0;
357         }
358       }
359       StopTasks();
360     } else {
361       HLTError("can not start task list");
362     }
363     DeinitTasks();
364   } else if (iResult!=-ENOENT) {
365     HLTError("can not initialize task list");
366   }
367   if (iResult>=0) {
368     iResult=iCount;
369     HLTInfo("HLT statistics:\n"
370             "    base:              R:%.3fs C:%.3fs\n"
371             "    input:             R:%.3fs C:%.3fs\n"
372             "    output:            R:%.3fs C:%.3fs\n"
373             "    event processing : R:%.3fs C:%.3fs"
374             , StopwatchBase.RealTime(),StopwatchBase.CpuTime()
375             , StopwatchInput.RealTime(),StopwatchInput.CpuTime()
376             , StopwatchOutput.RealTime(),StopwatchOutput.CpuTime()
377             , StopwatchDA.RealTime(),StopwatchDA.CpuTime());
378   }
379   ClearStatusFlags(kRunning);
380   return iResult;
381 }
int AliHLTSystem::SetStatusFlags (int flags) [private]
Set status flags.
Definition at line 718 of file AliHLTSystem.cxx.
References fState.
Referenced by BuildTaskListsFromTopConfigurations(), Configure(), LoadComponentLibraries(), and Run().
719 {
720   // see header file for class documentation
721   fState|=flags;
722   return fState;
723 }
int AliHLTSystem::StartTasks ()
Start task list. The AliHLTTask::StartRun(p.) method is called for each task, the components will be prepared for event processing.
Returns: neg error code if failed
Definition at line 456 of file AliHLTSystem.cxx.
References fTaskList, and AliHLTTask::StartRun().
Referenced by Run().
457 {
458   // see header file for class documentation
459   int iResult=0;
460   TObjLink *lnk=fTaskList.FirstLink();
461   while (lnk && iResult>=0) {
462     TObject* obj=lnk->GetObject();
463     if (obj) {
464       AliHLTTask* pTask=(AliHLTTask*)obj;
465       iResult=pTask->StartRun();
466     } else {
467     }
468     lnk = lnk->Next();
469   }
470   if (iResult<0) {
471   }
472   return iResult;
473 }
int AliHLTSystem::StopTasks ()
Stop task list. The AliHLTTask::EndRun(p.) method is called for each task, the components will be cleaned after event processing.
Returns: neg error code if failed
Definition at line 494 of file AliHLTSystem.cxx.
References AliHLTTask::EndRun(), and fTaskList.
Referenced by Run().
495 {
496   // see header file for class documentation
497   int iResult=0;
498   TObjLink *lnk=fTaskList.FirstLink();
499   while (lnk && iResult>=0) {
500     TObject* obj=lnk->GetObject();
501     if (obj) {
502       AliHLTTask* pTask=(AliHLTTask*)obj;
503       iResult=pTask->EndRun();
504     } else {
505     }
506     lnk = lnk->Next();
507   }
508   return iResult;
509 }
Member Data Documentation
int AliHLTSystem::fgNofInstances = 0 [static, private]
the number of instances of AliHLTSystem
Definition at line 126 of file AliHLTSystem.cxx.
Referenced by AliHLTSystem(), and ~AliHLTSystem().
AliHLTComponentHandler* AliHLTSystem::fpComponentHandler
Pointer to an instance of AliHLTComponentHandler(p.).
Definition at line 57 of file AliHLTSystem.h.
Referenced by FindDynamicSymbol(), InitTasks(), LoadComponentLibraries(), and ~AliHLTSystem().
AliHLTConfigurationHandler* AliHLTSystem::fpConfigurationHandler
transient
Pointer to an instance of AliHLTConfigurationHandler(p.).
Definition at line 62 of file AliHLTSystem.h.
Referenced by BuildTaskList(), BuildTaskListsFromTopConfigurations(), LoadConfigurations(), and ~AliHLTSystem().
int AliHLTSystem::fState [private]
state of the object
Definition at line 324 of file AliHLTSystem.h.
Referenced by CheckStatus(), ClearStatusFlags(), and SetStatusFlags().
TList AliHLTSystem::fTaskList [private]
list of tasks
Definition at line 318 of file AliHLTSystem.h.
Referenced by BuildTaskList(), CleanTaskList(), DeinitTasks(), FindTask(), InitBenchmarking(), InitTasks(), InsertTask(), PrintTaskList(), ProcessTasks(), StartTasks(), and StopTasks().
The documentation for this class was generated from the following files:
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTSystem.h
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTSystem.cxx