AliHLTConfigurationHandler Class Reference
#include <AliHLTConfigurationHandler.h>
Detailed Description
Global Handling of HLT configurations.
This class implements the global handling of AliHLTConfiguration(p.) objects. It is a list of all configuartion descriptor currently available in the system. Each AliHLTConfiguration(p.) object is registerd automatically with the handler and put into the list.
Note: This class is only used for the HLT integration into AliRoot(p.).
Definition at line 31 of file AliHLTConfigurationHandler.h.
Public Member Functions
AliHLTConfigurationHandler ()
virtual ~AliHLTConfigurationHandler ()
int RegisterConfiguration (AliHLTConfiguration *pConf)
int CreateConfiguration (const char *id, const char *component, const char *sources, const char *arguments)
int RemoveConfiguration (AliHLTConfiguration *pConf)
int RemoveConfiguration (const char *id)
AliHLTConfiguration * FindConfiguration (const char *id)
void PrintConfigurations ()
Private Member Functions
ClassDef (AliHLTConfigurationHandler, 1)
Private Attributes
TList fgListConfigurations
Constructor & Destructor Documentation
AliHLTConfigurationHandler::AliHLTConfigurationHandler ()
standard constructor
AliHLTConfigurationHandler::~AliHLTConfigurationHandler () [virtual]
destructor
Definition at line 1076 of file AliHLTConfiguration.cxx.
References fgListConfigurations, AliHLTConfiguration::GetName(), and HLTDebug.
1077 {
1078   // see header file for function documentation
1079   TObjLink* lnk=NULL;
1080   while (lnk=fgListConfigurations.FirstLink()) {
1081     AliHLTConfiguration* pConf=(AliHLTConfiguration*)lnk->GetObject();
1082     HLTDebug("delete configuration \"%s\"", pConf->GetName());
1083     fgListConfigurations.Remove(lnk);
1084     delete pConf;
1085   }
1086 }
Member Function Documentation
AliHLTConfigurationHandler::ClassDef (AliHLTConfigurationHandler, 1) [private]
int AliHLTConfigurationHandler::CreateConfiguration (const char * id, const char * component, const char * sources, const char * arguments)
Create a configuration and register it.
Parameters:
id
component
sources
arguments
Definition at line 1117 of file AliHLTConfiguration.cxx.
References FindConfiguration(), and HLTError.
1118 {
1119   // see header file for function documentation
1120   int iResult=0;
1121   AliHLTConfiguration* pConf= new AliHLTConfiguration(id, component, sources, arguments);
1122   if (pConf) {
1123     // the configuration will be registered automatically, if this failes the configuration
1124     // is missing -> delete it
1125     if (FindConfiguration(id)==NULL) {
1126       delete pConf;
1127       pConf=NULL;
1128       iResult=-EEXIST;
1129     }
1130   } else {
1131     HLTError("system error: object allocation failed");
1132     iResult=-ENOMEM;
1133   }
1134   return iResult;
1135 }
AliHLTConfiguration * AliHLTConfigurationHandler::FindConfiguration (const char * id)
Find a configuration from the global list.
Parameters:
id Id of the configuration to find
Definition at line 1193 of file AliHLTConfiguration.cxx.
References fgListConfigurations.
Referenced by AliHLTSystem::BuildTaskList(), AliHLTSystem::BuildTaskListsFromTopConfigurations(), CreateConfiguration(), AliHLTConfiguration::ExtractSources(), RegisterConfiguration(), RemoveConfiguration(), and AliHLTConfiguration::~AliHLTConfiguration().
1194 {
1195   // see header file for function documentation
1196   AliHLTConfiguration* pConf=NULL;
1197   if (id) {
1198     pConf=(AliHLTConfiguration*)fgListConfigurations.FindObject(id); 
1199   }
1200   return pConf;
1201 }
void AliHLTConfigurationHandler::PrintConfigurations ()
Print the registered configurations to the logging function.
Definition at line 1137 of file AliHLTConfiguration.cxx.
References fgListConfigurations, HLTLogKeyword, and HLTMessage.
1138 {
1139   // see header file for function documentation
1140   HLTLogKeyword("configuration listing");
1141   HLTMessage("registered configurations:");
1142   TObjLink *lnk = fgListConfigurations.FirstLink();
1143   while (lnk) {
1144     TObject *obj = lnk->GetObject();
1145     HLTMessage("  %s", obj->GetName());
1146     lnk = lnk->Next();
1147   }
1148 }
int AliHLTConfigurationHandler::RegisterConfiguration (AliHLTConfiguration * pConf)
Register a configuration to the global list of configurations.
Parameters:
pConf The configuration to register
Definition at line 1088 of file AliHLTConfiguration.cxx.
References fgListConfigurations, FindConfiguration(), AliHLTConfiguration::GetName(), HLTDebug, HLTWarning, AliHLTConfiguration::InvalidateSources(), and AliHLTConfiguration::SourcesResolved().
Referenced by AliHLTConfiguration::AliHLTConfiguration().
1089 {
1090   // see header file for function documentation
1091   int iResult=0;
1092   if (pConf) {
1093     if (FindConfiguration(pConf->GetName()) == NULL) {
1094       AliHLTConfiguration* pClone=new AliHLTConfiguration(*pConf);
1095       fgListConfigurations.Add(pClone);
1096       HLTDebug("configuration \"%s\" (%p) registered from %p", pClone->GetName(), pClone, pConf);
1097 
1098       // mark all configurations with unresolved dependencies for re-evaluation
1099       TObjLink* lnk=fgListConfigurations.FirstLink();
1100       while (lnk) {
1101         AliHLTConfiguration* pSrc=(AliHLTConfiguration*)lnk->GetObject();
1102         if (pSrc && pSrc!=pClone && pSrc->SourcesResolved()!=1) {
1103           pSrc->InvalidateSources();
1104         }
1105         lnk=lnk->Next();
1106       }
1107     } else {
1108       iResult=-EEXIST;
1109       HLTWarning("configuration \"%s\" already registered", pConf->GetName());
1110     }
1111   } else {
1112     iResult=-EINVAL;
1113   }
1114   return iResult;
1115 }
int AliHLTConfigurationHandler::RemoveConfiguration (const char * id)
Remove a configuration from the global list.
Parameters:
id The configuration to remove
Definition at line 1150 of file AliHLTConfiguration.cxx.
References FindConfiguration(), HLTWarning, and RemoveConfiguration().
1151 {
1152   // see header file for function documentation
1153   int iResult=0;
1154   if (id) {
1155     AliHLTConfiguration* pConf=NULL;
1156     if ((pConf=FindConfiguration(id))!=NULL) {
1157       iResult=RemoveConfiguration(pConf);
1158       delete pConf;
1159       pConf=NULL;
1160     } else {
1161       HLTWarning("can not find configuration \"%s\"", id);
1162       iResult=-ENOENT;
1163     }
1164   } else {
1165     iResult=-EINVAL;
1166   }
1167   return iResult;
1168 }
int AliHLTConfigurationHandler::RemoveConfiguration (AliHLTConfiguration * pConf)
Remove a configuration from the global list.
Parameters:
pConf The configuration to remove
Definition at line 1170 of file AliHLTConfiguration.cxx.
References fgListConfigurations, AliHLTConfiguration::GetName(), HLTDebug, and AliHLTConfiguration::InvalidateSource().
Referenced by RemoveConfiguration(), and AliHLTConfiguration::~AliHLTConfiguration().
1171 {
1172   // see header file for function documentation
1173   int iResult=0;
1174   if (pConf) {
1175     // remove the configuration from the list
1176     HLTDebug("remove configuration \"%s\"", pConf->GetName());
1177     fgListConfigurations.Remove(pConf);
1178     // remove cross links in the remaining configurations
1179     TObjLink* lnk=fgListConfigurations.FirstLink();
1180     while (lnk && iResult>=0) {
1181       AliHLTConfiguration* pRem=(AliHLTConfiguration*)lnk->GetObject();
1182       if (pRem) {
1183         pRem->InvalidateSource(pConf);
1184       } else {
1185         iResult=-EFAULT;
1186       }
1187       lnk=lnk->Next();
1188     }
1189   }
1190   return iResult;
1191 }
Member Data Documentation
TList AliHLTConfigurationHandler::fgListConfigurations [private]
the list of registered configurations
Definition at line 86 of file AliHLTConfigurationHandler.h.
Referenced by FindConfiguration(), PrintConfigurations(), RegisterConfiguration(), RemoveConfiguration(), and ~AliHLTConfigurationHandler().
The documentation for this class was generated from the following files:
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTConfigurationHandler.h
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTConfiguration.cxx