AliHLTPHOSModuleMergerComponent Class Reference
#include <AliHLTPHOSModuleMergerComponent.h>
Public Member Functions
AliHLTPHOSModuleMergerComponent ()
virtual ~AliHLTPHOSModuleMergerComponent ()
AliHLTPHOSModuleMergerComponent (const AliHLTPHOSModuleMergerComponent &)
AliHLTPHOSModuleMergerComponent & operator= (const AliHLTPHOSModuleMergerComponent &)
virtual int DoInit (int argc=0, const char **argv=0)
virtual int Deinit ()
virtual int DoDeinit ()
virtual int DoEvent (const AliHLTComponentEventData &evtData, const AliHLTComponentBlockData *blocks, AliHLTComponentTriggerData &trigData, AliHLTUInt8_t *outputPtr, AliHLTUInt32_t &size, vector< AliHLTComponentBlockData > &outputBlocks)
void DumpData (int gain=0)
int GetEquippmentId ()
virtual const char * GetComponentID ()
virtual void GetInputDataTypes (std::vector< AliHLTComponentDataType > &)
virtual AliHLTComponentDataType GetOutputDataType ()
virtual void GetOutputDataSize (unsigned long &constBase, double &inputMultiplier)
void SetEquippmentId (int id=0)
virtual AliHLTComponent * Spawn ()
Protected Member Functions
void Reset ()
void ResetDataPtr ()
Private Attributes
int fEventCount
AliHLTUInt32_t fEquippmentID
Double_t fTmpChannelData [ALTRO_MAX_SAMPLES]
Double_t fMaxValues [N_MODULES][N_ROWS_MOD][N_COLUMNS_MOD][N_GAINS]
Static Private Attributes
const AliHLTComponentDataType fgkInputDataTypes [] = {kAliHLTVoidDataType,{0,``,``}}
const AliHLTComponentDataType fgkOutputDataType = kAliHLTVoidDataType
Constructor & Destructor Documentation
AliHLTPHOSModuleMergerComponent::AliHLTPHOSModuleMergerComponent ()
Definition at line 31 of file AliHLTPHOSModuleMergerComponent.cxx.
31                                                                  :AliHLTProcessor(),  fEventCount(0),  fEquippmentID(0)
32 {
33 
34 } 
AliHLTPHOSModuleMergerComponent::~AliHLTPHOSModuleMergerComponent () [virtual]
Definition at line 37 of file AliHLTPHOSModuleMergerComponent.cxx.
38 {
39 
40 }
AliHLTPHOSModuleMergerComponent::AliHLTPHOSModuleMergerComponent (const AliHLTPHOSModuleMergerComponent &)
Definition at line 43 of file AliHLTPHOSModuleMergerComponent.cxx.
43                                                                                                           : AliHLTProcessor(),  fEventCount(0),  fEquippmentID(0)
44 {
45 
46 }
Member Function Documentation
int AliHLTPHOSModuleMergerComponent::Deinit () [virtual]
Clean-up function to terminate data processing. Clean-up of common data structures after data processing. The call is redirected to the internal method DoDeinit(p.) which can be overridden by the child class.
Reimplemented from AliHLTProcessor (p.).
Definition at line 50 of file AliHLTPHOSModuleMergerComponent.cxx.
51 {
52   return 0;
53 }
int AliHLTPHOSModuleMergerComponent::DoDeinit () [virtual]
Default method for the internal clean-up. The method is called by Deinit(p.)
Reimplemented from AliHLTComponent (p.).
Definition at line 57 of file AliHLTPHOSModuleMergerComponent.cxx.
References kHLTLogInfo, and AliHLTLogging::Logging().
58 {
59   Logging(kHLTLogInfo, "HLT", "PHOS", ",AliHLTPHOSModuleMerger DoDeinit");
60   return 0;
61 
62 }
int AliHLTPHOSModuleMergerComponent::DoEvent (const AliHLTComponentEventData & evtData, const AliHLTComponentBlockData * blocks, AliHLTComponentTriggerData & trigData, AliHLTUInt8_t * outputPtr, AliHLTUInt32_t & size, vector< AliHLTComponentBlockData > & outputBlocks) [virtual]
The low-level data processing method for the component. This is the custom processing method and can be overloaded by the component.
Parameters:
evtData event data structure
blocks input data block descriptors
trigData trigger data structure
outputPtr pointer to target buffer
size input: size of target buffer output:size of produced data
outputBlocks list to receive output block descriptors
Returns: neg. error code if failed
Reimplemented from AliHLTProcessor (p.).
Definition at line 102 of file AliHLTPHOSModuleMergerComponent.cxx.
References DumpData(), AliHLTComponentEventData::fBlockCnt, AliHLTPHOSRcuCellEnergyDataStruct::fCnt, AliHLTPHOSValidCellDataStruct::fEnergy, fEventCount, AliHLTPHOSValidCellDataStruct::fGain, fMaxValues, AliHLTPHOSRcuCellEnergyDataStruct::fModuleID, AliHLTComponentBlockData::fPtr, AliHLTPHOSRcuCellEnergyDataStruct::fRcuX, AliHLTPHOSRcuCellEnergyDataStruct::fRcuZ, AliHLTPHOSRcuCellEnergyDataStruct::fValidData, AliHLTPHOSValidCellDataStruct::fX, AliHLTPHOSValidCellDataStruct::fZ, N_COLUMNS_RCU, N_ROWS_RCU, N_XCOLUMNS_RCU, N_ZROWS_RCU, and Reset().
105 {
106   //Merging of data from 4 RCUS to one module
107   
108   unsigned long ndx;
109   const AliHLTComponentBlockData* iter = NULL;   
110   AliHLTPHOSRcuCellEnergyDataStruct *cellDataPtr;
111 
112   Reset();
113 
114   for( ndx = 0; ndx < evtData.fBlockCnt; ndx++ )
115     {
116       int tmpModuleID = 0;
117       int tmpRcuX = 0;
118       int tmpRcuZ = 0;
119       int tmpCnt =  cellDataPtr->fCnt;
120       iter = blocks+ndx;
121       AliHLTPHOSRcuCellEnergyDataStruct *cellDataPtr = (AliHLTPHOSRcuCellEnergyDataStruct*)( iter->fPtr);
122       tmpModuleID = cellDataPtr->fModuleID;
123       tmpRcuX     = cellDataPtr->fRcuX ;
124       tmpRcuZ     = cellDataPtr->fRcuZ;
125 
126       for(int i= 0; i< tmpCnt; tmpCnt ++)
127         {
128           if(cellDataPtr->fValidData[i].fGain == HIGH_GAIN)
129             {
130               fMaxValues[tmpModuleID][ cellDataPtr->fValidData[i].fZ +  N_ZROWS_RCU*tmpRcuZ][ cellDataPtr->fValidData[i].fX + N_XCOLUMNS_RCU*tmpRcuX][HIGH_GAIN] =  cellDataPtr->fValidData[i].fEnergy;
131             }
132           else if(cellDataPtr->fValidData[i].fGain == LOW_GAIN)
133             {
134               fMaxValues[tmpModuleID][ cellDataPtr->fValidData[i].fZ +  N_ROWS_RCU*tmpRcuZ][ cellDataPtr->fValidData[i].fX +N_COLUMNS_RCU*tmpRcuX][LOW_GAIN] =  cellDataPtr->fValidData[i].fEnergy;
135             }
136         }
137       
138     }
139 
140   DumpData(1);
141   fEventCount++; 
142   return 0;
143   
144 }//end DoEvent
int AliHLTPHOSModuleMergerComponent::DoInit (int argc = 0, const char ** argv = 0) [virtual]
Default method for the internal initialization. The method is called by Init(p.)
Reimplemented from AliHLTComponent (p.).
Definition at line 148 of file AliHLTPHOSModuleMergerComponent.cxx.
References Reset().
149 {
150   //See base classs for documenation
151   Reset();
152 
153   if (argc==0 && argv==NULL) {
154     // this is currently just to get rid of the warning "unused parameter"
155   }
156   return 0;
157 }
void AliHLTPHOSModuleMergerComponent::DumpData (int gain = 0)
Definition at line 161 of file AliHLTPHOSModuleMergerComponent.cxx.
References fMaxValues, and N_GAINS.
Referenced by DoEvent().
162 {
163   if(gain < 0 || gain >  N_GAINS)
164     {
165       cout <<"AliHLTPHOSModuleMergerComponent::DumpDat: Error, gain must be between " << 0 << "and" << N_GAINS << endl;
166     }
167   
168   for(int mod = 0; mod < N_MODULES; mod ++)
169     {
170       if(gain == HIGH_GAIN)
171         {
172           cout << endl <<" ***********  MODULE" << mod << "****HIGH_GAIN" <<"************" << endl;
173         }
174       else if(gain == LOW_GAIN)
175         {
176           cout << endl <<" ***********  MODULE" << mod << "****LOW_GAIN" <<"************" << endl;
177         }
178       
179       for(int row = 0; row < N_ROWS_MOD; row ++)
180         {
181           for(int col = 0; col < N_COLUMNS_MOD; col ++)
182             {
183                       if( fMaxValues[mod][row][col][0] != 0)
184                 { 
185                                   cout << fMaxValues[mod][row][col][0] << "\t";
186                 }
187             }
188         } 
189     }
190 }
const char * AliHLTPHOSModuleMergerComponent::GetComponentID () [virtual]
Get the id of the component. Each component is identified by a unique id. The function is pure virtual and must be implemented by the child class.
Returns: component id (string)
Implements AliHLTComponent (p.).
Definition at line 66 of file AliHLTPHOSModuleMergerComponent.cxx.
67 {
68   return "ModuleMerger";
69 }
int AliHLTPHOSModuleMergerComponent::GetEquippmentId ()
Definition at line 235 of file AliHLTPHOSModuleMergerComponent.cxx.
236 {
237   return  fEquippmentID;
238 }
void AliHLTPHOSModuleMergerComponent::GetInputDataTypes (std::vector< AliHLTComponentDataType > &) [virtual]
Definition at line 73 of file AliHLTPHOSModuleMergerComponent.cxx.
References AliHLTComponentDataType::fID.
74 {
76   const AliHLTComponentDataType* pType=fgkInputDataTypes;
77   while (pType->fID!=0) 
78     {
79       list.push_back(*pType);
80       pType++;
81     }
82 }
void AliHLTPHOSModuleMergerComponent::GetOutputDataSize (unsigned long & constBase, double & inputMultiplier) [virtual]
Get a ratio by how much the data volume is shrinked or enhanced. The function is pure virtual and must be implemented by the child class.
Parameters:
constBase return: additive part, independent of the input data volume
inputMultiplier return: multiplication ratio
Returns: values in the reference variables
Implements AliHLTComponent (p.).
Definition at line 94 of file AliHLTPHOSModuleMergerComponent.cxx.
95 {
97   constBase = 30;
98   inputMultiplier = 1;
99 }
AliHLTComponentDataType AliHLTPHOSModuleMergerComponent::GetOutputDataType () [virtual]
Get the output data type of the component. The function is pure virtual and must be implemented by the child class.
Returns: output data type
Implements AliHLTComponent (p.).
Definition at line 86 of file AliHLTPHOSModuleMergerComponent.cxx.
87 {
89   return AliHLTPHOSDefinitions::gkCellEnergyDataType;
90 }
AliHLTPHOSModuleMergerComponent& AliHLTPHOSModuleMergerComponent::operator= (const AliHLTPHOSModuleMergerComponent &) [inline]
Definition at line 17 of file AliHLTPHOSModuleMergerComponent.h.
18     {
19       return *this;
20    };
void AliHLTPHOSModuleMergerComponent::Reset () [protected]
Definition at line 195 of file AliHLTPHOSModuleMergerComponent.cxx.
References fMaxValues, and fTmpChannelData.
Referenced by DoEvent(), and DoInit().
196 {
197   for(int mod = 0; mod < N_MODULES; mod ++)
198     {
199       for(int row = 0; row <  N_ROWS_MOD; row ++)
200         {
201           for(int col = 0; col < N_COLUMNS_MOD; col ++)
202             {
203               for(int gain = 0; gain < N_GAINS; gain ++ )
204                 { 
205 
206                   fMaxValues[mod][row][col][gain] = 0;
207                 }
208             }
209         }
210     }
211 
212   for(int i = 0 ; i<  ALTRO_MAX_SAMPLES; i++)
213     {
214       fTmpChannelData[i] = 0;
215     }
216 } // end Reset
void AliHLTPHOSModuleMergerComponent::ResetDataPtr () [protected]
Definition at line 219 of file AliHLTPHOSModuleMergerComponent.cxx.
References fTmpChannelData.
220 {
221   for(int i = 0 ; i<  ALTRO_MAX_SAMPLES; i++)
222     {
223       fTmpChannelData[i] = 0;
224     }
225 }
void AliHLTPHOSModuleMergerComponent::SetEquippmentId (int id = 0)
Definition at line 229 of file AliHLTPHOSModuleMergerComponent.cxx.
References fEquippmentID.
230 {
231   fEquippmentID = id;
232 }
AliHLTComponent * AliHLTPHOSModuleMergerComponent::Spawn () [virtual]
Spawn function. Each component must implement a spawn function to create a new instance of the class. Basically the function must return new my_class_name.
Returns: new class instance
Implements AliHLTComponent (p.).
Definition at line 242 of file AliHLTPHOSModuleMergerComponent.cxx.
243 {
244   return new AliHLTPHOSModuleMergerComponent;
245 }
Member Data Documentation
AliHLTUInt32_t AliHLTPHOSModuleMergerComponent::fEquippmentID [private]
Eguippment ID as given by ALICE
Definition at line 46 of file AliHLTPHOSModuleMergerComponent.h.
Referenced by SetEquippmentId().
int AliHLTPHOSModuleMergerComponent::fEventCount [private]
event counter
Reimplemented from AliHLTComponent (p.).
Definition at line 45 of file AliHLTPHOSModuleMergerComponent.h.
Referenced by DoEvent().
const AliHLTComponentDataType AliHLTPHOSModuleMergerComponent::fgkInputDataTypes = {kAliHLTVoidDataType,{0,``,``}} [static, private]
The input datatypes the component can recieve (obsolete ?)
Definition at line 26 of file AliHLTPHOSModuleMergerComponent.cxx.
const AliHLTComponentDataType AliHLTPHOSModuleMergerComponent::fgkOutputDataType = kAliHLTVoidDataType [static, private]
The type of date the compnent writes to shared memory
Definition at line 27 of file AliHLTPHOSModuleMergerComponent.cxx.
Double_t AliHLTPHOSModuleMergerComponent::fMaxValues[N_MODULES][N_ROWS_MOD][N_COLUMNS_MOD][N_GAINS] [private]
Tower/Crystal energies
Definition at line 48 of file AliHLTPHOSModuleMergerComponent.h.
Referenced by DoEvent(), DumpData(), and Reset().
Double_t AliHLTPHOSModuleMergerComponent::fTmpChannelData[ALTRO_MAX_SAMPLES] [private]
Array to tmporarily store samples from a single ALTRO
Definition at line 47 of file AliHLTPHOSModuleMergerComponent.h.
Referenced by Reset(), and ResetDataPtr().
The documentation for this class was generated from the following files:
AliHLTPHOSModuleMergerComponent.h
AliHLTPHOSModuleMergerComponent.cxx