AliHLTPHOSRawAnalyzerLMS Class Reference
#include <AliHLTPHOSRawAnalyzerLMS.h>
Public Member Functions
AliHLTPHOSRawAnalyzerLMS ()
AliHLTPHOSRawAnalyzerLMS (double *dataPtr, double fs)
AliHLTPHOSRawAnalyzerLMS (const AliHLTPHOSRawAnalyzerLMS &)
AliHLTPHOSRawAnalyzerLMS & operator= (const AliHLTPHOSRawAnalyzerLMS)
virtual ~AliHLTPHOSRawAnalyzerLMS ()
virtual void Evaluate (int start=0, int lenght=100)
void BaselineCorrection (double *dataPtr, int N)
void BaselineCorrection (double *dataPtr, double baselineValue)
int FindStartIndex (double treshold)
float GetTiming ()
float GetEnergy ()
void SetData (double *data)
void SetSampleFreq (double freq)
void SetStartIndex (int startIndex)
void MakeInitialGuess ()
void MakeInitialGuess (int treshold)
virtual void SetTVector (Double_t *tVector, Int_t size)
virtual void SetAVector (Double_t *aVector, Int_t size)
Double_t GetMaxValue (Double_t *dta, Int_t size)
Protected Attributes
Double_t * fFloatDataPtr
double fSampleFrequency
double fDTofGuess
double fDAmplGuess
double fTau
double fDTof
double fDAmpl
int fStartIndex
Private Attributes
double kfMCovarPtrPtr [1008][1008]
double fPCovarPtrPtr [1008][1008]
Constructor & Destructor Documentation
AliHLTPHOSRawAnalyzerLMS::AliHLTPHOSRawAnalyzerLMS ()
The AliHLTPHOSPeakfinder class is the class for extracting the basic signal parameters `timing` and `energy` from the PHOS raw data. Physical data will for a given readout channel be a sequense of ADC digitized 10 bit integer values, however for performance reasons all values used in calculation is of type double.
Definition at line 38 of file AliHLTPHOSRawAnalyzerLMS.cxx.
38                                                   :AliHLTPHOSRawAnalyzer() 
39 {
40   cout <<"You cannot invoke the Fitter without arguments"<<endl;;
41 }
AliHLTPHOSRawAnalyzerLMS::AliHLTPHOSRawAnalyzerLMS (double * dtaPtr, double fs)
Main constructor
Parameters:
dataPtr Data array for wich a subarray will be taken to perform the fit
fs the sampling frequency in entities of MHz. Needed in order to calculate physical time
Definition at line 49 of file AliHLTPHOSRawAnalyzerLMS.cxx.
49                                                                            :AliHLTPHOSRawAnalyzer() 
50 {
51   fFloatDataPtr = dtaPtr;  
52   fSampleFrequency = fs;
53 } //end   AliHLTPHOSRawAnalyzerLMS 
AliHLTPHOSRawAnalyzerLMS::AliHLTPHOSRawAnalyzerLMS (const AliHLTPHOSRawAnalyzerLMS &)
AliHLTPHOSRawAnalyzerLMS::~AliHLTPHOSRawAnalyzerLMS () [virtual]
Definition at line 56 of file AliHLTPHOSRawAnalyzerLMS.cxx.
57 {
58 
59 } //end AliHLTPHOSRawAnalyzerLMS
Member Function Documentation
void AliHLTPHOSRawAnalyzer::BaselineCorrection (double * dataPtr, double baselineValue) [inherited]
Shifts the baseline with the amount given by baselineValue If pretrigger samples are not present then the basline correction will be incorrect.
Parameters:
dataPtr array for wich to correct the basline
BaslineValue the basline value to subtract..
Definition at line 75 of file AliHLTPHOSRawAnalyzer.cxx.
References AliHLTPHOSRawAnalyzer::fFloatDataPtr.
76 {
77   fFloatDataPtr = dataPtr;   
78   printf("\nbaselineValue = %f\n", baselineValue);
79   cout << "Baseline correction not yet implemeted" << endl;
80 } //end BaslineCorrection
void AliHLTPHOSRawAnalyzer::BaselineCorrection (double * dataPtr, int N) [inherited]
Attemps to level the basline to zero. The baseline will be calculated from the pretrigger samples and subtracted from the data array. If pretrigger samples are not present then the basline correction will be incorrect.
Parameters:
dataPtr array for wich to correct the basline
N the number of pretrigger samples used to calculate the baseline.
Definition at line 60 of file AliHLTPHOSRawAnalyzer.cxx.
References AliHLTPHOSRawAnalyzer::fFloatDataPtr.
61 {
62   fFloatDataPtr = dataPtr;  
63   //  n=N;
64   cout << "Baseline correction not yet implemeted" << endl;
65 } //end BaselineCorrection
void AliHLTPHOSRawAnalyzerLMS::Evaluate (int start = 0, int length = 100) [virtual]
Extraction of timing and energy using the Peakfinde Algorithm. The. The parameters `start` and `length` defines a sub array of the data array that will be used for the the fit. If start+length must not exeed the total length of the Data array. `start` must be chosen as close as possible to t0. The baseline must also be subtracted. The length of `tVector` and `aVector` mus be equal to length. `index + length` must not exeed the length of the data array set in the constructor.
Parameters:
start the start index of the subarray of the data array.
length the number of samples to use starting from index
Implements AliHLTPHOSRawAnalyzer (p.).
Definition at line 74 of file AliHLTPHOSRawAnalyzerLMS.cxx.
75 {
76   /*
77 
78   */
79 
80   //thats all 
81 } //end FitLMS
int AliHLTPHOSRawAnalyzer::FindStartIndex (double treshold) [inherited]
Definition at line 124 of file AliHLTPHOSRawAnalyzer.cxx.
125 {
126   printf("\ntreshold = %f \n", treshold);
127   cout << "Find Start index not yet implemented" << endl;
128   return 0;
129 } //end FindStartIndex
float AliHLTPHOSRawAnalyzer::GetEnergy () [inherited]
Gives the time in entities of ADC channels (quantization levels). Absolute enrgy is found by multiplying with offline calibration constants.
Definition at line 99 of file AliHLTPHOSRawAnalyzer.cxx.
Referenced by main().
100 {
101   return fDAmpl;
102 } //end GetEnergy
Double_t AliHLTPHOSRawAnalyzer::GetMaxValue (Double_t * dta, Int_t size) [inherited]
Definition at line 176 of file AliHLTPHOSRawAnalyzer.cxx.
177 {
178 
179   Double_t tmpMax = 0;
180 
181   for(int i = 0; i < size; i++)
182     {
183       if(dta[i] > tmpMax)
184         {
185           tmpMax = dta[i];
186         }
187 
188     }
189   
190   return tmpMax;
191 
192 }
float AliHLTPHOSRawAnalyzer::GetTiming () [inherited]
Gives the timing in entities of sample indexes Physical time is found by multiplying with the sampling intervall (Ts).
Definition at line 88 of file AliHLTPHOSRawAnalyzer.cxx.
Referenced by main().
89 {
90   return fDTof;
91 } //end GetTiming
void AliHLTPHOSRawAnalyzer::MakeInitialGuess (int treshold) [inherited]
This function applies only to the Chi and Least mean square fit. An initial guess is made based on the average of the first 5 samples and the first value exeeding threshold + this value.
Parameters:
treshold The index of the first value above treshold is ntaken to be the first value.
Definition at line 149 of file AliHLTPHOSRawAnalyzer.cxx.
150 {
151   printf("\ntreshold = %d\n", treshold);
152   cout << "Make initial guess not yet implemeted" << endl;  
153 }
void AliHLTPHOSRawAnalyzer::MakeInitialGuess () [inherited]
This function applies only to the Chi and Least mean square fit. An initial guess is made based on the average of the first 5 samples and the first value exeeding this value.
Definition at line 137 of file AliHLTPHOSRawAnalyzer.cxx.
138 {
139   cout << "Make initial guess not yet implemeted" << endl;
140 }
AliHLTPHOSRawAnalyzerLMS& AliHLTPHOSRawAnalyzerLMS::operator= (const AliHLTPHOSRawAnalyzerLMS) [inline]
Definition at line 18 of file AliHLTPHOSRawAnalyzerLMS.h.
19     {
20       return *this; 
21     }
void AliHLTPHOSRawAnalyzer::SetAVector (Double_t * aVector, Int_t size) [virtual, inherited]
Reimplemented in AliHLTPHOSRawAnalyzerPeakFinder (p.).
Definition at line 169 of file AliHLTPHOSRawAnalyzer.cxx.
Referenced by AliHLTPHOSRawAnalyzerPeakFinderComponent::LoadPFVector().
170 {
171  cout <<"ERROR: AliHLTPHOSRawAnalyzer::SetAVector:  You cannot set the peakfindervector here, must be set in derived class peakfinder"<<endl;
172 }
void AliHLTPHOSRawAnalyzer::SetData (double * data) [inherited]
Set data array. Overrides data data array set in the constructor.
Definition at line 109 of file AliHLTPHOSRawAnalyzer.cxx.
References AliHLTPHOSRawAnalyzer::fFloatDataPtr.
Referenced by main().
110 {
111   //  double *dta;
112   //  dta = data;
113   fFloatDataPtr = data;
114   //  cout << "Set data not yet implemented" << endl;
115 }
void AliHLTPHOSRawAnalyzer::SetSampleFreq (double freq) [inherited]
Definition at line 118 of file AliHLTPHOSRawAnalyzer.cxx.
References AliHLTPHOSRawAnalyzer::fSampleFrequency.
Referenced by main().
119 {
120   fSampleFrequency = freq;
121 }
void AliHLTPHOSRawAnalyzer::SetStartIndex (int startIndex) [inherited]
Definition at line 156 of file AliHLTPHOSRawAnalyzer.cxx.
References AliHLTPHOSRawAnalyzer::fStartIndex.
157 {
158   fStartIndex = index;
159 }
void AliHLTPHOSRawAnalyzer::SetTVector (Double_t * tVector, Int_t size) [virtual, inherited]
Reimplemented in AliHLTPHOSRawAnalyzerPeakFinder (p.).
Definition at line 162 of file AliHLTPHOSRawAnalyzer.cxx.
Referenced by AliHLTPHOSRawAnalyzerPeakFinderComponent::LoadPFVector().
163 {
164   cout <<"ERROR: AliHLTPHOSRawAnalyzer::SetTVector:  You cannot set the peakfindervector here, must be set in derived class peakfinder"<<endl;
165 }
Member Data Documentation
double AliHLTPHOSRawAnalyzer::fDAmpl [protected, inherited]
Amplitude in entities of ADC levels
Definition at line 44 of file AliHLTPHOSRawAnalyzer.h.
double AliHLTPHOSRawAnalyzer::fDAmplGuess [protected, inherited]
Initial guess for amplitude
Definition at line 41 of file AliHLTPHOSRawAnalyzer.h.
double AliHLTPHOSRawAnalyzer::fDTof [protected, inherited]
Time of flight in entities of sample intervals
Definition at line 43 of file AliHLTPHOSRawAnalyzer.h.
double AliHLTPHOSRawAnalyzer::fDTofGuess [protected, inherited]
Initial guess for t0
Definition at line 40 of file AliHLTPHOSRawAnalyzer.h.
Double_t* AliHLTPHOSRawAnalyzer::fFloatDataPtr [protected, inherited]
Float representation of data that should be fitted
Definition at line 38 of file AliHLTPHOSRawAnalyzer.h.
Referenced by AliHLTPHOSRawAnalyzer::AliHLTPHOSRawAnalyzer(), AliHLTPHOSRawAnalyzer::BaselineCorrection(), and AliHLTPHOSRawAnalyzer::SetData().
double AliHLTPHOSRawAnalyzerLMS::fPCovarPtrPtr[1008][1008] [private]
Covariance matrix of the estimated parameters
Definition at line 30 of file AliHLTPHOSRawAnalyzerLMS.h.
double AliHLTPHOSRawAnalyzer::fSampleFrequency [protected, inherited]
The ADC sample frequency in MHz used under data taking
Definition at line 39 of file AliHLTPHOSRawAnalyzer.h.
Referenced by AliHLTPHOSRawAnalyzer::AliHLTPHOSRawAnalyzer(), and AliHLTPHOSRawAnalyzer::SetSampleFreq().
int AliHLTPHOSRawAnalyzer::fStartIndex [protected, inherited]
Definition at line 46 of file AliHLTPHOSRawAnalyzer.h.
Referenced by AliHLTPHOSRawAnalyzer::SetStartIndex().
double AliHLTPHOSRawAnalyzer::fTau [protected, inherited]
The risetime in micro seconds
Definition at line 42 of file AliHLTPHOSRawAnalyzer.h.
double AliHLTPHOSRawAnalyzerLMS::kfMCovarPtrPtr[1008][1008] [private]
Covariance matrix of the measurements
Definition at line 29 of file AliHLTPHOSRawAnalyzerLMS.h.
The documentation for this class was generated from the following files:
AliHLTPHOSRawAnalyzerLMS.h
AliHLTPHOSRawAnalyzerLMS.cxx