AliHLTPHOSPulseGenerator Class Reference
#include <AliHLTPHOSPulseGenerator.h>
Public Member Functions
AliHLTPHOSPulseGenerator ()
virtual ~AliHLTPHOSPulseGenerator ()
AliHLTPHOSPulseGenerator (double a=1, double t0=0, const int N=64, const double tau=4, const double fs=10)
AliHLTPHOSPulseGenerator (const AliHLTPHOSPulseGenerator &)
AliHLTPHOSPulseGenerator & operator= (const AliHLTPHOSPulseGenerator)
void AddBaseline (double baselineLevel=0, double *samples=0)
void AddNoise (double *dataPtr=0, double *sigma=0)
void AddNoise (double *dataPtr=0, double *sigma=0, double cutoff=0)
double * AddPretriggerSamples (double baslineLevel=0, double *samples=0)
double * GetPulse ()
double * GetPulse (double a=1, double t0=0)
void Quantisize (double *dataPtr=0)
void SetAmplitude (double a=1)
void SetDT (double fs=10)
void SetTZero (double t0=0)
Private Member Functions
void MakePulse (double *dtaPtr=0)
void MakePulse (double *dtaPtr=0, double ampl=1)
Private Attributes
double fAmplitude
int fNSamples
double fTau
double fSampleFreq
double fTZero
double * fDataPtr
double fDT
double * fEvent
Constructor & Destructor Documentation
AliHLTPHOSPulseGenerator::AliHLTPHOSPulseGenerator ()
AliHLTPHOSPulseGenerator::~AliHLTPHOSPulseGenerator () [virtual]
Definition at line 39 of file AliHLTPHOSPulseGenerator.cxx.
References fDataPtr.
40 {
41   delete fDataPtr;
42   fDataPtr=0;
43 }
AliHLTPHOSPulseGenerator::AliHLTPHOSPulseGenerator (double a = 1, double t0 = 0, const int N = 64, const double tau = 4, const double fs = 10)
Contruct a pulsegenrator object an initializes all necessary parameters
Parameters:
a Amplitude in ADC levels (0 -1023)
t0 Timedelay in nanoseconds of signal relative the first sample. This value should be between 0 and Ts
N the number of samples
tau Rise time of the semi Gaussian signal
fs samling rate
Definition at line 53 of file AliHLTPHOSPulseGenerator.cxx.
References fDataPtr, fNSamples, fSampleFreq, fTau, MakePulse(), SetAmplitude(), SetDT(), and SetTZero().
53                                                                                                    : fAmplitude(a), fNSamples(N),fTau(0), fSampleFreq(fs), fTZero(0), fDataPtr(0), fDT(0), fEvent(0)
54 {
55   fDataPtr = new double[100];
56   SetAmplitude(a);
57   SetDT(fs);
58   SetTZero(t0);
59   fNSamples=N;
60   fTau=tau;
61   fSampleFreq=fs;
62   MakePulse(fDataPtr);
63 }
AliHLTPHOSPulseGenerator::AliHLTPHOSPulseGenerator (const AliHLTPHOSPulseGenerator &)
Definition at line 33 of file AliHLTPHOSPulseGenerator.cxx.
33                                                                                   : fAmplitude(0), fNSamples(0),fTau(0), fSampleFreq(0), fTZero(0), fDataPtr(0), fDT(0), fEvent(0)
34 {
35   
36 }
Member Function Documentation
void AliHLTPHOSPulseGenerator::AddBaseline (double baselineLevel = 0, double * samples = 0)
Adds a baseline offset to the signal
Parameters:
baselineLevel The basline level to add
*samples The sample array for which to add te basline offset
Definition at line 71 of file AliHLTPHOSPulseGenerator.cxx.
72 {
73   double *tmpSamples;
74   tmpSamples = samples;
75   printf("\nbaselineLevel = %f\n", baselineLevel);
76   cout << "AddBaseline not implemented yet" << endl;
77 }
void AliHLTPHOSPulseGenerator::AddNoise (double * dataPtr = 0, double * sigma = 0, double cutoff = 0)
Adds correlated Gaussian noise with cutof frequency `cutoff`
Parameters:
dataPtr array of values
sigma noise amplitude in entities of ADC levels
cutoff -30DB cutoff frequency of the noise in entities of sampling frequency
Definition at line 99 of file AliHLTPHOSPulseGenerator.cxx.
100 {
101   printf("\ndataPtr = %f, sigma = %f, cutoff = %f\n", *dataPtr, *sigma, cutoff);
102   cout << "AddNoise is not implemeted yet" << endl;
103 }
void AliHLTPHOSPulseGenerator::AddNoise (double * dataPtr = 0, double * sigma = 0)
Adds Gaussian white noise to the sample array given by *dataPtr.
Parameters:
dataPtr array of samples
sigma the noise amplitude in entities of ADC levels
Definition at line 85 of file AliHLTPHOSPulseGenerator.cxx.
86 {
87   printf("\ndataPtr = %f, sigma = %f\n", *dataPtr, *sigma);
88   cout << "AddNoise is not implemented yet" << endl;
89 }
double * AliHLTPHOSPulseGenerator::AddPretriggerSamples (double baselineLevel = 0, double * samples = 0)
Adds pretrigger samples to the sample array and returns a new array containing the pretrigger samples concatenatet in front of the samples given by `samples`
Parameters:
baselineLevel The baseline value of the pretrigger samples
samples The sample array for which to add the pretrigger samples
Definition at line 114 of file AliHLTPHOSPulseGenerator.cxx.
115 {
116   printf("\nbaslinelevel = %f, samples = %f\n", baselineLevel, *samples);
117   cout << "AddPretriggerSamples not implemented yet" << endl;
118   return 0;
119 }
double * AliHLTPHOSPulseGenerator::GetPulse (double a = 1, double t0 = 0)
Returns a Pulse with new amplidude and t0
Parameters:
a new amplidude, overriding the one given in the constructor
t0 start time of the pulse relative to the sampling clock.
Definition at line 138 of file AliHLTPHOSPulseGenerator.cxx.
139 {
140   return fDataPtr;
141 }
double * AliHLTPHOSPulseGenerator::GetPulse ()
Returns the generated pulse with the parameters given in the constructor
Definition at line 126 of file AliHLTPHOSPulseGenerator.cxx.
Referenced by main().
127 {
128   return fDataPtr;
129 }
void AliHLTPHOSPulseGenerator::MakePulse (double * dtaPtr = 0, double ampl = 1) [private]
void AliHLTPHOSPulseGenerator::MakePulse (double * dtaPtr = 0) [private]
Definition at line 176 of file AliHLTPHOSPulseGenerator.cxx.
References fAmplitude, fDT, fTau, and fTZero.
Referenced by AliHLTPHOSPulseGenerator().
177 {
178 for(int i=0; i<fNSamples; i++)
179   {
180     dtaPtr[i]=fAmplitude*exp((Double_t)2)*pow((i*fDT-fTZero)/fTau, 2)*exp(-2*(i*fDT-fTZero)/fTau);
181   }  
182 }
AliHLTPHOSPulseGenerator& AliHLTPHOSPulseGenerator::operator= (const AliHLTPHOSPulseGenerator) [inline]
Definition at line 15 of file AliHLTPHOSPulseGenerator.h.
16     {
17       return *this; 
18     }
void AliHLTPHOSPulseGenerator::Quantisize (double * dataPtr = 0)
Emulates the ADC. Rounds down to nearest Integerevalue all entries given by dataPtr
Definition at line 148 of file AliHLTPHOSPulseGenerator.cxx.
149 {
150   double *dtaPtr;
151   dtaPtr = new double[100];
152   dtaPtr = dataPtr;
153   //  cout << "Quantisize is not implemented yet" << endl;
154 }
void AliHLTPHOSPulseGenerator::SetAmplitude (double a = 1)
Definition at line 157 of file AliHLTPHOSPulseGenerator.cxx.
References fAmplitude.
Referenced by AliHLTPHOSPulseGenerator().
158 {
159   fAmplitude=a;
160 }
void AliHLTPHOSPulseGenerator::SetDT (double fs = 10)
Definition at line 163 of file AliHLTPHOSPulseGenerator.cxx.
References fDT.
Referenced by AliHLTPHOSPulseGenerator().
164 {
165   fDT=1/fs;  
166 }
void AliHLTPHOSPulseGenerator::SetTZero (double t0 = 0)
Definition at line 169 of file AliHLTPHOSPulseGenerator.cxx.
References fTZero.
Referenced by AliHLTPHOSPulseGenerator().
170 {
171   fTZero = -t0/1000; // Since time is in nanoseconds and the samplingfrequency is in MHz -> divide by 1000
172 }
Member Data Documentation
double AliHLTPHOSPulseGenerator::fAmplitude [private]
Definition at line 33 of file AliHLTPHOSPulseGenerator.h.
Referenced by MakePulse(), and SetAmplitude().
double* AliHLTPHOSPulseGenerator::fDataPtr [private]
Definition at line 38 of file AliHLTPHOSPulseGenerator.h.
Referenced by AliHLTPHOSPulseGenerator(), and ~AliHLTPHOSPulseGenerator().
double AliHLTPHOSPulseGenerator::fDT [private]
Definition at line 39 of file AliHLTPHOSPulseGenerator.h.
Referenced by MakePulse(), and SetDT().
double* AliHLTPHOSPulseGenerator::fEvent [private]
Definition at line 40 of file AliHLTPHOSPulseGenerator.h.
int AliHLTPHOSPulseGenerator::fNSamples [private]
Definition at line 34 of file AliHLTPHOSPulseGenerator.h.
Referenced by AliHLTPHOSPulseGenerator().
double AliHLTPHOSPulseGenerator::fSampleFreq [private]
Definition at line 36 of file AliHLTPHOSPulseGenerator.h.
Referenced by AliHLTPHOSPulseGenerator().
double AliHLTPHOSPulseGenerator::fTau [private]
Definition at line 35 of file AliHLTPHOSPulseGenerator.h.
Referenced by AliHLTPHOSPulseGenerator(), and MakePulse().
double AliHLTPHOSPulseGenerator::fTZero [private]
Definition at line 37 of file AliHLTPHOSPulseGenerator.h.
Referenced by MakePulse(), and SetTZero().
The documentation for this class was generated from the following files:
AliHLTPHOSPulseGenerator.h
AliHLTPHOSPulseGenerator.cxx