AliHLTTask Class Reference
#include <AliHLTTask.h>
Detailed Description
A task collects all the information which is necessary to process a certain step in the HLT data processing chain.
the instance of the component the task object creates and deletes the component object
the data buffer which receives the result of the component and provides the data to other tasks/components
a list of all dependencies
a list of consumers
the task object holds an external pointer to the configuration object; Note: the configuration object must exist through the existence of the task object!!!
Note: This class is only used for the HLT integration into AliRoot(p.).
Definition at line 46 of file AliHLTTask.h.
Public Member Functions
AliHLTTask ()
AliHLTTask (AliHLTConfiguration *pConf)
AliHLTTask (const AliHLTTask &)
AliHLTTask & operator= (const AliHLTTask &)
virtual ~AliHLTTask ()
int Init (AliHLTConfiguration *pConf, AliHLTComponentHandler *pCH)
int Deinit ()
const char * GetName () const
AliHLTConfiguration * GetConf () const
AliHLTComponent * GetComponent () const
AliHLTTask * FindDependency (const char *id)
int SetDependency (AliHLTTask *pDep)
int UnsetDependency (AliHLTTask *pDep)
int CheckDependencies ()
int Depends (AliHLTTask *pTask)
AliHLTTask * FindTarget (const char *id)
int SetTarget (AliHLTTask *pDep)
int UnsetTarget (AliHLTTask *pTarget)
int StartRun ()
int EndRun ()
int ProcessTask (Int_t eventNo)
int GetNofMatchingDataBlocks (const AliHLTTask *pConsumerTask) const
int GetNofMatchingDataTypes (const AliHLTTask *pConsumerTask) const
int Subscribe (const AliHLTTask *pConsumerTask, AliHLTComponentBlockData *arrayBlockDesc, int iArraySize)
int Release (AliHLTComponentBlockData *pBlockDesc, const AliHLTTask *pConsumerTask)
void PrintStatus ()
int FollowDependency (const char *id, TList *pTgtList=NULL)
void PrintDependencyTree (const char *id, int bMode=0)
int GetNofSources () const
Private Member Functions
ClassDef (AliHLTTask, 1)
Private Attributes
AliHLTConfiguration * fpConfiguration
AliHLTComponent * fpComponent
transient
AliHLTDataBuffer * fpDataBuffer
transient
TList fListTargets
transient
TList fListDependencies
AliHLTComponentBlockData * fpBlockDataArray
int fBlockDataArraySize
transient
Constructor & Destructor Documentation
AliHLTTask::AliHLTTask ()
standard constructor
AliHLTTask::AliHLTTask (AliHLTConfiguration * pConf)
constructor
Parameters:
pConf pointer to configuration descriptor
Definition at line 436 of file AliHLTConfiguration.cxx.
437   :
438   fpConfiguration(pConf),
439   fpComponent(NULL),
440   fpDataBuffer(NULL),
441   fListTargets(),
442   fListDependencies(),
443   fpBlockDataArray(NULL),
444   fBlockDataArraySize(0)
445 {
446   // see header file for function documentation
447 }
AliHLTTask::AliHLTTask (const AliHLTTask &)
not a valid copy constructor, defined according to effective C++ style
Definition at line 449 of file AliHLTConfiguration.cxx.
References HLTFatal.
450   :
451   TObject(),
452   AliHLTLogging(),
453   fpConfiguration(NULL),
454   fpComponent(NULL),
455   fpDataBuffer(NULL),
456   fListTargets(),
457   fListDependencies(),
458   fpBlockDataArray(NULL),
459   fBlockDataArraySize(0)
460 {
461   HLTFatal("copy constructor untested");
462 }
AliHLTTask::~AliHLTTask () [virtual]
destructor
Definition at line 471 of file AliHLTConfiguration.cxx.
References fListDependencies, fListTargets, fpBlockDataArray, fpComponent, UnsetDependency(), and UnsetTarget().
472 {
473   TObjLink* lnk=fListDependencies.FirstLink();
474 
475   while (lnk!=NULL) {
476     AliHLTTask* pTask=(AliHLTTask*)lnk->GetObject();
477     pTask->UnsetTarget(this);
478     lnk=lnk->Next();
479   }
480   lnk=fListTargets.FirstLink();
481 
482   while (lnk!=NULL) {
483     AliHLTTask* pTask=(AliHLTTask*)lnk->GetObject();
484     pTask->UnsetDependency(this);
485     lnk=lnk->Next();
486   }
487 
488   if (fpComponent) delete fpComponent;
489   fpComponent=NULL;
490   if (fpBlockDataArray) delete[] fpBlockDataArray;
491   fpBlockDataArray=NULL;
492 }
Member Function Documentation
int AliHLTTask::CheckDependencies ()
Return number of unresolved dependencies. Iterate through all the configurations the task depends on and check whether a corresponding task is available in the list.
Returns: number of unresolved dependencies
Definition at line 666 of file AliHLTConfiguration.cxx.
References FindDependency(), fpConfiguration, AliHLTConfiguration::GetFirstSource(), AliHLTConfiguration::GetName(), and AliHLTConfiguration::GetNextSource().
Referenced by AliHLTSystem::InsertTask().
667 {
668   // see header file for function documentation
669   int iResult=0;
670   AliHLTConfiguration* pSrc=fpConfiguration->GetFirstSource();
671   while (pSrc) {
672     if (FindDependency(pSrc->GetName())==NULL) {
673       //HLTDebug("dependency \"%s\" unresolved", pSrc->GetName());
674       iResult++;
675     }
676     pSrc=fpConfiguration->GetNextSource();
677   }
678   return iResult;
679 }
AliHLTTask::ClassDef (AliHLTTask, 1) [private]
int AliHLTTask::Deinit ()
De-Initialize the task. Final cleanup after the run. The AliHLTComponent::Deinit(p.) method of the component is called. The analysis component is deleted.
Definition at line 532 of file AliHLTConfiguration.cxx.
References AliHLTComponent::Deinit(), fpComponent, GetComponent(), GetName(), and HLTWarning.
Referenced by AliHLTSystem::DeinitTasks().
533 {
534   // see header file for function documentation
535   int iResult=0;
536   AliHLTComponent* pComponent=GetComponent();
537   fpComponent=NULL;
538   if (pComponent) {
539     //HLTDebug("delete component %s (%p)", pComponent->GetComponentID(), pComponent); 
540     pComponent->Deinit();
541     delete pComponent;
542   } else {
543     HLTWarning("task %s (%p) doesn't seem to be in initialized", GetName(), this);
544   }
545   return iResult;
546 }
int AliHLTTask::Depends (AliHLTTask * pTask)
Check whether the current task depends on the task pTask.
Parameters:
pTask pointer to Task descriptor
Returns: 1 the current task depends on pTask
 0 no dependency
 neg. error code if failed
Definition at line 682 of file AliHLTConfiguration.cxx.
References fpConfiguration, GetName(), and AliHLTConfiguration::GetSource().
Referenced by AliHLTSystem::InsertTask().
683 {
684   // see header file for function documentation
685   int iResult=0;
686   if (pTask) {
687     if (fpConfiguration) {
688       iResult=fpConfiguration->GetSource(pTask->GetName())!=NULL;
689       if (iResult>0) {
690         //HLTDebug("task  \"%s\" depends on \"%s\"", GetName(), pTask->GetName());
691       } else {
692         //HLTDebug("task  \"%s\" independend of \"%s\"", GetName(), pTask->GetName());
693       }
694     } else {
695       iResult=-EFAULT;
696     }
697   } else {
698     iResult=-EINVAL;
699   }
700   return iResult;
701 }
int AliHLTTask::EndRun ()
Clean-up the task after event processing. The method cleans up internal structures.
Definition at line 812 of file AliHLTConfiguration.cxx.
References fBlockDataArraySize, fpBlockDataArray, fpDataBuffer, GetName(), and HLTWarning.
Referenced by AliHLTSystem::StopTasks().
813 {
814   // see header file for function documentation
815   int iResult=0;
816   if (fpBlockDataArray) {
817     fBlockDataArraySize=0;
818     delete [] fpBlockDataArray;
819     fpBlockDataArray=0;
820   } else {
821     HLTWarning("task %s (%p) doesn't seem to be in running mode", GetName(), this);
822   }
823   if (fpDataBuffer) {
824     AliHLTDataBuffer* pBuffer=fpDataBuffer;
825     fpDataBuffer=NULL;
826     delete pBuffer;
827   }
828   return iResult;
829 }
AliHLTTask * AliHLTTask::FindDependency (const char * id)
Find a dependency with a certain name id. Searches in the list of dependencies for a task.
Parameters:
id the id of the CONFIGURATION
 NOTE: the id does NOT specify a COMPONENT
Returns: pointer to task
Definition at line 568 of file AliHLTConfiguration.cxx.
References fListDependencies.
Referenced by CheckDependencies(), PrintStatus(), and SetDependency().
569 {
570   // see header file for function documentation
571   AliHLTTask* pTask=NULL;
572   if (id) {
573     pTask=(AliHLTTask*)fListDependencies.FindObject(id);
574   }
575   return pTask;
576 }
AliHLTTask * AliHLTTask::FindTarget (const char * id)
Find a target with a certain id. Tasks which depend on the current task are referred to be targets.
Parameters:
id configuration id to search for
Returns: pointer to task instance
Definition at line 703 of file AliHLTConfiguration.cxx.
References fListTargets.
Referenced by SetTarget().
704 {
705   // see header file for function documentation
706   AliHLTTask* pTask=NULL;
707   if (id) {
708     pTask=(AliHLTTask*)fListTargets.FindObject(id);
709   }
710   return pTask;
711 }
int AliHLTTask::FollowDependency (const char * id, TList * pTgtList = NULL)
Search task dependency list recursively to find a dependency.
Parameters:
id id of the task to search for
pTgtList (optional) target list to receive dependency tree
Returns: 0 if not found, >0 found in the n-th level, dependency list in the target list
Definition at line 578 of file AliHLTConfiguration.cxx.
References fListDependencies.
Referenced by PrintDependencyTree().
579 {
580   // see header file for function documentation
581   int iResult=0;
582   if (id) {
583     AliHLTTask* pDep=NULL;
584     if ((pDep=(AliHLTTask*)fListDependencies.FindObject(id))!=NULL) {
585       if (pTgtList) pTgtList->Add(pDep);
586       iResult++;
587     } else {
588       TObjLink* lnk=fListDependencies.FirstLink();
589       while (lnk && iResult==0) {
590         pDep=(AliHLTTask*)lnk->GetObject();
591         if (pDep) {
592           if ((iResult=pDep->FollowDependency(id, pTgtList))>0) {
593             if (pTgtList) pTgtList->AddFirst(pDep);
594             iResult++;
595           }
596         } else {
597           iResult=-EFAULT;
598         }
599         lnk=lnk->Next();
600       }
601     }
602   } else {
603     iResult=-EINVAL;
604   }
605   return iResult;
606 }
AliHLTComponent * AliHLTTask::GetComponent () const
Return pointer to component, which the task internally holds. Never delete this object!!!
Returns: instance of the component
Definition at line 562 of file AliHLTConfiguration.cxx.
Referenced by Deinit(), GetNofMatchingDataBlocks(), GetNofMatchingDataTypes(), AliHLTSystem::InitBenchmarking(), PrintStatus(), ProcessTask(), Release(), StartRun(), and Subscribe().
563 {
564   // see header file for function documentation
565   return fpComponent;
566 }
AliHLTConfiguration * AliHLTTask::GetConf () const
Return pointer to configuration. The tasks holds internally the configuration object.
Returns: pointer to configuration
Definition at line 556 of file AliHLTConfiguration.cxx.
Referenced by AliHLTSystem::BuildTaskList().
557 {
558   // see header file for function documentation
559   return fpConfiguration;
560 }
const char * AliHLTTask::GetName () const
Get the name of the object. This is an overridden TObject function in order to return the configuration name instead of the class name. Enables use of TList standard functions.
Returns: name of the configuration
Definition at line 548 of file AliHLTConfiguration.cxx.
References fpConfiguration, and AliHLTConfiguration::GetName().
Referenced by AliHLTSystem::BuildTaskList(), Deinit(), Depends(), EndRun(), Init(), AliHLTSystem::InsertTask(), PrintDependencyTree(), PrintStatus(), ProcessTask(), AliHLTSystem::ProcessTasks(), SetDependency(), SetTarget(), and StartRun().
549 {
550   // see header file for function documentation
551   if (fpConfiguration)
552     return fpConfiguration->GetName();
553   return TObject::GetName();
554 }
int AliHLTTask::GetNofMatchingDataBlocks (const AliHLTTask * pConsumerTask) const
Determine the number of matching data block between the component and the data buffer of a consumer component. It checks which data types from the list of input data types of the consumer component can be provided by data blocks of the current component.
Parameters:
pConsumerTask the task which subscribes to the data
Returns: number of matching data blocks
Definition at line 959 of file AliHLTConfiguration.cxx.
References AliHLTDataBuffer::FindMatchingDataBlocks(), fpDataBuffer, GetComponent(), and HLTFatal.
Referenced by ProcessTask().
960 {
961   // see header file for function documentation
962   int iResult=0;
963   if (pConsumerTask) {
964     if (fpDataBuffer) {
965       iResult=fpDataBuffer->FindMatchingDataBlocks(pConsumerTask->GetComponent(), NULL);
966     } else {
967       HLTFatal("internal data buffer missing");
968       iResult=-EFAULT;
969     }
970   } else {
971     iResult=-EINVAL;
972   }
973   return iResult;
974 }
int AliHLTTask::GetNofMatchingDataTypes (const AliHLTTask * pConsumerTask) const
Determine the number of matching data types between the component and a consumer component. It checks which data types from the list of input data types of the consumer component can be provided by the current component.
Parameters:
pConsumerTask the task which subscribes to the data
Returns: number of matching data types
Definition at line 976 of file AliHLTConfiguration.cxx.
References AliHLTComponent::FindMatchingDataTypes(), GetComponent(), HLTError, and HLTFatal.
Referenced by StartRun().
977 {
978   // see header file for function documentation
979   int iResult=0;
980   if (pConsumerTask) {
981     AliHLTComponent* pComponent=GetComponent();
982     if (!pComponent) {
983       // init ?
984       HLTError("component not initialized");
985       iResult=-EFAULT;
986     }
987     if (pComponent) {
988       iResult=pComponent->FindMatchingDataTypes(pConsumerTask->GetComponent(), NULL);
989     } else {
990       HLTFatal("task initialization failed");
991       iResult=-EFAULT;
992     }
993   } else {
994     iResult=-EINVAL;
995   }
996   return iResult;
997 }
int AliHLTTask::GetNofSources () const [inline]
Get number of source tasks.
Returns: number of source tasks
Definition at line 269 of file AliHLTTask.h.
References fListDependencies.
269 {return fListDependencies.GetSize();}
int AliHLTTask::Init (AliHLTConfiguration * pConf, AliHLTComponentHandler * pCH)
Initialize the task. The task is initialized with a configuration descriptor. It needs a component handler instance to create the analysis component. The component is created and initialized.
Parameters:
pConf pointer to configuration descriptor, can be NULL if it was already provided to the constructor
pCH the HLT component handler
Definition at line 494 of file AliHLTConfiguration.cxx.
References AliHLTComponentHandler::CreateComponent(), fpComponent, fpConfiguration, AliHLTConfiguration::GetArguments(), AliHLTConfiguration::GetComponentID(), AliHLTConfiguration::GetName(), GetName(), HLTError, and HLTWarning.
Referenced by AliHLTSystem::InitTasks().
495 {
496   // see header file for function documentation
497   int iResult=0;
498   if (fpConfiguration!=NULL && pConf!=NULL && fpConfiguration!=pConf) {
499     HLTWarning("overriding existing reference to configuration object %p (%s) by %p",
500                fpConfiguration, GetName(), pConf);
501   }
502   if (pConf!=NULL) fpConfiguration=pConf;
503   if (fpConfiguration) {
504     if (pCH) {
505       int argc=0;
506       const char** argv=NULL;
507       if ((iResult=fpConfiguration->GetArguments(&argv))>=0) {
508         argc=iResult; // just to make it clear
509         // TODO: we have to think about the optional environment parameter,
510         // currently just set to NULL. 
511         iResult=pCH->CreateComponent(fpConfiguration->GetComponentID(), NULL, argc, argv, fpComponent);
512         if (fpComponent || iResult<=0) {
513           //HLTDebug("component %s (%p) created", fpComponent->GetComponentID(), fpComponent); 
514         } else {
515           HLTError("can not find component \"%s\" (%d)", fpConfiguration->GetComponentID(), iResult);
516         }
517       } else {
518         HLTError("can not get argument list for configuration %s (%s)", fpConfiguration->GetName(), fpConfiguration->GetComponentID());
519         iResult=-EINVAL;
520       }
521     } else {
522       HLTError("component handler instance needed for task initialization");
523       iResult=-EINVAL;
524     }
525   } else {
526     HLTError("configuration object instance needed for task initialization");
527     iResult=-EINVAL;
528   }
529   return iResult;
530 }
AliHLTTask & AliHLTTask::operator= (const AliHLTTask &)
not a valid assignment op, but defined according to effective C++ style
Definition at line 464 of file AliHLTConfiguration.cxx.
References HLTFatal.
465 { 
466   // see header file for function documentation
467   HLTFatal("assignment operator untested");
468   return *this;
469 }
void AliHLTTask::PrintDependencyTree (const char * id, int bMode = 0)
Print the tree for a certain dependency either from the task or configuration list. Each task posseses two `link lists`: The configurations are the origin of the task list. In case of an error during the built of the task list, the dependencies for the task list might be incomplete. In this case the configurations can give infomation on the error reason.
Parameters:
id id of the dependency to search for
bMode 0 (default) from task dependency list,
 1 from configuration list
Definition at line 608 of file AliHLTConfiguration.cxx.
References FollowDependency(), AliHLTConfiguration::FollowDependency(), fpConfiguration, GetName(), HLTLogKeyword, and HLTMessage.
Referenced by AliHLTSystem::BuildTaskList().
609 {
610   // see header file for function documentation
611   HLTLogKeyword("task dependencies");
612   int iResult=0;
613   TList tgtList;
614   if (bFromConfiguration) {
615     if (fpConfiguration)
616       iResult=fpConfiguration->FollowDependency(id, &tgtList);
617     else
618       iResult=-EFAULT;
619   } else
620     iResult=FollowDependency(id, &tgtList);
621   if (iResult>0) {
622     HLTMessage("     task \"%s\": dependency level %d ", GetName(), iResult);
623     TObjLink* lnk=tgtList.FirstLink();
624     int i=iResult;
625     char* pSpace = new char[iResult+1];
626     if (pSpace) {
627       memset(pSpace, 32, iResult);
628       pSpace[i]=0;
629       while (lnk) {
630         TObject* obj=lnk->GetObject();
631         HLTMessage("     %s^-- %s ", &pSpace[i--], obj->GetName());
632         lnk=lnk->Next();
633       }
634       delete [] pSpace;
635     } else {
636       iResult=-ENOMEM;
637     }
638   }
639 }
void AliHLTTask::PrintStatus ()
Print the status of the task with component, dependencies and targets.
Definition at line 1033 of file AliHLTConfiguration.cxx.
References FindDependency(), fListTargets, fpConfiguration, GetComponent(), AliHLTComponent::GetComponentID(), AliHLTConfiguration::GetFirstSource(), GetName(), AliHLTConfiguration::GetName(), AliHLTConfiguration::GetNextSource(), HLTLogKeyword, and HLTMessage.
Referenced by AliHLTSystem::PrintTaskList().
1034 {
1035   // see header file for function documentation
1036   HLTLogKeyword("task properties");
1037   AliHLTComponent* pComponent=GetComponent();
1038   if (pComponent) {
1039     HLTMessage("     component: %s (%p)", pComponent->GetComponentID(), pComponent);
1040   } else {
1041     HLTMessage("     no component set!");
1042   }
1043   if (fpConfiguration) {
1044     AliHLTConfiguration* pSrc=fpConfiguration->GetFirstSource();
1045     while (pSrc) {
1046       const char* pQualifier="unresolved";
1047       if (FindDependency(pSrc->GetName()))
1048         pQualifier="resolved";
1049       HLTMessage("     source: %s (%s)", pSrc->GetName(), pQualifier);
1050       pSrc=fpConfiguration->GetNextSource();
1051     }
1052     TObjLink* lnk = fListTargets.FirstLink();
1053     while (lnk) {
1054       TObject *obj = lnk->GetObject();
1055       HLTMessage("     target: %s", obj->GetName());
1056       lnk = lnk->Next();
1057     }
1058   } else {
1059     HLTMessage("     task \"%s\" not initialized", GetName());
1060   }
1061 }
int AliHLTTask::ProcessTask (Int_t eventNo)
Process the task. If all dependencies are resolved the tasks subscribes to the data of all source tasks, builds the block descriptor and calls the AliHLTComponent::ProcessEvent(p.) method of the component, after processing, the data blocks are released.
 The StartRun(p.) method must be called before.
Definition at line 831 of file AliHLTConfiguration.cxx.
References AliHLTUInt32_t, AliHLTUInt8_t, AliHLTComponentEventData::fBlockCnt, fBlockDataArraySize, AliHLTComponentEventData::fEventID, AliHLTComponent::FillEventData(), fListDependencies, fpBlockDataArray, fpComponent, fpDataBuffer, AliHLTComponentBlockData::fSize, GetComponent(), AliHLTComponent::GetComponentID(), AliHLTComponent::GetComponentType(), GetName(), GetNofMatchingDataBlocks(), AliHLTComponent::GetOutputDataSize(), AliHLTDataBuffer::GetTargetBuffer(), HLTDebug, HLTError, HLTFatal, AliHLTComponent::ProcessEvent(), Release(), AliHLTDataBuffer::Reset(), AliHLTDataBuffer::SetSegments(), and Subscribe().
Referenced by AliHLTSystem::ProcessTasks().
832 {
833   // see header file for function documentation
834   int iResult=0;
835   AliHLTComponent* pComponent=GetComponent();
836   if (pComponent && fpDataBuffer) {
837     HLTDebug("Processing task %s (%p) fpDataBuffer %p", GetName(), this, fpDataBuffer);
838     fpDataBuffer->Reset();
839     int iSourceDataBlock=0;
840     int iInputDataVolume=0;
841 
842     int iNofInputDataBlocks=0;
843     /* TODO: the assumption of only one output data type per component is the current constraint
844      * later it should be checked how many output blocks of the source component match the input
845      * data types of the consumer component (GetNofMatchingDataBlocks). If one assumes that a
846      * certain output block is always been produced, the initialization could be done in the
847      * StartRun. Otherwise the fpBlockDataArray has to be adapted each time.
848      */
849     iNofInputDataBlocks=fListDependencies.GetSize(); // one block per source
850     // is not been used since the allocation was done in StartRun, but check the size
851     if (iNofInputDataBlocks>fBlockDataArraySize) {
852       HLTError("block data array too small");
853     }
854 
855     AliHLTTask* pSrcTask=NULL;
856     TList subscribedTaskList;
857     TObjLink* lnk=fListDependencies.FirstLink();
858 
859     // subscribe to all source tasks
860     while (lnk && iResult>=0) {
861       pSrcTask=(AliHLTTask*)lnk->GetObject();
862       if (pSrcTask) {
863         int iMatchingDB=pSrcTask->GetNofMatchingDataBlocks(this);
864         if (iMatchingDB<=fBlockDataArraySize-iSourceDataBlock) {
865           if (fpBlockDataArray) {
866           if ((iResult=pSrcTask->Subscribe(this, &fpBlockDataArray[iSourceDataBlock],fBlockDataArraySize-iSourceDataBlock))>0) {
867             for (int i=0; i<iResult; i++) {
868               iInputDataVolume+=fpBlockDataArray[i+iSourceDataBlock].fSize;
869               // put the source task as many times into the list as it provides data blocks
870               // makes the bookkeeping for the data release easier
871               subscribedTaskList.Add(pSrcTask);
872             }
873             iSourceDataBlock+=iResult;
874             HLTDebug("Task %s (%p) successfully subscribed to %d data block(s) of task %s (%p)", GetName(), this, iResult, pSrcTask->GetName(), pSrcTask);
875             iResult=0;
876           } else {
877             HLTError("Task %s (%p): subscription to task %s (%p) failed with error %d", GetName(), this, pSrcTask->GetName(), pSrcTask, iResult);
878             iResult=-EFAULT;
879           }
880           } else {
881             HLTFatal("Task %s (%p): BlockData array not allocated", GetName(), this);
882             iResult=-EFAULT;
883           }
884         } else {
885           HLTFatal("Task %s (%p): too little space in data block array for subscription to task %s (%p)", GetName(), this, pSrcTask->GetName(), pSrcTask);
886           HLTDebug("#data types=%d, array size=%d, current index=%d", iMatchingDB, fBlockDataArraySize, iSourceDataBlock);
887           iResult=-EFAULT;
888         }
889       } else {
890         HLTFatal("fatal internal error in ROOT list handling");
891         iResult=-EFAULT;
892       }
893       lnk=lnk->Next();
894     }
895 
896     // process the event
897     if (iResult>=0) {
898       long unsigned int iConstBase=0;
899       double fInputMultiplier=0;
900       if (pComponent->GetComponentType()!=AliHLTComponent::kSink)
901         pComponent->GetOutputDataSize(iConstBase, fInputMultiplier);
902       int iOutputDataSize=int(fInputMultiplier*iInputDataVolume) + iConstBase;
903       //HLTDebug("task %s: reqired output size %d", GetName(), iOutputDataSize);
904       AliHLTUInt8_t* pTgtBuffer=NULL;
905       if (iOutputDataSize>0) pTgtBuffer=fpDataBuffer->GetTargetBuffer(iOutputDataSize);
906       //HLTDebug("provided raw buffer %p", pTgtBuffer);
907       AliHLTComponentEventData evtData;
908       AliHLTComponent::FillEventData(evtData);
909       evtData.fEventID=(AliHLTEventID_t)eventNo;
910       evtData.fBlockCnt=iSourceDataBlock;
911       AliHLTComponentTriggerData trigData;
912       AliHLTUInt32_t size=iOutputDataSize;
913       AliHLTUInt32_t outputBlockCnt=0;
914       AliHLTComponentBlockData* outputBlocks=NULL;
915       AliHLTComponentEventDoneData* edd;
916       if (pTgtBuffer!=NULL || iOutputDataSize==0) {
917         iResult=pComponent->ProcessEvent(evtData, fpBlockDataArray, trigData, pTgtBuffer, size, outputBlockCnt, outputBlocks, edd);
918         HLTDebug("task %s: component %s ProcessEvent finnished (%d): size=%d blocks=%d", GetName(), pComponent->GetComponentID(), iResult, size, outputBlockCnt);
919         if (iResult>=0 && pTgtBuffer) {
920           iResult=fpDataBuffer->SetSegments(pTgtBuffer, outputBlocks, outputBlockCnt);
921           delete [] outputBlocks; outputBlocks=NULL; outputBlockCnt=0;
922         }
923       } else {
924         HLTError("task %s: no target buffer available", GetName());
925         iResult=-EFAULT;
926       }
927     }
928 
929     // now release all buffers which we have subscribed to
930     iSourceDataBlock=0;
931     lnk=subscribedTaskList.FirstLink();
932     while (lnk) {
933       pSrcTask=(AliHLTTask*)lnk->GetObject();
934       if (pSrcTask) {
935         int iTempRes=0;
936         if ((iTempRes=pSrcTask->Release(&fpBlockDataArray[iSourceDataBlock], this))>=0) {
937           HLTDebug("Task %s (%p) successfully released task %s (%p)", GetName(), this, pSrcTask->GetName(), pSrcTask);
938         } else {
939           HLTError("Task %s (%p): realease of task %s (%p) failed with error %d", GetName(), this, pSrcTask->GetName(), pSrcTask, iTempRes);
940         }
941       } else {
942         HLTFatal("task %s (%p): internal error in ROOT list handling", GetName(), this);
943         if (iResult>=0) iResult=-EFAULT;
944       }
945       subscribedTaskList.Remove(lnk);
946       lnk=subscribedTaskList.FirstLink();
947       iSourceDataBlock++;
948     }
949     if (subscribedTaskList.GetSize()>0) {
950       HLTError("task %s (%p): could not release all data buffers", GetName(), this);
951     }
952   } else {
953     HLTError("task %s (%p): internal failure (not initialized component %p, data buffer %p)", GetName(), this, fpComponent, fpDataBuffer);
954     iResult=-EFAULT;
955   }
956   return iResult;
957 }
int AliHLTTask::Release (AliHLTComponentBlockData * pBlockDesc, const AliHLTTask * pConsumerTask)
Release a block descriptor. Notification from consumer task.
Parameters:
pBlockDesc descriptor of the data segment
pConsumerTask the task which subscribed to the data
Returns: : >0 if success, negative error code if failed
Definition at line 1016 of file AliHLTConfiguration.cxx.
References fpDataBuffer, GetComponent(), HLTFatal, and AliHLTDataBuffer::Release().
Referenced by ProcessTask().
1017 {
1018   // see header file for function documentation
1019   int iResult=0;
1020   if (pConsumerTask && pBlockDesc) {
1021     if (fpDataBuffer) {
1022       iResult=fpDataBuffer->Release(pBlockDesc, pConsumerTask->GetComponent());
1023     } else {
1024       HLTFatal("internal data buffer missing");
1025       iResult=-EFAULT;
1026     }
1027   } else {
1028     iResult=-EINVAL;
1029   }
1030   return iResult;
1031 }
int AliHLTTask::SetDependency (AliHLTTask * pDep)
Add a dependency for the task. The task maintains a list of other tasks it depends on.
Parameters:
pDep pointer to a task descriptor
Returns: 0 if suceeded, neg error code if failed
 -EEXIST : the dependencie exists already
Definition at line 641 of file AliHLTConfiguration.cxx.
References FindDependency(), fListDependencies, and GetName().
Referenced by AliHLTSystem::InsertTask().
642 {
643   // see header file for function documentation
644   int iResult=0;
645   if (pDep) {
646     if (FindDependency(pDep->GetName())==NULL) {
647       fListDependencies.Add(pDep);
648     } else {
649       iResult=-EEXIST;
650     }
651   } else {
652     iResult=-EINVAL;
653   }
654   return iResult;
655 }
int AliHLTTask::SetTarget (AliHLTTask * pDep)
Insert task into target list. The target list specifies all the tasks which depend on the current task.
Parameters:
pDep pointer task object
Returns: >=0 if succeeded, neg. error code if failed
Definition at line 713 of file AliHLTConfiguration.cxx.
References FindTarget(), fListTargets, and GetName().
Referenced by AliHLTSystem::InsertTask().
714 {
715   // see header file for function documentation
716   int iResult=0;
717   if (pTgt) {
718     if (FindTarget(pTgt->GetName())==NULL) {
719       fListTargets.Add(pTgt);
720     } else {
721       iResult=-EEXIST;
722     }
723   } else {
724     iResult=-EINVAL;
725   }
726   return iResult;
727 }
int AliHLTTask::StartRun ()
Prepare the task for event processing. The method initializes the Data Buffer and calls the AliHLTComponent::Init(p.) method of the component.
 The ProcessTask(p.) method can be called an arbitrary number of times as soon as the task is in running mode.
Definition at line 735 of file AliHLTConfiguration.cxx.
References fBlockDataArraySize, fListDependencies, fListTargets, fpBlockDataArray, fpDataBuffer, GetComponent(), GetName(), GetNofMatchingDataTypes(), HLTDebug, HLTError, HLTFatal, HLTWarning, and AliHLTDataBuffer::SetConsumer().
Referenced by AliHLTSystem::StartTasks().
736 {
737   // see header file for function documentation
738   int iResult=0;
739   int iNofInputDataBlocks=0;
740   AliHLTComponent* pComponent=GetComponent();
741   if (pComponent) {
742     // determine the number of input data blocks provided from the source tasks
743     TObjLink* lnk=fListDependencies.FirstLink();
744     while (lnk && iResult>=0) {
745       AliHLTTask* pSrcTask=(AliHLTTask*)lnk->GetObject();
746       if (pSrcTask) {
747         if ((iResult=pSrcTask->GetNofMatchingDataTypes(this))>0) {
748           iNofInputDataBlocks+=iResult;
749         } else if (iResult==0) {
750           HLTWarning("source task %s (%p) does not provide any matching data type for task %s (%p)", pSrcTask->GetName(), pSrcTask, GetName(), this);
751         } else {
752           HLTError("task %s (%p): error getting matching data types for source task %s (%p)", GetName(), this, pSrcTask->GetName(), pSrcTask);
753           iResult=-EFAULT;
754         }
755       }
756       lnk=lnk->Next();
757     }
758     if (iResult>=0) {
759       if (fpBlockDataArray) {
760         HLTWarning("block data array for task %s (%p) was not cleaned", GetName(), this);
761         delete [] fpBlockDataArray;
762         fpBlockDataArray=NULL;
763         fBlockDataArraySize=0;
764       }
765 
766       // component init
767       // the initialization of the component is done by the ComponentHandler after creation
768       // of the component.
769       //iResult=Init( AliHLTComponentEnvironment* environ, void* environ_param, int argc, const char** argv );
770 
771       // allocate internal task variables for bookkeeping aso.
772       // we allocate the BlockData array with at least one member
773       if (iNofInputDataBlocks==0) iNofInputDataBlocks=1;
774       fpBlockDataArray=new AliHLTComponentBlockData[iNofInputDataBlocks];
775       if (fpBlockDataArray) {
776         fBlockDataArraySize=iNofInputDataBlocks;
777       } else {
778         HLTError("memory allocation failed");
779         iResult=-ENOMEM;
780       }
781 
782       // allocate the data buffer, which controls the output buffer and subscriptions
783       if (iResult>=0) {
784         fpDataBuffer=new AliHLTDataBuffer;
785         if (fpDataBuffer!=NULL) {
786           HLTDebug("created data buffer %p for task %s (%p)", fpDataBuffer, GetName(), this);
787           TObjLink* lnk=fListTargets.FirstLink();
788           while (lnk && iResult>=0) {
789             AliHLTTask* pTgtTask=(AliHLTTask*)lnk->GetObject();
790             if (pTgtTask) {
791               if ((iResult=fpDataBuffer->SetConsumer(pTgtTask->GetComponent()))>=0) {
792               }
793             } else {
794               break;
795               iResult=-EFAULT;
796             }
797             lnk=lnk->Next();
798           }
799         } else {
800           HLTFatal("can not create data buffer object, memory allocation failed");
801           iResult=-ENOMEM;
802         }
803       }
804     }
805   } else {
806     HLTError("task %s (%p) does not have a component", GetName(), this);
807     iResult=-EFAULT;
808   }
809   return iResult;
810 }
int AliHLTTask::Subscribe (const AliHLTTask * pConsumerTask, AliHLTComponentBlockData * arrayBlockDesc, int iArraySize)
Subscribe to the data of a source task. The function prepares the block descriptors for subsequent use with the AliHLTComponent::ProcessEvent(p.) method, the method prepares all block descriptors which match the input data type of the consumer the function returns the number of blocks which would be prepared in case the target array is big enough.
Parameters:
pConsumerTask the task which subscribes to the data
arrayBlockDesc pointer to block descriptor to be filled
iArraySize size of the block descriptor array
Returns: number of matching data blocks, negative error code if failed
Definition at line 999 of file AliHLTConfiguration.cxx.
References fpDataBuffer, GetComponent(), HLTFatal, and AliHLTDataBuffer::Subscribe().
Referenced by ProcessTask().
1000 {
1001   // see header file for function documentation
1002   int iResult=0;
1003   if (pConsumerTask) {
1004     if (fpDataBuffer) {
1005       iResult=fpDataBuffer->Subscribe(pConsumerTask->GetComponent(), pBlockDesc, iArraySize);
1006     } else {
1007       HLTFatal("internal data buffer missing");
1008       iResult=-EFAULT;
1009     }
1010   } else {
1011     iResult=-EINVAL;
1012   }
1013   return iResult;
1014 }
int AliHLTTask::UnsetDependency (AliHLTTask * pDep)
Clear a dependency. The ROOT TList touches the object which is in the list, even though it shouldn't care about. Thats why all lists have to be cleared before objects are deleted.
Definition at line 657 of file AliHLTConfiguration.cxx.
References fListDependencies, fpConfiguration, and AliHLTConfiguration::InvalidateSources().
Referenced by ~AliHLTTask().
658 {
659   fListDependencies.Remove(pDep);
660   if (fpConfiguration) {
661     fpConfiguration->InvalidateSources();
662   }
663   return 0;
664 }
int AliHLTTask::UnsetTarget (AliHLTTask * pTarget)
Clear a target. The ROOT TList touches the object which is in the list, even though it shouldn't care about. Thats why all lists have to be cleared before objects are deleted.
Definition at line 729 of file AliHLTConfiguration.cxx.
References fListTargets.
Referenced by ~AliHLTTask().
730 {
731   fListTargets.Remove(pTarget);
732   return 0;
733 }
Member Data Documentation
int AliHLTTask::fBlockDataArraySize [private]
transient
size of the block data array
Definition at line 290 of file AliHLTTask.h.
Referenced by EndRun(), ProcessTask(), and StartRun().
TList AliHLTTask::fListDependencies [private]
the list of sources (tasks upon which the current one depends)
Definition at line 281 of file AliHLTTask.h.
Referenced by FindDependency(), FollowDependency(), GetNofSources(), ProcessTask(), SetDependency(), StartRun(), UnsetDependency(), and ~AliHLTTask().
TList AliHLTTask::fListTargets [private]
transient
the list of targets (tasks which depend upon the current one)
Definition at line 279 of file AliHLTTask.h.
Referenced by FindTarget(), PrintStatus(), SetTarget(), StartRun(), UnsetTarget(), and ~AliHLTTask().
AliHLTComponentBlockData* AliHLTTask::fpBlockDataArray [private]
block data array to be passed as argument to the AliHLTComponent::ProcessEvent(p.) method. Filled through subscription to source tasks (Subscribe(p.)).
Definition at line 288 of file AliHLTTask.h.
Referenced by EndRun(), ProcessTask(), StartRun(), and ~AliHLTTask().
AliHLTComponent* AliHLTTask::fpComponent [private]
transient
the component described by this task (created and deleted internally)
Definition at line 275 of file AliHLTTask.h.
Referenced by Deinit(), Init(), ProcessTask(), and ~AliHLTTask().
AliHLTConfiguration* AliHLTTask::fpConfiguration [private]
the configuration descriptor (external pointer)
Definition at line 273 of file AliHLTTask.h.
Referenced by CheckDependencies(), Depends(), GetName(), Init(), PrintDependencyTree(), PrintStatus(), and UnsetDependency().
AliHLTDataBuffer* AliHLTTask::fpDataBuffer [private]
transient
the data buffer for the component processing
Definition at line 277 of file AliHLTTask.h.
Referenced by EndRun(), GetNofMatchingDataBlocks(), ProcessTask(), Release(), StartRun(), and Subscribe().
The documentation for this class was generated from the following files:
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTTask.h
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTConfiguration.cxx