AliHLTProcessor Class Reference
#include <AliHLTProcessor.h>
Detailed Description
Base class of HLT data analysis components. The class provides a common interface for the implementation of HLT data analysis components. The child class must implement the functions:
DoInit(p.) (optional)
DoDeinit(p.) (optional)
DoEvent(p.)
GetComponentID(p.)
GetInputDataTypes(p.)
GetOutputDataType(p.)
GetOutputDataSize(p.)
Spawn(p.)
Definition at line 32 of file AliHLTProcessor.h.
Public Member Functions
AliHLTProcessor ()
virtual ~AliHLTProcessor ()
int Init (AliHLTComponentEnvironment *environ, void *environParam, int argc, const char **argv)
int Deinit ()
int DoProcessing (const AliHLTComponentEventData &evtData, const AliHLTComponentBlockData *blocks, AliHLTComponentTriggerData &trigData, AliHLTUInt8_t *outputPtr, AliHLTUInt32_t &size, vector< AliHLTComponentBlockData > &outputBlocks, AliHLTComponentEventDoneData *&edd)
TComponentType GetComponentType ()
Private Member Functions
virtual int DoEvent (const AliHLTComponentEventData &evtData, const AliHLTComponentBlockData *blocks, AliHLTComponentTriggerData &trigData, AliHLTUInt8_t *outputPtr, AliHLTUInt32_t &size, vector< AliHLTComponentBlockData > &outputBlocks)
virtual int DoEvent (const AliHLTComponentEventData &evtData, AliHLTComponentTriggerData &trigData)
Constructor & Destructor Documentation
AliHLTProcessor::AliHLTProcessor ()
standard constructor
AliHLTProcessor::~AliHLTProcessor () [virtual]
standard destructor
Definition at line 43 of file AliHLTProcessor.cxx.
44 { 
45   // see header file for class documentation
46 }
Member Function Documentation
int AliHLTProcessor::Deinit () [virtual]
Clean-up function to terminate data processing. Clean-up of common data structures after data processing. The call is redirected to the internal method DoDeinit(p.) which can be overridden by the child class.
Reimplemented from AliHLTComponent (p.).
Reimplemented in AliHLTPHOSDDLDecoderComponent (p.), AliHLTPHOSHistogramProducerComponent (p.), AliHLTPHOSModuleMergerComponent (p.), AliHLTPHOSRawAnalyzerComponent (p.), and AliHLTPHOSRcuHistogramProducerComponent (p.).
Definition at line 56 of file AliHLTProcessor.cxx.
References AliHLTComponent::Deinit().
57 {
58   // see header file for class documentation
59   int iResult=0;
60   iResult=AliHLTComponent::Deinit();
61   return iResult;
62 }
int AliHLTProcessor::DoEvent (const AliHLTComponentEventData & evtData, AliHLTComponentTriggerData & trigData) [private, virtual]
The high-level data processing method. This is the default processing method; the method is called if no low level DoEvent(p.) method is overloaded by the component.
Parameters:
evtData event data structure
trigData trigger data structure
Returns: neg. error code if failed
Definition at line 89 of file AliHLTProcessor.cxx.
References HLTFatal.
90 {
91   HLTFatal("no processing method implemented");
92   return -ENOSYS;
93 }
int AliHLTProcessor::DoEvent (const AliHLTComponentEventData & evtData, const AliHLTComponentBlockData * blocks, AliHLTComponentTriggerData & trigData, AliHLTUInt8_t * outputPtr, AliHLTUInt32_t & size, vector< AliHLTComponentBlockData > & outputBlocks) [private, virtual]
The low-level data processing method for the component. This is the custom processing method and can be overloaded by the component.
Parameters:
evtData event data structure
blocks input data block descriptors
trigData trigger data structure
outputPtr pointer to target buffer
size input: size of target buffer output:size of produced data
outputBlocks list to receive output block descriptors
Returns: neg. error code if failed
Reimplemented in AliHLTPHOSDDLDecoderComponent (p.), AliHLTPHOSHistogramProducerComponent (p.), AliHLTPHOSModuleMergerComponent (p.), AliHLTPHOSRawAnalyzerComponent (p.), and AliHLTPHOSRcuHistogramProducerComponent (p.).
Definition at line 77 of file AliHLTProcessor.cxx.
Referenced by DoProcessing().
83 {
84   // we just forward to the high level method, all other parameters already
85   // have been stored internally
86   return DoEvent(evtData, trigData);
87 }
int AliHLTProcessor::DoProcessing (const AliHLTComponentEventData & evtData, const AliHLTComponentBlockData * blocks, AliHLTComponentTriggerData & trigData, AliHLTUInt8_t * outputPtr, AliHLTUInt32_t & size, vector< AliHLTComponentBlockData > & outputBlocks, AliHLTComponentEventDoneData *& edd) [virtual]
Event processing function. The method is called by the framework to process one event. After preparation of data structures. The call is redirected to DoEvent.
Returns: neg. error code if failed
Implements AliHLTComponent (p.).
Definition at line 64 of file AliHLTProcessor.cxx.
References DoEvent().
69 {
70   // see header file for class documentation
71   int iResult=0;
72   iResult=DoEvent(evtData, blocks, trigData, outputPtr, size, outputBlocks);
73   edd = NULL;
74   return iResult;
75 }
TComponentType AliHLTProcessor::GetComponentType () [inline, virtual]
Return AliHLTComponent::kProcessor(p.) type as component type.
Returns: component type id
Implements AliHLTComponent (p.).
Definition at line 64 of file AliHLTProcessor.h.
64 { return AliHLTComponent::kProcessor;}
int AliHLTProcessor::Init (AliHLTComponentEnvironment * environ, void * environParam, int argc, const char ** argv) [virtual]
Init function to prepare data processing. Initialization of common data structures for a sequence of events. The call is redirected to the internal method DoInit(p.) which can be overridden by the child class.
 During Init also the environment structure is passed to the component.
Parameters:
environ environment pointer with environment dependend function calls
environParam additionel parameter for function calls, the pointer is passed as it is
argc size of the argument array
argv agument array for component initialization
Reimplemented from AliHLTComponent (p.).
Definition at line 48 of file AliHLTProcessor.cxx.
References AliHLTComponent::Init().
49 {
50   // see header file for class documentation
51   int iResult=0;
52   iResult=AliHLTComponent::Init(environ, environParam, argc, argv);
53   return iResult;
54 }
The documentation for this class was generated from the following files:
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTProcessor.h
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTProcessor.cxx