AliHLTComponentHandler Class Reference
#include <AliHLTComponentHandler.h>
Detailed Description
The component handler controls all the processing components available in the system. It also controls the component shared libraries.
Definition at line 32 of file AliHLTComponentHandler.h.
Public Member Functions
AliHLTComponentHandler ()
AliHLTComponentHandler (AliHLTComponentEnvironment *pEnv)
AliHLTComponentHandler (const AliHLTComponentHandler &)
AliHLTComponentHandler & operator= (const AliHLTComponentHandler &)
virtual ~AliHLTComponentHandler ()
void SetEnvironment (AliHLTComponentEnvironment *pEnv)
int LoadLibrary (const char *libraryPath)
void * FindSymbol (const char *library, const char *symbol)
int UnloadLibrary (const char *libraryPath)
int ScheduleRegister (AliHLTComponent *pSample)
int RegisterComponent (AliHLTComponent *pSample)
int RegisterScheduledComponents ()
int DeregisterComponent (const char *componentID)
int AddStandardComponents ()
int DeleteStandardComponents ()
int CreateComponent (const char *componentID, void *pEnvParam, int argc, const char **argv, AliHLTComponent *&component)
int CreateComponent (const char *componentID, void *pEnvParam, AliHLTComponent *&component)
void List ()
int AnnounceVersion ()
Private Member Functions
int FindComponentIndex (const char *componentID)
AliHLTComponent * FindComponent (const char *componentID)
int InsertComponent (AliHLTComponent *pSample)
int UnloadLibraries ()
AliHLTLibHandle * FindLibrary (const char *library)
int UnloadLibrary (AliHLTComponentHandler::AliHLTLibHandle &handle)
ClassDef (AliHLTComponentHandler, 0)
Private Attributes
vector< AliHLTComponent * > fComponentList
vector< AliHLTComponent * > fScheduleList
vector< AliHLTLibHandle > fLibraryList
AliHLTComponentEnvironment fEnvironment
vector< AliHLTComponent * > fStandardList
Constructor & Destructor Documentation
AliHLTComponentHandler::AliHLTComponentHandler ()
standard constructor
AliHLTComponentHandler::AliHLTComponentHandler (AliHLTComponentEnvironment * pEnv)
constructor
Definition at line 67 of file AliHLTComponentHandler.cxx.
References AddStandardComponents(), fEnvironment, AliHLTComponentEnvironment::fLoggingFunc, and AliHLTLogging::Init().
68   :
69   fComponentList(),
70   fScheduleList(),
71   fLibraryList(),
72   fEnvironment(),
73   fStandardList()
74 {
75   // see header file for class documentation
76   if (pEnv) {
77     memcpy(&fEnvironment, pEnv, sizeof(AliHLTComponentEnvironment));
78     if (pEnv->fLoggingFunc) {
79       // the AliHLTLogging::Init method also sets the stream output
80       // and notification handler to AliLog. This should only be done
81       // if the logging environment contains a logging function
82       // for redirection
83       AliHLTLogging::Init(pEnv->fLoggingFunc);
84     }
85   }  else
86     memset(&fEnvironment, 0, sizeof(AliHLTComponentEnvironment));
87   AddStandardComponents();
88 }
AliHLTComponentHandler::AliHLTComponentHandler (const AliHLTComponentHandler &)
not a valid copy constructor, defined according to effective C++ style
Definition at line 90 of file AliHLTComponentHandler.cxx.
References HLTFatal.
91   :
92   fComponentList(),
93   fScheduleList(),
94   fLibraryList(),
95   fEnvironment(),
96   fStandardList()
97 {
98   // see header file for class documentation
99   HLTFatal("copy constructor untested");
100 }
AliHLTComponentHandler::~AliHLTComponentHandler () [virtual]
destructor
Definition at line 109 of file AliHLTComponentHandler.cxx.
References DeleteStandardComponents(), and UnloadLibraries().
110 {
111   // see header file for class documentation
112   DeleteStandardComponents();
113   UnloadLibraries();
114 }
Member Function Documentation
int AliHLTComponentHandler::AddStandardComponents ()
Add standard components The standard components are part of the libHLTbase library and need therefore a special handling.
Definition at line 447 of file AliHLTComponentHandler.cxx.
References RegisterScheduledComponents(), AliHLTComponent::SetGlobalComponentHandler(), and AliHLTComponent::UnsetGlobalComponentHandler().
Referenced by AliHLTComponentHandler().
448 {
449   // see header file for class documentation
450   int iResult=0;
451   AliHLTComponent::SetGlobalComponentHandler(this);
452 //   fStandardList.push_back(new AliHLTFilePublisher);
453 //   fStandardList.push_back(new AliHLTFileWriter);
454 //   fStandardList.push_back(new AliHLTRootFilePublisherComponent);
455 //   fStandardList.push_back(new AliHLTRootFileWriterComponent);
456   AliHLTComponent::UnsetGlobalComponentHandler();
457   iResult=RegisterScheduledComponents();
458   return iResult;
459 }
int AliHLTComponentHandler::AnnounceVersion ()
Announce version and compilation info of the base library.
Definition at line 116 of file AliHLTComponentHandler.cxx.
References HLTInfo.
Referenced by AliHLT_C_Component_InitSystem().
117 {
118   // see header file for class documentation
119   int iResult=0;
120 #ifdef PACKAGE_STRING
121   void HLTbaseCompileInfo( char*& date, char*& time);
122   char* date="";
123   char* time="";
124   HLTbaseCompileInfo(date, time);
125   if (!date) date="unknown";
126   if (!time) time="unknown";
127   HLTInfo("%s build on %s (%s)", PACKAGE_STRING, date, time);
128 #else
129   HLTInfo("ALICE High Level Trigger build on %s (%s) (embedded AliRoot build)", __DATE__, __TIME__);
130 #endif
131   return iResult;
132 }
AliHLTComponentHandler::ClassDef (AliHLTComponentHandler, 0) [private]
int AliHLTComponentHandler::CreateComponent (const char * componentID, void * pEnvParam, AliHLTComponent *& component) [inline]
Create a component of the given name (ID). Introduced for backward compatibility.
Parameters:
componentID ID of the component to create
pEnvParam environment parameter for the component
component reference to receive the create component instance
Returns: component pointer in component, neg. error code if failed
Definition at line 166 of file AliHLTComponentHandler.h.
References CreateComponent().
168     {
169     return CreateComponent( componentID, pEnvParam, 0, NULL, component );
170     }
int AliHLTComponentHandler::CreateComponent (const char * componentID, void * pEnvParam, int argc, const char ** argv, AliHLTComponent *& component)
Create a component of the given name (ID). The method tries to find a registerd component of id componentID and calls the Spawn method of the template component. After successful creation of a new object, the Init method is called in order to initialize the environment and the component arguments.
 The environment is the same for all components, but each component can have an additional private parameter pEnvParam.
 The component arguments consist of an array of strings and the array size in the usual manner of the main()(p.) function.
Parameters:
componentID ID of the component to create
pEnvParam environment parameter for the component
argc number of arguments in argv
argv argument array like in main()(p.)
component reference to receive the create component instance
Returns: component pointer in component, neg. error code if failed
Definition at line 180 of file AliHLTComponentHandler.cxx.
References fEnvironment, FindComponent(), HLTDebug, HLTError, HLTWarning, AliHLTComponent::Init(), and AliHLTComponent::Spawn().
Referenced by AliHLT_C_CreateComponent(), CreateComponent(), and AliHLTTask::Init().
181 {
182   // see header file for class documentation
183   int iResult=0;
184   if (componentID) {
185     AliHLTComponent* pSample=FindComponent(componentID);
186     if (pSample!=NULL) {
187       component=pSample->Spawn();
188       if (component) {
189         HLTDebug("component \"%s\" created (%p)", componentID, component);
190         if ((iResult=component->Init(&fEnvironment, pEnvParam, argc, argv))!=0) {
191           HLTError("Initialization of component \"%s\" failed with error %d", componentID, iResult);
192           delete component;
193           component=NULL;
194         }
195       } else {
196         HLTError("can not spawn component \"%s\"", componentID);
197         iResult=-ENOENT;
198       }
199     } else {
200       HLTWarning("can not find component \"%s\"", componentID);
201       iResult=-ENOENT;
202     }
203   } else {
204     iResult=-EINVAL;
205   }
206   return iResult;
207 }
int AliHLTComponentHandler::DeleteStandardComponents ()
Definition at line 476 of file AliHLTComponentHandler.cxx.
References fStandardList.
Referenced by ~AliHLTComponentHandler().
477 {
478   // see header file for class documentation
479   int iResult=0;
480   vector<AliHLTComponent*>::iterator element=fStandardList.begin();
481   while (element!=fStandardList.end()) {
482     //DeregisterComponent((*element)->GetComponentID());
483     delete(*element);
484     fStandardList.erase(element);
485     element=fStandardList.begin();
486   }
487   return iResult;
488 }
int AliHLTComponentHandler::DeregisterComponent (const char * componentID)
Deregister a component.
Parameters:
componentID ID of the component
Returns: neg. error code if failed
Definition at line 155 of file AliHLTComponentHandler.cxx.
References HLTWarning.
156 {
157   // see header file for class documentation
158 
159   int iResult=0;
160   if (componentID) {
161     HLTWarning("not yet implemented, please notify the developers if you need this function");
162   } else {
163     iResult=-EINVAL;
164   }
165   return iResult;
166 }
AliHLTComponent * AliHLTComponentHandler::FindComponent (const char * componentID) [private]
Find a component.
Parameters:
componentID ID of the component to find
Returns: descriptor
Definition at line 229 of file AliHLTComponentHandler.cxx.
References fComponentList, and FindComponentIndex().
Referenced by CreateComponent(), and RegisterComponent().
230 {
231   // see header file for class documentation
232   AliHLTComponent* pSample=NULL;
233   Int_t index=FindComponentIndex(componentID);
234   if (index>=0) {
235     pSample=(AliHLTComponent*)fComponentList.at(index);
236   }
237   return pSample;
238 }
Int_t AliHLTComponentHandler::FindComponentIndex (const char * componentID) [private]
Find a component.
Parameters:
componentID ID of the component to find
Returns: index, neg. error code if failed
Definition at line 209 of file AliHLTComponentHandler.cxx.
References fComponentList.
Referenced by FindComponent().
210 {
211   // see header file for class documentation
212   Int_t iResult=0;
213   if (componentID) {
214     vector<AliHLTComponent*>::iterator element=fComponentList.begin();
215     while (element!=fComponentList.end() && iResult>=0) {
216       if (strcmp(componentID, (*element)->GetComponentID())==0) {
217         break;
218       }
219       element++;
220       iResult++;
221     }
222     if (element==fComponentList.end()) iResult=-ENOENT;
223   } else {
224     iResult=-EINVAL;
225   }
226   return iResult;
227 }
AliHLTComponentHandler::AliHLTLibHandle * AliHLTComponentHandler::FindLibrary (const char * library) [private]
Find a specific library among the loaded libraries.
Parameters:
library library name/path
Returns: pointer to AliHLTLibHandle(p.)
Definition at line 431 of file AliHLTComponentHandler.cxx.
References fLibraryList.
Referenced by FindSymbol(), and LoadLibrary().
432 {
433   // see header file for class documentation
434   AliHLTLibHandle* hLib=NULL;
435   vector<AliHLTLibHandle>::iterator element=fLibraryList.begin();
436   while (element!=fLibraryList.end()) {
437     TString* name=reinterpret_cast<TString*>((*element).fName);
438     if (name->CompareTo(library)==0) {
439       hLib=&(*element);
440       break;
441     }
442     element++;
443   }
444   return hLib;
445 }
void * AliHLTComponentHandler::FindSymbol (const char * library, const char * symbol)
Find a symbol in a dynamically loaded library.
Parameters:
library library
symbol the symbol to find
Returns: void pointer to function
Definition at line 416 of file AliHLTComponentHandler.cxx.
References AliHLTComponentHandler::AliHLTLibHandle::fHandle, FindLibrary(), and AliHLTComponentHandler::AliHLTLibHandle::fName.
Referenced by AliHLTSystem::FindDynamicSymbol(), and AliHLTLogging::InitAliLogTrap().
417 {
418   // see header file for class documentation
419   AliHLTLibHandle* hLib=FindLibrary(library);
420   if (hLib==NULL) return NULL;
421   void* pFunc=NULL;
422 #ifdef HAVE_DLFCN_H
423   pFunc=dlsym(hLib->fHandle, symbol);
424 #else
425   TString* name=reinterpret_cast<TString*>(hLib->fName);
426   pFunc=gSystem->DynFindSymbol(name->Data(), symbol);
427 #endif
428   return pFunc;
429 }
Int_t AliHLTComponentHandler::InsertComponent (AliHLTComponent * pSample) [private]
Insert component to the list
Parameters:
pSample sample object of the component
Returns: neg. error code if failed
Definition at line 240 of file AliHLTComponentHandler.cxx.
References fComponentList.
Referenced by RegisterComponent().
241 {
242   // see header file for class documentation
243   Int_t iResult=0;
244   if (pSample!=NULL) {
245     fComponentList.push_back(pSample);
246   } else {
247     iResult=-EINVAL;
248   }
249   return iResult;
250 }
void AliHLTComponentHandler::List ()
Print registered components to stdout.
Returns: none
Definition at line 252 of file AliHLTComponentHandler.cxx.
References fComponentList, and HLTInfo.
253 {
254   // see header file for class documentation
255   vector<AliHLTComponent*>::iterator element=fComponentList.begin();
256   int index=0;
257   while (element!=fComponentList.end()) {
258     HLTInfo("%d. %s", index++, (*element++)->GetComponentID());
259   }
260 }
int AliHLTComponentHandler::LoadLibrary (const char * libraryPath)
Load a component shared library. The component library needs to be loaded from the ComponentHanler in order to automatically register all components in the library. Registration is done by passing a sample object of the component to the handler. The object has to be valid during the whole runtime and should thus be a global object which is ONLY used for the purpose of registration. This also ensures automatically registration at library load time.
Parameters:
libraryPath const char string containing the library name/path
Returns: 0 if succeeded, neg. error code if failed
Definition at line 277 of file AliHLTComponentHandler.cxx.
References AliHLTComponentHandler::AliHLTLibHandle::fHandle, FindLibrary(), fLibraryList, AliHLTComponentHandler::AliHLTLibHandle::fName, HLTDebug, HLTError, HLTInfo, RegisterScheduledComponents(), AliHLTComponent::SetGlobalComponentHandler(), and AliHLTComponent::UnsetGlobalComponentHandler().
Referenced by AliHLT_C_Component_LoadLibrary(), AliHLTLogging::InitAliLogTrap(), and AliHLTSystem::LoadComponentLibraries().
278 {
279   // see header file for class documentation
280   int iResult=0;
281   if (libraryPath) {
282     AliHLTComponent::SetGlobalComponentHandler(this);
283     AliHLTLibHandle hLib;
284     const char* loadtype="";
285 #ifdef HAVE_DLFCN_H
286     // use interface to the dynamic linking loader
287     hLib.fHandle=dlopen(libraryPath, RTLD_NOW);
288     loadtype="dlopen";
289 #else
290     // use ROOT dynamic loader
291     // check if the library was already loaded, as Load returns
292     // 'failure' if the library was already loaded
293     AliHLTLibHandle* pLib=FindLibrary(libraryPath);
294     if (pLib) {
295         int* pRootHandle=reinterpret_cast<int*>(pLib->fHandle);
296         (*pRootHandle)++;
297         HLTDebug("instance %d of library %s loaded", (*pRootHandle), libraryPath);
298         hLib.fHandle=pRootHandle;
299     }
300     
301     if (hLib.fHandle==NULL && gSystem->Load(libraryPath)==0) {
302       int* pRootHandle=new int;
303       if (pRootHandle) *pRootHandle=1;
304       hLib.fHandle=pRootHandle;
305       //HLTDebug("library %s loaded via gSystem", libraryPath);
306     }
307     loadtype="gSystem";
308 #endif //HAVE_DLFCN_H
309     if (hLib.fHandle!=NULL) {
310       // create TString object to store library path and use pointer as handle 
311       hLib.fName=new TString(libraryPath);
312       HLTInfo("library %s loaded (%s)", libraryPath, loadtype);
313       fLibraryList.insert(fLibraryList.begin(), hLib);
314       iResult=RegisterScheduledComponents();
315     } else {
316       HLTError("can not load library %s", libraryPath);
317 #ifdef HAVE_DLFCN_H
318       HLTError("dlopen error: %s", dlerror());
319 #endif //HAVE_DLFCN_H
320 #ifdef __APPLE__
321       iResult=-EFTYPE;
322 #else
323       iResult=-ELIBACC;
324 #endif
325     }
326     AliHLTComponent::UnsetGlobalComponentHandler();
327   } else {
328     iResult=-EINVAL;
329   }
330   return iResult;
331 }
AliHLTComponentHandler & AliHLTComponentHandler::operator= (const AliHLTComponentHandler &)
not a valid assignment op, but defined according to effective C++ style
Definition at line 102 of file AliHLTComponentHandler.cxx.
References HLTFatal.
103 { 
104   // see header file for class documentation
105   HLTFatal("assignment operator untested");
106   return *this;
107 }
Int_t AliHLTComponentHandler::RegisterComponent (AliHLTComponent * pSample)
Register a component. Registration is done by passing a sample object of the component to the handler. The object has to be valid during the whole runtime and should thus be a global object which is ONLY used for the purpose of registration.
Parameters:
pSample a sample object of the component
Returns: neg. error code if failed
Definition at line 134 of file AliHLTComponentHandler.cxx.
References FindComponent(), AliHLTComponent::GetComponentID(), HLTDebug, HLTInfo, and InsertComponent().
Referenced by RegisterScheduledComponents().
135 {
136   // see header file for class documentation
137   Int_t iResult=0;
138   if (pSample) {
139     if (FindComponent(pSample->GetComponentID())==NULL) {
140       iResult=InsertComponent(pSample);
141       if (iResult>=0) {
142         HLTInfo("component %s registered", pSample->GetComponentID());
143       }
144     } else {
145       // component already registered
146       HLTDebug("component %s already registered, skipped", pSample->GetComponentID());
147       iResult=-EEXIST;
148     }
149   } else {
150     iResult=-EINVAL;
151   }
152   return iResult;
153 }
int AliHLTComponentHandler::RegisterScheduledComponents ()
Registers all scheduled components.
Definition at line 461 of file AliHLTComponentHandler.cxx.
References fScheduleList, and RegisterComponent().
Referenced by AddStandardComponents(), and LoadLibrary().
462 {
463   // see header file for class documentation
464   int iResult=0;
465   vector<AliHLTComponent*>::iterator element=fScheduleList.begin();
466   int iLocalResult=0;
467   while (element!=fScheduleList.end()) {
468     iLocalResult=RegisterComponent(*element);
469     if (iResult==0) iResult=iLocalResult;
470     fScheduleList.erase(element);
471     element=fScheduleList.begin();
472   }
473   return iResult;
474 }
Int_t AliHLTComponentHandler::ScheduleRegister (AliHLTComponent * pSample)
Schedule a component for registration. Full registration will be done after successfull loading of the shared library.
Parameters:
pSample a sample object of the component
Returns: neg. error code if failed
Definition at line 168 of file AliHLTComponentHandler.cxx.
References fScheduleList.
Referenced by AliHLTComponent::AliHLTComponent().
169 {
170   // see header file for class documentation
171   Int_t iResult=0;
172   if (pSample) {
173     fScheduleList.push_back(pSample);
174   } else {
175     iResult=-EINVAL;
176   }
177   return iResult;
178 }
void AliHLTComponentHandler::SetEnvironment (AliHLTComponentEnvironment * pEnv)
Set the environment for the HLT framework. The environment mainly consists of function pointers for the integration of the HLT framework into a system like the PubSub online system or AliRoot offline system.
Parameters:
pEnv pointer to AliHLTComponentEnvironment(p.) structure
Returns: none
Definition at line 262 of file AliHLTComponentHandler.cxx.
References fEnvironment, AliHLTComponentEnvironment::fLoggingFunc, and AliHLTLogging::Init().
263 {
264   // see header file for class documentation
265   if (pEnv) {
266     memcpy(&fEnvironment, pEnv, sizeof(AliHLTComponentEnvironment));
267     if (fEnvironment.fLoggingFunc) {
268       // the AliHLTLogging::Init method also sets the stream output
269       // and notification handler to AliLog. This should only be done
270       // if the logging environment contains a logging function
271       // for redirection
272       AliHLTLogging::Init(fEnvironment.fLoggingFunc);
273     }
274   }
275 }
int AliHLTComponentHandler::UnloadLibraries () [private]
Close all libraries.
Returns: neg. error code if failed
Definition at line 403 of file AliHLTComponentHandler.cxx.
References fLibraryList, and UnloadLibrary().
Referenced by ~AliHLTComponentHandler().
404 {
405   // see header file for class documentation
406   int iResult=0;
407   vector<AliHLTLibHandle>::iterator element=fLibraryList.begin();
408   while (element!=fLibraryList.end()) {
409     UnloadLibrary(*element);
410     fLibraryList.erase(element);
411     element=fLibraryList.begin();
412   }
413   return iResult;
414 }
int AliHLTComponentHandler::UnloadLibrary (AliHLTComponentHandler::AliHLTLibHandle & handle) [private]
Unload a component shared library. All components will be de-registered when the last instance of the library was unloaded.
Parameters:
handle handle to the library to unload
Returns: 0 if succeeded, neg. error code if failed
Definition at line 354 of file AliHLTComponentHandler.cxx.
References AliHLTComponentHandler::AliHLTLibHandle::fHandle, AliHLTComponentHandler::AliHLTLibHandle::fName, HLTDebug, HLTError, and HLTWarning.
355 {
356   // see header file for class documentation
357   int iResult=0;
358   fgAliLoggingFunc=NULL;
359   TString* pName=reinterpret_cast<TString*>(handle.fName);
360 #ifdef HAVE_DLFCN_H
361   dlclose(handle.fHandle);
362 #else
363   int* pCount=reinterpret_cast<int*>(handle.fHandle);
364   if (--(*pCount)==0) {
365     if (pName) {
384     }
385     else {
386       HLTError("missing library name, can not unload");
387     }
388     delete pCount;
389   }
390 #endif //HAVE_DLFCN_H
391   handle.fName=NULL;
392   handle.fHandle=NULL;
393   if (pName) {
394     HLTDebug("unload library %s", pName->Data());
395     delete pName;
396   } else {
397     HLTWarning("missing name for unloaded library");
398   }
399   pName=NULL;
400   return iResult;
401 }
int AliHLTComponentHandler::UnloadLibrary (const char * libraryPath)
Unload a component shared library. All components will be de-registered when the last instance of the library was unloaded.
Parameters:
libraryPath library name as specified to LoadLibrary(p.)
Returns: 0 if succeeded, neg. error code if failed
Definition at line 333 of file AliHLTComponentHandler.cxx.
References fLibraryList.
Referenced by AliHLT_C_Component_UnloadLibrary(), and UnloadLibraries().
334 {
335   // see header file for class documentation
336   int iResult=0;
337   if (libraryPath) {
338     vector<AliHLTLibHandle>::iterator element=fLibraryList.begin();
339     while (element!=fLibraryList.end()) {
340       TString* pName=reinterpret_cast<TString*>((*element).fName);
341       if (pName->CompareTo(libraryPath)==0) {
342         UnloadLibrary(*element);
343         fLibraryList.erase(element);
344         break;
345       }
346       element++;
347   }
348   } else {
349     iResult=-EINVAL;
350   }
351   return iResult;
352 }
Member Data Documentation
vector<AliHLTComponent*> AliHLTComponentHandler::fComponentList [private]
list of registered components
Definition at line 241 of file AliHLTComponentHandler.h.
Referenced by FindComponent(), FindComponentIndex(), InsertComponent(), and List().
AliHLTComponentEnvironment AliHLTComponentHandler::fEnvironment [private]
running environment for the component
Definition at line 247 of file AliHLTComponentHandler.h.
Referenced by AliHLTComponentHandler(), CreateComponent(), and SetEnvironment().
vector<AliHLTLibHandle> AliHLTComponentHandler::fLibraryList [private]
list of libraries
Definition at line 245 of file AliHLTComponentHandler.h.
Referenced by FindLibrary(), LoadLibrary(), UnloadLibraries(), and UnloadLibrary().
vector<AliHLTComponent*> AliHLTComponentHandler::fScheduleList [private]
list of scheduled components
Definition at line 243 of file AliHLTComponentHandler.h.
Referenced by RegisterScheduledComponents(), and ScheduleRegister().
vector<AliHLTComponent*> AliHLTComponentHandler::fStandardList [private]
list of standard components
Definition at line 249 of file AliHLTComponentHandler.h.
Referenced by DeleteStandardComponents().
The documentation for this class was generated from the following files:
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTComponentHandler.h
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTComponentHandler.cxx