The HLT wrapper interface
Detailed Description
The wrapper interface is a pure C interface which allows to use the analysis components in external applications. The interface is utilized to bind the analysis code to the PubSub framework.
Typedefs
typedef void * AliHLTComponentHandle
Functions
int AliHLT_C_Component_InitSystem (AliHLTComponentEnvironment *environ)
int AliHLT_C_Component_DeinitSystem ()
int AliHLT_C_Component_LoadLibrary (const char *libraryPath)
int AliHLT_C_Component_UnloadLibrary (const char *libraryPath)
int AliHLT_C_CreateComponent (const char *componentType, void *environ_param, int argc, const char **argv, AliHLTComponentHandle *handle)
void AliHLT_C_DestroyComponent (AliHLTComponentHandle)
int AliHLT_C_ProcessEvent (AliHLTComponentHandle handle, const AliHLTComponent_EventData *evtData, const AliHLTComponent_BlockData *blocks, AliHLTComponent_TriggerData *trigData, AliHLTUInt8_t *outputPtr, AliHLTUInt32_t *size, AliHLTUInt32_t *outputBlockCnt, AliHLTComponent_BlockData **outputBlocks, AliHLTComponent_EventDoneData **edd)
int AliHLT_C_GetOutputDataType (AliHLTComponentHandle, AliHLTComponent_DataType *dataType)
int AliHLT_C_GetOutputSize (AliHLTComponentHandle, unsigned long *constBase, double *inputMultiplier)
Variables
const AliHLTComponentHandle kEmptyHLTComponentHandle = 0
Typedef Documentation
typedef void* AliHLTComponentHandle
Definition at line 49 of file AliHLT_C_Component_WrapperInterface.h.
Function Documentation
int AliHLT_C_Component_DeinitSystem ()
Definition at line 51 of file AliHLT_C_Component_WrapperInterface.cxx.
References gComponentHandler_C.
52 {
53   if ( gComponentHandler_C )
54     {
55       delete gComponentHandler_C;
56       gComponentHandler_C = NULL;
57     }
58   return 0;
59 }
int AliHLT_C_Component_InitSystem (AliHLTComponentEnvironment * environ)
Definition at line 37 of file AliHLT_C_Component_WrapperInterface.cxx.
References AliHLTComponentHandler::AnnounceVersion(), gComponentHandler_C, and AliHLTLogging::InitAliLogTrap().
38 {
39   if ( gComponentHandler_C )
40     {
41       return EINPROGRESS;
42     }
43   gComponentHandler_C = new AliHLTComponentHandler(environ);
44   if ( !gComponentHandler_C )
45     return EFAULT;
46   gComponentHandler_C->InitAliLogTrap(gComponentHandler_C);
47   gComponentHandler_C->AnnounceVersion();
48   return 0;
49 }
int AliHLT_C_Component_LoadLibrary (const char * libraryPath)
Definition at line 61 of file AliHLT_C_Component_WrapperInterface.cxx.
References gComponentHandler_C, and AliHLTComponentHandler::LoadLibrary().
62 {
63   if ( !gComponentHandler_C )
64     return ENXIO;
65   return gComponentHandler_C->LoadLibrary( libraryPath );
66 }
int AliHLT_C_Component_UnloadLibrary (const char * libraryPath)
Definition at line 68 of file AliHLT_C_Component_WrapperInterface.cxx.
References gComponentHandler_C, and AliHLTComponentHandler::UnloadLibrary().
69 {
70   if ( !gComponentHandler_C )
71     return ENXIO;
72   return gComponentHandler_C->UnloadLibrary( libraryPath );
73 }
int AliHLT_C_CreateComponent (const char * componentType, void * environ_param, int argc, const char ** argv, AliHLTComponentHandle * handle)
Definition at line 75 of file AliHLT_C_Component_WrapperInterface.cxx.
References AliHLTComponentHandler::CreateComponent(), and gComponentHandler_C.
76 {
77   if ( !gComponentHandler_C )
78     return ENXIO;
79   AliHLTComponent* comp;
80   int ret = gComponentHandler_C->CreateComponent( componentType, environ_param, argc, argv, comp );
81   *handle = reinterpret_cast<AliHLTComponentHandle>( comp );
82   return ret;
83 }
void AliHLT_C_DestroyComponent (AliHLTComponentHandle)
Definition at line 85 of file AliHLT_C_Component_WrapperInterface.cxx.
References AliHLTComponent::Deinit().
86 {
87   if ( !handle )
88     return;
89   
90   AliHLTComponent* pComp=reinterpret_cast<AliHLTComponent*>( handle );
91   pComp->Deinit();
92   delete pComp;
93 }
int AliHLT_C_GetOutputDataType (AliHLTComponentHandle, AliHLTComponent_DataType * dataType)
Definition at line 107 of file AliHLT_C_Component_WrapperInterface.cxx.
References AliHLTComponent_DataType, and AliHLTComponent::GetOutputDataType().
108 {
109   if ( !handle )
110     return ENXIO;
111   AliHLTComponent* comp = reinterpret_cast<AliHLTComponent*>( handle );
112   *dataType = comp->GetOutputDataType();
113   return 0;
114 }
int AliHLT_C_GetOutputSize (AliHLTComponentHandle, unsigned long * constBase, double * inputMultiplier)
Definition at line 116 of file AliHLT_C_Component_WrapperInterface.cxx.
References AliHLTComponent::GetOutputDataSize().
117 {
118   if ( !handle )
119     return ENXIO;
120   AliHLTComponent* comp = reinterpret_cast<AliHLTComponent*>( handle );
121   comp->GetOutputDataSize( *constBase, *inputMultiplier );
122   return 0;
123 }
int AliHLT_C_ProcessEvent (AliHLTComponentHandle handle, const AliHLTComponent_EventData * evtData, const AliHLTComponent_BlockData * blocks, AliHLTComponent_TriggerData * trigData, AliHLTUInt8_t * outputPtr, AliHLTUInt32_t * size, AliHLTUInt32_t * outputBlockCnt, AliHLTComponent_BlockData ** outputBlocks, AliHLTComponent_EventDoneData ** edd)
Definition at line 95 of file AliHLT_C_Component_WrapperInterface.cxx.
References AliHLTComponent_BlockData, AliHLTComponent_EventData, AliHLTComponent_EventDoneData, AliHLTComponent_TriggerData, and AliHLTComponent::ProcessEvent().
100 {
101   if ( !handle )
102     return ENXIO;
103   AliHLTComponent* comp = reinterpret_cast<AliHLTComponent*>( handle );
104   return comp->ProcessEvent( *evtData, blocks, *trigData, outputPtr, *size, *outputBlockCnt, *outputBlocks, *edd );
105 }
Variable Documentation
const AliHLTComponentHandle kEmptyHLTComponentHandle = 0
Definition at line 55 of file AliHLT_C_Component_WrapperInterface.h.