AliHLTComponentEnvironment Struct Reference
#include <AliHLTDataTypes.h>
Public Attributes
AliHLTUInt32_t fStructSize
void * fParam
void *(* fAllocMemoryFunc)(void *param, unsigned long size)
int(* fGetEventDoneDataFunc)(void *param, AliHLTEventID_t eventID, unsigned long size, AliHLTComponentEventDoneData **edd)
AliHLTfctLogging fLoggingFunc
Member Data Documentation
void*(* AliHLTComponentEnvironment::fAllocMemoryFunc)(void *param, unsigned long size)
Referenced by AliHLTComponent::AllocMemory(), and ClassImp().
int(* AliHLTComponentEnvironment::fGetEventDoneDataFunc)(void *param, AliHLTEventID_t eventID, unsigned long size, AliHLTComponentEventDoneData **edd)
Referenced by AliHLTComponent::GetEventDoneData().
AliHLTfctLogging AliHLTComponentEnvironment::fLoggingFunc
Definition at line 103 of file AliHLTDataTypes.h.
Referenced by AliHLTComponentHandler::AliHLTComponentHandler(), ClassImp(), and AliHLTComponentHandler::SetEnvironment().
void* AliHLTComponentEnvironment::fParam
Definition at line 97 of file AliHLTDataTypes.h.
Referenced by AliHLTComponent::AllocMemory(), AliHLTComponent::GetEventDoneData(), and AliHLTComponent::Init().
AliHLTUInt32_t AliHLTComponentEnvironment::fStructSize
Definition at line 96 of file AliHLTDataTypes.h.
The documentation for this struct was generated from the following file:
/home/perthi/cern/aliroot/AliRoot_head020507/HLT/BASE/AliHLTDataTypes.h