/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOFERMICUTOFF
#define ROOFERMICUTOFF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooFermiCutoff : public RooAbsPdf {
public:
  RooFermiCutoff() {} ; 
  RooFermiCutoff(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _cutoff,
	      RooAbsReal& _power);
  RooFermiCutoff(const RooFermiCutoff& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooFermiCutoff(*this,newname); }
  inline virtual ~RooFermiCutoff() { }

protected:

  RooRealProxy x ;
  RooRealProxy cutoff ;
  RooRealProxy power ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooFermiCutoff,1) // Your description goes here...
};
 
#endif
