/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOINVERSEGAUSSIANTAIL
#define ROOINVERSEGAUSSIANTAIL

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooInverseGaussianTail : public RooAbsPdf {
public:
  RooInverseGaussianTail() {} ; 
  RooInverseGaussianTail(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
	      RooAbsReal& _sigma,
	      RooAbsReal& _tail);
  RooInverseGaussianTail(const RooInverseGaussianTail& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooInverseGaussianTail(*this,newname); }
  inline virtual ~RooInverseGaussianTail() { }

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy sigma ;
  RooRealProxy tail ;
  
  Double_t evaluate() const;

private:

  ClassDef(RooInverseGaussianTail,1) // Your description goes here...
};
 
#endif
