rm galice.root
rm AliTPCclusters.root
rm AliTPCtracks.root
rm AliTPCtracksSorted.root
rm AliITSclustersV2.root
rm AliITStracksV2.root
rm AliITStracksV2Pid.root
rm itstracks.root
rm good_tracks_tpc
rm itsgood_tracks
