      BLOCK DATA LHAPDFSET
c... additions for multiset use
      include 'parmsetup.inc'
      include 'pathsetup.inc'
c      character*172 LHANAMES(nmxset)
      integer LHASET, LHAMEMB
      common/LHAPDF/LHANAME, LHASET, LHAMEMB
      integer LHAMEMBERS(nmxset),LHANUMBERS(nmxset)
      common/LHASETS/LHANAMES,LHANUMBERS,LHAMEMBERS,nsets
c...
c      CHARACTER*132 LHAPATH
      COMMON/LHAPDFC/LHAPATH
      SAVE /LHAPDFC/
      CHARACTER*20 LHAPARM(20)
      DOUBLE PRECISION LHAVALUE(20)
      COMMON/LHACONTROL/LHAPARM,LHAVALUE
      SAVE/LHACONTROL/
      DOUBLE PRECISION XMINNUM,XMAXNUM,Q2MINNUM,Q2MAXNUM,TOTNUM,
     >                 XMINNUP,XMAXNUP,Q2MINNUP,Q2MAXNUP,TOTNUP
      COMMON/LHAGLSTA/ XMINNUM,XMAXNUM,Q2MINNUM,Q2MAXNUM,TOTNUM,
     >                 XMINNUP,XMAXNUP,Q2MINNUP,Q2MAXNUP,TOTNUP
      SAVE/LHAGLSTA/
C...Interface to PDFLIB.
      COMMON/W50511/ NPTYPEPDFL,NGROUPPDFL,NSETPDFL,MODEPDFL,
     >               NFLPDFL,LOPDFL,TMASPDFL
      SAVE /W50511/
      DOUBLE PRECISION TMASPDFL
C...Interface to PDFLIB.
*      COMMON/W50512/QCDL4,QCDL5
*      SAVE /W50512/
*      DOUBLE PRECISION QCDL4,QCDL5
C...Interface to PDFLIB.
      COMMON/W50513/XMIN,XMAX,Q2MIN,Q2MAX
      SAVE /W50513/
      DOUBLE PRECISION XMIN,XMAX,Q2MIN,Q2MAX
      COMMON/LHAPDFE/LHAEXTRP
      SAVE /LHAPDFE/
      COMMON/LHAPDFR/QCDLHA4, QCDLHA5, NFLLHA
      SAVE /LHAPDFR/
c... following 2 for earlier Pythia versions
      COMMON/LUDAT1/MSTU5(200),PARU5(200),MSTJ5(200),PARJ5(200)
      SAVE /LUDAT1/

      data nsets/0/
      DATA LHAPATH/'PDFsets'/ ! Default = PDFsets (below current dir)
      DATA LHAPARM /20*' '/
      DATA LHAVALUE /20*0.0D0/
      DATA XMINNUM,XMAXNUM,Q2MINNUM,Q2MAXNUM,TOTNUM/5*0.D0/
      DATA XMINNUP,XMAXNUP,Q2MINNUP,Q2MAXNUP,TOTNUP/5*0.D0/
      END
