      BLOCK DATA LHAPDFSET
c... additions for multiset use
      include 'parmsetup.inc'
      include 'pathsetup.inc'
c      character*172 LHANAMES(nmxset)
      integer LHASET, LHAMEMB
      common/LHAPDF/LHANAME, LHASET, LHAMEMB
      integer LHAMEMBERS(nmxset),LHANUMBERS(nmxset)
      common/LHASETS/LHANAMES,LHANUMBERS,LHAMEMBERS,nsets
c...
c      CHARACTER*132 LHAPATH
      COMMON/LHAPDFC/LHAPATH
      SAVE /LHAPDFC/
      CHARACTER*20 LHAPARM(20)
      DOUBLE PRECISION LHAVALUE(20)
      COMMON/LHACONTROL/LHAPARM,LHAVALUE
      SAVE/LHACONTROL/
      DOUBLE PRECISION XMINNUM,XMAXNUM,Q2MINNUM,Q2MAXNUM,TOTNUM,
     >                 XMINNUP,XMAXNUP,Q2MINNUP,Q2MAXNUP,TOTNUP
      COMMON/LHAGLSTA/ XMINNUM,XMAXNUM,Q2MINNUM,Q2MAXNUM,TOTNUM,
     >                 XMINNUP,XMAXNUP,Q2MINNUP,Q2MAXNUP,TOTNUP
      SAVE/LHAGLSTA/
      COMMON/LHAPDFE/LHAEXTRP
      SAVE /LHAPDFE/
      COMMON/LHAPDFR/QCDLHA4, QCDLHA5, NFLLHA
      SAVE /LHAPDFR/

      data nsets/0/
      DATA LHAPATH/'PDFsets'/ ! Default = PDFsets (below current dir)
      DATA LHAPARM /20*' '/
      DATA LHAVALUE /20*0.0D0/
      DATA XMINNUM,XMAXNUM,Q2MINNUM,Q2MAXNUM,TOTNUM/5*0.D0/
      DATA XMINNUP,XMAXNUP,Q2MINNUP,Q2MAXNUP,TOTNUP/5*0.D0/
      END
