# $Id$
# Flugg tag $Name$

# Id: GNUmakefile,v 2.1 1998/07/02 15:26:52 gunter Exp 
# --------------------------------------------------------------
# GNUmakefile for examples module.  Gabriele Cosmo, 06/04/98
# --------------------------------------------------------------

name := test
G4TARGET := $(name)
G4EXLIB := true

ifndef FLUGGINSTALL
  FLUGGINSTALL = ../../..
endif

.PHONY: all
all: lib bin

include $(FLUGGINSTALL)/config/binmake.gmk
