#ifdef __CINT__

#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;

#pragma link C++ class AliAnalysisTaskCDMeson+;
#pragma link C++ class AliAnalysisTaskCDskimESD+;
#pragma link C++ class AliAnalysisTaskCDex+;
#pragma link C++ class AliAnalysisTaskCDTree+;
#pragma link C++ class AliMultiplicitySelectionCP+;
#pragma link C++ class AliAnalysisTaskCDPWA+;
#pragma link C++ class AliAnalysisTaskCDPWA::EventInfo+;
#pragma link C++ class AliAnalysisTaskCDPWA::CombInfo+;
#pragma link C++ class AliAnalysisTaskCDPWA::TrackInfo+;
#pragma link C++ class AliMultiplicitySelectionCPPWA+;
#pragma link C++ class AliCDMesonBaseStripped+;
#pragma link C++ class AliCDMesonBase+;
#pragma link C++ class AliCDMesonTracks+;
#pragma link C++ class AliCDMesonUtilsStripped+;
#pragma link C++ class AliCDMesonUtils+;
#pragma link C++ class AliAnalysisTaskCPQA++;
#pragma link C++ class AliAnalysisTaskCEPQA++;
#pragma link C++ class AliAnalysisTaskDG++;
#pragma link C++ class AliAnalysisTaskDG::TreeData++;
#pragma link C++ class AliAnalysisTaskDG::TrackData++;
#pragma link C++ class AliAnalysisTaskDG::EventInfo++;
#pragma link C++ class AliAnalysisTaskDG::ADV0++;
#pragma link C++ class AliAnalysisTaskDG::FMD++;
#pragma link C++ class AliAnalysisTaskDG::ZDC++;
#pragma link C++ class AliAnalysisTaskDG::SPD_0STG++;
#pragma link C++ class AliAnalysisTaskDgTree;
#pragma link C++ class AliSPDTriggerEfficiencyTask;
#pragma link C++ class AliTOFTriggerEfficiencyTask;
#pragma link C++ class AliTriggerStudy0STP+;
#pragma link C++ class AliAnalysisTaskDiffCrossSections+;
#pragma link C++ class AliAnalysisTaskDiffCrossSections::EventInfo+;
#pragma link C++ class AliAnalysisTaskDiffCrossSections::VtxInfo+;
#pragma link C++ class AliAnalysisTaskDiffCrossSections::FMDInfo+;
#pragma link C++ class AliAnalysisTaskDiffCrossSections::ADV0+;
#pragma link C++ class AliAnalysisTaskDiffCrossSections::TreeData+;
#pragma link C++ class AliAnalysisTaskDiffCrossSections::MCInfo+;
#pragma link C++ class AliAnalysisTaskDiffCrossSections::PseudoTrack+;
#pragma link C++ class AliAnalysisTaskDiffCrossSections::PseudoTracks+;
#pragma link C++ class AliCEPBase+;
#pragma link C++ class AliCEPUtils+;
#pragma link C++ class CEPRawADBuffer+;
#pragma link C++ class CEPRawCaloBuffer+;
#pragma link C++ class CEPRawCaloClusterTrack+;
#pragma link C++ class CEPRawEventBuffer+;
#pragma link C++ class CEPRawFMDBuffer+;
#pragma link C++ class CEPRawTrackBuffer+;
#pragma link C++ class CEPRawV0Buffer+;
#pragma link C++ class CEPEventBuffer+;
#pragma link C++ class CEPTrackBuffer+;
#pragma link C++ class AliAnalysisTaskCEP+;
#pragma link C++ class AliSPDGeometryUtils+;

#endif
