//if like define a different number of signal for TPC PID

//by default the task is anyway computing 1, 2 and 3 sigmas


//----------------------------------------------------



AliAnalysisTaskSEB0toDminuspi *AddTaskB0Dminuspi(Int_t system=0/*0=pp,1=PbPb*/,

						   Float_t minC=0, Float_t maxC=100,

						   TString cutsfile="", TString usercomment = "username",

						 Bool_t theMCon=kFALSE,  Double_t TopomaticDdaughter=0.,Double_t pTD=0.,Double_t pTpi=0.,Double_t prodd0=999., Double_t cosB=-999.,Double_t cosBXY=-999.,Double_t dlB=0.,Double_t NdlBXY=0., Double_t TopomaticD=999.,Double_t Topomaticpi=999., Double_t cosoaDpi=-999.)

{


const Bool_t theRareOn = kTRUE;

const Bool_t anaType   = 1;//0 HD; 1 UU;

const Bool_t doImp   = kFALSE;// imp par studies

  AliAnalysisManager *mgr = AliAnalysisManager::GetAnalysisManager();

  if (!mgr) {

    Printf("ERROR: No analysis manager to connect to.");

    return NULL;

  }  

  

  // cuts are stored in a TFile generated by makeTFile4CutsB0toDminuspi.C in ./macros/

  // set there the cuts!!!!!

 Bool_t stdcuts=kFALSE;
 // Bool_t stdcuts=kTRUE;
  
  TFile* filecuts;
  if( cutsfile.EqualTo("") ) {
    stdcuts=kTRUE; 
  } else {
      filecuts=TFile::Open(cutsfile.Data());
      if(!filecuts ||(filecuts&& !filecuts->IsOpen())){
	//AliFatal("Input file not found : check your cut object");
	Printf("ERROR: Input file not found : check your cut object");
	return NULL;
      }
  }
  


  AliRDHFCutsDplustoKpipi* RDHFB0toDminuspi;

  

  if(stdcuts) {
    RDHFB0toDminuspi=new AliRDHFCutsDplustoKpipi();
    if(system==0){ 
      RDHFB0toDminuspi->SetStandardCutsPP2010();
      //      RDHFB0toDminuspi->SetUseCentrality(kFALSE);


    }
    else if(system==1) {

      RDHFB0toDminuspi->SetStandardCutsPbPb2010();

      RDHFB0toDminuspi->SetMinCentrality(minC);

      RDHFB0toDminuspi->SetMinCentrality(maxC);

      RDHFB0toDminuspi->SetUseAOD049(kTRUE);

      RDHFB0toDminuspi->SetUseCentrality(AliRDHFCuts::kCentV0M);

    }

  }

  else RDHFB0toDminuspi = (AliRDHFCutsDplustoKpipi*)filecuts->Get("AnalysisCuts");

  //  RDHFB0toDminuspi->SetName("AnalysisCuts");


   if(theMCon==kFALSE){

     RDHFB0toDminuspi->SetOptPileup(AliRDHFCuts::kRejectPileupEvent);
     RDHFB0toDminuspi->SetTriggerMask(AliVEvent::kINT7);
     RDHFB0toDminuspi->SetTriggerClass("");
   }

  //  RDHFB0toDminuspi->SetUseCentrality(kFALSE);


  // mm let's see if everything is ok

  if(!RDHFB0toDminuspi){

    cout<<"Specific AliRDHFCuts not found"<<endl;

    return NULL;

  }

 

  //CREATE THE TASK

  printf("CREATE TASK\n");

  // create the task

  AliAnalysisTaskSEB0toDminuspi *task = new AliAnalysisTaskSEB0toDminuspi("AliAnalysisTaskSEB0toDminuspi",RDHFB0toDminuspi);

 
  task->SetReadMC(theMCon);
  task->SetDebugLevel(2);
 
  // task->SetDplusMassLimit(1.845,1.895);
  //  task->SetBMassLimits(4.5,6.5);


  //SetCut on inverted topomatic cut for D mesons  
  task->SetTopomaticCutOnDDaughters(TopomaticDdaughter);

  //Set B 2prong cuts
  task->SetDpTCut(pTD); 
  task->SetpipTCut(pTpi); 
  task->Setprodd0Cut(prodd0); 
  task->SetCosBCut(cosB); 
  task->SetCosXYBCut(cosBXY); 
  task->SetdlBCut(dlB); 
  task->SetNdlXYBCut(NdlBXY); 
  task->SetTopomaticD(TopomaticD); 
  task->SetTopomaticpi(Topomaticpi); 
  task->SetcosoaDpi(cosoaDpi);
  
  mgr->AddTask(task);



  // Create and connect containers for input/output

  usercomment = "_" + usercomment;  

  TString outputfile = AliAnalysisManager::GetCommonFileName();

  outputfile += ":PWG3_D2H_B0piDplus";
  outputfile += usercomment;
  

  // ------ input data ------
  TString input = "cinputB0";
  //input += usercomment;
  TString output1 = "Integrated";
  output1 += usercomment;
  TString output2 = "pTbin";
  output2 += usercomment;
  TString output3 = "coutputB0Norm";
  output3 += usercomment;
  TString output4 = "cuts";
  output4 += usercomment;
  //AliAnalysisDataContainer *cinput0  = mgr->GetCommonInputContainer();

  AliAnalysisDataContainer *cinput0  =  mgr->CreateContainer(input,TChain::Class(), 

							     AliAnalysisManager::kInputContainer);

 // ----- output data -----

  AliAnalysisDataContainer *coutput1 = mgr->CreateContainer(output1,TList::Class(),AliAnalysisManager::kOutputContainer,outputfile.Data());

  AliAnalysisDataContainer *coutputBin = mgr->CreateContainer(output2,TList::Class(),AliAnalysisManager::kOutputContainer,outputfile.Data());

  AliAnalysisDataContainer *coutputB0Norm = mgr->CreateContainer(output3,AliNormalizationCounter::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data());

  AliAnalysisDataContainer *coutputCuts = mgr->CreateContainer(output4,AliRDHFCutsDplustoKpipi::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data()); //cuts



  mgr->ConnectInput(task,0,mgr->GetCommonInputContainer());

  mgr->ConnectOutput(task,1,coutput1);

  mgr->ConnectOutput(task,2,coutputBin);

  mgr->ConnectOutput(task,3,coutputB0Norm);

  mgr->ConnectOutput(task,4,coutputCuts);
  

  return task;

}



