
AliAnalysisTaskSEB0toDStarPi *AddTaskB0toDStarPi(
                                TString cutsfile="",
                                TString usercomment = "doremalen",
                                Bool_t bUseMCInfo=kFALSE,
                                Int_t  nUseQuickSignalAnalysis=0,
                                Bool_t bGetCutInfo=kTRUE, 
                                Bool_t bShowRejection=kFALSE, 
                                Bool_t bShowMask=kFALSE,
                                Bool_t bUse3DHistograms=kFALSE, 
                                Bool_t bCheckBackground=kFALSE, 
                                Int_t nDebugLevel=0,
                                Int_t nUpgradeSetting=0,
                                Int_t nDegreePerRotation=3,
                                Int_t nNumberOfRotations=0,
                                Double_t fHistMassWindow=0.125,
                                Bool_t fCheckInjected = 1,
                                Int_t fRemoveInjected = 1
                                )
{
  AliAnalysisManager *mgr = AliAnalysisManager::GetAnalysisManager();

  // gDebug = 1;
  if (!mgr) {
    ::Error("AddTaskB0toDStarPi", "No analysis manager to connect to.");
    return NULL;
  }  

  if(nUseQuickSignalAnalysis != 0 && !bUseMCInfo){
    ::Error("AddTaskB0toDStarPi", "Quick signal analysis only works for Monte Carlo.");
    return NULL;
  }  
  
  // cuts are stored in a TFile generated by makeTFile4CutsB0toDStarPi.C in ./macros/
  // set the cuts there!

  TFile* filecuts;
  if( cutsfile.EqualTo("") ) {
    ::Error("Input file not found : add a cut object","");
  } else {
      filecuts=TFile::Open(cutsfile.Data());
      if(!filecuts ||(filecuts && !filecuts->IsOpen())){
  ::Error("Input file not found : check your cut object","");
      }
  }

  AliRDHFCutsB0toDStarPi* RDHFB0toDStarPi=new AliRDHFCutsB0toDStarPi();
  RDHFB0toDStarPi = (AliRDHFCutsB0toDStarPi*)filecuts->Get("B0toDStarPiCuts");
  if(!RDHFB0toDStarPi){
    cout<<"Specific AliRDHFCutsB0toDStarPi not found"<<endl;
    return 0;
  }


  RDHFB0toDStarPi->SetName("B0toDStarPiCuts");

  RDHFB0toDStarPi->SetGetCutInfo(bGetCutInfo);

  //CREATE THE TASK
  printf("CREATE TASK\n");

  // create the task
  AliAnalysisTaskSEB0toDStarPi *task = new AliAnalysisTaskSEB0toDStarPi("AliAnalysisTaskSEB0toDStarPi",RDHFB0toDStarPi);

  task->SetMC(bUseMCInfo);
  task->SetQuickSignalAnalysis(nUseQuickSignalAnalysis);
  task->SetGetCutInfo(bGetCutInfo);
  task->SetDebugLevel(nDebugLevel);
  task->SetShowRejection(bShowRejection);
  task->SetShowMask(bShowMask);
  task->SetUse3DHistograms(bUse3DHistograms);
  task->SetCheckBackground(bCheckBackground);
  task->SetUpgradeSetting(nUpgradeSetting);
  task->SetHistMassWindow(fHistMassWindow);
  task->SetDegreePerRotation(nDegreePerRotation);
  task->SetNumberOfRotations(nNumberOfRotations);
  task->SetCheckInjected(fCheckInjected);
  task->SetRemoveInjected(fRemoveInjected);


  mgr->AddTask(task);

  // Create and connect containers for input/output
  usercomment = "_" + usercomment; 

  TString outputfile = AliAnalysisManager::GetCommonFileName();

  outputfile += ":PWG3_D2H_B0toDStarPi";
  outputfile += usercomment;
  
  // ------ input data ------
  TString input = "input";
  input += usercomment;
  TString output1 = "chist1";
  output1 += usercomment;
  TString output2 = "cuts";
  output2 += usercomment;
  TString output3 = "D0FirstDaughter";
  output3 += usercomment;
  TString output4 = "D0SecondDaughter";
  output4 += usercomment;
  TString output5 = "DStarPion";
  output5 += usercomment;
  TString output6 = "B0Pion";
  output6 += usercomment;
  TString output7 = "D0";
  output7 += usercomment;
  TString output8 = "DStar";
  output8 += usercomment;
  TString output9 = "B0";
  output9 += usercomment;
  TString output10 = "D0_D0Pt";
  output10 += usercomment;
  TString output11 = "D0_DStarPt";
  output11 += usercomment;
  TString output12 = "DStar_DStarPt";
  output12 += usercomment;
  TString output13 = "B0MC";
  output13 += usercomment;


  AliAnalysisDataContainer *cinput0  =                    mgr->CreateContainer(input,TChain::Class(), AliAnalysisManager::kInputContainer);

 // ----- output data -----
  AliAnalysisDataContainer *coutput1 =                    mgr->CreateContainer(output1,TList::Class(),AliAnalysisManager::kOutputContainer,outputfile.Data());
  AliAnalysisDataContainer *coutputCuts =                 mgr->CreateContainer(output2,TList::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data()); //cuts
  AliAnalysisDataContainer *coutputD0FirstDaughter =      mgr->CreateContainer(output3,TList::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputD0SecondDaughter =     mgr->CreateContainer(output4,TList::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputDStarPion =            mgr->CreateContainer(output5,TList::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputB0Pion =               mgr->CreateContainer(output6,TList::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputD0 =                   mgr->CreateContainer(output7,TList::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputDStar =                mgr->CreateContainer(output8,TList::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputB0 =                   mgr->CreateContainer(output9,TList::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputD0_D0Pt =              mgr->CreateContainer(output10,TList::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputD0_DStarPt =           mgr->CreateContainer(output11,TList::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputDStar_DStarPt =        mgr->CreateContainer(output12,TList::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputB0MC =                 mgr->CreateContainer(output13,TList::Class(),AliAnalysisManager::kOutputContainer, outputfile.Data());


  mgr->ConnectInput(task,0,mgr->GetCommonInputContainer());
  mgr->ConnectOutput(task,1,coutput1);
  mgr->ConnectOutput(task,2,coutputCuts);
  mgr->ConnectOutput(task,3,coutputD0FirstDaughter);
  mgr->ConnectOutput(task,4,coutputD0SecondDaughter);
  mgr->ConnectOutput(task,5,coutputDStarPion);
  mgr->ConnectOutput(task,6,coutputB0Pion);
  mgr->ConnectOutput(task,7,coutputD0);
  mgr->ConnectOutput(task,8,coutputDStar);
  mgr->ConnectOutput(task,9,coutputB0);
  mgr->ConnectOutput(task,10,coutputD0_D0Pt);
  mgr->ConnectOutput(task,11,coutputD0_DStarPt);
  mgr->ConnectOutput(task,12,coutputDStar_DStarPt);
  mgr->ConnectOutput(task,13,coutputB0MC);


  return task;
}



