

// Temporary code to perform DStar EMCAL MC production check with MCGen trains using DStar code as basis. Do not use for DStar analysis.

const Bool_t theRareOn = kFALSE;

const Bool_t anaType   = 1;//0 HD; 1 UU;

const Bool_t doImp   = kFALSE;// imp par studies

//----------------------------------------------------



AliAnalysisTaskSEDStarEMCALProductionCheck *AddTaskDStarEMCALProductionCheck(Int_t system = 0/*0=pp,1=PbPb*/,

    Float_t minC = 0, Float_t maxC = 100,

    TString cutsfile = "", TString usercomment = "username",

    Bool_t theMCon = kFALSE, Bool_t doDStarVsY = kFALSE, TString cutsname = "DStartoKpipiCuts",

    Bool_t bUseEMCalTrigger = kFALSE, TString nameEMCalTrigger = "G1", Bool_t bCheckEMCalAcceptance = kFALSE, Int_t nCheckEMCalAcceptanceNumber = 0, Bool_t bApplyEMCALClusterEventCut = kFALSE)

{



  AliAnalysisManager *mgr = AliAnalysisManager::GetAnalysisManager();

  if (!mgr) {

    ::Error("AddTaskDStarEMCALProductionCheck", "No analysis manager to connect to.");

    return NULL;

  }



  // cuts are stored in a TFile generated by makeTFile4CutsDStartoKpipi.C in ./macros/

  // set there the cuts!!!!!

  Bool_t stdcuts = kFALSE;

  TFile* filecuts;
  if ( cutsfile.EqualTo("") ) {
    stdcuts = kTRUE;
  } else {
    filecuts = TFile::Open(cutsfile.Data());
    if (!filecuts || (filecuts && !filecuts->IsOpen())) {
      ::Fatal("AddTaskDStarEMCALProductionCheck", "Input file not found : check your cut object");
    }
  }





  AliRDHFCutsDStartoKpipi* RDHFDStartoKpipi = new AliRDHFCutsDStartoKpipi();

  if (stdcuts) {

    if (system == 0) RDHFDStartoKpipi->SetStandardCutsPP2010();

    else if (system == 1) {

      RDHFDStartoKpipi->SetStandardCutsPbPb2010();

      RDHFDStartoKpipi->SetMinCentrality(minC);

      RDHFDStartoKpipi->SetMinCentrality(maxC);

      RDHFDStartoKpipi->SetUseAOD049(kTRUE);

      RDHFDStartoKpipi->SetUseCentrality(AliRDHFCuts::kCentV0M);

    }

  }

  else {
    RDHFDStartoKpipi = (AliRDHFCutsDStartoKpipi*)filecuts->Get(cutsname.Data());
    if (minC != 0 && maxC != 0) { //if centrality 0 and 0 leave the values in the cut object
      RDHFDStartoKpipi->SetMinCentrality(minC);
      RDHFDStartoKpipi->SetMaxCentrality(maxC);
    }

  }

  RDHFDStartoKpipi->SetName("DStartoKpipiCuts");



  // mm let's see if everything is ok

  if (!RDHFDStartoKpipi) {

    cout << "Specific AliRDHFCuts not found" << endl;

    return NULL;

  }



  //CREATE THE TASK

  printf("CREATE TASK\n");

  // create the task

  AliAnalysisTaskSEDStarEMCALProductionCheck *task = new AliAnalysisTaskSEDStarEMCALProductionCheck("AliAnalysisTaskSEDStarEMCALProductionCheck", RDHFDStartoKpipi);

  task->SetAnalysisType(anaType);

  task->SetMC(theMCon);

  task->SetRareSearch(theRareOn);

  task->SetDoImpactParameterHistos(doImp);

  task->SetDebugLevel(0);

  task->SetDoDStarVsY(doDStarVsY);

  task->SetUseEMCalTrigger(bUseEMCalTrigger);

  task->SetTriggerSelectionString(nameEMCalTrigger);

  task->SetCheckEMCalAcceptance(bCheckEMCalAcceptance);

  task->SetCheckEMCalAcceptanceNumber(nCheckEMCalAcceptanceNumber);

  task->SetApplyEMCALClusterEventCut(bApplyEMCALClusterEventCut);

  mgr->AddTask(task);



  // Create and connect containers for input/output

  usercomment = "_" + usercomment;

  TString outputfile = AliAnalysisManager::GetCommonFileName();

  outputfile += ":PWG3_D2H_DStarSpectra";
  outputfile += usercomment;


  // ------ input data ------
  TString input = "indstar";
  input += usercomment;
  TString output1 = "chist1";
  output1 += usercomment;
  TString output2 = "DStarAll";
  output2 += usercomment;
  TString output3 = "DStarPID";
  output3 += usercomment;
  TString output4 = "cuts";
  output4 += usercomment;
  TString output5 = "coutputDstarNorm";
  output5 += usercomment;
  TString output6 = "ProductionCheck";
  output6 += usercomment;

  //AliAnalysisDataContainer *cinput0  = mgr->GetCommonInputContainer();

  AliAnalysisDataContainer *cinput0  =  mgr->CreateContainer(input, TChain::Class(),

                                        AliAnalysisManager::kInputContainer);

// ----- output data -----

  AliAnalysisDataContainer *coutput1 = mgr->CreateContainer(output1, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data());

  AliAnalysisDataContainer *coutputDStar1 = mgr->CreateContainer(output2, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data());

  AliAnalysisDataContainer *coutputDStar2 = mgr->CreateContainer(output3, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data());

  AliAnalysisDataContainer *coutputDStar3 = mgr->CreateContainer(output4, AliRDHFCutsDStartoKpipi::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data()); //cuts

  AliAnalysisDataContainer *coutputDstarNorm = mgr->CreateContainer(output5, AliNormalizationCounter::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data());

  AliAnalysisDataContainer *coutputProductionCheck = mgr->CreateContainer(output6, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data());


  mgr->ConnectInput(task, 0, mgr->GetCommonInputContainer());

  mgr->ConnectOutput(task, 1, coutput1);

  mgr->ConnectOutput(task, 2, coutputDStar1);

  mgr->ConnectOutput(task, 3, coutputDStar2);

  mgr->ConnectOutput(task, 4, coutputDStar3);

  mgr->ConnectOutput(task, 5, coutputDstarNorm);

  mgr->ConnectOutput(task, 6, coutputProductionCheck);

  return task;

}



