AliAnalysisTaskSELc2V0bachelorTMVA* AddTaskLc2V0bachpA_TMVA(TString finname="Lc2V0bachelorCuts.root",
							    Bool_t theMCon=kTRUE,
							    Bool_t onTheFly=kFALSE,
							    Bool_t keepingOnlyHIJINGbkd=kFALSE,
							    TString suffixName="",
								Int_t system=AliAnalysisTaskSELc2V0bachelorTMVA::kpPb2013,
								TString estimatorFilename = "", Double_t refMult = 27.99){
  
  AliAnalysisManager *mgr = AliAnalysisManager::GetAnalysisManager();
  if (!mgr) {
    ::Error("AddTaskLc2V0bachelor", "No analysis manager to connect to.");
    return NULL;
  }  
  
  // cuts are stored in a TFile generated by makeTFile4CutsLc2V0bachelor.C in ./macros/
  // set there the cuts!!!!!
  Bool_t stdcuts=kFALSE;
  TFile* filecuts;
  if( finname.EqualTo("") ) {
    stdcuts=kTRUE; 
  } else {
    filecuts=TFile::Open(finname.Data());
    if(!filecuts ||(filecuts&& !filecuts->IsOpen())){
      Printf("FATAL: Input file not found : check your cut object");
      return NULL;
    }
  }
  
  AliRDHFCutsLctoV0* RDHFCutsLctoV0anal = new AliRDHFCutsLctoV0();
  if (stdcuts) RDHFCutsLctoV0anal->SetStandardCutsPP2010();
  else RDHFCutsLctoV0anal = (AliRDHFCutsLctoV0*)filecuts->Get("LctoV0AnalysisCuts");
  RDHFCutsLctoV0anal->SetName("LctoV0AnalysisCuts");
  RDHFCutsLctoV0anal->SetMinPtCandidate(-1.);
  RDHFCutsLctoV0anal->SetMaxPtCandidate(10000.);
  
  
  // mm let's see if everything is ok
  if (!RDHFCutsLctoV0anal) {
    cout << "Specific AliRDHFCutsLctoV0 not found\n";
    return NULL;
  }
  
  
  //CREATE THE TASK
  printf("CREATE TASK\n");
  AliAnalysisTaskSELc2V0bachelorTMVA *task = new AliAnalysisTaskSELc2V0bachelorTMVA("AliAnalysisTaskSELc2V0bachelorTMVA", RDHFCutsLctoV0anal, onTheFly);

  task->SetMC(theMCon);
  task->SetKeepingKeepingOnlyHIJINGBkg(keepingOnlyHIJINGbkd);
  task->SetK0sAnalysis(kTRUE);
  task->SetDebugLevel(0);
  task->SetAnalysisType(system);
  
   // attempt to load histogram for multiplicity vs zvtx correction

  const Char_t* profilebasename="SPDmult10";
  const Char_t* periodNames[4];
  TProfile* multEstimatorAvg[4];
  if (estimatorFilename.EqualTo("")) {//Warn if undefined
     printf("Warning: Estimator file not defined, correction of Ntrk will not be performed!\n");}
      else { //Load file if defined
           TFile *fileEstimator = TFile::Open(estimatorFilename.Data());
           if (!fileEstimator) {
               Printf("FATAL: File with multiplicity estimator not found! Please check the filepath and retry.\n");
               return NULL;
           }
          task->SetReferenceMultiplicity(refMult);
          
          switch (system) {
           case (Int_t)AliAnalysisTaskSELc2V0bachelorTMVA::kpPb2013:   //LHC13b & LHC13c
            task->SetIspA(kTRUE);
            periodNames[0] = "LHC13b";
	    periodNames[1] = "LHC13c";
            for (Int_t ip = 0; ip < 2; ip++) {
               cout << "Trying to get " << Form("%s_%s",profilebasename,periodNames[ip]) << endl;
               multEstimatorAvg[ip] = (TProfile*)(fileEstimator->Get(Form("%s_%s",profilebasename,periodNames[ip]))->Clone(Form("%s_%s_clone",profilebasename,periodNames[ip])));
               if (!multEstimatorAvg[ip]) { // mult estimator not found
                  Printf("Multiplicity estimator for %s not found! Please check that your estimator file contains %s_%s",periodNames[ip],profilebasename,periodNames[ip]);
                  return NULL;
                  }
            }
               task->SetMultVsZProfileLHC13b(multEstimatorAvg[0]);
               task->SetMultVsZProfileLHC13c(multEstimatorAvg[1]);
            break;
         
           case (Int_t)AliAnalysisTaskSELc2V0bachelorTMVA::kpPb2016:  //LHC16q & LHC16t
            task->SetIspA(kTRUE);
            periodNames[0] = "LHC16q_265499to265525_265309to265387";
	    periodNames[1] = "LHC16q_265435";
	    periodNames[2] = "LHC16q_265388to265427";
	    periodNames[3] = "LHC16t_267163to267166";
            for (Int_t ip = 0; ip < 4; ip++) {
               cout << "Trying to get " << Form("%s_%s",profilebasename,periodNames[ip]) << endl;
               multEstimatorAvg[ip] = (TProfile*)(fileEstimator->Get(Form("%s_%s",profilebasename,periodNames[ip]))->Clone(Form("%s_%s_clone",profilebasename,periodNames[ip])));
               if (!multEstimatorAvg[ip]) { // mult estimator not found
                  Printf("Multiplicity estimator for %s not found! Please check that your estimator file contains %s_%s",periodNames[ip],profilebasename,periodNames[ip]);
                  return NULL;
                  }
            }
               task->SetMultVsZProfileLHC16qt1stBunch(multEstimatorAvg[0]);
               task->SetMultVsZProfileLHC16qt2ndBunch(multEstimatorAvg[1]);
               task->SetMultVsZProfileLHC16qt3rdBunch(multEstimatorAvg[2]);
               task->SetMultVsZProfileLHC16qt4thBunch(multEstimatorAvg[3]);
            break;
           case (Int_t)AliAnalysisTaskSELc2V0bachelorTMVA::kpp2016:  //LHC16j,k,l
            task->SetIspA(kFALSE);
            periodNames[0] = "LHC16j";
	    periodNames[1] = "LHC16k";
	    periodNames[2] = "LHC16l";
            for (Int_t ip = 0; ip < 3; ip++) {
               cout << "Trying to get " << Form("%s_%s",profilebasename,periodNames[ip]) << endl;
               multEstimatorAvg[ip] = (TProfile*)(fileEstimator->Get(Form("%s_%s",profilebasename,periodNames[ip]))->Clone(Form("%s_%s_clone",profilebasename,periodNames[ip])));
               if (!multEstimatorAvg[ip]) { // mult estimator not found
                  Printf("Multiplicity estimator for %s not found! Please check that your estimator file contains %s_%s",periodNames[ip],profilebasename,periodNames[ip]);
                  return NULL;
                  }
            }
                task->SetMultVsZProfileLHC16j(multEstimatorAvg[0]);
                task->SetMultVsZProfileLHC16k(multEstimatorAvg[1]);
                task->SetMultVsZProfileLHC16l(multEstimatorAvg[2]);
               break; 
           case (Int_t)AliAnalysisTaskSELc2V0bachelorTMVA::kpp2010:  //LHC10bcde
            task->SetIspA(kFALSE);
            periodNames[0] = "LHC10b";
	    periodNames[1] = "LHC10c";
	    periodNames[2] = "LHC10d";
	    periodNames[3] = "LHC10e";
            for (Int_t ip = 0; ip < 4; ip++) {
               cout << "Trying to get " << Form("%s_%s",profilebasename,periodNames[ip]) << endl;
               multEstimatorAvg[ip] = (TProfile*)(fileEstimator->Get(Form("%s_%s",profilebasename,periodNames[ip]))->Clone(Form("%s_%s_clone",profilebasename,periodNames[ip])));
               if (!multEstimatorAvg[ip]) { // mult estimator not found
                  Printf("Multiplicity estimator for %s not found! Please check that your estimator file contains %s_%s",periodNames[ip],profilebasename,periodNames[ip]);
                  return NULL;
                  }
            }
               task->SetMultVsZProfileLHC10b(multEstimatorAvg[0]);
               task->SetMultVsZProfileLHC10c(multEstimatorAvg[1]);
               task->SetMultVsZProfileLHC10d(multEstimatorAvg[2]);
               task->SetMultVsZProfileLHC10e(multEstimatorAvg[3]);
            break;
           default: 
            Printf("FATAL: Multiplicity profiles specified but analysis mode incorrect. Please check collision system and retry.");
            return NULL;
            }
          
 }

  mgr->AddTask(task);
  
  // Create and connect containers for input/output  
  //TString outputfile = AliAnalysisManager::GetCommonFileName();
  TString outputfile = Form("Lc2K0Sp_tree_pA%s.root", suffixName.Data());
  TString output1name="", output2name="", output3name="", output4name="", output5name="", output6name="", output7name="", output8name="", output9name="";

  output1name = Form("treeList%s", suffixName.Data());
  output2name = Form("listCounters%s", suffixName.Data());
  output3name = Form("Lc2pK0SCuts%s", suffixName.Data());
  output4name = Form("treeSgn%s", suffixName.Data());
  output5name = Form("treeBkg%s", suffixName.Data());
  output6name = Form("listHistoKF%s", suffixName.Data());
  output7name = Form("weights%s", suffixName.Data());
  output8name = Form("multhists%s", suffixName.Data());
  output9name = Form("listProfiles%s", suffixName.Data());

  mgr->ConnectInput(task, 0, mgr->GetCommonInputContainer());
  AliAnalysisDataContainer *coutput1   = mgr->CreateContainer(output1name, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data()); // trees
  mgr->ConnectOutput(task, 1, coutput1);
  
  AliAnalysisDataContainer *coutputLc2 = mgr->CreateContainer(output2name,TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data()); //counter
  mgr->ConnectOutput(task, 2, coutputLc2);
  
  AliAnalysisDataContainer *coutputLc3 = mgr->CreateContainer(output3name, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data()); // cuts
  mgr->ConnectOutput(task, 3, coutputLc3);
  
  AliAnalysisDataContainer *coutput4   = mgr->CreateContainer(output4name, TTree::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data()); // trees
  mgr->ConnectOutput(task, 4, coutput4);
  
  AliAnalysisDataContainer *coutput5   = mgr->CreateContainer(output5name, TTree::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data()); // trees
  mgr->ConnectOutput(task, 5, coutput5);
  
  AliAnalysisDataContainer *coutput6   = mgr->CreateContainer(output6name, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data()); // trees
  mgr->ConnectOutput(task, 6, coutput6);  
  
  AliAnalysisDataContainer *coutput7   = mgr->CreateContainer(output7name, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data()); // weights
  mgr->ConnectOutput(task, 7, coutput7);
 
 AliAnalysisDataContainer *coutput8    = mgr->CreateContainer(output8name, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data()); //multiplicity-based histograms (zvtx dist, etc)
  mgr->ConnectOutput(task, 8, coutput8);

 AliAnalysisDataContainer *coutput9    = mgr->CreateContainer(output9name, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data());  //input multiplicity profiles
  mgr->ConnectOutput(task, 9, coutput9);

  return task;
  
}
