
AliAnalysisTaskSEB0toDPi *AddTaskB0toDPi(
                              TString   cutsfile = "",
                              TString   usercomment = "doremalen",
                              Bool_t    bUseMCInfo = kFALSE,
                              Int_t     nUseQuickSignalAnalysis = 0,
                              Bool_t    bShowRejection = kFALSE,
                              Bool_t    bShowMask = kFALSE,
                              Int_t     nDebugLevel = 0,
                              Int_t     nDegreePerRotation = 3,
                              Int_t     nNumberOfRotations = 0,
                              Double_t  fHistMassWindow = 0.125, // 0.125 is about 4 to 5 sigma for B0 width of 0.025 to 0.032
                              Bool_t    bPerformCutOptimization = kFALSE,
                              Bool_t    bRemoveInjected = kFALSE,
                              Bool_t    bUseSideBands = kFALSE,
                              Double_t  fSideBandLow =  0.125,
                              Double_t  fSideBandHigh = 0.225,
                              Bool_t    bSaveTRHists = kFALSE // overwrites normal background histograms
)
{

  AliAnalysisManager *mgr = AliAnalysisManager::GetAnalysisManager();

  // gDebug = 1;
  if (!mgr) {
    ::Error("AddTaskB0toDPi", "No analysis manager to connect to.");
    return NULL;
  }

  if (nUseQuickSignalAnalysis != 0 && !bUseMCInfo) {
    ::Error("AddTaskB0toDPi", "Quick signal analysis only works for Monte Carlo.");
    return NULL;
  }

  // cuts are stored in a TFile generated by makeTFile4CutsB0toDPi.C in ./macros/
  // set the cuts there!

  TFile* filecuts;
  if ( cutsfile.EqualTo("") ) {
    ::Error("Input file not found : add a cut object", "");
  } else {
    filecuts = TFile::Open(cutsfile.Data());
    if (!filecuts || (filecuts && !filecuts->IsOpen())) {
      ::Error("Input file not found : check your cut object", "");
    }
  }

  AliRDHFCutsB0toDPi* RDHFB0toDPi = new AliRDHFCutsB0toDPi();
  RDHFB0toDPi = (AliRDHFCutsB0toDPi*)filecuts->Get("B0toDPiCuts");
  if (!RDHFB0toDPi) {
    cout << "Specific AliRDHFCutsB0toDPi not found" << endl;
    return 0;
  }


  RDHFB0toDPi->SetName("B0toDPiCuts");

  //CREATE THE TASK
  printf("CREATE TASK\n");

  // create the task
  AliAnalysisTaskSEB0toDPi *task = new AliAnalysisTaskSEB0toDPi("AliAnalysisTaskSEB0toDPi", RDHFB0toDPi);

  task->SetMC(bUseMCInfo);
  task->SetQuickSignalAnalysis(nUseQuickSignalAnalysis);
  task->SetDebugLevel(nDebugLevel);
  task->SetShowRejection(bShowRejection);
  task->SetShowMask(bShowMask);
  task->SetHistMassWindow(fHistMassWindow);
  task->SetDegreePerRotation(nDegreePerRotation);
  task->SetNumberOfRotations(nNumberOfRotations);
  task->SetPerformCutOptimization(bPerformCutOptimization);
  task->SetRemoveInjected(bRemoveInjected);
  task->SetUseSideBands(bUseSideBands);
  task->SetSideBandLow(fSideBandLow);
  task->SetSideBandHigh(fSideBandHigh);
  task->SetSaveTRHists(bSaveTRHists);

  mgr->AddTask(task);

  // Create and connect containers for input/output
  usercomment = "_" + usercomment;

  TString outputfile = AliAnalysisManager::GetCommonFileName();

  outputfile += ":PWG3_D2H_B0toDPi";
  outputfile += usercomment;

  // ------ input data ------
  TString input = "input";
  input += usercomment;
  TString output1 = "GeneralInfo";
  output1 += usercomment;
  TString output2 = "cuts";
  output2 += usercomment;
  TString output3 = "DPlusKaon";
  output3 += usercomment;
  TString output4 = "DPlusPions";
  output4 += usercomment;
  TString output5 = "B0Pion";
  output5 += usercomment;
  TString output6 = "DPlus";
  output6 += usercomment;
  TString output7 = "B0";
  output7 += usercomment;
  TString output8 = "DPlus_DPlusPt";
  output8 += usercomment;
  TString output9 = "B0Results";
  output9 += usercomment;


  AliAnalysisDataContainer *cinput0  =                    mgr->CreateContainer(input, TChain::Class(), AliAnalysisManager::kInputContainer);

// ----- output data -----
  AliAnalysisDataContainer *coutput1 =                    mgr->CreateContainer(output1, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputCuts =                 mgr->CreateContainer(output2, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data()); //cuts
  AliAnalysisDataContainer *coutputDPlusKaon =            mgr->CreateContainer(output3, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputDPlusPions =           mgr->CreateContainer(output4, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputB0Pion =           mgr->CreateContainer(output5, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputDPlus =                mgr->CreateContainer(output6, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputB0 =                mgr->CreateContainer(output7, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputDPlus_DPlusPt =        mgr->CreateContainer(output8, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data());
  AliAnalysisDataContainer *coutputB0Results =         mgr->CreateContainer(output9, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data());


  mgr->ConnectInput(task, 0, mgr->GetCommonInputContainer());
  mgr->ConnectOutput(task, 1, coutput1);
  mgr->ConnectOutput(task, 2, coutputCuts);
  mgr->ConnectOutput(task, 3, coutputDPlusKaon);
  mgr->ConnectOutput(task, 4, coutputDPlusPions);
  mgr->ConnectOutput(task, 5, coutputB0Pion);
  mgr->ConnectOutput(task, 6, coutputDPlus);
  mgr->ConnectOutput(task, 7, coutputB0);
  mgr->ConnectOutput(task, 8, coutputDPlus_DPlusPt);
  mgr->ConnectOutput(task, 9, coutputB0Results);


  return task;
}



