class AliAnalysisTaskSESigmacTopK0Spi;

AliAnalysisTaskSESigmacTopK0Spi* AddTaskSigmacTopK0Spi(Int_t nvars, TString library = "_6_12", TString finname="Lc2V0bachelorCuts.root",
						      Float_t ptMin=0, Float_t ptMax=24,
						      Bool_t theMCon=kTRUE,
						      Bool_t fillTree=kFALSE,
						      Bool_t onTheFly=kFALSE,
						      Bool_t keepingOnlyHIJINGbkd=kFALSE,
						      TString suffixName="",
						      Bool_t debugFlag = kFALSE,
						      Bool_t useXmlWeightsFile = kTRUE,
						      Bool_t useWeightsLibrary = kFALSE,
						      TString xmlWeightsFile = "$ALICE_PHYSICS/PWGHF/vertexingHF/TMVA/LHC19c2a_TMVAClassification_BDT_2_4_noP.weights.xml",
						      Bool_t useXmlFileFromCVMFS = kFALSE,
						      TString xmlFileFromCVMFS = "LHC19c2a_TMVAClassification_BDT_2_4_noP.weights.xml",
						      Bool_t useMultCorrection = kFALSE,
						      TString estimatorFilename="",       //  Multicity estimator file
						      Double_t refMult=9.26,              // refrence multiplcity (period b)
						      Int_t year = 16,                    // Production year 
						      Int_t recoEstimator = AliAnalysisTaskSESigmacTopK0Spi::kNtrk10, // fMultiplicityEstimator
						      Bool_t useMultCut = kFALSE,
						      Float_t multMin = 0.,    // Minimum is included
						      Float_t multMax = 99999. // Maximum is excluded
						      ){
  
  AliAnalysisManager *mgr = AliAnalysisManager::GetAnalysisManager();
  if (!mgr) {
    ::Error("AddTaskLc2V0bachelor", "No analysis manager to connect to.");
    return NULL;
  }  
  
  // cuts are stored in a TFile generated by makeTFile4CutsLc2V0bachelor.C in ./macros/
  // set there the cuts!!!!!
  Bool_t stdcuts=kFALSE;
  TFile* filecuts;
  if( finname.EqualTo("") ) {
    stdcuts=kTRUE; 
  } else {
    filecuts=TFile::Open(finname.Data());
    if(!filecuts ||(filecuts&& !filecuts->IsOpen())){
      Printf("Input file not found : check your cut object"); return NULL;
    }
  }

  AliRDHFCutsLctoV0* RDHFCutsLctoV0anal = new AliRDHFCutsLctoV0();
  if (stdcuts) RDHFCutsLctoV0anal->SetStandardCutsPP2010();
  else RDHFCutsLctoV0anal = (AliRDHFCutsLctoV0*)filecuts->Get("LctoV0AnalysisCuts");
  RDHFCutsLctoV0anal->SetName("LctoV0AnalysisCuts");
  //RDHFCutsLctoV0anal->SetMinPtCandidate(ptMin);
  //RDHFCutsLctoV0anal->SetMaxPtCandidate(ptMax);
  RDHFCutsLctoV0anal->SetUseCentrality(1);
  
  // mm let's see if everything is ok
  if (!RDHFCutsLctoV0anal) {
    cout << "Specific AliRDHFCutsLctoV0 not found\n";
    return NULL;
  }
  
  Int_t nvarsSpectators = 0;
  TString namesTMVAvars, namesTMVAvarsSpectators;
  if (nvars == 12) {
    namesTMVAvars = "massK0S,tImpParBach,tImpParV0,DecayLengthK0S*0.497/v0P,cosPAK0S,signd0,nSigmaTOFpr,nSigmaTOFpi,nSigmaTOFka,nSigmaTPCpr,nSigmaTPCpi,nSigmaTPCka";
    nvarsSpectators = 14;
    namesTMVAvarsSpectators = "massLc2K0Sp,LcPt,massLambda,massLambdaBar,cosPAK0S,V0positivePt,V0negativePt,dcaV0pos,dcaV0neg,v0Pt,dcaV0,V0positiveEta,bachelorEta,centrality";
  }
  else if (nvars == 11) {
    namesTMVAvars = "massK0S,tImpParBach,tImpParV0,DecayLengthK0S*0.497/v0P,cosPAK0S,CosThetaStar,signd0,nSigmaTOFpr,nSigmaTPCpr,nSigmaTPCpi,nSigmaTPCka";
    nvarsSpectators = 14;
    namesTMVAvarsSpectators = "massLc2K0Sp,LcPt,massLambda,massLambdaBar,cosPAK0S,V0positivePt,V0negativePt,dcaV0pos,dcaV0neg,v0Pt,dcaV0,V0positiveEta,bachelorEta,centrality";
  }
  else if (nvars == 10) {
    namesTMVAvars = "massK0S,tImpParBach,tImpParV0,DecayLengthK0S*0.497/v0P,cosPAK0S,CosThetaStar,nSigmaTOFpr,nSigmaTPCpr,nSigmaTPCpi,nSigmaTPCka";
    nvarsSpectators = 14;
    namesTMVAvarsSpectators = "massLc2K0Sp,LcPt,massLambda,massLambdaBar,cosPAK0S,V0positivePt,V0negativePt,dcaV0pos,dcaV0neg,v0Pt,dcaV0,V0positiveEta,bachelorEta,centrality";
  }
  else if (nvars == 9) {
    namesTMVAvars = "massK0S,tImpParBach,tImpParV0,DecayLengthK0S*0.497/v0P,cosPAK0S, nSigmaTOFpr,nSigmaTPCpr,nSigmaTPCpi,nSigmaTPCka";
    nvarsSpectators = 14;
    namesTMVAvarsSpectators = "massLc2K0Sp,LcPt,massLambda,massLambdaBar,cosPAK0S,V0positivePt,V0negativePt,dcaV0pos,dcaV0neg,v0Pt,dcaV0,V0positiveEta,bachelorEta,centrality";
  }
  else if (nvars == 8) {
    namesTMVAvars = "massK0S,tImpParBach,tImpParV0,DecayLengthK0S*0.497/v0P,cosPAK0S,CosThetaStar,signd0,combinedProtonProb";
    nvarsSpectators = 14;
    namesTMVAvarsSpectators = "massLc2K0Sp,LcPt,massLambda,massLambdaBar,cosPAK0S,V0positivePt,V0negativePt,dcaV0pos,dcaV0neg,v0Pt,dcaV0,V0positiveEta,bachelorEta,centrality";
  }

  //CREATE THE TASK
  printf("CREATE TASK\n");
  AliAnalysisTaskSESigmacTopK0Spi *task = new AliAnalysisTaskSESigmacTopK0Spi("AliAnalysisTaskSESigmacTopK0Spi", RDHFCutsLctoV0anal, onTheFly);
  //  task->SetMVReader(fBDTReader);
  task->SetNVars(nvars);
  task->SetNamesTMVAVariables(namesTMVAvars);
  task->SetTMVAlibName("libvertexingHFTMVA.so");
  task->SetTMVAlibPtBin(library);
  task->SetFillTree(fillTree);

  Printf("************* fillTree = %d", (Int_t)fillTree);
  task->SetMC(theMCon);
  task->SetSigmaCptMin(ptMin);
  task->SetSigmaCptMax(ptMax);
  task->SetKeepingOnlyHIJINGBkg(keepingOnlyHIJINGbkd);
  task->SetK0sAnalysis(kTRUE);
  task->SetDebugLevel(0);
  task->SetDebugHistograms(debugFlag);
  // TMVA reader
  task->SetNVarsSpectators(nvarsSpectators);
  task->SetNamesTMVAVariablesSpectators(namesTMVAvarsSpectators);
  task->SetUseXmlWeightsFile(useXmlWeightsFile);
  task->SetUseWeightsLibrary(useWeightsLibrary);
  task->SetXmlWeightsFile(TString(gSystem->ExpandPathName(Form("%s", xmlWeightsFile.Data()))));
  
  task->SetUseXmlFileFromCVMFS(useXmlFileFromCVMFS);
  task->SetXmlFileFromCVMFS(xmlFileFromCVMFS);

  if(useMultCorrection){

    task->SetUseMultiplicityCorrection(useMultCorrection);
    task->SetMultiplicityEstimator(recoEstimator);
    task->SetUseVZEROParameterizedVertexCorr(1);

    if(estimatorFilename.EqualTo("") ) {
      printf("Estimator file not provided, multiplcity corrected histograms will not be filled\n");
    } 
    else{

      TFile* fileEstimator=TFile::Open(estimatorFilename.Data());
      if(!fileEstimator)  {
        Printf("FATAL: File with multiplicity estimator not found\n");
        return NULL;
      }

      task->SetReferenceMultiplcity(refMult); // < FUNCTION NEEDS TO BE ADDED TO AliAnalysisTaskSELc2V0bachelorMultTMVAApp.h
      const Char_t* profilebasename="SPDmult10";
      if(recoEstimator==AliAnalysisTaskSELc2V0bachelorTMVAApp::kVZEROA || recoEstimator==AliAnalysisTaskSELc2V0bachelorTMVAApp::kVZEROAEq) profilebasename="VZEROAmult";
      else if(recoEstimator==AliAnalysisTaskSELc2V0bachelorTMVAApp::kVZERO || recoEstimator==AliAnalysisTaskSELc2V0bachelorTMVAApp::kVZEROEq) profilebasename="VZEROMmult";
      cout<<endl<<endl<<" profilebasename="<<profilebasename<<endl<<endl;

      // Only pp data is calibrated
      if(year == 10){
        const Char_t* periodNames[4] = {"LHC10b", "LHC10c", "LHC10d", "LHC10e"};
        TProfile* multEstimatorAvg[4];
        for(Int_t ip=0; ip<4; ip++) {
          multEstimatorAvg[ip] = (TProfile*)(fileEstimator->Get(Form("%s_%s",profilebasename,periodNames[ip]))->Clone(Form("%s_%s_clone",profilebasename,periodNames[ip])));
          if (!multEstimatorAvg[ip]) {
            Printf("Multiplicity estimator for %s not found! Please check your estimator file",periodNames[ip]);
            return NULL;
          }
        }
        task->SetMultiplVsZProfileLHC10b(multEstimatorAvg[0]);
        task->SetMultiplVsZProfileLHC10c(multEstimatorAvg[1]);
        task->SetMultiplVsZProfileLHC10d(multEstimatorAvg[2]);
        task->SetMultiplVsZProfileLHC10e(multEstimatorAvg[3]);
      }
      else if(year == 16){
        const Char_t* periodNames[10]={"LHC16d","LHC16e","LHC16g","LHC16h_1", "LHC16h_2","LHC16j","LHC16k","LHC16l","LHC16o","LHC16p"};
        TProfile *multEstimatorAvg[10];
        for(Int_t ip=0;ip<10; ip++){
          multEstimatorAvg[ip] = (TProfile*)(fileEstimator->Get(Form("%s_%s",profilebasename,periodNames[ip]))->Clone(Form("%s_%s_clone",profilebasename,periodNames[ip])));
          if (!multEstimatorAvg[ip]) {
            Printf("Multiplicity estimator for %s not found! Please check your estimator file",periodNames[ip]);
            return NULL;
          }
        }
        task->SetMultiplVsZProfileLHC16d(multEstimatorAvg[0]);
        task->SetMultiplVsZProfileLHC16e(multEstimatorAvg[1]);
        task->SetMultiplVsZProfileLHC16g(multEstimatorAvg[2]);
        task->SetMultiplVsZProfileLHC16h1(multEstimatorAvg[3]);
        task->SetMultiplVsZProfileLHC16h2(multEstimatorAvg[4]);
        task->SetMultiplVsZProfileLHC16j(multEstimatorAvg[5]);
        task->SetMultiplVsZProfileLHC16k(multEstimatorAvg[6]);
        task->SetMultiplVsZProfileLHC16l(multEstimatorAvg[7]);
        task->SetMultiplVsZProfileLHC16o(multEstimatorAvg[8]);
        task->SetMultiplVsZProfileLHC16p(multEstimatorAvg[9]);
      }
      else if(year == 17){
        const Char_t* periodNames[10]={"LHC17e","LHC17f","LHC17h","LHC17i", "LHC17j","LHC17k","LHC17l","LHC17m","LHC17o","LHC17r"};
        TProfile *multEstimatorAvg[10];
        for(Int_t ip=0;ip<10; ip++){
          multEstimatorAvg[ip] = (TProfile*)(fileEstimator->Get(Form("%s_%s",profilebasename,periodNames[ip]))->Clone(Form("%s_%s_clone",profilebasename,periodNames[ip])));
          if (!multEstimatorAvg[ip]) {
            Printf("Multiplicity estimator for %s not found! Please check your estimator file",periodNames[ip]);
            return NULL;
          }
        }
        task->SetMultiplVsZProfileLHC17e(multEstimatorAvg[0]);
        task->SetMultiplVsZProfileLHC17f(multEstimatorAvg[1]);
        task->SetMultiplVsZProfileLHC17h(multEstimatorAvg[2]);
        task->SetMultiplVsZProfileLHC17i(multEstimatorAvg[3]);
        task->SetMultiplVsZProfileLHC17j(multEstimatorAvg[4]);
        task->SetMultiplVsZProfileLHC17k(multEstimatorAvg[5]);
        task->SetMultiplVsZProfileLHC17l(multEstimatorAvg[6]);
        task->SetMultiplVsZProfileLHC17m(multEstimatorAvg[7]);
        task->SetMultiplVsZProfileLHC17o(multEstimatorAvg[8]);
        task->SetMultiplVsZProfileLHC17r(multEstimatorAvg[9]);
      }
      else if(year == 18){
        const Char_t* periodNames[14]={"LHC18b","LHC18d","LHC18e","LHC18f", "LHC18g","LHC18h","LHC18i","LHC18j","LHC18k","LHC18l","LHC18m","LHC18n","LHC18o","LHC18p"};
        TProfile *multEstimatorAvg[14];
        for(Int_t ip=0;ip<14; ip++){
          multEstimatorAvg[ip] = (TProfile*)(fileEstimator->Get(Form("%s_%s",profilebasename,periodNames[ip]))->Clone(Form("%s_%s_clone",profilebasename,periodNames[ip])));
          if (!multEstimatorAvg[ip]) {
            Printf("Multiplicity estimator for %s not found! Please check your estimator file",periodNames[ip]);
            return NULL;
          }
        }
        task->SetMultiplVsZProfileLHC18b(multEstimatorAvg[0]);
        task->SetMultiplVsZProfileLHC18d(multEstimatorAvg[1]);
        task->SetMultiplVsZProfileLHC18e(multEstimatorAvg[2]);
        task->SetMultiplVsZProfileLHC18f(multEstimatorAvg[3]);
        task->SetMultiplVsZProfileLHC18g(multEstimatorAvg[4]);
        task->SetMultiplVsZProfileLHC18h(multEstimatorAvg[5]);
        task->SetMultiplVsZProfileLHC18i(multEstimatorAvg[6]);
        task->SetMultiplVsZProfileLHC18j(multEstimatorAvg[7]);
        task->SetMultiplVsZProfileLHC18k(multEstimatorAvg[8]);
        task->SetMultiplVsZProfileLHC18l(multEstimatorAvg[9]);
        task->SetMultiplVsZProfileLHC18m(multEstimatorAvg[10]);
        task->SetMultiplVsZProfileLHC18n(multEstimatorAvg[11]);
        task->SetMultiplVsZProfileLHC18o(multEstimatorAvg[12]);
        task->SetMultiplVsZProfileLHC18p(multEstimatorAvg[13]);
      }
    }
  }

  if(useMultCut){
    task->SetUseMultiplcityCut(useMultCut);
    task->SetMinimumMultiplicity(multMin);
    task->SetMaximumMultiplicity(multMax);
  }
  
  mgr->AddTask(task);
  
  // Create and connect containers for input/output  
  //TString outputfile = AliAnalysisManager::GetCommonFileName();
  TString outputfile = "AnalysisResults.root";
  TString output1name="", output2name="", output3name="", output4name="", output5name="", output6name="", output7name="";

  output1name = Form("treeList%s%s", suffixName.Data(), library.Data());
  output2name = Form("Lc2pK0Scounter%s%s", suffixName.Data(), library.Data());
  output3name = Form("Lc2pK0SCuts%s%s", suffixName.Data(), library.Data());
  output4name = Form("treeSgn%s%s", suffixName.Data(), library.Data());
  output5name = Form("treeBkg%s%s", suffixName.Data(), library.Data());
  output6name = Form("listTHnSpares%s%s", suffixName.Data(), library.Data());
  output7name = Form("listWeights%s%s", suffixName.Data(), library.Data());

  mgr->ConnectInput(task, 0, mgr->GetCommonInputContainer());
  AliAnalysisDataContainer *coutput1   = mgr->CreateContainer(output1name, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data()); // trees
  mgr->ConnectOutput(task, 1, coutput1);
  
  AliAnalysisDataContainer *coutputLc2 = mgr->CreateContainer(output2name, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data()); //counter
  mgr->ConnectOutput(task, 2, coutputLc2);
  
  AliAnalysisDataContainer *coutputLc3 = mgr->CreateContainer(output3name, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data()); // cuts
  mgr->ConnectOutput(task, 3, coutputLc3);
  
  AliAnalysisDataContainer *coutput4   = mgr->CreateContainer(output4name, TTree::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data()); // trees
  mgr->ConnectOutput(task, 4, coutput4);
  
  AliAnalysisDataContainer *coutput5   = mgr->CreateContainer(output5name, TTree::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data()); // trees
  mgr->ConnectOutput(task, 5, coutput5);
  
  AliAnalysisDataContainer *coutput6   = mgr->CreateContainer(output6name, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data()); // trees
  mgr->ConnectOutput(task, 6, coutput6);  

  AliAnalysisDataContainer *coutput7   = mgr->CreateContainer(output7name, TList::Class(), AliAnalysisManager::kOutputContainer, outputfile.Data()); // trees
  mgr->ConnectOutput(task, 7, coutput7);  

  return task;
  
}
