/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooFermiCutoff.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooFermiCutoff) 

 RooFermiCutoff::RooFermiCutoff(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _cutoff,
                        RooAbsReal& _power) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   cutoff("cutoff","cutoff",this,_cutoff),
   power("power","power",this,_power)
 { 
 } 


 RooFermiCutoff::RooFermiCutoff(const RooFermiCutoff& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   cutoff("cutoff",this,other.cutoff),
   power("power",this,other.power)
 { 
 } 



 Double_t RooFermiCutoff::evaluate() const 
 { 
   return (1. / (TMath::Exp((cutoff - x) / power) + 1.)); 
 } 



