{
  gSystem->Load("libVMC");
  gSystem->Load("libTree");
  gSystem->Load("libProofPlayer");
  gSystem->Load("libPhysics");
  gSystem->Load("libMatrix");
  gSystem->Load("libMinuit");
  gSystem->Load("libXMLParser");
  gSystem->Load("libGui");
  gSystem->Load("libSTEERBase");
  gSystem->Load("libESD");
  gSystem->Load("libAOD");
  gSystem->Load("libANALYSIS");
  gSystem->Load("libRAWDatabase");
}
