/**
 * @file 
 * 
 * Scripts to draw energy loss fits from correction object file 
 *
 * @ingroup pwglf_forward_scripts_corr
 */
/** 
 * Draw secondary maps fits to a multi-page PDF. 
 *
 * @par Input: 
 * The input is expected to be parameters to obtain a
 * AliFMDCorrSecondaryMap object from the correction manager
* 
 * @par Output: 
 * A multi-page PDF.  Note, that the PDF generated by ROOT in this way
 * is broken (cannot be read by Acrobat Reader on Windows and MacOSX)
 * and one should pass it through a filter to correct these problems.
 * 
 * @param fname   File name 
 * @param option  Drawing options 
 *
 * @ingroup pwglf_forward_scripts_corr
 */
void
DrawCorrSecMap(ULong_t runNo, UShort_t sys, UShort_t sNN, Short_t field,
	    const char* fname=0, Bool_t details=true)
{
  //__________________________________________________________________
  // Load libraries and object 
  // const char* fwd = "$ALICE_ROOT/PWGLF/FORWARD/analysis2";
  const char* fwd = "$ALICE_ROOT/PWGLF/FORWARD/analysis2";
  gROOT->Macro(Form("%s/scripts/LoadLibs.C", fwd));
  gROOT->LoadMacro(Form("%s/scripts/SummaryDrawer.C", fwd));
  gROOT->LoadMacro(Form("%s/corrs/CorrDrawer.C", fwd));

  CorrDrawer d;
  d.Run(AliForwardCorrectionManager::kSecondaryMap, runNo, sys, sNN, field, 
	false, false, "", fname);
}
//
// EOF
//
