/**
 * @file 
 * 
 * Scripts to draw energy loss fits from correction object file 
 *
 * @ingroup pwglf_forward_scripts_corr
 */
/** 
 * Draw energy loss fits to a multi-page PDF. 
 *
 * @par Input: 
 * The input file is expected to contain a AliFMDCorrELossFit object
 * named @c elossfits in the top level directory.
 * 
 * @par Output: 
 * A multi-page PDF.  Note, that the PDF generated by ROOT in this way
 * is broken (cannot be read by Acrobat Reader on Windows and MacOSX)
 * and one should pass it through a filter to correct these problems.
 * 
 * @param fname   File name 
 * @param option  Drawing options 
 *
 * @ingroup pwglf_forward_scripts_corr
 */
void
DrawCorrELoss(ULong_t runNo, UShort_t sys, UShort_t sNN, Short_t field,
	      Bool_t mc=false, Bool_t sat=false, 
	      const char* fname=0, Bool_t details=true)
{
  //__________________________________________________________________
  // Load libraries and object 
  // const char* fwd = "$ALICE_ROOT/PWGLF/FORWARD/analysis2";
  const char* fwd = "$ALICE_ROOT/PWGLF/FORWARD/analysis2";
  gROOT->Macro(Form("%s/scripts/LoadLibs.C", fwd));
  gROOT->LoadMacro(Form("%s/scripts/SummaryDrawer.C", fwd));
  gROOT->LoadMacro(Form("%s/corrs/CorrDrawer.C", fwd));

  CorrDrawer d;
  d.Summarize(AliForwardCorrectionManager::kELossFits, runNo, sys, sNN, field, 
	      mc, sat, "", fname);
}
void
DrawCorrELoss(Bool_t      mc, 
	      const char* file="forward_eloss.root", 
	      const char* local="fmd_corrections.root")
{
  const char* fwd = "$ALICE_ROOT/PWGLF/FORWARD/analysis2";
  gROOT->Macro(Form("%s/scripts/LoadLibs.C", fwd));
  gROOT->LoadMacro(Form("%s/scripts/SummaryDrawer.C", fwd));
  gROOT->LoadMacro(Form("%s/corrs/CorrDrawer.C", fwd));

  CorrDrawer::Summarize(AliForwardCorrectionManager::kELossFits, 
			mc, file, local);
}

void 
DrawCorrELoss(Bool_t mc, Bool_t dummy, 
	      const char* file="forward_eloss_rerun.root")
{
  const char* fwd = "$ALICE_ROOT/PWGLF/FORWARD/analysis2";
  if (!gROOT->GetClass("AliAODForwardMult"))
    gROOT->Macro(Form("%s/scripts/LoadLibs.C", fwd));
  gROOT->LoadMacro(Form("%s/scripts/SummaryDrawer.C", fwd));
  gROOT->LoadMacro(Form("%s/corrs/CorrDrawer.C", fwd));

  TFile* hist = TFile::Open(file, "READ");
  if (!hist) { 
    Error("DrawCorrELoss", "Failed to open %s", file);
    return;
  }
  TList* res = static_cast<TList*>(hist->Get("ForwardResults"));
  if (!res) { 
    Error("DrawCorrEloss", "Failed to get ForwardResults from %s", file);
    return;
  }
  TList* ef = static_cast<TList*>(res->FindObject("fmdEnergyFitter"));
  if (!ef) { 
    Error("DrawCorrEloss", "Failed to get fmdEnergyFitter from %s:/%s", 
	  file, res->GetName());
    return;
  }

  AliFMDCorrELossFit* fits = 
    static_cast<AliFMDCorrELossFit*>(ef->FindObject("AliFMDCorrELossFit"));
  if (!fits) {
    Error("DrawCorrEloss", "Failed to get AliFMDCorrELossFit from %s:/%s/%s", 
	  file, res->GetName(), ef->GetName());
    return;
  }
  
  CorrDrawer* cd = new CorrDrawer;
  cd->fELossExtra = file;
  cd->fMinQuality = 8;
  cd->Summarize(fits);
}

//
// EOF
//
