// Generated by ExtractELoss.C
TString MakeDest(const TString& dest, const TString& fname)
{
  TString tmp(dest);
  if (!tmp.IsNull()) {
    if (!tmp.EndsWith("/")) tmp.Append("/");
    tmp.Append(fname);
  }
  return tmp;
}

void Upload(const TString& dest="")
{
  gROOT->Macro("$ALICE_PHYSICS/PWGLF/FORWARD/analysis2/scripts/LoadLibs.C");
  
  const char* fmdFile = "fmd_corrections.root";
  TString fdest = MakeDest(dest, fmdFile);
  
  AliForwardCorrectionManager::Instance().Append(fmdFile, fdest);
}
// EOF

