configurationName: "EMCal MC Correction Cluster V1"
pass: "pass1"
CellEnergy:
    enabled: false
    createHistos: false
CellBadChannel:
    enabled: true
    createHistos: true
CellTimeCalib:
    enabled: false
    createHistos: false
Clusterizer:
    enabled: true
    clusterizer: kClusterizerv1
    cellE: 0.1
    seedE: 0.5
    cellTimeMin: -50e-6
    cellTimeMax:  50e-6
    clusterTimeLength: 1e6
    createHistos: true
    recalDistToBadChannels: true
    recalShowerShape: false
    remapMcAod: false
ClusterExotics:
    enabled: true
    createHistos: true
ClusterNonLinearity:
    enabled: true
    setForceClusterE: true
    createHistos: true
    nonLinFunct: kPi0MCv3
ClusterTrackMatcher:
    enabled: true
    createHistos: true
CellEmulateCrosstalk:                               # Component to emulate crosstalk
    enabled: false                                  # Whether to enable the task
    createHistos: false                             # Whether the task should create output histograms
sharedParameters:
    # You can define here any parameters that you would like to share between tasks. See the documentation for more information
    enableFracEMCRecalc: true                       # Enables the recalculation of the MC labels including the fractional energy on cell level
    removeNMCGenerators: 0                          # set number of accepted MC generators input (only for enableFracEMCRecalc=1)
    enableMCGenRemovTrack: true                     # apply the MC generators rejection also for track matching
    removeMCGen1: ""                                # name of generator input to be accepted
    removeMCGen2: ""                                # name of generator input to be accepted
