
FIND_FILE(DPMJET_OBJECT NAMES dpmjet3.0-5.o PATHS $ENV{DPMJETDIR})
FIND_FILE(DPMJET_PY_OBJECT NAMES pythia6115dpm3v1.o PATHS $ENV{DPMJETDIR})
FIND_FILE(DPMJET_PHO_OBJECT NAMES phojet1.12-35c4.o PATHS $ENV{DPMJETDIR})

IF (DPMJET_OBJECT AND DPMJET_PY_OBJECT AND DPMJET_PHO_OBJECT) 
   SET(DPMJET_OBJECTS ${DPMJET_OBJECT} ${DPMJET_PY_OBJECT} ${DPMJET_PHO_OBJECT})
   SET(DPMJET_FOUND TRUE)
   SET_SOURCE_FILES_PROPERTIES(
      ${DPMJET_OBJECTS}
      PROPERTIES
      EXTERNAL_OBJECT true 
   )
ENDIF (DPMJET_OBJECT AND DPMJET_PY_OBJECT AND DPMJET_PHO_OBJECT)

IF (DPMJET_FOUND)
   IF (NOT DPMJet_FIND_QUIETLY)
      MESSAGE(STATUS "Found DPMJet: ${DPMJET_OBJECT}")
   ENDIF (NOT DPMJet_FIND_QUIETLY)
ELSE (DPMJET_FOUND)
   IF (DPMJet_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find DPMJet, we look in $DPMJETDIR")
   ELSE(DPMJet_FIND_REQUIRED)
      IF(NOT DPMJet_FIND_QUIETLY)
	 MESSAGE(STATUS "Could not find DPMJet, we look in $DPMJETDIR")
      ENDIF(NOT DPMJet_FIND_QUIETLY)
   ENDIF (DPMJet_FIND_REQUIRED)
ENDIF (DPMJET_FOUND)

