#!/bin/bash
#################################################################
#
#  Runs the event display in a specified data directory
#
#  Origin: Mikolaj Krzewicki, Nikhef, Mikolaj.Krzewicki@cern.ch
#
#################################################################
cd ~/data/current
ls -1tr
echo""
read -p "  Choose a directory to work in: " dir
if [[ -d $dir ]]
then
  cd $dir
else
  echo "no such directory - typo?"
  return 999
fi

alieve anyscan_init.C

echo "done"
