///
/// \file PWGCF/FEMTOSCOPY/macros/Train/AddTaskFemtoWithConfig.C
/// \author Andrew Kubera, Ohio State University, andrew.kubera@cern.ch
///

#if !defined(__CINT__) && !defined(__CLING__)

#include "AliAnalysisTaskFemto.C"
#include "AliFemtoAnalysisPionPion.h"

#endif


/// \brief Adds an AliAnalysisTaskFemto analysis object, constructed
///        with parameters provided, to the global AliAnalysisManager.
///
/// This macro creates and returns a pointer to an AliAnalysisTaskFemto,
/// object, which constucts a AliFemtoManager.
///
/// The task object is given the config macro "Train/PionPionFemto/ConfigFemtoAnalysis.C"
/// which is run to create the analysis objects. This is fixed (for now), and
/// if an alternative is required, you should use the general AddTaskFemto.C
/// macro.
///
/// Subwagons are supported, the name of which will be appended to the task
/// name. The task name by default is "TaskPionPionFemto" which cannot be changed.
///
/// The output container name is fixed at the standard "femtolist".
///
/// \param configuration
///     A string containing commands to execute, separated by semicolons.
///     Assign the old parameters using this command.
///     Single quotes are turned to double quotes.
///
///     * macro: Path to the FemtoConfig macro to load; "%%" is expaneded
///              to directory containing this file.
///     * output_filename: Name of the output file to produce.
///                   Default generated by AliAnalysisManager::GetCommonFileName()
///     * output_container: Name of top-level ROOT directory in the output file.
///                   Default PWG2FEMTO.
///     * container: Name of the AliAnalysis container.
///     * task_name: Name of the AliAnalysisTask - May need to be unique...
///     * verbose: Task created in verbose mode
///
/// \param params
///     A string forwarded to the ConfigFemtoAnalysis macro for parsing.
///     This string is wrapped in double-quotes so escaping some to
///     ensure results is a string is unneccessary.
///
/// \param subwagon_suffix
///     If this macro is run in a train with subwagons, this will be
///     set with the identifier.
///
/// Examples
/// --------
///
/// AddTaskFemtoWithConfig("macro='%%/PionPionFemto/ConfigFemtoAnalysis.C';", "");
///
///
AliAnalysisTaskFemto* AddTaskFemtoWithConfig(TString configuration,
                                             TString params,
                                             TString subwagon_suffix="")
{
  const TString AUTO_DIRECTORY = "$ALICE_PHYSICS/PWGCF/FEMTOSCOPY/macros/Train"
              , DEFAULT_MACRO = ""
              , DEFAULT_CONTAINER_NAME = "femtolist"
              , DEFAULT_OUTPUT_CONTAINER = "PWG2FEMTO"
              , DEFAULT_TASK_NAME = "TaskConfigured"
              , DEFAULT_SUBWAGON_TYPE = "centrality"
              ;

  const std::string CONFIG_DEFAULTS
	  = "{ directory:'$ALICE_PHYSICS/PWGCF/FEMTOSCOPY/macros/Train'"
      ", container:'femtolist'"
      ", output_container:'PWG2FEMTO'"
      ", task_name:'TaskConfigured'"
      ", subwagon_type:'centrality'"
      "}";


  const AliFemtoConfigObject cfg
	  = AliFemtoConfigObject::ParseWithDefaults(configuration, CONFIG_DEFAULTS);

  std::string macro_name;
  if (!cfg.find_and_load("macro", macro_name)) {
    std::cerr << " ** Error - Configuration missing key 'macro'.\n"
                 "      Please include path to macro file, similar to "
		 "{macro: '%%/PionPionFemto/ConfigFemtoAnalysis.C'}\n";
    return nullptr;
  }

  TString task_name, container, output_container, subwagon_type;
  cfg.find_and_load("task_name", task_name);
  cfg.find_and_load("container", container);
  cfg.find_and_load("output_container", output_container);
  cfg.find_and_load("subwagon_type", subwagon_type);

  // Get the global manager
  AliAnalysisManager *mgr = AliAnalysisManager::GetAnalysisManager();
  if (!mgr) {
    Error("AddTaskFemtoWithConfig", "Could not get the global AliAnalysisManager.");
    return NULL;
  }

  TString output_filename = mgr->GetCommonFileName();

  bool verbose = kFALSE;

  // Replace %% with this directory for convenience
  if (macro == "") {
    std::cerr << "\n\n"
                 "ERROR - AddTaskFemtoWithConfig - No setup macro provided.\n"
                 " - Please specify a path like macro='%%/PionPionFemto/ConfigFemtoAnalysis.C'\n";
    return NULL;
  }

  cout << "[AddTaskFemtoWithConfig]\n"
          "   output: '" << output_filename << "'\n"
          "   macro: '" << macro << "'\n"
          "   params: '" << params << "'\n";

  // The analysis config macro must accept a single string
  // argument, which it uses to configure the analysis.
  // This line escapes some escapable characters (backslash, newline, tab)
  // and wraps that string in double quotes, ensuring that the interpreter
  // reads a string when passing to the macro.
  const TString analysis_params = '"' + params.ReplaceAll("\\", "\\\\")
                                              .ReplaceAll("\n", "\\n")
                                              .ReplaceAll("\t", "\\t") + '"';

  AliAnalysisTaskFemto *taskfemto = new AliAnalysisTaskFemto(
    task_name,
    macro,
    analysis_params,
    verbose
  );

  mgr->AddTask(taskfemto);

  const TString outputfile = (output_container == "")
                           ? output_filename
                           : output_filename + ":" + output_container);

  AliAnalysisDataContainer *out_container = mgr->CreateContainer(container,
                                                                 TList::Class(),
                                                                 AliAnalysisManager::kOutputContainer,
                                                                 outputfile);

  // connect task to the containers
  mgr->ConnectInput(taskfemto, 0, mgr->GetCommonInputContainer());
  mgr->ConnectOutput(taskfemto, 0, out_container);

  // Return the task pointer
  return taskfemto;
}
