.TH alifs 4 "" "ALICE Reference Manual"
.ad b
.SH NAME
alifs - a front-end shell for CASTOR and SHIFT
.SH SYNOPSIS
alifs [flags] <command [options]>

File System implementation:
             ls [-cdilRu] path
             mv oldname newname...                   
             rm [-f] [-i] [-r] dirname...            
             mkdir [-m absolute_mode] [-p] dirname...
             cp f1 f2                   
             cp f1 <dir2>                            

CASTOR implementation:
             ls [-cdilRTu] [--class] [--comment] path
             mv oldname newname...                   
             rm [-f] [-i] [-r] dirname...            
             mkdir [-m absolute_mode] [-p] dirname...
             cp [-s maxsize] f1 f2                   
             cp f1 <dir2>                            

.SH DESCRIPTION
This is an interface script to underlying mass storage manager. At present it supports CASTOR on RH6.1 and offers some basic Unix like commands:

o) list directory
      alifs ls [-cdilRTu] [--class] [--comment] path 

o) move (rename) file or directory
      alifs mv oldname newname...

o) remove file or directory
      alifs rm [-f] [-i] [-r] dirname... 

o) create directory
      alifs mkdir [-m absolute_mode] [-p] dirname...

o) copy files
      alifs cp [-s maxsize] f1 f2
      alifs cp f1 <dir2>

 CASTOR file system is accessible via RFIO (root must be configured configured with --enable-rfio switch and linked with appropriate libshift.a library). It provides experiment topl level directory (/castor/cern.ch/alice) and user directories following the AFS naming scheeme (like /castor/cern.ch/user/b/buncic).
For more info on CASTOR commands, see related man pages (nsls, nsrename, nsrm, nsmkdir,rfcp,rfstat).
  

.SH AUTHOR
Predrag Buncic, e-mail: Predrag.Buncic@cern.ch 

.SH CREATION DATE
15-Feb-2001
