#!/bin/sh
#############################################################################
# alijob - a shell script to run AliRoot in batch
#############################################################################
#
# modification history
#
# $Log$
#
# SYNOPSIS
# alijob [-setroot $ALICE_ROOT $ROOTSYS] command...
#
# DESCRIPTION

#C<
###########################################################################

###########################################################################
AliJob()
###########################################################################
{
   printf "alijob [-setroot \$ALICE_ROOT \$ROOTSYS] command...\n"
   exit
}

###########################################################################

for param in $*
do
    case $1 in
        -trace)
            shift 1
            set -vx
            ;;
        -help)
            AliJob
            ;;
        -setroot)
            shift 1
            ALICE_ROOT=$1
            ROOTSYS=$2
            shift 1
            ;;
        -echo)
            shift 1
            ECHO="echo "
            ;;
        *)
            break
            ;;
    esac
done

if [ "$1" = "" ]
then
  AliJob
else
  $ECHO bsub -setroot $ALICE_ROOT $ROOTSYS $*
fi

