#!/bin/sh
outdir=${2:-"./"}
tm=`date "+%Y-%m-%d-%H-%M-%S"`
list=/tmp/$tm
tar=$outdir/$tm.tar.gz
cvs -z3 -qn update -Ad | grep -v conf/MachineDef | grep -v quickExecution > $list
if [ `cat $list | grep -c -e "^C " -e "U "` -gt 0 ] 
then  
  cat $list | grep -e "^C " -e "^U "
else
  files=$outdir/$tm
  cat $list | grep -e "^M " -e "^?" | awk '{print $2}' > $outdir/$tm
  cvs -z3 diff `cat $files` >  $outdir/$tm.diffs
  if [ "$1" = "touch" ] ; then
    touch `cat $files`
  fi
  tar zcvf $tar `cat $files` man share/alirun share/mangen share/makepatch
  rm $list
fi

