#ifndef CERNLIB_ISAJET_IZPJET_INC
#define CERNLIB_ISAJET_IZPJET_INC
*
*
* izpjet.inc
*
C-----------------------------------------------------------------------
C    Created   7-NOV-1989 18:10:09.84  Chip Stewart
C    Link offset of bank PJET in mother bank PJHD
C-----------------------------------------------------------------------
      INTEGER      IZPJET
      PARAMETER  ( IZPJET = 1)

#endif
