#ifndef CERNLIB_ISAJET_IZPJHD_INC
#define CERNLIB_ISAJET_IZPJHD_INC
*
*
* izpjhd.inc
*
C-----------------------------------------------------------------------
C    Created   7-NOV-1989 17:57:58.00  Chip Stewart
C    Link offset of bank PJHD in mother bank ISAE
C-----------------------------------------------------------------------
      INTEGER      IZPJHD
      PARAMETER  ( IZPJHD = 8)

#endif
