#ifndef CERNLIB_ISAJET_PI_INC
#define CERNLIB_ISAJET_PI_INC
*
*
* pi.inc
*
        DOUBLE PRECISION PI, TWOPI, HALFPI, RADIAN
C
C last significant (correctly rounded) decimal place on VAX:
C                                                |
C                                                V
        PARAMETER (PI=        3.1415 92653 58979 32384 6)
        PARAMETER (TWOPI=     6.2831 85307 17958 64769 3)
        PARAMETER (HALFPI=    1.5707 96326 79489 66192 3)
        PARAMETER (RADIAN= 0.0174532 92519 94329 5769237)

#endif
