void ViewFRAME()
{
/*
   gMC->Gsatt("BFMO","seen",0);
   gMC->Gsatt("BRO1","seen",1);
   gMC->Gsatt("BRI1","seen",0);
   gMC->Gsatt("BRO2","seen",1);
   gMC->Gsatt("BRI2","seen",0);
   gMC->Gsatt("BRO3","seen",1);
   gMC->Gsatt("BRI3","seen",0);
   gMC->Gsatt("BLO1","seen",0);
   gMC->Gsatt("BLD1","seen",0);
   gMC->Gsatt("BLO2","seen",0);
   gMC->Gsatt("BLD2","seen",0);
   gMC->Gsatt("BLO3","seen",0);
   gMC->Gsatt("BLD3","seen",0);
   gMC->Gsatt("BL01","seen",1);
   gMC->Gsatt("BL02","seen",1);
   gMC->Gsatt("BL11","seen",1);
   gMC->Gsatt("BL12","seen",1);
   gMC->Gsatt("BLO4","seen",0);
   gMC->Gsatt("BLD4","seen",0);
   gMC->Gsatt("BL03","seen",1);
   gMC->Gsatt("BL04","seen",1);
*/
   gMC->Gsatt("B010","seen",0);
   gMC->Gsatt("B001","seen",0);
   gMC->Gsatt("B002","seen",0);
   gMC->Gsatt("B003","seen",1);
   gMC->Gsatt("B004","seen",0);
   gMC->Gsatt("B005","seen",1);
   gMC->Gsatt("B006","seen",0);
   gMC->Gsatt("B007","seen",1);
   gMC->Gsatt("B008","seen",0);
   gMC->Gsatt("B009","seen",0);
   gMC->Gsatt("B011","seen",0);
   gMC->Gsatt("B012","seen",0);
   gMC->Gsatt("B013","seen",1);
   gMC->Gsatt("B014","seen",0);
   gMC->Gsatt("B015","seen",1);
   gMC->Gsatt("B016","seen",0);
   gMC->Gsatt("B017","seen",1);
   gMC->Gsatt("B018","seen",0);
   gMC->Gsatt("B019","seen",0);
   gMC->Gsatt("B020","seen",0);
   gMC->Gsatt("B021","seen",1);
   gMC->Gsatt("B022","seen",1);
   gMC->Gsatt("B023","seen",1);
   gMC->Gsatt("B024","seen",0);
   gMC->Gsatt("B025","seen",0);
   gMC->Gsatt("B026","seen",0);
}
