void ViewHALL()
{
   gMC->Gsatt("HUFL","seen",1);
   gMC->Gsatt("HUWA","seen",1);
   gMC->Gsatt("HUP2","seen",1);
   gMC->Gsatt("HEW1","seen",1);
   gMC->Gsatt("HHF1","seen",1);
   gMC->Gsatt("HHW1","seen",1);
   gMC->Gsatt("HBW1","seen",1);
   gMC->Gsatt("HHW2","seen",1);
   gMC->Gsatt("HHW3","seen",1);
   gMC->Gsatt("HHC1","seen",1);
   gMC->Gsatt("HHF2","seen",1);
   gMC->Gsatt("HPIL","seen",1);
   gMC->Gsatt("HMBS","seen",1);
   gMC->Gsatt("HBBS","seen",1);
   gMC->Gsatt("HPBS","seen",1);
   gMC->Gsatt("HXFI","seen",1);
   gMC->Gsatt("HXII","seen",1);
}
