//automatically generated ROOT DICT definition
//!!! DO NOT EDIT THIS FILE !!!
#ifdef __CINT__
#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;
#pragma link C++ class AliHLTJETAgent+;
#pragma link C++ class AliHLTJETTrackCuts+;
#pragma link C++ class AliHLTJETReader+;
#pragma link C++ class AliHLTJETReaderHeader+;
#pragma link C++ class AliHLTJETConeJetComponent+;
#endif
