#$Id$
###########################
# Makefile for HLT code.  #
#                         #
# Author: Anders Vestbo   #                    
###########################

#Define whether you want to run with ALIROOT or only ROOT
#Only one of them should be defined
ifndef USEPACKAGE
USEPACKAGE = ALIROOT
#USEPACKAGE = ROOT
#USEPACKAGE = STANDALONE
endif

#Specify the directory where the level3code tree is located.
ifndef TOPDIR
TOPDIR = $(HOME)/workcode/level3code
endif
ifndef LIBDIR
LIBDIR = $(LEVEL3)/lib_$(USERNAME)
endif

#Switch on/off HLT logging classes
NOLOGGING = 1

#Switch on/off saving MC data through the chain.
#This will only have an effect if you are running with aliroot.
#DO_MC = 1 

CXX          = g++
LD           = g++
GCCVERSION   = $(shell $(CXX) --version | head -n 1 | cut -d" " -f 3 | cut -d. -f 1)

CXXGCC3FLAGS = -DGCCVERSION=$(GCCVERSION)
#CXXGCC3FLAGS += -pedantic
#CXXGCC3FLAGS += -Wno-deprecated

CXXFLAGS     = -O2 -Wall -fPIC -Woverloaded-virtual $(CXXGCC3FLAGS) $(EXTRACXXFLAGS) 
LDFLAGS      = -O2 $(EXTRALDFLAGS)
SOFLAGS      = -shared
