#ifdef __CINT__
  
#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;
  
#pragma link C++ class AliJetHeader+;
#pragma link C++ class AliUA1JetHeader+;
#pragma link C++ class AliJetFinder+;
#pragma link C++ class AliJetReaderHeader+;
#pragma link C++ class AliJetESDReaderHeader+;
#pragma link C++ class AliJetReader+;
#pragma link C++ class AliJetESDReader+;
#pragma link C++ class AliJetProductionData+;
#pragma link C++ class AliUA1JetFinderV1+;
#pragma link C++ class AliUA1JetFinderV2+;
#pragma link C++ class AliUA1JetHeaderV1+;
#pragma link C++ class AliCdfJetFinder+;
#pragma link C++ class AliCdfJetHeader+;
#pragma link C++ class AliJetGrid+;
#pragma link C++ class AliJetUnitArray+;
#pragma link C++ class AliJetHadronCorrection+; 
#pragma link C++ class AliJetHadronCorrectionv0+;
#pragma link C++ class AliJetHadronCorrectionv1+; 
#pragma link C++ class AliJetFillUnitArray+;
#pragma link C++ class AliJetESDFillUnitArrayTracks+;
#pragma link C++ class AliJetESDFillUnitArrayEMCalDigits+;
#pragma link C++ class AliJetAODFillUnitArrayTracks+;
#pragma link C++ class AliJetAODFillUnitArrayEMCalDigits+;
#pragma link C++ class AliJetDummyGeo+;
#pragma link C++ class AliJetDummyShishKebabTrd1Module+;
#pragma link C++ class AliAnalysisTaskJets+;
#pragma link C++ class AliAnalysisTaskJetsCDF+;
#pragma link C++ class AliDAJetFinder+;
#pragma link C++ class AliDAJetHeader+;
#pragma link C++ class AliJetAODReader+;
#pragma link C++ class AliJetAODReaderHeader+;
#pragma link C++ class AliJetKineReader;
#pragma	link C++ class AliJetKineReaderHeader;
#pragma	link C++ class AliJetMCReader;
#pragma	link C++ class AliJetMCReaderHeader;
#pragma	link C++ class AliJetHistos+;
#pragma	link C++ class AliAnalysisTaskDiJets+;
#pragma	link C++ class AliEventShape+;
#pragma	link C++ class AliKMeansClustering+;
#pragma	link C++ class AliKMeansResult+;
#pragma	link C++ class AliAnalysisTaskKMeans+;
#pragma	link C++ class AliAnalysisTaskFastEmbedding+;
#endif
