#error This is not for compilation 
/** 
 * @page mid_doc The Mid-rapidity code 
 *
 * Module: @ref pwglf_forward_tracklets
 *
 * @tableofcontents 
 *
 * @section mid_intro Introduction 
 *
 * The code in this section defines methods to measure the
 * charged-particle pseudorapidity density over @f$|\eta|<2@f$ using
 * SPD tracklets.
 *
 * The input to this analysis is the ESD information from the SPD, and
 * SPD clusters (Rec-points).  The code is derived from Ruben's
 * original code plus modifications from Roberto for reweighing the
 * simulation input.
 * 
 * @section mid_analysis_flow Analysis flow
 *
 * The analysis requires real data and simulated data, anchored to the
 * real data runs being processed.  For both real and simulated data,
 * the analysis progresses through two steps:
 * 
 * - A pass over ESD plus clusters to generate an AOD branch
 *   containing a TClonesArray of AliAODTracklet objects.  In this
 *   pass, there are no selections imposed on the events.  In this
 *   pass, the SPD clusters are reprocesed and the tracklets are
 *   re-reconstructed.  
 * 
 *   In this pass, we also form so-called injection events. In these
 *   events, a real cluster is removed and a new cluster put in at
 *   some other location in the detector. The tracklets of the event
 *   is then reconstructed and stored.  This procedure is repeated as
 *   many times as possible.  The injection events are therefore
 *   superpositions of many events - each with a real cluster removed
 *   and replaced by a fake cluster.  The injection events are used
 *   later for background estimates.
 *
 *   When processing simulated data, the tracklets are also inspected
 *   for their origin.  A tracklet can have three distinct classes of
 *   origins:
 *
 *   - The tracklet is formed from two clusters generated by the same
 *     primary particle.
 *
 *   - The tracklet is formed from two clusters generated by the same
 *     secondary particle.
 *
 *   - The tracklet is formed from two clusters generated by two
 *     different particles (primary or secondary).
 *
 *   The last class is the background from combinations of clusters
 *   that does not correspond to true particles.  This background must
 *   be removed from the measurements. 
 *
 *   The second class, tracklets from secondaries, also form a
 *   background, but these tracklets are suppressed by cuts on the
 *   sum-of-square residuals
 *
 * @f[ 
 \Delta = \left[\frac{\Delta_{\theta}^2\sin^2\theta}{\sigma_{\theta}^2}+
                \frac{(\Delta_{\phi}-\delta_{\phi})^2}{\sigma_{\phi}^2}\right]
 @f] 		
 *
 * - In the second pass, the tracklets are read from the AOD events
 *   and processed in @f$\eta,\mathrm{IP}_z@f$ bins.  The measured
 *   tracklets (@f$M@f$ or @f$M'@f$), tracklets from injection events
 *   (@f$ I@f$ or @f$ I'@f$) - and for simulated data - tracklets
 *   corresponding to primary (@f$ P'@f$), secondary (@f$ S'@f$), and
 *   combinatorial background (@f$ C'@f$), as well as the
 *   pseudo-tracklets corresponding to the generated charged, primary
 *   paricles (@f$ G'@f$), are histogrammed to form 
 *
 * @f[
 \frac{d^2N_X}{d\eta d\mathrm{IP}_z}\quad,
 @f] 
 *
 *   where @f$ X@f$ is @f$ M@f$ or @f$ I@f$ for real data, or @f$
 *   M',I',P',S',C'@f$ or @f$ G'@f$ for simulated data.
 *
 *   For each of these tracklet samples, except @f$ G'@f$, we also
 *   form the 3-dimensional differential @f$\Delta@f$ distributions
 *
 * @f[
 \frac{d^3N_X}{d\eta d\mathrm{IP}_z d\Delta}\quad,
 @f] 
 *
 *   which are later used to estimate the background due to wrong
 *   combinations of clusters into tracks.
 *
 * Once both the real and simulated data has passed these two steps,
 * we combine the to data sets into the final measurement.  The final
 * measurement is given by
 *
 * @f[ 
 R = \frac{G'}{(1-\beta')M'}(1-\beta)M, 
 @f] 
 * 
 * where 
 @f[ 
 \beta' = \frac{C'}{M'}\quad\mathrm{and}\quad \beta = k\beta'\quad.
 @f] 
 *
 * Here, @f$ k@f$ is some scaling derived from the 3-dimensional
 * differential @f$\Delta_M@f$ and @f$\Delta_{M'}@f$ distributions .
 *
 * @section mid_structure Structure
 *
 * There are classes for containing data, classes that represent
 * analysis tasks, and classes that perform calculations, as well as
 * specialized classes for analysis of simulation (MC) output. 
 *
 * @subsection mid_struct_data Data structures 
 *
 * The classes AliAODTracklet and AliAODMCTracklet stores individual
 * tracklet parameters.  The difference between the two are that
 * AliAODMCTracklet also stores the PDG code(s) and transverse
 * momentum (momenta) of the mother primary particle (which may be the
 * particle it self).
 *
 * @subsection mid_struct_tasks Tasks 
 * 
 * The pass over the ESD is done by the classes AliTrackletAODTask and
 * AliTrackletAODMCTask.  These tasks generated the array of tracklets
 * in the AOD events.  The difference between the two is that
 * AliTrackletAODMCTask inspects and groups each tracklet according to
 * it's origin, and create pseudo-tracklets corresponding to the
 * generated primary, charged particles.
 *
 * The second pass is done by one of the three classes
 * AliTrackletAODdNdeta, AliTrackletAODMCdNdeta, or
 * AliTrackletAODWeightedMCdNdeta.  These tasks build the ditributions 
 *
 * @f[
 \frac{d^2N_X}{d\eta d\mathrm{IP}_z}\quad,
 @f] 
 * 
 * and 
 *
 * @f[
 \frac{d^3N_X}{d\eta d\mathrm{IP}_z d\Delta}\quad.
 @f] 
 * 
 * The first task does this for @f$ X=M@f$ and @f$ I@f$, while the
 * second and thhird tasks does this for @f$ X=M',I',P',S',C'@f$ and
 * @f$ G'@f$.  The third task reweighs all tracklets according to the
 * particle specie(s) and transverse momentum (momenta) of the mother
 * primary particle(s).  AliTrackletWeights defines the interface used
 * for reqeighing the data.
 *
 *
 * @subsection mid_misc Misc.
 *
 */
//
// EOF
//
