#!/bin/bash

if [[ $# -eq 0 || -n $( echo $* | egrep -- "--help|-h" ) ]]; then
    echo "lhapdf-config: configuration tool for the LHAPDF"
    echo "               parton density function evolution library"
    echo "               http://projects.hepforge.org/lhapdf/"
    echo
    echo "Usage: lhapdf-config [[--help|-h] | [--prefix] | [--pdfsets-path]]"
    echo "Options:"
    echo "  --help | -h    : show this help message"
    echo "  --libdir       : show the path to the LHAPDF library directory"
    echo "  --ldflags      : get compiler flags for use with the linker stage of any compilation"
fi

# First, let's get the path to the lib
rootExec=$(which root)
alirootExec=$(which aliroot)
changeFrom=\/bin
changeTo=\/lib
rootLib=$(dirname $rootExec)
alirootLib=$(dirname $alirootExec)
rootLib=${rootLib//$changeFrom/$changeTo}
alirootLib=${alirootLib//$changeFrom/$changeTo}

OUT=""

tmp=$( echo "$*" | egrep -- '--\<libdir\>')
test -n "$tmp" && OUT="$OUT ${rootLib}:${alirootLib}"

tmp=$( echo "$*" | egrep -- '--\<ldflags\>')
test -n "$tmp" && OUT="$OUT -L${rootLib} -lCore -L${alirootLib} -llhapdf5_9_1"

echo $OUT
