#include "DrawResBase.h"

/** 
 * @defgroup pwg2_forward_analysis_scripts PWG2 Forward analysis - scripts
 *
 * @ingroup pwg2_forward_analysis
 */
/** 
 * Example macro to loop over the event-by-event 2D histogram of 
 * @f[
 *   \frac{d^{2}N_{ch}}{d\eta\,d\phi}
 * @f]
 * stored in an AOD.  
 * 
 * The class needs the files &lt;<i>base</i>&gt;<tt>_hists.root</tt> 
 * containing the histograms generated by AliForwardMultiplicity and 
 * the file &lt;<i>base</i>&gt;<tt>_aods.root</tt> containing the tree 
 * with AliAODEvent objects where AliAODForwardMult objects have been 
 * added to in the branch <tt>Forward</tt>
 * 
 * @ingroup pwg2_forward_analysis_scripts
 */
class DrawRes1D : public DrawResBase
{
public:
  /** 
   * Constructor 
   * 
   * @param special If true, add to the list of 'specials'
   */
  DrawRes1D()
    : fTotal1D(0)
  {}
  //__________________________________________________________________
  virtual void Clear(Option_t* option) 
  {
    DrawResBase::Clear(option);
    if (fTotal1D) delete fTotal1D;
    fTotal1D = 0;
  }
  //__________________________________________________________________
  virtual Bool_t IsInit() const { return fTotal1D; }
  //__________________________________________________________________
  /** 
   * Utility function to set-up histograms based on the input 
   * @f$ dd^{2}N_{ch}/d\eta\,d\phi@f$ histogram.   This member function 
   * is called on the first event so that we have the proper binning 
   * 
   * @param templ Input histogram
   * 
   * @return true on succcess
   */
  virtual Bool_t FirstEvent(const TH2D& templ) 
  { 
    if (!DrawResBase::FirstEvent(templ)) return kFALSE;
    const TAxis* etaAxis = templ.GetXaxis();
    
    // Generate sum histograms. 
    // - fTotal1D will be the sum of projections on the X axis of the input  
    //   histograms 
    fTotal1D = new TH1D("dndeta", 
			"#frac{1}{N}#frac{dN_{ch}}{d#eta}",
			etaAxis->GetNbins(),
			etaAxis->GetXmin(),
			etaAxis->GetXmax());
    fTotal1D->SetMarkerStyle(29);
    fTotal1D->SetMarkerSize(1);
    fTotal1D->SetStats(0);
    fTotal1D->SetDirectory(0);
    fTotal1D->Sumw2();

    return kTRUE;
  }


  //__________________________________________________________________
  /** 
   * Process the events 
   * 
   * 
   * @return true on success, false otherwise 
   */
  virtual void AddContrib(const TH2D& hist, Int_t) 
  {
    // Make a projection on the X axis of the input histogram 
    TH1D*    proj  = hist.ProjectionX("_px", 0, -1, "e");
    
    // Add to 1D summed histogram
    fTotal1D->Add(proj); // , scale);
    
    // Remove the projection 
    delete proj;
  }
  //__________________________________________________________________
  /** 
   * Process the events 
   * 
   * 
   * @return true on success, false otherwise 
   */
  virtual TH1D* GetResult() 
  {
    // Scale our direct sum of the projects of the input histograms to 
    // the number of vertex bins and the bin width. If we do rebinning, 
    // we must scale it one more time.
    // fTotal1D->Scale(1. / fNAccepted, "width");
    fTotal1D->Divide(fNorm);
    fTotal1D->Scale(1., "width");
    return fTotal1D;
  }
  /** 
   * Browse this object 
   * 
   * @param b Browser to use 
   */
  virtual void Browse(TBrowser* b) 
  {
    if (fTotal1D) b->Add(fTotal1D);
    DrawResBase::Browse(b);
  }
  /** 
   * Create a new object of this class, and add it to the list of 
   * specials, and create a browse and browse to this object 
   * 
   * @return Newly created object
   */
  static DrawRes1D* Create() 
  {
    DrawRes1D* dr = new DrawRes1D;
    gROOT->GetListOfSpecials()->Add(dr);
    TBrowser* b = new TBrowser("b");
    b->BrowseObject(gROOT->GetListOfSpecials());
    return dr;
  }
protected:
  TH1D*              fTotal1D;   // Direct sum of input histograms

  ClassDef(DrawRes1D,0)
};

//
// EOF
//
