AliAnalysisTaskNOmegaLPK *AddTaskNOmegaLPK(TString finname="",
						     Bool_t theMCon=kFALSE,
						     Int_t nTour=0,
						     Bool_t additionalChecks=kFALSE)

{

  AliAnalysisManager *mgr = AliAnalysisManager::GetAnalysisManager();
  if (!mgr) {
    ::Error("AddTask", "No analysis manager to connect to.");
    return NULL;
  }  
  
  // cuts are stored in a TFile generated by makeTFile4CutsLc2V0YW.C in ./macros/
  // set there the cuts!!!!!

  Bool_t stdcuts=kFALSE;
  TFile* filecuts;
  if( finname.EqualTo("") ) {
    stdcuts=kTRUE; 
  } else {
      filecuts=TFile::Open(finname.Data());
      if(!filecuts ||(filecuts&& !filecuts->IsOpen())){
	AliFatal("Input file not found : check your cut object");
      }
  }


  //CREATE THE TASK

  printf("CREATE TASK\n");
  AliAnalysisTaskNOmegaLPK *task = new AliAnalysisTaskNOmegaLPK("AliAnalysisTaskNOmegaLPK");
  //task->SetAdditionalChecks(additionalChecks);
  task->SetMC(theMCon);
  task->SetDebugLevel(1);
  mgr->AddTask(task);

  // Create and connect containers for input/output  
  TString outputfile = AliAnalysisManager::GetCommonFileName();
  outputfile += ":Dibaryon_";
  outputfile += nTour;

  mgr->ConnectInput(task,0,mgr->GetCommonInputContainer());

  // ----- output data -----
	AliAnalysisDataContainer *coutput1 = mgr->CreateContainer(Form("Vertex%1d",nTour),TTree::Class(),AliAnalysisManager::kOutputContainer,outputfile.Data()); // variables tree
	mgr->ConnectOutput(task,1,coutput1);
	AliAnalysisDataContainer *coutput2 = mgr->CreateContainer(Form("VertexSelf%1d",nTour),TTree::Class(),AliAnalysisManager::kOutputContainer,outputfile.Data()); // variables tree
	mgr->ConnectOutput(task,2,coutput2);

  return task;

}
