void ViewPMD()
{
gMC->Gsatt("DP11","seen",0);
gMC->Gsatt("DS11","seen",0);
gMC->Gsatt("SUPR","seen",0);
gMC->Gsatt("SMSS","seen",1);
gMC->Gsatt("SMAR","seen",1);
gMC->Gsatt("DW11","seen",0);
gMC->Gsatt("SUPB","seen",0);
gMC->Gsatt("SUFE","seen",0);
gMC->Gsatt("DM11","seen",0);
gMC->Gsatt("DPMD","seen",0);
gMC->Gsatt("PM01","seen",0);
gMC->Gsatt("PM02","seen",0);
gMC->Gsatt("PM03","seen",0);
gMC->Gsatt("PM04","seen",0);
gMC->Gsatt("PM05","seen",0);
gMC->Gsatt("PM06","seen",0);
gMC->Gsatt("PM07","seen",0);
gMC->Gsatt("PM08","seen",0);
gMC->Gsatt("PM09","seen",0);
gMC->Gsatt("PM10","seen",0);
gMC->Gsatt("PM11","seen",0);
gMC->Gsatt("PM12","seen",0);
gMC->Gsatt("PM13","seen",0);
gMC->Gsatt("PM14","seen",0);
gMC->Gsatt("PMDL","seen",0);
gMC->Gsatt("PMDR","seen",0);

}
