void ViewFMD()
{
  gMC->Gsatt("BR3_","seen",1);
  gMC->Gsatt("CB3_","seen",0);
  gMC->Gsatt("BR5_","seen",1);
  gMC->Gsatt("CB5_","seen",0);
  gMC->Gsatt("R1R3","seen",1);
  gMC->Gsatt("R2R3","seen",1);
  gMC->Gsatt("R3R3","seen",1);
  gMC->Gsatt("R1SP","seen",1);
  gMC->Gsatt("R1L3","seen",1);
  gMC->Gsatt("R2L3","seen",1);
  gMC->Gsatt("R3L3","seen",1);
  gMC->Gsatt("R2SP","seen",1);
  gMC->Gsatt("R3SP","seen",1);
  gMC->Gsatt("BR2_","seen",1);
  gMC->Gsatt("CB2_","seen",0);
  gMC->Gsatt("R1R2","seen",1);
  gMC->Gsatt("R2R2","seen",1);
  gMC->Gsatt("R3R2","seen",1);
  gMC->Gsatt("R1L2","seen",1);
  gMC->Gsatt("R2L2","seen",1);
  gMC->Gsatt("R3L2","seen",1);
  gMC->Gsatt("BR1_","seen",1);
  gMC->Gsatt("CB1_","seen",0);
  gMC->Gsatt("R1R1","seen",1);
  gMC->Gsatt("R2R1","seen",1);
  gMC->Gsatt("R3R1","seen",1);
  gMC->Gsatt("R1L1","seen",1);
  gMC->Gsatt("R2L1","seen",1);
  gMC->Gsatt("R3L1","seen",1);
  gMC->Gsatt("BR4_","seen",1);
  gMC->Gsatt("CB4_","seen",0);
  gMC->Gsatt("R1L4","seen",1);
  gMC->Gsatt("R2L4","seen",0);
  gMC->Gsatt("R3L4","seen",1);
}
