void ViewABSO()
{
  gMC->Gsatt("ABSS","seen",0);
  gMC->Gsatt("ABSM","seen",1);
  gMC->Gsatt("ABST","seen",0);
  gMC->Gsatt("APOL","seen",1);
  gMC->Gsatt("ANOS","seen",0);
  gMC->Gsatt("AWIN","seen",1);
  gMC->Gsatt("AITR","seen",1);
  gMC->Gsatt("ARPB","seen",0);
  gMC->Gsatt("ACON","seen",1);
  gMC->Gsatt("ACAR","seen",0);
  gMC->Gsatt("ACAO","seen",1);
  gMC->Gsatt("ARW0","seen",1);
  gMC->Gsatt("ARW1","seen",1);
  gMC->Gsatt("ARPE","seen",1);
  gMC->Gsatt("AV11","seen",1);
  gMC->Gsatt("AI11","seen",0);
  gMC->Gsatt("AP11","seen",0);
  gMC->Gsatt("AV21","seen",1);
  gMC->Gsatt("AI21","seen",0);
  gMC->Gsatt("AP21","seen",1);
}
