void ViewDIPO()
{
  gMC->Gsatt("DDIP","seen",0);
  gMC->Gsatt("DC1","seen",1);
  gMC->Gsatt("DC2","seen",1);
  gMC->Gsatt("DC3","seen",1);
  gMC->Gsatt("DC4","seen",1);
  gMC->Gsatt("DC11","seen",1);
  gMC->Gsatt("DC12","seen",1);
  gMC->Gsatt("DL1","seen",1);
  gMC->Gsatt("DL2","seen",1);
  gMC->Gsatt("DCO1","seen",1);
  gMC->Gsatt("DCO2","seen",1);
  gMC->Gsatt("DCO3","seen",1);
  gMC->Gsatt("DCO4","seen",1);
  gMC->Gsatt("DCO5","seen",1);
  gMC->Gsatt("DCO6","seen",1);
  gMC->Gsatt("DCO7","seen",1);
  gMC->Gsatt("DCO8","seen",1);
  gMC->Gsatt("DCO9","seen",1);
  gMC->Gsatt("DCOA","seen",1);
  gMC->Gsatt("DCOB","seen",1);
  gMC->Gsatt("DCOC","seen",1);
  gMC->Gsatt("DCOD","seen",1);
  gMC->Gsatt("DCOE","seen",1);
  gMC->Gsatt("DCOF","seen",1);
  gMC->Gsatt("DCOG","seen",1);
  gMC->Gsatt("DCOH","seen",1);
  gMC->Gsatt("DCOI","seen",1);
  gMC->Gsatt("DCOJ","seen",1);
  gMC->Gsatt("DCOK","seen",1);
  gMC->Gsatt("DY1","seen",1);
  gMC->Gsatt("DY11","seen",1);
  gMC->Gsatt("DY2","seen",1);
  gMC->Gsatt("DY22","seen",1);
}
