/**
 * @file 
 * 
 * Scripts to draw energy loss fits from correction object file 
 *
 * @ingroup pwg2_forward_analysis_scripts
 */
/** 
 * Clear canvas 
 * 
 * @param c Canvas to clear 
 *
 * @ingroup pwg2_forward_analysis_scripts
 */
void
ClearCanvas(TCanvas* c)
{
  c->SetLeftMargin(.1);
  c->SetRightMargin(.05);
  c->SetBottomMargin(.1);
  c->SetTopMargin(.05);
  c->Clear();
}

/** 
 * Draw energy loss fits to a multi-page PDF. 
 *
 * @par Input: 
 * The input file is expected to contain a AliFMDCorrELossFit object
 * named @i elossfits in the top level directory.
 * 
 * @para Output: 
 * A multi-page PDF.  Note, that the PDF generated by ROOT in this way
 * is broken (cannot be read by Acrobat Reader on Windows and MacOSX)
 * and one should pass it through a filter to correct these problems.
 * 
 * @param fname   File name 
 * @param option  Drawing options 
 *
 * @ingroup pwg2_forward_analysis_scripts
 */
void
DrawCorrCentralSecMap2(const char* fname, const char* option="colz")
{
  //__________________________________________________________________
  // Load libraries and object 
  gROOT->Macro("$ALICE_ROOT/PWG2/FORWARD/analysis2/scripts/LoadLibs.C");

  TFile* file = TFile::Open(fname, "READ");
  if (!file) { 
    Error("DrawCorrSecMap", "Failed to open %s", fname);
    return;
  }
  TString pname(fname);
  pname.ReplaceAll(".root", ".png");
  pname = gSystem->BaseName(pname);

  AliCentralMultiplicityTask::Manager* mgr = 
    new AliCentralMultiplicityTask::Manager;
  const char* objName = mgr->GetObjectName(0);
  AliCentralCorrSecondaryMap* corr = 
    static_cast<AliCentralCorrSecondaryMap*>(file->Get(objName));
  if (!corr) { 
    Error("DrawCorrCentralSecMap", "Object '%s' not found in %s", 
	  objName, fname);
    return;
  }

  //__________________________________________________________________
  // Create a canvas
  Int_t w = 1200;
  TCanvas* c = new TCanvas("c", "c", w, w / TMath::Sqrt(2));
  c->SetFillColor(0);
  c->SetBorderSize(0);
  c->SetBorderMode(0);
  // c->Print(Form("%s[", pname.Data()));
  
  gStyle->SetOptStat(0);
  gStyle->SetTitleColor(0);
  gStyle->SetTitleStyle(0);
  gStyle->SetTitleBorderSize(0);
  gStyle->SetTitleX(.1);
  gStyle->SetTitleY(1);
  gStyle->SetTitleW(.8);
  gStyle->SetTitleH(.09);
  gStyle->SetFrameFillColor(kWhite);
  gStyle->SetFrameBorderSize(1);
  gStyle->SetFrameBorderMode(1);
  gStyle->SetPalette(1);

  ClearCanvas(c);
  //__________________________________________________________________
  // Draw all corrections
  const TAxis& vtxAxis = corr->GetVertexAxis();
  Int_t        nVtx    = vtxAxis.GetNbins();
  c->Divide((nVtx+2)/3, 3, 0, 0);
  Int_t ipad = 0;
  for (UShort_t v=1; v <= nVtx; v++) { 
    ipad++;
    if (ipad == 1) {
      c->cd(ipad);
      TLatex* l = new TLatex(.5, .5, 
			     "#frac{#sum N_{ch,SPD0}}{#sum N_{ch,primary}}");
      l->SetNDC();
      l->SetTextAlign(22);
      l->SetTextSize(.1);
      l->Draw();
      ipad++;
    }
    if (ipad == 12) ipad++;
    
    TVirtualPad* p = c->cd(ipad);
    p->SetFillColor(kWhite);
    p->SetGridx();
    p->SetGridy();

    TH2*   h1 = corr->GetCorrection(v);
    TH1D*  pr = h1->ProjectionX(Form("vtxbin%02d", v), -1, -1, "e");
    pr->SetDirectory(0);
    pr->SetTitle(Form("%+5.1f<v_{z}<%+5.1f", 
		      vtxAxis.GetBinLowEdge(v),
		      vtxAxis.GetBinUpEdge(v)));
    pr->Scale(1. / h1->GetNbinsY());
    pr->SetMarkerColor(kRed+1);
    pr->SetFillColor(kRed+1);
    pr->SetFillStyle(3001);
    pr->SetMaximum(1.65);
    pr->GetXaxis()->SetRangeUser(-3.1,3.1);
    pr->Draw("hist"); 
    pr->Draw("same");
   
  }
  
  //__________________________________________________________________
  // Close output file 
  c->SaveAs(pname.Data());
  
}
//
// EOF
//
