//Awful naming but this is also for plotting data
void PrintCent(int i);
float etaacc = 1.0;
Bool_t sim = kFALSE;
Bool_t sysErr = kTRUE;
Bool_t isEMCal = kTRUE;
Bool_t isTPC = kTRUE;
TH1D * DrawHistogram(TList *list, char *name,char *option, Int_t rebin, Int_t color, Int_t marker, Float_t scale, Bool_t draw = kTRUE){

  TH1D *histo = list->FindObject(name);
  histo->SetMarkerColor(color);
  histo->SetMarkerStyle(marker);
  histo->SetLineColor(color);
  histo->Rebin(rebin);
  histo->Scale(1.0/((Float_t)rebin));
  histo->Scale(scale);
  histo->SetMarkerSize(1.2);
  if(draw) histo->Draw(option);
  return histo;
}
//Int_t colors[] = {TColor::kRed,TColor::kOrange+7,TColor::kOrange+1,TColor::kOrange-2,TColor::kYellow+1,TColor::kSpring+9,TColor::kSpring-5,TColor::kGreen+1,TColor::kGreen-2,TColor::kTeal+5,TColor::kTeal-5,TColor::kCyan-7,TColor::kCyan-2,TColor::kAzure+7,TColor::kAzure-1,TColor::kAzure-6,TColor::kBlue+3};
Int_t colors[] = {TColor::kRed,TColor::kOrange+7,TColor::kOrange+1,TColor::kYellow+1,TColor::kGreen+1,TGolor::kTeal+5,TColor::kTeal-7,TColor::kCyan-7,TColor::kAzure,TColor::kBlue+3,TColor::kViolet-6,TColor::kViolet,1,1,1,1,1,1,1};
Int_t markers[] = {20,21,22,23,29,33,34, 20,21,22,23,29,33,34, 20,21,22,23,29,33,34, 20,21,22,23,29,33,34};

//void PlotSimPbPb(char *filename = "rootFiles/LHC11a4_bis/Et.ESD.new.sim.LHC11a4_bis.root", Bool_t sim = kFALSE, Bool_t sysErr = kTRUE, char *corrfilename = "rootFiles/corrections/corrections.LHC11a4_bis.PbPb.ForData.root", Bool_t isEMCal = kTRUE, Bool_t isTPC = kTRUE){
void PlotHadEtDistributions(char *filename = "rootFiles/LHC10hPass2/Et.ESD.sim.LHC10hPass2.Run139465.root",char *corrfilename = "rootFiles/corrections/corrections.LHC11a10a_bis.PbPb.139465.ForData.root"){
  gStyle->SetOptTitle(0);
  gStyle->SetOptStat(0);
  gStyle->SetOptFit(0);

  TFile *file = new TFile(filename);
  TCanvas *c1 = new TCanvas("c1","Reconstructed Hadronic Et",700,500);
  c1->SetTopMargin(0.04);
  c1->SetRightMargin(0.04);
  c1->SetBorderSize(0);
  c1->SetFillColor(0);
  c1->SetFillColor(0);
  c1->SetBorderMode(0);
  c1->SetFrameFillColor(0);
  c1->SetFrameBorderMode(0);
  c1->SetLeftMargin(0.140805);
  c1->SetRightMargin(0.0158046);
  c1->SetBottomMargin(0.16);
  c1->SetTopMargin(0.0168776);
  c1->SetLogy();
//   TH1D *histoHadRecoAll = out2->FindObject("RecoHadEtFullAcceptanceTPC");
//   histoHadRecoAll->Rebin(2);
//   histoHadRecoAll->Draw();
  TH1D *histoHadRecoAll = DrawHistogram(out2,"RecoHadEtFullAcceptanceTPC","",2,1,20,1.0);
  Float_t scale = 1.0 / histoHadRecoAll->GetEntries() / histoHadRecoAll->GetXaxis()->GetBinWidth(1);
  histoHadRecoAll->Scale(scale);
  histoHadRecoAll->GetXaxis()->SetRange( 1, histoHadRecoAll->GetXaxis()->FindBin(2700));
  histoHadRecoAll->SetMinimum(1e-6);
  histoHadRecoAll->SetMaximum(5e-3);
  histoHadRecoAll->GetXaxis()->SetLabelSize(0.06);
  histoHadRecoAll->GetYaxis()->SetLabelSize(0.06);
  histoHadRecoAll->GetXaxis()->SetTitleSize(0.07);
  histoHadRecoAll->GetYaxis()->SetTitleSize(0.07);
  histoHadRecoAll->GetXaxis()->SetTitle("dE_{T}^{had}/d#eta (GeV)");
  histoHadRecoAll->GetYaxis()->SetTitle("1/N_{eve} dN_{eve}/d(dE_{T}^{had}/d#eta) (1/GeV)");
  Int_t rebin = 4;
  Int_t color = 0;
  TH1D *histoHadReco0 = DrawHistogram(out2,"RecoHadEtFullAcceptanceTPCCB0","same",rebin,colors[color],markers[color],scale);
  color++;
  TH1D *histoHadReco1 = DrawHistogram(out2,"RecoHadEtFullAcceptanceTPCCB1","same",rebin,colors[color],markers[color],scale);
  color++;
  TH1D *histoHadReco2 = DrawHistogram(out2,"RecoHadEtFullAcceptanceTPCCB2","same",rebin,colors[color],markers[color],scale);
  color++;
  TH1D *histoHadReco3 = DrawHistogram(out2,"RecoHadEtFullAcceptanceTPCCB3","same",rebin,colors[color],markers[color],scale);
  color++;
  TH1D *histoHadReco4 = DrawHistogram(out2,"RecoHadEtFullAcceptanceTPCCB4","same",rebin,colors[color],markers[color],scale);
  color++;
  rebin = 2;
  TH1D *histoHadReco5 = DrawHistogram(out2,"RecoHadEtFullAcceptanceTPCCB5","same",rebin,colors[color],markers[color],scale);
  color++;
  TH1D *histoHadReco6 = DrawHistogram(out2,"RecoHadEtFullAcceptanceTPCCB6","same",rebin,colors[color],markers[color],scale);
  color++;
  TH1D *histoHadReco7 = DrawHistogram(out2,"RecoHadEtFullAcceptanceTPCCB7","same",rebin,colors[color],markers[color],scale);
  color++;
  TH1D *histoHadReco8 = DrawHistogram(out2,"RecoHadEtFullAcceptanceTPCCB8","same",rebin,colors[color],markers[color],scale);
  TH1D *histoHadReco9 = DrawHistogram(out2,"RecoHadEtFullAcceptanceTPCCB9","same",rebin,colors[color],markers[color],scale,kFALSE);
  color++;
  histoHadReco8->Add(histoHadReco9);
  rebin = 1;
  TH1D *histoHadReco10 = DrawHistogram(out2,"RecoHadEtFullAcceptanceTPCCB10","same",rebin,colors[color],markers[color],scale);
  TH1D *histoHadReco11 = DrawHistogram(out2,"RecoHadEtFullAcceptanceTPCCB11","same",rebin,colors[color],markers[color],scale,kFALSE);
  color++;
  histoHadReco10->Add(histoHadReco11);
  TH1D *histoHadReco12 = DrawHistogram(out2,"RecoHadEtFullAcceptanceTPCCB12","same",rebin,colors[color],markers[color],scale);
  TH1D *histoHadReco13 = DrawHistogram(out2,"RecoHadEtFullAcceptanceTPCCB13","same",rebin,colors[color],markers[color],scale,kFALSE);
  color++;
  histoHadReco12->Add(histoHadReco13);
  TH1D *histoHadReco14 = DrawHistogram(out2,"RecoHadEtFullAcceptanceTPCCB14","same",rebin,colors[color],markers[color],scale);
  TH1D *histoHadReco15 = DrawHistogram(out2,"RecoHadEtFullAcceptanceTPCCB15","same",rebin,colors[color],markers[color],scale,kFALSE);
  TH1D *histoHadReco16 = DrawHistogram(out2,"RecoHadEtFullAcceptanceTPCCB16","same",rebin,colors[color],markers[color],scale,kFALSE);
  TH1D *histoHadReco17 = DrawHistogram(out2,"RecoHadEtFullAcceptanceTPCCB17","same",rebin,colors[color],markers[color],scale,kFALSE);
  color++;
  histoHadReco14->Add(histoHadReco15);
  //histoHadReco14->Add(histoHadReco16);
  //histoHadReco14->Add(histoHadReco17);
  TLegend *leg1 = new TLegend(0.66523,0.64346,0.784483,0.964135);//(0.505747,0.64346,0.625,0.964135);
  leg1->SetFillStyle(0);
  leg1->SetFillColor(0);
  leg1->SetBorderSize(0);
  leg1->SetTextSize(0.056962);
  leg1->AddEntry(histoHadReco0,"0-5%");
  leg1->AddEntry(histoHadReco1,"5-10%");
  leg1->AddEntry(histoHadReco2,"10-15%");
  leg1->AddEntry(histoHadReco3,"15-20%");
  leg1->AddEntry(histoHadReco4,"20-25%");
  leg1->AddEntry(histoHadReco5,"25-30%");
  leg1->Draw();
  TLegend *leg2 = new TLegend(0.824713,0.64346,0.945402,0.964135);//(0.66523,0.64346,0.784483,0.964135);
  leg2->SetFillStyle(0);
  leg2->SetFillColor(0);
  leg2->SetBorderSize(0);
  leg2->SetTextSize(0.056962);
  leg2->AddEntry(histoHadReco6,"30-35%");
  leg2->AddEntry(histoHadReco7,"35-40%");
  leg2->AddEntry(histoHadReco8,"40-50%");
  //leg2->AddEntry(histoHadReco9,"45-50%");
  leg2->AddEntry(histoHadReco10,"50-60%");
  //leg2->AddEntry(histoHadReco11,"55-60%");
  leg2->AddEntry(histoHadReco12,"60-70%");
  //leg3->AddEntry(histoHadReco13,"65-70%");
  leg2->AddEntry(histoHadReco14,"70-80%");
  leg2->Draw();
  TLegend *leg3 = new TLegend(0.824713,0.64346,0.945402,0.964135);
  leg3->SetFillStyle(0);
  leg3->SetFillColor(0);
  leg3->SetBorderSize(0);
  leg3->SetTextSize(0.056962);
  leg3->AddEntry(histoHadReco12,"60-70%");
  //leg3->AddEntry(histoHadReco13,"65-70%");
  leg3->AddEntry(histoHadReco14,"70-90%");
  //leg3->AddEntry(histoHadReco15,"75-80%");
  //leg3->AddEntry(histoHadReco16,"80-90%");
  //leg3->AddEntry(histoHadReco17,"85-90%");
  //leg3->Draw();

  TLatex *tex = new TLatex(64.871,0.00259747,"ALICE Pb-Pb #sqrt{s_{NN}}=2.76 TeV");
	tex->SetTextSize(0.0590717);
	tex->Draw();
  c1->SaveAs("/tmp/ETHadDistributions.eps");
  c1->SaveAs("/tmp/ETHadDistributions.png");
  c1->SaveAs("/tmp/ETHadDistributions.pdf");

}
