#ifndef ALIGENSLEVTGEN_H
#define ALIGENSLEVTGEN_H

/* Copyright(c) 2007-2009, ALICE Experiment at CERN, All rights reserved. *
 * See cxx source for full Copyright notice                               */
///////////////////////////////////////////////////////////////////////////
//                                                                       //
//  AliGenSLEvtGen class to performs decays of particles generated by    //
//  Starlight as previous generator. It inherits from AliGenerator.      //
//                                                                       //  
//  Origin: Michal.Broz@cern.ch   					 //
///////////////////////////////////////////////////////////////////////////

#include "AliGenerator.h"
#include "AliDecayerSLEvtGen.h"

class TParticle;

class AliGenSLEvtGen : public AliGenerator {

  public:

  AliGenSLEvtGen();
 
  ~AliGenSLEvtGen();

  virtual void Init();
  virtual void Generate(); 
  AliDecayer* GetDecayer() {return fDecayer;}
  Bool_t SetUserDecayTable(Char_t *path);
  void SetEvtGenPartNumber(Int_t val){fEvtGenNumber = val;}
  void SetPolarization(Int_t val){fPolarization = val; fDecayPolarized=kTRUE;}
  void SetSeed(UInt_t /*seed*/) {;}
  
  void SetEtaChildRange(Double_t etaMin, Double_t etaMax) {
    fEtaChildMin = etaMin;
    fEtaChildMax = etaMax;
  }
  protected:
  
  private:
  AliStack *fStack;		   //!pointer to AliStack
  AliDecayerSLEvtGen  *fDecayer;   //!pointer to AliDecayerSLEvtGen
  Bool_t fUserDecay;		   //!TRUE if a user decay table is set	
  Char_t    *fUserDecayTablePath;  //!pointer to path of user decay table
  Int_t  fEvtGenNumber;		   //!EvtGen number of particle
  Bool_t fDecayPolarized;	   //!Flag for polarized decay
  Int_t  fPolarization;		   //!Polarization of mother particle
  Double_t    fEtaChildMin;       // Max < Min: no cut
  Double_t    fEtaChildMax;

  AliGenSLEvtGen(const AliGenSLEvtGen &SLEvtGen);
  AliGenSLEvtGen & operator=(const AliGenSLEvtGen & rhs);
  
  ClassDef(AliGenSLEvtGen,0) //AliGenerator interface to SLEvtGen
};

////////////////////////////////////////////////////////////////////////////////////////////////

#endif
