*
* $Id$
*
* $Log$
* Revision 1.1.1.3  2000/04/19 13:27:43  mclareni
* Import version 8.04
*
* Revision 1.4  2000/04/15 14:10:43  plothow
* Version 8.03: Nuclear PDFs introduced
*
* Revision 1.3  2000/04/09 10:06:18  plothow
* new version 8.00 - MRS 98 and 99, CTEQ5 and GRV98 added
*
* Revision 1.2  1996/10/28 16:01:58  pdflib
* PDFLIB new version 7.04
*
* Revision 1.1.1.1  1996/04/12 15:28:48  plothow
* Version 7.01
*
*
*
* w5051p2.inc
*
      PARAMETER (MODEMX = 300)
      PARAMETER (NPTYMX = 4, NGRMAX = 9, NSETMX = 100)
      PARAMETER (NCHDIM=20)
