void AliceHelp(){
////////////////////////////////////////////////////
//            H O W  to run  A l i R o o t        //
////////////////////////////////////////////////////

  /*
 To execute the Alice simulation program, type aliroot.
 This starts AliRoot in interactive mode by default.
 After a few seconds, you get the Root prompt.

 You can start your interactive session by invoking
 the standard menu
    Root > .x menu.C
 or do directly
    Root > gAlice->Run()
 or Root > gAlice->RunLego()
 
 if you want to divert the long output generated by
 the AliRoot initialisation phase to a file (eg AliRoot.log)
    Root > .x menu.C > AliRoot.log
 or Root > gAlice->Run(); > AliRoot.log
 
 The initialisation phase of AliRoot takes time (30 seconds).
 By default the macro menu.C invokes AliRun::Init with
 the configuration file "Config.C".
 When the initialisation is finished, you get the promt again.
 You also get a Root control bar menu.
 Select:
   - Run  to generate a complete event with the number of tracks
          and the configuration specified in "Config.C"

   - RunLego  to generate the standard lego plots for radiation
          and absorption length. By default, the granularity
          is 60 rays in theta and 60 rays in phi.
          When this command is finished, you can view the results
          with  Root > .x lego.C
          If you do not want to run with the default parameters,do
          Root > gAlice->RunLego( list of params), see AliRun::RunLego

   - Top/Front/Side view to generate the corresponding cut view of Alice.
         Note that a cut view takes a long time to execute (30 seconds).

   - Menu Trees  This shows a new menu from which you can draw
         the geometry tree for most Alice detectors.
         Double-clicking on an Alice detector generates the SPECs.

   - Menu Pictures  This shows a new menu from which you can draw
         the major Alice detectors in SHADe mode.

   - Other items allow you to switch ON/OFF various drawing modes.

 See the classes AliRun and TGeant3 for more detailed functionality.
 A global variable "gAlice" can be used to invoke the AliRun class functions.
 A global variable "geant3" can be used to invoke the TGeant3 class functions.

 Note that several TGeant3 functions are also available by clicking
 with the right mouse button on a canvas.

 When you want to leave gAlice type the command ".q"
    Root > .q
  */
}
