///
/// \file PWGCF/FEMTOSCOPY/macros/Train/PionPionFemto/AddNuTaskPionPionRoot6.C
/// \author Andrew Kubera, Ohio State University, andrew.kubera@cern.ch
///

#include <TROOT.h>

#include <TString.h>
#include <TList.h>
#include <TObjArray.h>
#include <TObjString.h>

#include <AliAnalysisManager.h>

#include "AliAnalysisTaskFemtoNu.h"


/// \class MacroCfg
/// \brief All parameters for this macro
///
struct MacroCfg : public TNamed {

  TString macro = "%%/ConfigNuFemtoAnalysisR6.C+",
          auto_directory = "$ALICE_PHYSICS/PWGCF/FEMTOSCOPY/macros/Train/PionPionFemto",
          output_filename,
          output_container = "PWG2FEMTO",
          subwagon_array = "",
          subwagon_type = "centrality";

  MacroCfg()
    : TNamed("cfg", "MacroCfg")
    , output_filename(AliAnalysisManager::GetAnalysisManager()->GetCommonFileName())
    {}

  TString GetFilename()
    {
      return (output_container == "")
           ? output_filename
           : TString::Format("%s:%s", output_filename.Data(), output_container.Data());
    }
};


/// \brief Adds an AliAnalysisTaskFemtoNu analysis object, constructed
///        with parameters provided, to the global AliAnalysisManager.
///
/// This macro creates and returns an :class:`AliAnalysisTaskFemto` object.
/// The task object is given a macro
/// is given the config macro "Train/PionPionFemto/ConfigFemtoAnalysis.C"
/// which is run to create the analysis objects.
/// This is fixed (for now), and if an alternative is required, you
/// should use the general AddTaskFemto.C macro.
///
/// Subwagons are supported, the name of which will be appended to
/// the task name.
/// The task name by default is "TaskPionPionFemto" which cannot be
/// changed.
///
/// The output container name is fixed at the standard "femtolist".
///
/// \param configuration
///     A string containing commands to execute, separated by semicolons.
///     Assign the old parameters using this command.
///     Single quotes are turned to double quotes.
///
///     * macro: Path to the FemtoConfig macro to load; "%%" is
///          expaneded to directory containing this file.
///     * output_filename: Name of the output file to produce.
///         Default generated by AliAnalysisManager::GetCommonFileName()
///     * output_container: Name of top-level ROOT directory in the output file.
///         Default is the classic 'PWG2FEMTO'.
///     * container: Name of the AliAnalysis container.
///     * task_name: Name of the AliAnalysisTask - May need to be unique...
///     * verbose: Task created in verbose mode
///
/// \param params
///     A string forwarded to the ConfigFemtoAnalysis macro for parsing.
///     This string is wrapped in double-quotes so escaping some to
///     ensure results is a string is unneccessary.
///
/// \param subwagon_suffix
///     If this macro is run in a train with subwagons, this will be
///     set with the identifier.
///
AliAnalysisTask* AddNuTaskPionPionRoot6(TString container,
                                        TString configuration,
                                        TString params,
                                        TString subwagon_suffix)
{
  std::cout << "\n\n============== AddNuTaskPionPion (ROOT6 Version) ===============\n";

  // Get the global analysis manager
  AliAnalysisManager *mgr = AliAnalysisManager::GetAnalysisManager();
  if (!mgr) {
    Error("AddNuTaskPionPion", "Could not get the global AliAnalysisManager.");
    return nullptr;
  }

  MacroCfg cfg;

  bool verbose = kFALSE;

  TObjArray* lines = configuration.Tokenize("\n;");

  TIter next_line(lines);
  TObject *line_obj = nullptr;

  gDirectory->Add(&cfg);

  while ((line_obj = next_line())) {
    TObjString *s = static_cast<TObjString*>(line_obj);
    TString cmd = s->String().Strip(TString::kBoth, ' ');
    if (cmd.IsWhitespace()) {
      continue;
    }

    cmd.ReplaceAll("'", '"');

    cmd = "static_cast<MacroCfg*>(cfg)->" + cmd + ";";

    std::cout << "running `" << cmd  << "`\n";
    gROOT->ProcessLineFast(cmd);
  }

  gDirectory->Remove(&cfg);

  // Replace %% with this directory for convenience
  cfg.macro.ReplaceAll("%%", cfg.auto_directory);

  // Dealing with subwagons
  if (!subwagon_suffix.IsWhitespace()) {
    Int_t index = subwagon_suffix.Atoi();
    TObjArray *values = cfg.subwagon_array.Tokenize("~");
    TIter next_value(values);
    if (values->GetEntries() < index) {
      std::cerr << "Could not use subwagon-index " << index << " in subwagon_array of only " << values->GetEntries() << " entries\n";
      return nullptr;
    }
    for (int i=0; i<index; ++i) {
      next_value();
    }
    TString ss = ((TObjString*)next_value())->String();
    params += ";" + cfg.subwagon_type + " = " + ss;

    container += "_" + subwagon_suffix;
  }

  std::cout << "[AddTaskPionPion]\n"
               "   container: " << container << "\n"
               "   output: '" << cfg.output_filename << "'\n"
               "   macro: '" << cfg.macro << "'\n"
               "   params: '" << params << "'\n";

  // The analysis config macro for PionPionFemto accepts a single string
  // argument, which it interprets.
  // This line escapes some escapable characters (backslash, newline, tab)
  // and wraps that string in double quotes, ensuring that the interpreter
  // reads a string when passing to the macro.
  const TString analysis_params = '"' + params.ReplaceAll("\\", "\\\\")
                                              .ReplaceAll("\n", "\\n")
                                              .ReplaceAll("\"", "\\\"")
                                              .ReplaceAll("\t", "\\t") + '"';

  std::cout << "   params-normalized: '" << analysis_params << "'\n";

  AliAnalysisTaskFemto *femtotask = new AliAnalysisTaskFemtoNu(
    container,
    cfg.macro,
    analysis_params,
    verbose
  );

  mgr->AddTask(femtotask);

  const TString outputfile = cfg.GetFilename();
  auto *out_container = mgr->CreateContainer(container,
                                             AliFemtoResultStorage::Class(),
                                             AliAnalysisManager::kOutputContainer,
                                             outputfile);

  mgr->ConnectInput(femtotask, 0, mgr->GetCommonInputContainer());
  mgr->ConnectOutput(femtotask, AliAnalysisTaskFemtoNu::RESULT_STORAGE_OUTPUT_SLOT, out_container);

  // quiet a warning
  out_container = mgr->CreateContainer(container + "_list",
                                       TList::Class(),
                                       AliAnalysisManager::kOutputContainer,
                                       outputfile);
  mgr->ConnectOutput(femtotask, 0, out_container);

  std::cout << "============== AddNuTaskPionPion : Done ===============\n\n";
  return femtotask;
}


AliAnalysisTask*
AddNuTaskPionPionRoot6(TString container,
                       TString configuration,
                       TString params="")
{
  return AddNuTaskPionPionRoot6(container, configuration, params, "");
}


AliAnalysisTask*
AddNuTaskPionPionRoot6(TString container)
{
  AddNuTaskPionPionRoot6(container, "", "");
  return nullptr;
}
