///
/// \file PWGCF/FEMTOSCOPY/macros/Train/PionPionFemto/AddNuTaskPionPion.C
/// \author Andrew Kubera, Ohio State University, andrew.kubera@cern.ch
///

#if !defined(__CINT__) && !defined(__CLING__)

#include <TROOT.h>

#include <TString.h>
#include <TList.h>
#include <TObjArray.h>
#include <TObjString.h>

#include <AliAnalysisManager.h>

#include "AliAnalysisTaskFemtoNu.h"

#endif

/// \brief Adds an AliAnalysisTaskFemtoNu analysis object, constructed
///        with parameters provided, to the global AliAnalysisManager.
///
/// This macro creates and returns an :class:`AliAnalysisTaskFemto` object.
/// The task object is given a macro
/// is given the config macro "Train/PionPionFemto/ConfigFemtoAnalysis.C"
/// which is run to create the analysis objects.
/// This is fixed (for now), and if an alternative is required, you
/// should use the general AddTaskFemto.C macro.
///
/// Subwagons are supported, the name of which will be appended to
/// the task name.
/// The task name by default is "TaskPionPionFemto" which cannot be
/// changed.
///
/// The output container name is fixed at the standard "femtolist".
///
/// \param configuration
///     A string containing commands to execute, separated by semicolons.
///     Assign the old parameters using this command.
///     Single quotes are turned to double quotes.
///
///     * macro: Path to the FemtoConfig macro to load; "%%" is
///          expaneded to directory containing this file.
///     * output_filename: Name of the output file to produce.
///         Default generated by AliAnalysisManager::GetCommonFileName()
///     * output_container: Name of top-level ROOT directory in the output file.
///         Default is the classic 'PWG2FEMTO'.
///     * container: Name of the AliAnalysis container.
///     * task_name: Name of the AliAnalysisTask - May need to be unique...
///     * verbose: Task created in verbose mode
///
/// \param params
///     A string forwarded to the ConfigFemtoAnalysis macro for parsing.
///     This string is wrapped in double-quotes so escaping some to
///     ensure results is a string is unneccessary.
///
/// \param subwagon_suffix
///     If this macro is run in a train with subwagons, this will be
///     set with the identifier.
///
AliAnalysisTask* AddNuTaskPionPion(TString container,
                                   TString configuration,
                                   TString params,
                                   TString subwagon_suffix)
{
  std::cout << "\n\n============== AddNuTaskPionPion ===============\n";

  const TString AUTO_DIRECTORY = "$ALICE_PHYSICS/PWGCF/FEMTOSCOPY/macros/Train/PionPionFemto",
                DEFAULT_MACRO = "%%/ConfigNuFemtoAnalysis.C",
                DEFAULT_OUTPUT_CONTAINER = "PWG2FEMTO",
                DEFAULT_SUBWAGON_TYPE = "centrality";

  // Get the global analysis manager
  AliAnalysisManager *mgr = AliAnalysisManager::GetAnalysisManager();
  if (!mgr) {
    Error("AddNuTaskPionPion", "Could not get the global AliAnalysisManager.");
    return NULL;
  }

  TString macro = DEFAULT_MACRO,
          output_filename = mgr->GetCommonFileName(),
          output_container = DEFAULT_OUTPUT_CONTAINER,
          subwagon_array = "",
          subwagon_type = DEFAULT_SUBWAGON_TYPE;

  bool verbose = kFALSE;

  TObjArray* lines = configuration.Tokenize("\n;");

  TIter next_line(lines);
  TObject *line_obj = NULL;

  while ((line_obj = next_line())) {
    TObjString *s = static_cast<TObjString*>(line_obj);
    TString cmd = s->String().Strip(TString::kBoth, ' ');
    if (cmd.IsWhitespace()) {
      continue;
    }

    cmd.ReplaceAll("'", '"');
    std::cout << "running `" << cmd  << "`\n";
    gROOT->ProcessLineFast(cmd + ';');
  }

  // Replace %% with this directory for convenience
  macro.ReplaceAll("%%", AUTO_DIRECTORY);

  // Dealing with subwagons
  if (!subwagon_suffix.IsWhitespace()) {
    Int_t index = subwagon_suffix.Atoi();
    TObjArray *values = subwagon_array.Tokenize(",");
    TIter next_value(values);
    for (int i=0; i<index; ++i) {
      next_value();
    }
    TString ss = ((TObjString*)next_value())->String();
    params += Form("%s = %s;", subwagon_type.Data(), ss.Data());

    container += "_" + subwagon_suffix;
  }

  std::cout << "[AddTaskPionPion]\n"
               "   container: " << container << "\n"
               "   output: '" << output_filename << "'\n"
               "   macro: '" << macro << "'\n"
               "   params: '" << params << "'\n";

  // The analysis config macro for PionPionFemto accepts a single string
  // argument, which it interprets.
  // This line escapes some escapable characters (backslash, newline, tab)
  // and wraps that string in double quotes, ensuring that the interpreter
  // reads a string when passing to the macro.
  const TString analysis_params = '"' + params.ReplaceAll("\\", "\\\\")
                                              .ReplaceAll("\n", "\\n")
                                              .ReplaceAll("\"", "\\\"")
                                              .ReplaceAll("\t", "\\t") + '"';

  AliAnalysisTaskFemto *femtotask = new AliAnalysisTaskFemtoNu(
    container,
    macro,
    analysis_params,
    verbose
  );

  mgr->AddTask(femtotask);

  const TString outputfile = (output_container == "")
                           ? output_filename
                           : TString::Format("%s:%s", output_filename.Data(), output_container.Data());

  AliAnalysisDataContainer *out_container = mgr->CreateContainer(container,
                                                                 AliFemtoResultStorage::Class(),
                                                                 AliAnalysisManager::kOutputContainer,
                                                                 outputfile);

  mgr->ConnectInput(femtotask, 0, mgr->GetCommonInputContainer());
  mgr->ConnectOutput(femtotask, AliAnalysisTaskFemtoNu::RESULT_STORAGE_OUTPUT_SLOT, out_container);

  // quiet a warning
  out_container = mgr->CreateContainer(container + "_list",
                                       TList::Class(),
                                       AliAnalysisManager::kOutputContainer,
                                       outputfile);
  mgr->ConnectOutput(femtotask, 0, out_container);

  std::cout << "============== AddNuTaskPionPion : Done ===============\n\n";
  return femtotask;
}

AliAnalysisTask* AddNuTaskPionPion(TString container,
                                   TString configuration,
                                   TString params="")
{
  return AddNuTaskPionPion(container, configuration, params, "");
}

AliAnalysisTask* AddNuTaskPionPion(TString container)
{
  return AddNuTaskPionPion(container, "", "");
}
